### PR TITLE
Don't Return Unwanted Slot 0 on BeaconBlocksByRange Call

### LINKED ISSUE #602: beaconBlocksByRange doesn't respect startSlot
**Describe the bug**

When requesting blocks by range with start:1, it will return block with slot 0 and onward.
When requesting blocks by range with start: 2, it will return block with slot 2 and onward.

**Expected behavior**

If start:1 block with slot 0 should not be returned

### PR DESCRIPTION
**Pull request by aunyks**
Fixes #602. It appears that unwanted blocks with slot 0 are returned whenever BeaconBlocksByRange's `step` and `lowerLimit` arguments are equal, since `(0 - lowerLimit) % step === 0` is true whenever the two are equal.

Ensuring that some `slot` is greater than or equal to the `lowerLimit` should fix this.

### CODE REVIEW

File: packages/lodestar/src/db/api/beacon/repositories/blockArchive.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ export class BlockArchiveRepository extends BulkRepository<BeaconBlock> {
       .map((datum) => deserialize(this.type, datum))
```
Comment (wemeetagain) [inline packages/lodestar/src/db/api/beacon/repositories/blockArchive.ts:45]: Not exactly related to this PR, but it seems strange that `safeLowerLimit` is set to a number or Buffer.

Comment (aunyks) [reply packages/lodestar/src/db/api/beacon/repositories/blockArchive.ts:45]: Yeah, I’ve been thinking the same thing. I assumed it has some significance, so I never decided to delete it in case it broke something somewhere else.

Comment (wemeetagain) [reply packages/lodestar/src/db/api/beacon/repositories/blockArchive.ts:45]: It seems to work as expected, even with `Buffer.alloc(0)`. It should probably be just `0` though.
We can change in a later PR

**Review by wemeetagain — APPROVED** [review]
