### PR TITLE
fix: prune checkpoint states in processSlotsToNearestCheckpoint

### LINKED ISSUE #7495: Not able to prune checkpoint state during nft of holesky
### Describe the bug

```
Feb-25 02:22:59.925[chain]           ^[[34mdebug^[[39m: Error processing block state blockRootHex=0x2db899881ed8546476d0b92c6aa9110bea9a4cd0dbeb5519eb0ea69575f1f359, slot=3711006 - Can only get block root in the past currentSlot=3711006 slot=3711008
Error: Can only get block root in the past currentSlot=3711006 slot=3711008
    at getBlockRootAtSlot (file:///usr/app/packages/state-transition/src/util/blockRoot.ts:21:11)
    at PersistentCheckpointStateCache.processPastEpoch (file:///usr/app/packages/beacon-node/src/chain/stateCache/persistentCheckpointsCache.ts:627:66)
    at PersistentCheckpointStateCache.processState (file:///usr/app/packages/beacon-node/src/chain/stateCache/persistentCheckpointsCache.ts:478:34)
Feb-25 02:22:59.934[sync]          ^[[36mverbose^[[39m: Batch download error id=Head, startEpoch=115972, status=Downloading, peer=16...YDwG3Y, code=REQUEST_ERROR_DIAL_ERROR, error=unexpected end of input
Error: unexpected end of input
    at Object.read (file:///usr/app/node_modules/it-byte-stream/dist/src/index.js:86:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.read (file:///usr/app/node_modules/it-length-prefixed-stream/dist/src/index.js:51:37)
    at async read (file:///usr/app/node_modules/@libp2p/multistream-select/dist/src/multistream.js:22:17)
    at async Module.readString (file:///usr/app/node_modules/@libp2p/multistream-select/dist/src/multistream.js:33:17)
    at async Module.select (file:///usr/app/node_modules/@libp2p/multistream-select/dist/src/select.js:72:20)
    at async ConnectionImpl.newStream [as _newStream] (file:///usr/app/node_modules/libp2p/dist/src/upgrader.js:330:50)
    at async ConnectionImpl.newStream (file:///usr/app/node_modules/libp2p/dist/src/connection/index.js:94:24)
    at async file:///usr/app/packages/reqresp/lib/request/index.js:57:26
    at async withTimeout (file:///usr/app/packages/utils/lib/timeout.js:12:16)
Error: REQUEST_ERROR_DIAL_ERROR
    at file:///usr/app/packages/reqresp/lib/request/index.js:65:19
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async sendRequest (file:///usr/app/packages/reqresp/lib/request/index.js:55:24)
    at async ReqRespBeaconNode.sendRequest (file:///usr/app/packages/reqresp/lib/ReqResp.js:110:13)
    at async AsyncIterableBridgeHandler.onRequest (file:///usr/app/packages/beacon-node/lib/util/asyncIterableToEvents.js:99:30)
```

while block state cache is consistently at 64, checkpoint state cache spiked due to the error

Image

### Expected behavior

no error, checkpoint state cache's epoch should be consistently  <=4

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.27.1

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- in holesky, there was a single block killing lodestar because we have to process multiple epoch transitions at the same time, see https://github.com/ChainSafe/lodestar/issues/7495#issuecomment-2680800898

**Description**

- for single epoch transition, let the next block prune it at the last 1/3 slot of next epoch
- if there are multiple epoch transitions, it means network is not healthy so prune it right away or we'll get OOM
- also fix "Can only get block root in the past" in #7495

Closes #7495

**Steps to test or reproduce**

Test holesky

### CODE REVIEW

**Comment by twoeths** [comment]
verified this on feat1 group

```
verbose: processSlotsToNearestCheckpoint calls checkpointStateCache to process checkpoint state root=0xf1c7bba5b0507cf18dccfbc2d1f2c29e4c86798a95cffc190fb28968d8248eb8, epoch=115973, persistCount=6
```

that should help us avoid OOM

File: packages/beacon-node/src/chain/regen/regen.ts [hunk 1]
```diff
@@ -368,7 +385,31 @@ async function processSlotsToNearestCheckpoint(
...
+
+    if (count >= 1) {
+      // in normal condition, we only process 1 epoch so never reach this
+      // in that case, we want to prune state at the last 1/3 slot of slot 0 of the next epoch after importing the 1st block of epoch
+      // in non-finality time, we may process a lot of epochs so need to prune the cache to keep the node healthy
+      // this happened to holesky on Feb 2025, see https://github.com/ChainSafe/lodestar/issues/7495#issuecomment-2680800898
+      // cannot use getBlockRootAtSlot() because nextEpochSlot = postState
+      const latestBlockHex = toRootHex(cp.root);
+      try {
+        const persistCount = await checkpointStateCache.processState(latestBlockHex, checkpointState);
```
Comment (nazarhussain) [inline packages/beacon-node/src/chain/regen/regen.ts:398]: Can we not split the logic to pruning cache and processing epoch? Mixing these both here is a bit confusing.

File: packages/beacon-node/src/chain/regen/regen.ts [hunk 2]
```diff
@@ -368,7 +385,31 @@ async function processSlotsToNearestCheckpoint(
...
+        logger?.verbose("processSlotsToNearestCheckpoint calls checkpointStateCache to process checkpoint state", {
```
Comment (nazarhussain) [inline packages/beacon-node/src/chain/regen/regen.ts]: This seems like a call stack log using exact function names in the logs. 

```suggestion
        logger?.verbose("pruning the checkpointStateCache to process checkpoint state", {
```

**Review by nazarhussain — DISMISSED** [review]

File: packages/beacon-node/src/chain/regen/regen.ts (hunk 2 above)
Comment (wemeetagain) [inline packages/beacon-node/src/chain/regen/regen.ts]:
```suggestion
        logger?.verbose("pruning checkpointStateCache during processSlotsToNearestCheckpoint", {
```

**Review by wemeetagain — APPROVED** [review]
LGTM

File: packages/beacon-node/src/chain/regen/regen.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/regen/regen.ts:398]: this `processState` contains the pruning logic, epoch transition is at line 377 above through `processSlots()` call

Comment (wemeetagain) [reply packages/beacon-node/src/chain/regen/regen.ts:398]: One alternative would be to rely on the `ChainEvent.checkpoint` event, modifying it to take optionally pass in the checkpoint state.

And then somewhere 
```ts
onCheckpoint(cp: Checkpoint, checkpointState?: BeaconState) {
  if (!checkpointState) return;
  const latestBlockHex = toRootHex(cp.root);
  try {
    const persistCount = await checkpointStateCache.processState(latestBlockHex, checkpointState);
    logger?.verbose("pruning checkpointStateCache during processSlotsToNearestCheckpoint", {
        root: latestBlockHex,
        epoch: cp.epoch,
        persistCount,
      });
  } catch (e) {
    ...
  }
}
```

Although the difference is that in this PR, we await the pruning, and ^ we don't await.

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.28.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.28.0) :tada:
