### PR TITLE
Handle forkChoiceFinalized event - skipped slot checkpoint

### LINKED ISSUE #2643: Error lightclientUpdater.onFinalized
**Describe the bug**

Got this while syncing `oonoonba` network:
```
Jun-07 10:33:48.782 [CHAIN]           error: Error lightclientUpdater.onFinalized epoch=515 message=REGEN_ERROR_BLOCK_NOT_IN_FORKCHOICE
Error: REGEN_ERROR_BLOCK_NOT_IN_FORKCHOICE
    at StateRegenerator.getBlockSlotState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/regen/regen.ts:92:13)
    at StateRegenerator.getCheckpointState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/regen/regen.ts:86:23)
    at Object.job (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/regen/queued.ts:91:66)
    at Timeout._onTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/util/queue/index.ts:106:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Expected behavior**

No error

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

It failed to handle finalized checkpoint event for skipped slot

**Description**

+ Use `ChainEvent.forkChoiceFinalized` event instead of `ChainEvent.finalized` to coordinate with archive tasks
+ For a skipped slot checkpoint state, use `state.latestBlockHeader.slot` instead of `state.slot` since there is no block at `state.slot`

Closes #2643

**Steps to test or reproduce**

Sync `yeerongpilly`

### CODE REVIEW

File: packages/lodestar/src/chain/eventHandlers.ts [hunk 1]
```diff
@@ -169,12 +169,20 @@ export function onJustified(
...
+
+export async function onForkChoiceFinalized(this: BeaconChain, cp: phase0.Checkpoint): Promise<void> {
+  this.logger.verbose("Fork choice finalized", ssz.phase0.Checkpoint.toJson(cp));
   // Only after altair
   if (cp.epoch >= this.config.ALTAIR_FORK_EPOCH) {
     try {
       const state = await this.regen.getCheckpointState(cp);
-      const block = await this.getCanonicalBlockAtSlot(state.slot);
+      // using state.slot is not correct for a checkpoint with skipped slot
+      const block = await this.getCanonicalBlockAtSlot(state.latestBlockHeader.slot);
```
Comment (dapplion) [inline packages/lodestar/src/chain/eventHandlers.ts:185]: Good pick!

**Review by dapplion — APPROVED** [review]

**Review by wemeetagain — COMMENTED** [review]
:+1:
