### PR TITLE
fix: correctly parse validator indices when querying state balances

### LINKED ISSUE #7881: Lodestar can not parse non-hex string `validator_index` in `getStateValidatorBalances`
Hello Lodestar team,

I’ve encountered a potential inconsistency with how Lodestar handles validator_balances requests.

According to the [beacon-API specification](https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidatorBalances), the id parameter can be a validator index represented as a string (e.g., "22710") or a hex-encoded public key. However, when making the following request:

```
curl -X GET http://localhost:4000/eth/v1/beacon/states/head/validator_balances?id=22710
```

The differential testing results show that only lodestar return error

```shell
{"code":500,"message":"hex string length 5 must be multiple of 2"} # lodestar
{"data": [], "execution_optimistic": false, "finalized": false} # prysm
{"data": [], "execution_optimistic": false, "finalized": false} # lighthouse
{"data": [], "execution_optimistic": false, "finalized": false} # teku
{"data": [], "execution_optimistic": false, "finalized": false} # nimbus
{"data": [], "execution_optimistic": false, "finalized": false} # grandine
```

Schema:
```json
{
  "name": "id",
  "description": "Either hex encoded public key (any bytes48 with 0x prefix) or validator index",
  "in": "query",
  "required": false,
  "schema": {
    "type": "array",
    "maxItems": 64,
    "uniqueItems": true,
    "items": {
      "description": "Either hex encoded public key (any bytes48 with 0x prefix) or validator index",
      "type": "string"
    }
  }
}
```
Related code implementation in lodestar: 
https://github.com/ChainSafe/lodestar/blob/33ca09539ba6df5ec44fb767fa59545edc89fa7e/packages/beacon-node/src/api/impl/beacon/state/index.ts#L203-L212

Thanks for your time!

### PR DESCRIPTION
**Pull request by bomanaps**
**Motivation**
Fixes an issue in `getStateValidatorBalances` where `validator_index` fails to parse if it's not a hex string.

**Description**
Screenshot 2025-06-11 at 10 23 43

Note this was tested in dev mode

Closes https://github.com/ChainSafe/lodestar/issues/7881

**Steps to test or reproduce**
Run in Dev mode:
```
./lodestar dev
```
```
 curl http://localhost:9596/eth/v1/beacon/states/head/validator_balances?id=22710

/// Test with validator index 0 (should exist)
curl http://localhost:9596/eth/v1/beacon/states/head/validator_balances?id=0

/// Check total validator count
curl http://localhost:9596/eth/v1/beacon/states/head/validators | jq '.data | length'
```

### CODE REVIEW

**Comment by bomanaps** [comment]
Hello @nflaig  Could you please review this when you have time?

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 1]
```diff
@@ -215,9 +215,16 @@ export function getBeaconStateApi({
             }
             balances.push({index: id, balance: state.balances.get(id)});
           } else {
-            const index = headState.epochCtx.pubkey2index.get(fromHex(id));
-            if (index != null && index <= state.validators.length) {
-              balances.push({index, balance: state.balances.get(index)});
+            if (id.startsWith("0x")) {
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: we might be able to reuse `getStateValidatorIndex` here https://github.com/ChainSafe/lodestar/blob/f3e21c76794869cadedccce10ca02401e150351a/packages/beacon-node/src/api/impl/beacon/state/utils.ts#L150

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 2]
```diff
@@ -210,16 +210,16 @@ export function getBeaconStateApi({
...
-            }
-            balances.push({index: id, balance: state.balances.get(id)});
-          } else {
-            const index = headState.epochCtx.pubkey2index.get(fromHex(id));
-            if (index != null && index <= state.validators.length) {
-              balances.push({index, balance: state.balances.get(index)});
-            }
+          const validatorIndex =
+            typeof id === "number"
+              ? {valid: true, validatorIndex: id}
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: why do we need to handle numbers separately?

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 3]
```diff
@@ -210,16 +210,16 @@ export function getBeaconStateApi({
...
-            if (state.validators.length <= id) {
-              continue;
-            }
-            balances.push({index: id, balance: state.balances.get(id)});
-          } else {
-            const index = headState.epochCtx.pubkey2index.get(fromHex(id));
-            if (index != null && index <= state.validators.length) {
-              balances.push({index, balance: state.balances.get(index)});
-            }
+          const validatorIndex =
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: call this result or resp, as it's a wrapper around validator index

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.34.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.34.0) :tada:
