### PR TITLE
fix: avoid BeaconState commit() clone() in beacon-node

### LINKED ISSUE #8725: Avoid calling BeaconState.clone() in beacon-node
### Problem description

The only place we modify our BeaconState is state-transition
so either move the concerning function there (rewards api is an example) or do not use it
the reason is we also should not call it when we integrate to lodestar-z

### Solution description

Check all places calling BeaconState.clone() and either move to state-transition or not to call it

### Additional context

part of #8650

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- we never mutate state inside beacon-node so we should not do the clone() there, same to commit()
- it's not a problem for ts BeaconStateView, even not a big performance issue for the native BeaconStateView, it's just that we don't have to because it's a principle to not to mutate any BeaconStates in beacon-node
- this helps us not having to implement `clone()` and `commit()` in the BeaconStateView interface

**Description**

- remove `clone()` in state caches and `regen.getState()` api
- remove `commit()`
- remove unused functions
- do `state.clone()` of rewards api to inside its implementation
- simplify `computeBlockRewards()`

Closes #8725

### CODE REVIEW

**Comment by twoeths** [comment]
tested this for almost 1 day, the only change is state clone count decreased clearly

Screenshot 2026-01-08 at 13 56 30

on mainnet super node, the attestation subnet surged but not affect memory much

Screenshot 2026-01-08 at 13 57 15

on other nodes it's just the same. So I guess it does not affect much, it's more about stability not about performance anyway

File: packages/beacon-node/src/api/impl/proof/index.ts [hunk 1]
```diff
@@ -24,11 +23,14 @@ export function getProofApi(
 
       const res = await getStateResponseWithRegen(chain, stateId);
 
-      const state =
-        res.state instanceof Uint8Array ? loadState(config, chain.getHeadState(), res.state).state : res.state;
+      if (res.state instanceof Uint8Array) {
+        // this should not happen because stateId is a string, check `getStateResponseWithRegen` implementation
+        throw new Error(`State for stateId ${stateId} is not available for proof generation.`);
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/proof/index.ts]: this seems wrong, `stateId` is a string but it can be a slot in which case we might query a historical state which will be of type `Uint8Array`

https://github.com/ChainSafe/lodestar/blob/46c9c672fd5634e0a7abf2b618166b2dfb867b30/packages/beacon-node/src/api/impl/beacon/state/utils.ts#L36

File: packages/beacon-node/src/api/impl/validator/index.ts [hunk 2]
```diff
@@ -1039,21 +1036,12 @@ export function getValidatorApi(
         } else {
           const res = await getStateResponseWithRegen(chain, startSlot);
 
-          const stateViewDU =
-            res.state instanceof Uint8Array
-              ? loadState(config, chain.getHeadState(), res.state).state
-              : res.state.clone();
+          if (res.state instanceof Uint8Array) {
+            // should not happen because we query a startSlot as a number in getStateResponseWithRegen() api
+            throw new Error(`Cannot load CachedBeaconState for slot ${startSlot} for proposer duties`);
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/validator/index.ts]: I don't understand this case, same as before, if slot is finalized then this will return a `Uint8Array` since we will run `getHistoricalStateBySlot`

File: packages/beacon-node/src/chain/chain.ts [hunk 3]
```diff
@@ -587,8 +587,11 @@ export class BeaconChain implements IBeaconChain {
       };
     }
 
-    const data = await this.db.stateArchive.getByRoot(fromHex(stateRoot));
-    return data && {state: data, executionOptimistic: false, finalized: true};
+    // we can do a `this.db.stateArchive.getByRoot()` here, but
+    // returning 1 per 100s of states that are persisted in the archive state is not useful enough
```
Comment (nflaig) [inline packages/beacon-node/src/chain/chain.ts]: we had users run with `--chain.archiveStateEpochFrequency 1` to have faster state access, not sure this is still the case but we need to keep that in mind

**Review by nflaig — COMMENTED** [review]
this seems to limit our ability to serve historical data, need to be careful that we don't break those use cases

File: packages/beacon-node/src/chain/chain.ts (hunk 3 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/chain.ts]: I changed it to query state archive db to return Uint8Array instead
the goal is not to return the BeaconStateAllForks, I want to use CachedBeaconStateAllForks only to make it easier to migrate to BeaconStateView later

File: packages/beacon-node/src/api/impl/proof/index.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/api/impl/proof/index.ts]: reverted the change in https://github.com/ChainSafe/lodestar/pull/8728/changes/f7d9c5cea2ff8d795bc7a00f353844cece1c9cea

File: packages/beacon-node/src/chain/chain.ts (hunk 3 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/chain.ts]: https://github.com/ChainSafe/lodestar/pull/8728/changes/42f853f0864b3c4328bcb79095475014b5678b7f

File: packages/beacon-node/src/chain/blocks/verifyBlocksStateTransitionOnly.ts [hunk 4]
```diff
@@ -59,6 +59,7 @@ export async function verifyBlocksStateTransitionOnly(
         // if block is trusted don't verify proposer or op signature
         verifyProposer: !useBlsBatchVerify && !validSignatures && !validProposerSignature,
         verifySignatures: !useBlsBatchVerify && !validSignatures,
+        dontTransferCache: false,
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/verifyBlocksStateTransitionOnly.ts:62]: how is this change related to the other changes in the PR?

File: packages/beacon-node/src/chain/regen/queued.ts [hunk 5]
```diff
@@ -82,18 +82,15 @@ export class QueuedStateRegenerator implements IStateRegenerator {
    * This is not for block processing so don't transfer cache
    */
   getStateSync(stateRoot: RootHex): CachedBeaconStateAllForks | null {
-    return this.blockStateCache.get(stateRoot, {dontTransferCache: true});
+    return this.blockStateCache.get(stateRoot);
```
Comment (nflaig) [inline packages/beacon-node/src/chain/regen/queued.ts:84]: the comment above explicitly notes that we don't transfer cache, either comment or code needs to be adapted

File: packages/beacon-node/src/chain/blocks/verifyBlocksStateTransitionOnly.ts (hunk 4 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/blocks/verifyBlocksStateTransitionOnly.ts:62]: `dontTransferCache` is used silently inside this call, so I make it explicit. There is nothing changed here.

see https://github.com/ChainSafe/lodestar/blob/393267517436992def2c161f6705526e206c5828/packages/state-transition/src/stateTransition.ts#L100

**Comment by nflaig** [comment]
there is still a clone here https://github.com/ChainSafe/lodestar/blob/42f853f0864b3c4328bcb79095475014b5678b7f/packages/beacon-node/src/api/impl/validator/index.ts#L1045

is it required because we pass state into `createCachedBeaconState`?

**Comment by twoeths** [comment]
> is it required because we pass state into createCachedBeaconState?

good catch, removed it

**Review by nflaig — APPROVED** [review]
LGTM

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.40.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.40.0) :tada:
