### PR TITLE
Run fork-choice spec tests against production code

### LINKED ISSUE #3227: chain/blocks block processor is not properly tested
**Describe the bug**

Block verification does some assumptions to speed up verification, such as validating the signatures afterwards. This code is not tested e2e against many test vectors like the spec tests. Consider running spec tests of block verification against the block processor, not only the state transition itself.

**Expected behavior**

Catch bugs such as https://github.com/ChainSafe/lodestar/pull/3226

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

Our current verify / import block flow are quite complex but are not covered by spec tests. Instead the fork-choice spec tests rely on a lot of custom copied code that may differ from production. This is a huge issue as issues may be fixed in the tests but not on production.

**Description**

- Run fork-choice spec tests against production code

Closes https://github.com/ChainSafe/lodestar/issues/3227

### CODE REVIEW

File: packages/beacon-node/test/spec/presets/fork_choice.ts [hunk 1]
```diff
@@ -54,139 +59,180 @@ const logger = testLogger("spec-test");
...
             }
 
-            state = runStateTranstion(preState, signedBlock, forkchoice, checkpointStateCache, blockDelaySec);
-            // TODO: May be part of runStateTranstion, necessary to commit again?
-            state.commit();
-            cacheState(state, stateCache);
-          } catch (e) {
-            if (validBlock) throw e;
+            // Never run
+            if (process === null) {
```
Comment (dapplion) [inline packages/beacon-node/test/spec/presets/fork_choice.ts]: TEMP, keeping this code here until all issues are solved, then remove

**Comment by dapplion** [comment]
spec test logs are clean, from https://github.com/ChainSafe/lodestar/runs/7376533608?check_suite_focus=true

```
2022-07-17T09:11:06.6577079Z [0m  minimal/altair/fork_choice/ex_ante/pyspec_tests[0m
2022-07-17T09:11:06.6579493Z   [32m  [32m✔[39m[0m[90m ex_ante_sandwich_with_honest_attestation[0m[31m (83ms)[0m
2022-07-17T09:11:06.6579966Z   [32m  [32m✔[39m[0m[90m ex_ante_sandwich_without_attestations[0m[33m (73ms)[0m
2022-07-17T09:11:06.6581427Z   [32m  [32m✔[39m[0m[90m ex_ante_vanilla[0m[33m (72ms)[0m
2022-07-17T09:11:06.6707764Z 
2022-07-17T09:11:06.6710382Z [0m  minimal/altair/fork_choice/get_head/pyspec_tests[0m
2022-07-17T09:11:06.6710886Z   [32m  [32m✔[39m[0m[90m chain_no_attestations[0m[33m (61ms)[0m
2022-07-17T09:11:06.6713246Z   [32m  [32m✔[39m[0m[90m filtered_block_tree[0m[31m (148ms)[0m
2022-07-17T09:11:06.6713628Z   [32m  [32m✔[39m[0m[90m genesis[0m[33m (46ms)[0m
2022-07-17T09:11:06.6714031Z   [32m  [32m✔[39m[0m[90m proposer_boost_correct_head[0m[33m (62ms)[0m
2022-07-17T09:11:06.6717315Z   [32m  [32m✔[39m[0m[90m shorter_chain_but_heavier_weight[0m[33m (74ms)[0m
2022-07-17T09:11:06.6717771Z   [32m  [32m✔[39m[0m[90m split_tie_breaker_no_attestations[0m[33m (65ms)[0m
2022-07-17T09:11:06.6718969Z 
2022-07-17T09:11:06.6719249Z [0m  minimal/altair/fork_choice/on_block/pyspec_tests[0m
2022-07-17T09:11:06.6720970Z   [32m  [32m✔[39m[0m[90m basic[0m[33m (71ms)[0m
2022-07-17T09:11:06.6721983Z   [32m  [32m✔[39m[0m[90m new_finalized_slot_is_justified_checkpoint_ancestor[0m[31m (494ms)[0m
2022-07-17T09:11:06.6722504Z   [32m  [32m✔[39m[0m[90m new_finalized_slot_is_not_justified_checkpoint_ancestor[0m[31m (492ms)[0m
2022-07-17T09:11:06.6726081Z   [32m  [32m✔[39m[0m[90m new_justified_is_later_than_store_justified[0m[31m (476ms)[0m
2022-07-17T09:11:06.6727647Z   [32m  [32m✔[39m[0m[90m on_block_bad_parent_root[0m[33m (46ms)[0m
2022-07-17T09:11:06.6729189Z   [32m  [32m✔[39m[0m[90m on_block_before_finalized[0m[31m (300ms)[0m
2022-07-17T09:11:06.6729603Z   [32m  [32m✔[39m[0m[90m on_block_checkpoints[0m[31m (123ms)[0m
2022-07-17T09:11:06.6731119Z   [32m  [32m✔[39m[0m[90m on_block_finalized_skip_slots[0m[31m (267ms)[0m
2022-07-17T09:11:06.6732797Z   [32m  [32m✔[39m[0m[90m on_block_finalized_skip_slots_not_in_skip_chain[0m[31m (259ms)[0m
2022-07-17T09:11:06.6734243Z   [32m  [32m✔[39m[0m[90m on_block_future_block[0m[33m (51ms)[0m
2022-07-17T09:11:06.6735989Z   [32m  [32m✔[39m[0m[90m on_block_outside_safe_slots_but_finality[0m[31m (394ms)[0m
2022-07-17T09:11:06.6737232Z   [32m  [32m✔[39m[0m[90m on_block_update_justified_checkpoint_within_safe_slots[0m[31m (175ms)[0m
2022-07-17T09:11:06.6737667Z   [32m  [32m✔[39m[0m[90m proposer_boost[0m[33m (58ms)[0m
2022-07-17T09:11:06.6740012Z   [32m  [32m✔[39m[0m[90m proposer_boost_root_same_slot_untimely_block[0m[33m (55ms)[0m
```

```
2022-07-17T09:11:07.3422389Z [0m  minimal/bellatrix/fork_choice/ex_ante/pyspec_tests[0m
2022-07-17T09:11:07.3423179Z   [32m  [32m✔[39m[0m[90m ex_ante_sandwich_with_honest_attestation[0m[33m (74ms)[0m
2022-07-17T09:11:07.3425918Z   [32m  [32m✔[39m[0m[90m ex_ante_sandwich_without_attestations[0m[33m (74ms)[0m
2022-07-17T09:11:07.3427303Z   [32m  [32m✔[39m[0m[90m ex_ante_vanilla[0m[33m (75ms)[0m
2022-07-17T09:11:07.3427760Z 
2022-07-17T09:11:07.3428462Z [0m  minimal/bellatrix/fork_choice/get_head/pyspec_tests[0m
2022-07-17T09:11:07.3429210Z   [32m  [32m✔[39m[0m[90m chain_no_attestations[0m[33m (61ms)[0m
2022-07-17T09:11:07.3430337Z   [32m  [32m✔[39m[0m[90m filtered_block_tree[0m[31m (129ms)[0m
2022-07-17T09:11:07.3431431Z   [32m  [32m✔[39m[0m[90m genesis[0m[31m (202ms)[0m
2022-07-17T09:11:07.3432512Z   [32m  [32m✔[39m[0m[90m proposer_boost_correct_head[0m[31m (240ms)[0m
2022-07-17T09:11:07.3433612Z   [32m  [32m✔[39m[0m[90m shorter_chain_but_heavier_weight[0m[33m (73ms)[0m
2022-07-17T09:11:07.3435016Z   [32m  [32m✔[39m[0m[90m split_tie_breaker_no_attestations[0m[33m (62ms)[0m
2022-07-17T09:11:07.3435241Z 
2022-07-17T09:11:07.3435535Z [0m  minimal/bellatrix/fork_choice/on_block/pyspec_tests[0m
2022-07-17T09:11:07.3436516Z   [32m  [32m✔[39m[0m[90m basic[0m[33m (63ms)[0m
2022-07-17T09:11:07.3437719Z   [32m  [32m✔[39m[0m[90m new_finalized_slot_is_justified_checkpoint_ancestor[0m[31m (464ms)[0m
2022-07-17T09:11:07.3438798Z   [32m  [32m✔[39m[0m[90m new_finalized_slot_is_not_justified_checkpoint_ancestor[0m[31m (498ms)[0m
2022-07-17T09:11:07.3439837Z   [32m  [32m✔[39m[0m[90m new_justified_is_later_than_store_justified[0m[31m (531ms)[0m
2022-07-17T09:11:07.3440878Z   [32m  [32m✔[39m[0m[90m on_block_bad_parent_root[0m[33m (53ms)[0m
2022-07-17T09:11:07.3442107Z   [32m  [32m✔[39m[0m[90m on_block_before_finalized[0m[31m (324ms)[0m
2022-07-17T09:11:07.3443204Z   [32m  [32m✔[39m[0m[90m on_block_checkpoints[0m[31m (124ms)[0m
2022-07-17T09:11:07.3444337Z   [32m  [32m✔[39m[0m[90m on_block_finalized_skip_slots[0m[31m (300ms)[0m
2022-07-17T09:11:07.3445443Z   [32m  [32m✔[39m[0m[90m on_block_finalized_skip_slots_not_in_skip_chain[0m[31m (295ms)[0m
2022-07-17T09:11:07.3446462Z   [32m  [32m✔[39m[0m[90m on_block_future_block[0m[33m (51ms)[0m
2022-07-17T09:11:07.3447599Z   [32m  [32m✔[39m[0m[90m on_block_outside_safe_slots_but_finality[0m[31m (431ms)[0m
2022-07-17T09:11:07.3448723Z   [32m  [32m✔[39m[0m[90m on_block_update_justified_checkpoint_within_safe_slots[0m[31m (202ms)[0m
2022-07-17T09:11:07.3449720Z   [32m  [32m✔[39m[0m[90m proposer_boost[0m[33m (66ms)[0m
2022-07-17T09:11:07.3450876Z   [32m  [32m✔[39m[0m[90m proposer_boost_root_same_slot_untimely_block[0m[33m (66ms)[0m
2022-07-17T09:11:07.3451296Z 
2022-07-17T09:11:07.3452010Z [0m  minimal/bellatrix/fork_choice/on_merge_block/pyspec_tests[0m
2022-07-17T09:11:07.3452690Z   [32m  [32m✔[39m[0m[90m all_valid[0m[33m (59ms)[0m
2022-07-17T09:11:07.3456254Z   [32m  [32m✔[39m[0m[90m block_lookup_failed[0m[33m (70ms)[0m
2022-07-17T09:11:07.3457270Z   [32m  [32m✔[39m[0m[90m too_early_for_merge[0m[33m (59ms)[0m
2022-07-17T09:11:07.3458350Z   [32m  [32m✔[39m[0m[90m too_late_for_merge[0m[33m (57ms)[0m
```

**Review by twoeths — APPROVED** [review]
