### PR TITLE
ci: add native module CPU portability check

### LINKED ISSUE #9042: Celeron N5105 compatibility
### Describe the bug

I tried to run a v1.40 validator client via docker on a Celeron N5105 CPU and got the below error.  

vc-lodestar-1  | Importing key keystore-0.json
vc-lodestar-1  | Processed all keys imported=1, existing=0, total=1
vc-lodestar-1 exited with code 132 (restarting)

I think that this is likely a reoccurrence of https://github.com/ChainSafe/lodestar/issues/8073 

    CPU Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc art arch_perfmon pebs bts
                             rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_
                             deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault epb cat_l2 cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust s
                            mep erms rdt_a rdseed smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_re
                             q vnmi umip waitpkg gfni rdpid movdiri movdir64b md_clear flush_l1d arch_capabilities

### Expected behavior

lodestar can run on CPUs without AVX instructions

### Steps to reproduce

_No response_

### Additional context

Is compatibility with CPUs that don't support AVX part of the release testing?

This was in a VM that I was trying to move from a different computer where it was working.  The VM CPU type was set to 'host'.  It was not able to launch the validator client properly on the N5105 CPU

### Operating system

Linux

### Lodestar version or commit hash

v1.40.0

### PR DESCRIPTION
**Pull request by lodekeeper**
## What

Adds a CI workflow that scans prebuilt native (`.node`) binaries for unconditional AVX/AVX2 instructions. Native modules using AVX **must** have CPUID-based runtime dispatch to avoid SIGILL crashes on CPUs without AVX support.

## Why

Closes #9042. A user running Lodestar v1.40.0 on a Celeron N5105 (no AVX) hit exit code 132 (SIGILL). Root cause: [`@vekexasia/bigint-buffer2@1.1.0`](https://github.com/vekexasia/bigint-swissknife/issues/6) is compiled with hard-coded `-C target-feature=+avx2,+bmi2`, producing 1292 AVX instructions with zero CPUID dispatch.

All other native modules in our tree (`blst`, `node-eth-kzg`, `hashtree`, `libp2p-quic`) have proper CPUID-based runtime detection.

## How it works

After `pnpm install`, the script:
1. Finds all `linux-x64` native `.node` files
2. Counts AVX instructions (YMM register references) via `objdump`
3. Counts CPUID calls (runtime CPU feature detection)
4. Fails if any module has AVX instructions but zero CPUID calls

Triggers on dependency changes (`package.json`, `pnpm-lock.yaml`) and on `workflow_dispatch`.

## Example output

```
OK:   @chainsafe/blst-linux-x64-gnu (104 AVX insns, 9 CPUID calls)
OK:   @chainsafe/hashtree-linux-x64-gnu (6067 AVX insns, 10 CPUID calls)
OK:   @chainsafe/libp2p-quic-linux-x64-gnu (6755 AVX insns, 21 CPUID calls)
OK:   @crate-crypto/node-eth-kzg-linux-x64-gnu (100 AVX insns, 11 CPUID calls)
FAIL: @vekexasia/bigint-buffer2
   1292 AVX instructions, 0 CPUID dispatch calls
   Binary will crash with SIGILL on CPUs without AVX (e.g. Celeron N5105)
```

Upstream issue filed: https://github.com/vekexasia/bigint-swissknife/issues/6

---
> This PR was authored with AI assistance (Lodekeeper 🌟)

### CODE REVIEW

**Comment by lodekeeper** [comment]
**CI note:** The `Check native module portability` failure is **expected and intentional** — it's the new check successfully detecting `@vekexasia/bigint-buffer2`'s unconditional AVX usage (1292 AVX instructions, 0 CPUID dispatch calls). All other native modules pass (proper CPUID-based runtime detection).

This failure is the whole point of the PR — it surfaces the root cause of #9042 in CI so we catch future regressions. The upstream fix is tracked at https://github.com/vekexasia/bigint-swissknife/issues/6.

File: scripts/ci/check_native_portability.sh [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+# check_native_portability.sh
+#
+# Scans prebuilt native (.node) binaries for unconditional AVX/AVX2 usage.
+# Native modules that use AVX instructions MUST have CPUID-based runtime
+# dispatch to fall back on CPUs without AVX support (e.g. Intel Atom/Celeron).
+#
+# Catches issues like https://github.com/ChainSafe/lodestar/issues/9042
+# where a dependency was compiled with hard-coded -C target-feature=+avx2.
+
+set -euo pipefail
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply scripts/ci/check_native_portability.sh:11]: @gemini-code-assist Applied in 177f1b8 — added `command -v objdump` guard with graceful skip. Thanks!

File: scripts/ci/check_native_portability.sh [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+while IFS= read -r node_file; do
+  found=1
+  # Relative path from node_modules for readable output
+  name=$(echo "$node_file" | sed 's|.*node_modules/||;s|/[^/]*\.node$||')
+
+  # Count AVX instructions (YMM register = 256-bit AVX)
+  ymm_count=$(objdump -d "$node_file" 2>/dev/null | grep -c "ymm" || true)
+
+  # Count CPUID calls (runtime CPU feature detection)
+  cpuid_count=$(objdump -d "$node_file" 2>/dev/null | grep -c "cpuid" || true)
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply scripts/ci/check_native_portability.sh]: @gemini-code-assist Applied — disassemble once, grep the stored output. Also added `|| true` on the `objdump` call itself for robustness.

File: scripts/ci/check_native_portability.sh [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+echo ""
+
+found=0
+while IFS= read -r node_file; do
+  found=1
+  # Relative path from node_modules for readable output
+  name=$(echo "$node_file" | sed 's|.*node_modules/||;s|/[^/]*\.node$||')
+
+  # Count AVX instructions (YMM register = 256-bit AVX)
+  ymm_count=$(objdump -d "$node_file" 2>/dev/null | grep -c "ymm" || true)
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply scripts/ci/check_native_portability.sh]: @chatgpt-codex-connector Good point 👍. Expanded detection in 177f1b8 to match common VEX-prefix SIMD mnemonics (`vmov`, `vadd`, `vzeroupper`, `vfmadd`, etc.) that also SIGILL on non-AVX CPUs. Reports YMM count and VEX-encoded count separately for diagnostics.

File: .github/workflows/native-portability.yml [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+on:
+  pull_request:
+    paths:
+      - "package.json"
+      - "pnpm-lock.yaml"
+      - "packages/*/package.json"
+      - "scripts/ci/check_native_portability.sh"
+  push:
+    branches: [unstable, stable]
```
Comment (nflaig) [inline .github/workflows/native-portability.yml:8]: we wanna run this on PRs mostly, not on push only, please align this with existing workflows, eg. unit tests

File: scripts/ci/check_native_portability.sh [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+
+# ---------------------------------------------------------------------------
+# Known portability issues (package name prefix → tracking issue URL)
+#
+# Packages listed here will be reported as WARN instead of FAIL.
+# Remove entries once the upstream dependency ships a fixed version.
+# ---------------------------------------------------------------------------
+declare -A KNOWN_PORTABILITY_ISSUES=(
+  ["@vekexasia/bigint-buffer2"]="https://github.com/nicolo-ribaudo/bigint-buffer/issues/1"
+)
```
Comment (nflaig) [inline scripts/ci/check_native_portability.sh]: `KNOWN_PORTABILITY_ISSUES` shouldn't exist, we can wait until a new bigint buffer release with a fix is out before merging this PR

File: .github/workflows/native-portability.yml [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+      - "packages/*/package.json"
+      - "scripts/ci/check_native_portability.sh"
+  workflow_dispatch:
+
+jobs:
+  check-native-portability:
+    name: Check native module portability
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
```
Comment (nflaig) [inline .github/workflows/native-portability.yml:17]: are the up to thae with https://github.com/ChainSafe/lodestar/pull/9048, please double check, update the branch against unstable please

File: .github/workflows/native-portability.yml (hunk 4 above)
Comment (lodekeeper) [reply .github/workflows/native-portability.yml:8]: Removed paths filter, aligned with test.yml pattern (`push: [unstable, stable]` + bare `pull_request:` + `workflow_dispatch:`). Pushed in 68edf2a.

File: scripts/ci/check_native_portability.sh (hunk 5 above)
Comment (lodekeeper) [reply scripts/ci/check_native_portability.sh]: Removed the entire `KNOWN_PORTABILITY_ISSUES` mechanism — the script now fails hard on any unconditional AVX. We'll wait for the bigint-buffer upstream fix before merging.

File: .github/workflows/native-portability.yml (hunk 6 above)
Comment (lodekeeper) [reply .github/workflows/native-portability.yml:17]: Merged unstable (which includes #9048) and updated `pnpm/action-setup` hash to match the #9048 bump (`@fc06bc1`). `actions/checkout` and `actions/setup-node` were already aligned.

**Comment by nflaig** [comment]
@lodekeeper can you check the bigint library for a new release and bump it once a release with the CPU fix is out in this PR

**Comment by lodekeeper** [comment]
Checked — the AVX2 fix landed upstream:

- [`e3ebb89`](https://github.com/vekexasia/bigint-swissknife/commit/e3ebb892) (2026-03-16): `fix: remove hard-coded AVX2 target feature for x86_64`
- [`7ff9fef`](https://github.com/vekexasia/bigint-swissknife/commit/7ff9fef3) (2026-03-17): bumped to `1.1.1`

However, `@vekexasia/bigint-buffer2@1.1.1` is **not yet published to npm** — latest is still `1.1.0`. I'll monitor and bump + push as soon as it lands on the registry.

**Comment by nflaig** [comment]
@lodekeeper the release is out

**Comment by lodekeeper** [comment]
Bumped to `@vekexasia/bigint-buffer2@1.1.1` in 9a27947. Portability check passes locally — bigint-buffer2 now reports `(no AVX)` ✅

Had to add `@vekexasia/bigint-buffer2` to `minimumReleaseAgeExclude` in `pnpm-workspace.yaml` since the release is brand new and the 48h age gate blocked resolution.

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.41.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.41.0) :tada:
