### PR TITLE
fix: improve forkchoice getBlock hasBlock

### LINKED ISSUE #5901: Improve forkchoice hasBlock and getBlock
### Describe the bug

The `hasBlock*()` function is as below:

```
hasBlockHex(blockRoot: RootHex): boolean {
    return this.protoArray.hasBlock(blockRoot) && this.isDescendantOfFinalized(blockRoot);
  }
```

the `isDescendantOfFinalized()` function is redundant and has low performance since it involves a for loop, we should use new proto array api `isFinalizedRootOrDescendant()` (from #5867) instead

### Expected behavior

No forkchoice loop in this function

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.10.0

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Improve forkchoice `getBlock*()` and `hasBlock*()` functions

**Description**

- Use new api `isFinalizedRootOrDescendant` of ProtoArray so that we don't have to loop through nodes proto array

Closes #5901

### CODE REVIEW

**Review by wemeetagain — APPROVED** [review]

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 1]
```diff
@@ -592,7 +592,12 @@ export class ForkChoice implements IForkChoice {
    * Returns `true` if the block is known **and** a descendant of the finalized root.
    */
   hasBlockHex(blockRoot: RootHex): boolean {
-    return this.protoArray.hasBlock(blockRoot) && this.isDescendantOfFinalized(blockRoot);
+    const node = this.protoArray.getNode(blockRoot);
+    if (node === undefined) {
+      return false;
+    }
+
+    return this.protoArray.isFinalizedRootOrDescendant(node);
```
Comment (dapplion) [inline packages/fork-choice/src/forkChoice/forkChoice.ts:600]: A bit unrelated to the PR, but can you merge all the if statements in https://github.com/ChainSafe/lodestar/blob/67d0aea6354b577843f516c17bf6da14f547204b/packages/fork-choice/src/protoArray/protoArray.ts#L752

**Review by dapplion — APPROVED** [review]

File: packages/fork-choice/src/forkChoice/forkChoice.ts (hunk 1 above)
Comment (twoeths) [reply packages/fork-choice/src/forkChoice/forkChoice.ts:600]: I created https://github.com/ChainSafe/lodestar/pull/5908

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.11.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.11.0) :tada:
