### PR TITLE
Unify attestation validation

### LINKED ISSUE #2249: Prater logs - FORKCHOICE_ERROR_INVALID_ATTESTATION
**Describe the bug**

In Prater genesis running our Beacon node in very overloaded conditions this error appears multiple times only after the first log time shown below.

```
2021-03-23 15:22:46 [CHAIN]         verbose: Block processed slot=36, root=0x7a93e1f09d0c4c398cb70a4d965acb274b56e8ac75cf47cca1479b7383d595d5
2021-03-23 15:22:46 [CHAIN]         verbose: New chain head headSlot=36, headRoot=0x7a93e1f09d0c4c398cb70a4d965acb274b56e8ac75cf47cca1479b7383d595d5
2021-03-23 15:22:46 [CHAIN]           error: Non AttestationError received code=FORKCHOICE_ERROR_INVALID_ATTESTATION, err={"code":"PAST_EPOCH","attestationEpoch":1,"currentEpoch":3}
Error: FORKCHOICE_ERROR_INVALID_ATTESTATION
    at LodestarForkChoice.validateOnAttestation (/root/lodestar/packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts:630:13)
    at LodestarForkChoice.onAttestation (/root/lodestar/packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts:377:10)
    at processAttestation (/root/lodestar/packages/lodestar/src/chain/attestation/process.ts:59:14)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at processAttestationJob (/root/lodestar/packages/lodestar/src/chain/attestation/processor.ts:45:5)
    at AttestationProcessor.processAttestationJob (/root/lodestar/packages/lodestar/src/chain/attestation/processor.ts:28:5)
    at async Promise.all (index 88)
    at BeaconChain.onBlock (/root/lodestar/packages/lodestar/src/chain/eventHandlers.ts:235:5)

... 42 times more same error
```

- Why is the chain not expecting this error? `error: Non AttestationError received`
- Why did this attestation make it to the ForkChoice? Maybe it took so long to process that it was still in the same epoch on the chain and then not when it reached the ForkChoice.
- Seems that some validations are done twice in the Chain and ForkChoice, is that expected?

**Expected behavior**

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ Forkchoice throws attestation error and lodestar does not understand it's attestation error
+ It's a waste to maintain attestation validation in both lodestar and forkchoice (in order to follow the spec)

**Description**

+ Unify attestation validation in forkchoice
+ Lodestar handle its errors and transform to its own AttestationError

Closes #2249

### CODE REVIEW

File: packages/lodestar/src/chain/attestation/processor.ts [hunk 1]
```diff
@@ -41,10 +46,77 @@ export class AttestationProcessor {
...
+/**
+ * Map ForkChoice attestation error to lodestar version.
+ */
+function mapAttestationError(e: Error, job: IAttestationJob): AttestationError | null {
+  if (e instanceof ForkChoiceError && e.type.code === ForkChoiceErrorCode.INVALID_ATTESTATION) {
+    const attError = e.type.err;
+    switch (attError.code) {
+      case InvalidAttestationCode.EMPTY_AGGREGATION_BITFIELD:
+        return new AttestationError({
+          code: AttestationErrorCode.EMPTY_AGGREGATION_BITFIELD,
```
Comment (wemeetagain) [inline packages/lodestar/src/chain/attestation/processor.ts]: It seems that the errors map 1 to 1?
Can we have an implementation that looks like this (may need some tweaking):
```ts
if (e instanceof ForkChoiceError && e.type.code === ForkChoiceErrorCode.INVALID_ATTESTATION) {
    const attError = e.type.err;
    (attError as AttestationError).job = job;
    return attError as AttestationError;
  }
```
This way we can retain the right stack trace

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 2]
```diff
@@ -720,6 +720,17 @@ export class ForkChoice implements IForkChoice {
         },
       });
     }
+
+    if (this.fcStore.currentSlot < indexedAttestation.data.slot + 1) {
```
Comment (wemeetagain) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: This check should go on L657, be done before checking the protoarray

**Review by wemeetagain — APPROVED** [review]
