### PR TITLE
fix: broken status in getPeers endpoint

### LINKED ISSUE #8007: Peer data `earliestAvailableSlot` is undefined
cannot fetch peers via `getPeers` api post-fulu

```
Jun-25 08:36:23.302[rest]            [31merror[39m: Req req-hq getPeers error - Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toString')
    at UintNumberType.toJson (file:///usr/app/node_modules/@chainsafe/ssz/lib/type/uint.js:179:22)
    at ContainerType.toJson (file:///usr/app/node_modules/@chainsafe/ssz/lib/type/container.js:273:39)
    at NetworkCore._dumpPeer (file:///usr/app/packages/beacon-node/lib/network/core/networkCore.js:338:65)
    at file:///usr/app/packages/beacon-node/lib/network/core/networkCore.js:352:105
    at Array.map (<anonymous>)
    at NetworkCore.dumpPeers (file:///usr/app/packages/beacon-node/lib/network/core/networkCore.js:352:66)
    at dumpPeers (file:///usr/app/packages/beacon-node/lib/network/core/networkCoreWorker.js:113:27)
    at /usr/app/node_modules/@chainsafe/threads/dist/worker/index.js:109:26
    at Generator.next (<anonymous>)
    at /usr/app/node_modules/@chainsafe/threads/dist/worker/index.js:8:71
```

it looks like `earliestAvailableSlot` is `undefined` for some peers, likely because we connected pre-fulu

this happens becasue we use `ssz.fulu.Status` here which requires `earliestAvailableSlot` to be set to a `number`

https://github.com/ChainSafe/lodestar/blob/2af9ff83264e0406411d70e0b6e5b176345909d6/packages/beacon-node/src/network/core/networkCore.ts#L423

### PR DESCRIPTION
**Pull request by matthewkeil**
**Motivation**

fixes #8007

peers that survive across fork boundary have old status in peer manager and ssz.toJson fails if the value is undefined

### CODE REVIEW

**Review by nflaig — APPROVED** [review]

File: packages/beacon-node/src/network/core/networkCore.ts [hunk 1]
```diff
@@ -418,6 +419,10 @@ export class NetworkCore implements INetworkCore {
   private _dumpPeer(peerIdStr: string, connections: Connection[]): routes.lodestar.LodestarNodePeer {
     const peerData = this.peersData.connectedPeers.get(peerIdStr);
     const fork = this.config.getForkName(this.clock.currentSlot);
+    if (isForkPostFulu(fork) && peerData) {
```
Comment (nflaig) [inline packages/beacon-node/src/network/core/networkCore.ts]:
```suggestion
    if (isForkPostFulu(fork) && peerData?.status) {
```
