### PR TITLE
fix: add log and metrics to ColumnReconstructionTracker

### LINKED ISSUE #8402: [block-input-refactor] add logs for ColumnReconstructionTracker
### Problem description

in a deployed node of #8200 there were some late block import and I was not able to trace how ColumnReconstructionTracker helps in that case

### Solution description

add logs for ColumnReconstructionTracker

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- we want to know more insight of ColumnReconstructionTracker

**Description**

- add logs to ColumnReconstructionTracker
- fix metrics of ColumnReconstructionTracker: centralize to 1 place and make it better to render on Grafana
- remove unused error

Closes #8402

### CODE REVIEW

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts [hunk 1]
```diff
@@ -64,9 +64,23 @@ export class ColumnReconstructionTracker {
...
+      recoverDataColumnSidecars(blockInput, this.emitter, this.metrics)
+        .then((result) => {
+          this.metrics?.recoverDataColumnSidecars.reconstructionResult.inc({result});
+          this.logger.debug("Data column sidecar reconstruction complete", {...logCtx, result});
+        })
+        .catch((e) => {
+          this.metrics?.recoverDataColumnSidecars.reconstructionResult.inc({
+            result: DataColumnReconstructionCode.Failed,
+          });
+          this.logger.error("Error during data column sidecar reconstruction", logCtx, e as Error);
```
Comment (wemeetagain) [inline packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]:
```suggestion
          this.logger.debug("Error during data column sidecar reconstruction", logCtx, e as Error);
```

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.35.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.35.0) :tada:
