### PR TITLE
fix: unknown block sync to subscribe/unsubscribe to network events

### LINKED ISSUE #5653: Only enable unknown block sync after block is synced
### Describe the bug

As found in https://github.com/ChainSafe/lodestar/issues/5650#issuecomment-1592822730, when node is syncing it may also receive unknown block root event (especially in a setup with fallback urls), there is no need to search for block at that time

also this is to avoid this case https://github.com/ChainSafe/lodestar/blob/2eddf466394680cb1c6a24700b9a3a2958a3ef90/packages/beacon-node/src/sync/unknownBlock.ts#L228

### Expected behavior

Only start/init unknown block sync once the node is synced

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.9.0-rc.2

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Unknown block sync received unknown block roots while the node is syncing, this lead to:
- Pending blocks may be filled up quickly
- Incorrect catch of this case https://github.com/ChainSafe/lodestar/blob/2eddf466394680cb1c6a24700b9a3a2958a3ef90/packages/beacon-node/src/sync/unknownBlock.ts#L228

**Description**

- Add subscribe/unsubscribe methods to UnknownBlock sync
- Only subscribe once the node is synced, similar to `network.subscribeGossipCoreTopics()`

Closes #5653

### CODE REVIEW

File: packages/beacon-node/src/sync/sync.ts [hunk 1]
```diff
@@ -196,36 +199,48 @@ export class BeaconSync implements IBeaconSync {
...
+        this.network
+          .subscribeGossipCoreTopics()
+          .then(() => {
+            this.metrics?.syncSwitchGossipSubscriptions.inc({action: "subscribed"});
+            this.logger.info("Subscribed gossip core topics");
+          })
+          .catch((e) => {
+            this.logger.error("Error subscribing to gossip core topics", {}, e);
+          });
+      }
```
Comment (dapplion) [inline packages/beacon-node/src/sync/sync.ts:213]: Can we rebundle this if statement as before? If you need you can re-order the conditions
```js
    if (
      state === SyncState.Synced &&
      this.chain.clock.currentEpoch >= MIN_EPOCH_TO_START_GOSSIP &&
      !this.network.isSubscribedToGossipCoreTopics()
    ) {
```

**Review by dapplion — COMMENTED** [review]
I can't think of any immediate issues with this, let's merge it. Added a minor comment to reduce diff

**Review by dapplion — APPROVED** [review]

File: packages/beacon-node/src/sync/sync.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/sync/sync.ts:213]: yes we can do it but then the below `this.unknownBlockSync.subscribeToNetwork();` has to depend on `this.network.isSubscribedToGossipCoreTopics()`. Logically it's the same but it'll make it hard to reason about later.

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.9.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.9.0) :tada:
