### PR TITLE
fix: bootstrap already-open libp2p connections at PeerManager startup

### LINKED ISSUE #8779: Handle peers connected before PeerManager init
See https://github.com/ChainSafe/lodestar/pull/8770 for details.

### PR DESCRIPTION
**Pull request by lodekeeper**
## Summary

PeerManager.connectedPeers map was empty at startup even when libp2p already had established connections (e.g., from bootnodes). This caused STATUS not being sent to peers, violating the consensus spec requirement that the dialing client MUST send a Status request upon connection.

This is the same issue addressed in PR #8770 (`bal-devnet-2`), ported to `unstable`.

## Changes

1. Extract core peer-tracking logic from `onLibp2pPeerConnect` into a reusable `trackLibp2pConnection()` helper
2. Add `bootstrapAlreadyOpenConnections()` that seeds `connectedPeers` from existing libp2p connections at init
3. Defer initial status/ping sweep via `setTimeout` to avoid listener-order race

## Test plan

- Added E2E test verifying peers connected before PeerManager init are tracked
- Type check: `pnpm --filter @lodestar/beacon-node check-types` ✅
- Validated in cross-client EPBS devnet (LH+LS): resolved immediate peer disconnect at startup

Closes https://github.com/ChainSafe/lodestar/issues/8779

> [!NOTE]
> This PR was authored with AI assistance (Claude/Codex).

### CODE REVIEW

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 1]
```diff
@@ -692,46 +697,63 @@ export class PeerManager {
...
+        const peerIdStr = connection.remotePeer.toString();
+        if (this.connectedPeers.has(peerIdStr)) {
+          continue;
+        }
+
+        if (this.trackLibp2pConnection(connection, {overwriteExisting: false, triggerHandshakeNow: false})) {
+          bootstrapped++;
+        }
+      }
+    }
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/network/peers/peerManager.ts:713]: Good point about the redundant iterations. In practice, `getConnectionsMap` groups connections by peer, so the outer loop already iterates per-peer. The inner loop typically has 1 connection per peer (multiple connections to the same peer are pruned by libp2p). But the early `break` after successful tracking is a nice defensive optimization.

Since this is a backport keeping minimal diff, I'd prefer not to restructure the loop here. Happy to include it if this lands as a follow-up refactor though.

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 2]
```diff
@@ -196,6 +196,11 @@ export class PeerManager {
 
     this.lastStatus = this.statusCache.get();
 
+    // A connection may already be open before listeners are attached.
+    // Seed those peers and trigger status/ping on the next macrotask.
+    this.bootstrapAlreadyOpenConnections();
+    setTimeout(() => this.pingAndStatusTimeouts(), 0);
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/network/peers/peerManager.ts]: Valid concern. The `setTimeout` in the bootstrap path could fire after `close()` if the manager is torn down quickly. In practice the timeout is very short (next tick via `setTimeout(fn, 0)`), and `pingAndStatusTimeouts` is guarded by `connectedPeers` which would be empty after close. But storing the handle and clearing in `close()` is the correct defensive pattern.

I'll add this fix — it's a one-liner to store the timeout ID and clear it in `close()`.

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 3]
```diff
@@ -196,6 +197,13 @@ export class PeerManager {
 
     this.lastStatus = this.statusCache.get();
 
+    // A connection may already be open before listeners are attached.
+    // Seed those peers so they are tracked in connectedPeers immediately.
+    this.bootstrapAlreadyOpenConnections();
+    // Defer status/ping to the next macrotask so the heartbeat interval and
+    // event listeners are fully registered before we begin handshakes.
+    this.bootstrapTimeout = setTimeout(() => this.pingAndStatusTimeouts(), 0);
```
Comment (nflaig) [inline packages/beacon-node/src/network/peers/peerManager.ts]: you can use `callInNextEventLoop` here

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 4]
```diff
@@ -230,6 +238,7 @@ export class PeerManager {
     );
     this.networkEventBus.off(NetworkEvent.reqRespRequest, this.onRequest);
     for (const interval of this.intervals) clearInterval(interval);
+    if (this.bootstrapTimeout) clearTimeout(this.bootstrapTimeout);
```
Comment (nflaig) [inline packages/beacon-node/src/network/peers/peerManager.ts]: why do we need to keep track of the timeout? it's just set with value 0 and will be cleared in the next eventloop tick anyways?

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 5]
```diff
@@ -692,46 +701,59 @@ export class PeerManager {
...
+      for (const connection of connections) {
+        // trackLibp2pConnection handles deduplication via overwriteExisting: false
+        if (this.trackLibp2pConnection(connection, {overwriteExisting: false, triggerHandshakeNow: false})) {
+          bootstrapped++;
+        }
+      }
+    }
+
+    if (bootstrapped > 0) {
+      this.logger.info("Bootstrapped already-open libp2p peers", {bootstrapped});
```
Comment (nflaig) [inline packages/beacon-node/src/network/peers/peerManager.ts]: this should be a verbose log, not info

File: packages/beacon-node/src/network/peers/peerManager.ts (hunk 3 above)
Comment (lodekeeper) [reply packages/beacon-node/src/network/peers/peerManager.ts]: Done — switched to `callInNextEventLoop` from `../../util/eventLoop.js`.

File: packages/beacon-node/src/network/peers/peerManager.ts (hunk 4 above)
Comment (lodekeeper) [reply packages/beacon-node/src/network/peers/peerManager.ts]: You're right — it fires on the next tick, it'll be long gone before `close()` is ever called. Removed the tracking entirely.

File: packages/beacon-node/src/network/peers/peerManager.ts (hunk 5 above)
Comment (lodekeeper) [reply packages/beacon-node/src/network/peers/peerManager.ts]: Changed to verbose.

**Review by nflaig — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.41.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.41.0) :tada:
