### PR TITLE
YargsError handling across whole lodestar-cli package

### LINKED ISSUE #1099: Use custom error for expected CLI exceptions
Use a custom error for CLI errors that are expected and should not trigger an exception nor show a stack trace. Then catch that error at the top level, log the error message and exit cleanly with `process.exit(1)`.

Check https://github.com/ChainSafe/lodestar/pull/1093 and https://github.com/ChainSafe/lodestar/pull/1093#discussion_r449721256 with its `YargsError` as a reference.

### PR DESCRIPTION
**Pull request by 3xtr4t3rr3str14l**
fixes #1099 by using YargsOptions across the whole lodestar-cli package

### CODE REVIEW

File: packages/lodestar-cli/src/cmds/account/cmds/validator/deposit.ts [hunk 1]
```diff
@@ -96,7 +96,7 @@ export async function handler(options: IAccountValidatorDepositOptions): Promise
       value: (depositData.amount * BigInt(1e9)).toString(),
       data: rlp
     });
-    if (!tx.hash) throw Error("No transaction hash");
+    if (!tx.hash) throw new YargsError("No transaction hash");
```
Comment (dapplion) [inline packages/lodestar-cli/src/cmds/account/cmds/validator/deposit.ts]: This is not a quite "expected" error so I would throw a regular error

File: packages/lodestar-cli/src/cmds/beacon/cmds/init/index.ts [hunk 2]
```diff
@@ -14,7 +14,13 @@ export function builder(yargs: Argv<IBeaconArgs>): Argv<IBeaconArgs> {
...
   const args = parseArgs(yargs) as IBeaconInitArgs;
   if (args.templateConfigFile) {
-    yargs.config(readBeaconConfig(args.templateConfigFile));
+    try {
+      yargs.config(readBeaconConfig(args.templateConfigFile));
+    } catch(error) {
+      // eslint-disable-next-line no-console
+      console.log(` ✖ ${error.message}\n`);
+      process.exit(1);
+    }
```
Comment (dapplion) [inline packages/lodestar-cli/src/cmds/beacon/cmds/init/index.ts]: Errors thrown here are not catched by yargs.fail handler? I would avoid using process.exit() anywhere but a very predictable spot, like in the root index of the CLI.

File: packages/lodestar-cli/src/depositContract/depositData.ts [hunk 3]
```diff
@@ -35,7 +36,7 @@ export function decodeEth1TxData(
   // Sanity check
   const depositDataRoot = config.types.DepositData.hashTreeRoot(depositData);
   if (depositDataRoot != root)
-    throw Error("deposit data root mismatch");
+    throw new YargsError("deposit data root mismatch");
```
Comment (dapplion) [inline packages/lodestar-cli/src/depositContract/depositData.ts]: This is not an "expected" error, I would throw a regular error

File: packages/lodestar-cli/src/util/file.ts [hunk 4]
```diff
@@ -31,7 +32,7 @@ export function stringify<T=Json>(obj: T, fileFormat: FileFormat): string {
       contents = JSON.stringify(obj, null, 2);
       break;
     default:
-      throw new Error("Invalid filetype");
+      throw new YargsError("Invalid filetype");
```
Comment (dapplion) [inline packages/lodestar-cli/src/util/file.ts]: This is not an "expected" error, I would throw a regular error

**Review by dapplion — CHANGES_REQUESTED** [review]
I would exclusively use YargsError for expected errors that just by seeing the error message the user can take action and correct the error. Such as `"Must supply either keystorePath, rpcUrl, or ipcPath"`. Any other error that is not that obvious must have a stack trace so we can help users debug the problem.

File: packages/lodestar-cli/src/cmds/beacon/cmds/init/index.ts (hunk 2 above)
Comment (3xtr4t3rr3str14l) [reply packages/lodestar-cli/src/cmds/beacon/cmds/init/index.ts]: yeah i wasn't able to figure out how get the errors to be thrown to the top-level for `beacon`.  for now, i'll take out that process.exit, but after this PR, i might start to look into refactoring mergeBeaconOptions and see if maybe that's the culprit

File: packages/lodestar-cli/src/util/file.ts (hunk 4 above)
Comment (3xtr4t3rr3str14l) [reply packages/lodestar-cli/src/util/file.ts]: done

File: packages/lodestar-cli/src/depositContract/depositData.ts (hunk 3 above)
Comment (3xtr4t3rr3str14l) [reply packages/lodestar-cli/src/depositContract/depositData.ts]: done

File: packages/lodestar-cli/src/cmds/account/cmds/validator/deposit.ts (hunk 1 above)
Comment (3xtr4t3rr3str14l) [reply packages/lodestar-cli/src/cmds/account/cmds/validator/deposit.ts]: done

File: packages/lodestar-cli/src/cmds/beacon/cmds/run/index.ts [hunk 5]
```diff
@@ -14,9 +14,18 @@ export const description = "Run a lodestar beacon node";
...
+  try {
+    yargsConfig = yargs
+      .options(beaconRunOptions)
+      .config(readBeaconConfig(args.config)) as unknown as Argv<IBeaconArgs & Partial<IBeaconNodeOptions>>;
+  } catch(error) {
+    // eslint-disable-next-line no-console
+    console.log(` ✖ ${error.message}\n`);
+  }
+
+  return yargsConfig;
```
Comment (dapplion) [inline packages/lodestar-cli/src/cmds/beacon/cmds/run/index.ts]: Is this type-safe? In case of error it will be returning an undefined object that the Typescript compilers assumes is a defined object.

**Comment by dapplion** [comment]
I would exclusively use YargsError in yargs handlers, so to files within `lodestar-cli/src/cmds`.

File: packages/lodestar-cli/src/cmds/beacon/cmds/run/index.ts (hunk 5 above)
Comment (3xtr4t3rr3str14l) [reply packages/lodestar-cli/src/cmds/beacon/cmds/run/index.ts]: fixed

**Comment by 3xtr4t3rr3str14l** [comment]
> I would exclusively use YargsError in yargs handlers, so to files within `lodestar-cli/src/cmds`.

ah yeah i see what you mean.  going to push something for that in a sec

**Review by dapplion — DISMISSED** [review]

File: packages/lodestar-cli/src/util/file.ts [hunk 6]
```diff
@@ -21,7 +21,7 @@ export function parse<T=Json>(contents: string, fileFormat: FileFormat): T {
     case FileFormat.json:
       return JSON.parse(contents);
     default:
-      throw new Error("Invalid filetype");
+      throw Error("Invalid filetype");
```
Comment (wemeetagain) [inline packages/lodestar-cli/src/util/file.ts]: `new` got omitted off here, this should still be `throw new Error`, same with the error in `stringify` in this file.

Comment (3xtr4t3rr3str14l) [reply packages/lodestar-cli/src/util/file.ts]: fixed

**Review by wemeetagain — APPROVED** [review]
