### PR TITLE
Sync: handle failed to get block range

### LINKED ISSUE #1433: Initial Sync: handle waitForPeers
**Describe the bug**
Initial Sync misunderstand that "no peer" means no block in range
image

**Expected behavior**
Initial Sync should retry same range when waiting for peers

### PR DESCRIPTION
**Pull request by twoeths**
resolves #1433 

In case of failed to fetch block range, we need to yield null instead of yield nothing so that we can handle in `processSyncBlocks`. Otherwise it's not possible to distinguish empty range vs failed range in `processSyncBlocks` since it always pass `for..await`.

### CODE REVIEW

File: packages/lodestar/src/sync/initial/fast/index.ts [hunk 1]
```diff
@@ -121,7 +121,7 @@ export class FastSync extends (EventEmitter as {new (): InitialSyncEventEmitter}
   };
 
   private setBlockImportTarget = (fromSlot?: Slot): void => {
-    const lastTarget = fromSlot || this.blockImportTarget;
+    const lastTarget = typeof fromSlot === "number" ? fromSlot : this.blockImportTarget;
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/initial/fast/index.ts]: I think you are looking for https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing :smile:

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 2]
```diff
@@ -95,7 +95,7 @@ export class NaiveRegularSync extends (EventEmitter as {new (): RegularSyncEvent
   }
 
   private setTarget = (newTarget?: Slot, triggerSync = true): void => {
-    newTarget = newTarget || this.getNewTarget();
+    newTarget = typeof newTarget === "number" ? newTarget : this.getNewTarget();
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/regular/naive/naive.ts]: same as above

**Review by mpetrunic — COMMENTED** [review]
Seems good, just small syntax sugar notice

**Review by mpetrunic — DISMISSED** [review]

**Comment by mpetrunic** [comment]
@tuyennhv seems like there are lint errors

**Review by mpetrunic — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]
