### PR TITLE
fix: set Eth-Consensus-Version header in publish block requests

### LINKED ISSUE #6580: Eth-Consensus-Version header is missing in publish block requests
### Describe the bug

The spec requires to set Eth-Consensus-Version header in publish block requests

[blocks.v2.yaml#L39-L44](https://github.com/nflaig/beacon-APIs/blob/425824e42ff55a4e3c06ab2d434232d8ea2b543e/apis/beacon/blocks/blocks.v2.yaml#L39-L44)
```yaml
    - in: header
      schema:
        $ref: '../../../beacon-node-oapi.yaml#/components/schemas/ConsensusVersion'
      required: true
      name: Eth-Consensus-Version
      description: "Version of the block being submitted."
```

While Lodestar itself uses the request payload to determine the fork type from `data.message.slot` other clients like Prysm BN require this header to be set.

https://github.com/ChainSafe/lodestar/blob/129f300d143b0447978e06e575f9a2c7c31d7b26/packages/api/src/beacon/routes/beacon/block.ts#L296-L298

### Expected behavior

Set all headers as required by the spec

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.17.0

### PR DESCRIPTION
**Pull request by jeluard**
**Motivation**

Follow the [beacon-APIs](https://github.com/ethereum/beacon-APIs) specs.

Note that [submitBlindedBlock](https://github.com/ChainSafe/lodestar/blob/59a49ff945dfef6831d282c85f3818446fefb9e9/packages/api/src/builder/routes.ts#L57) reuses [publishBlindedBlock](https://github.com/ChainSafe/lodestar/blob/59a49ff945dfef6831d282c85f3818446fefb9e9/packages/api/src/builder/routes.ts#L81) serializers.

**Description**

Properly sets `Eth-Consensus-Version` when calling relevant beacon-APIs endpoints. This is a short term fix. The proper solution will ship via a later refactoring.

Fixes https://github.com/ChainSafe/lodestar/issues/6580

### CODE REVIEW

File: packages/api/src/beacon/routes/beacon/block.ts [hunk 1]
```diff
@@ -319,6 +319,12 @@ export function getReqSerializers(config: ChainForkConfig): ReqSerializers<Api,
     fromJson: (data) => getSignedBlindedBeaconBlockType(data as allForks.SignedBlindedBeaconBlock).fromJson(data),
   };
 
+  function extractSlot(signedBlockOrContents: allForks.SignedBeaconBlockOrContents): Slot {
+    return isSignedBlockContents(signedBlockOrContents)
```
Comment (nflaig) [inline packages/api/src/beacon/routes/beacon/block.ts:323]: this logic is only for (full) signed block and not blinded block, in case of blinded block the slot is always accessible via `data.message.slot` even post deneb

**Review by nflaig — CHANGES_REQUESTED** [review]
Need to make sure to test blinded block publish flow as well, can be easily done by adding `--blindedLocal` flag

File: packages/api/src/beacon/routes/beacon/block.ts [hunk 2]
```diff
@@ -335,6 +341,7 @@ export function getReqSerializers(config: ChainForkConfig): ReqSerializers<Api,
       writeReq: (item, {broadcastValidation} = {}) => ({
         body: AllForksSignedBlockOrContents.toJson(item),
         query: {broadcast_validation: broadcastValidation},
+        headers: {"Eth-Consensus-Version": config.getForkName(extractSlot(item))},
```
Comment (nflaig) [inline packages/api/src/beacon/routes/beacon/block.ts:344]: nit: I would probably just inline the logic here, avoids jumping in multiple functions if you wanna review the code but doesn't matter much for this change

**Review by nflaig — COMMENTED** [review]
Looks good to me, giving this a try locally as spec tests don't cover headers yet

**Review by nflaig — APPROVED** [review]
LGTM

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada:
