### PR TITLE
fix genesisStateFile flag

### LINKED ISSUE #1188: genesisStateFile not being copied over to beacon.config.json during beacon init
**Describe the bug**

when i run `yarn run cli beacon init --template-config-file altona.json --chain.genesisStateFile=genesis.ssz --rootDir .altona` (or if I omit the cli parameter and include chain.genesisStateFile as `"genesisStateFile": "genesis.ssz",` in my altona.json), I don't see the genesisStateFile parameter copied over in the resultant beacon.config.json

**Expected behavior**

the genesisStateFile parameter should be copied over to the resultant beacon.config.json both when passed as a cli option and when specified in the altona.json

### PR DESCRIPTION
**Pull request by 3xtr4t3rr3str14l**
fixes #1188

### CODE REVIEW

File: packages/lodestar-cli/src/cmds/init/handler.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ export async function initHandler(options: IBeaconArgs & IGlobalArgs): Promise<v
     Object.assign(options, deepmerge(options, testnetConfig));
     const genesisFileUrl = getGenesisFileUrl(options.testnet);
     if (genesisFileUrl) {
-      const genesisStateFile = path.join(options.beaconDir, "genesis.ssz");
+      const genesisStateFile = path.join(options.beaconDir, options.genesisStateFile || "genesis.ssz");
```
Comment (wemeetagain) [inline packages/lodestar-cli/src/cmds/init/handler.ts]: Can you use `joinIfRelative` instead of `path.join`?

**Review by wemeetagain — CHANGES_REQUESTED** [review]

File: packages/lodestar-cli/src/cmds/init/handler.ts (hunk 1 above)
Comment (3xtr4t3rr3str14l) [reply packages/lodestar-cli/src/cmds/init/handler.ts]: done

**Review by dapplion — APPROVED** [review]

**Review by mpetrunic — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]
