### PR TITLE
fix: improve sync committee updates

### LINKED ISSUE #7366: Electra: performance issue computing sync committee indices
### Describe the bug

as informed by @dapplion it could be much slow to compute sync committee indices in electra, theorically 64x slower https://github.com/ChainSafe/lodestar/blob/0ac8bb9647653b8e62a8ef3af6bb461bbee7a08b/packages/state-transition/src/util/seed.ts#L105

### Expected behavior

- need to write a benchmark for it when all validators have `effectiveBalanceIncrement` = 32 (worse case scenario)
- improve it. 2 ways i can think of:
  - use hashtree. Considering the below for loop, we can compute `randByte` ahead for the next `n` loops
 
```typescript
 while (syncCommitteeIndices.length < SYNC_COMMITTEE_SIZE) {
    const shuffledIndex = computeShuffledIndex(i % activeValidatorCount, activeValidatorCount, seed);
    const candidateIndex = activeValidatorIndices[shuffledIndex];
    const randByte = digest(
      Buffer.concat([
        seed,
        //
        intToBytes(Math.floor(i / 32), 8, "le"),
      ])
    )[i % 32];

    const effectiveBalanceIncrement = effectiveBalanceIncrements[candidateIndex];
    if (effectiveBalanceIncrement * MAX_RANDOM_BYTE >= MAX_EFFECTIVE_BALANCE_INCREMENT * randByte) {
      syncCommitteeIndices.push(candidateIndex);
    }

    i++;
  }
```
    - otherwise go native

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.25.0

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- from electra, `processSyncCommitteeUpdates()` could be >15s according to the devnet

**Description**

- the main fix is in `computeShuffledIndex` where we can cache pivot and source computation there
- some other optimization other than that:
  - only compute hash once every 16 iterations
  - compute int manually instead of using `bytesToInt` in order not to use BigInt
  - cache shuffled index

I guess if we use `hashtree` we can improve more but the diff is a lot already and the main optimization is in `computeShuffledIndex()`, not the hash function. We can consider that in the future.

We can also improve pre-electra but I think it's been not that bad for a long time, so only focus on electra in this PR

Closes #7366

**Tests**

- added unit tests to compare naive version vs the optimized version
- benchmarks on local show >1000x difference for the main concerned function `naiveGetNextSyncCommitteeIndices()` while CI only show >20x difference. This is my local

```
computeProposerIndex
    ✔ naive computeProposerIndex 100000 validators                        31.86491 ops/s    31.38248 ms/op        -         10 runs   34.5 s
    ✔ computeProposerIndex 100000 validators                              106.2267 ops/s    9.413833 ms/op        -         10 runs   10.4 s

  getNextSyncCommitteeIndices electra
    ✔ naiveGetNextSyncCommitteeIndices 1000 validators                   0.2121840 ops/s    4.712890  s/op        -         10 runs   51.7 s
    ✔ getNextSyncCommitteeIndices 1000 validators                         214.9251 ops/s    4.652783 ms/op        -         45 runs  0.714 s
    ✔ naiveGetNextSyncCommitteeIndices 10000 validators                  0.2122278 ops/s    4.711918  s/op        -         10 runs   51.8 s
    ✔ getNextSyncCommitteeIndices 10000 validators                        220.2337 ops/s    4.540632 ms/op        -         46 runs  0.710 s
    ✔ naiveGetNextSyncCommitteeIndices 100000 validators                 0.2117828 ops/s    4.721820  s/op        -         10 runs   52.2 s
    ✔ getNextSyncCommitteeIndices 100000 validators                       204.7383 ops/s    4.884283 ms/op        -         43 runs  0.714 s

  computeShuffledIndex
    ✔ naive computeShuffledIndex 100000 validators                      0.06638498 ops/s    15.06365  s/op        -          3 runs   60.3 s
    ✔ cached computeShuffledIndex 100000 validators                       1.932706 ops/s    517.4092 ms/op        -         10 runs   5.72 s
```

### CODE REVIEW

**Comment by twoeths** [comment]
posting benchmark from my personal ubuntu node which is the same to `lg/mainnet` nodes:

```
computeProposerIndex
    ✔ naive computeProposerIndex 100000 validators                        15.96156 ops/s    62.65051 ms/op        -          9 runs   62.6 s
    ✔ computeProposerIndex 100000 validators                              93.41964 ops/s    10.70439 ms/op        -         10 runs   11.8 s

  getNextSyncCommitteeIndices electra
    ✔ naiveGetNextSyncCommitteeIndices 1000 validators                   0.1083408 ops/s    9.230135  s/op        -          6 runs   64.5 s
    ✔ getNextSyncCommitteeIndices 1000 validators                         141.7483 ops/s    7.054757 ms/op        -         31 runs  0.726 s
    ✔ naiveGetNextSyncCommitteeIndices 10000 validators                  0.1075031 ops/s    9.302056  s/op        -          6 runs   65.1 s
    ✔ getNextSyncCommitteeIndices 10000 validators                        141.9954 ops/s    7.042481 ms/op        -         31 runs  0.723 s
    ✔ naiveGetNextSyncCommitteeIndices 100000 validators                 0.1068357 ops/s    9.360169  s/op        -          6 runs   65.5 s
    ✔ getNextSyncCommitteeIndices 100000 validators                       142.0709 ops/s    7.038738 ms/op        -         31 runs  0.722 s

  computeShuffledIndex
    ✔ naive computeShuffledIndex 100000 validators                      0.03294994 ops/s    30.34907  s/op        -          2 runs   90.1 s
    ✔ cached computeShuffledIndex 100000 validators                       1.535617 ops/s    651.2041 ms/op        -         10 runs   7.17 s
    ✔ naive computeShuffledIndex 2000000 validators                    0.001597753 ops/s    625.8789  s/op        -          1 runs 1.25e+3 s
    ✔ cached computeShuffledIndex 2000000 validators                    0.02168103 ops/s    46.12328  s/op        -          1 runs   92.5 s
```

it also shows >1000x improvement for some tests, similar to my local environment

**Review by wemeetagain — DISMISSED** [review]
LGTM, appreciate the thorough analysis

File: packages/state-transition/src/util/seed.ts [hunk 1]
```diff
@@ -161,13 +248,109 @@ export function getNextSyncCommitteeIndices(
...
+    const MAX_EFFECTIVE_BALANCE_INCREMENT = MAX_EFFECTIVE_BALANCE_ELECTRA / EFFECTIVE_BALANCE_INCREMENT;
+
+    const epoch = computeEpochAtSlot(state.slot) + 1;
+    const activeValidatorCount = activeValidatorIndices.length;
+    const seed = getSeed(state, epoch, DOMAIN_SYNC_COMMITTEE);
+    const shuffledIndexFn = getComputeShuffledIndexFn(activeValidatorCount, seed);
+
+    let i = 0;
+    let cachedHash: Uint8Array | null = null;
+    const cachedHashInput = Buffer.allocUnsafe(32 + 8);
```
Comment (wemeetagain) [inline packages/state-transition/src/util/seed.ts:277]: added: reuse this buffer as the input for `digest` below

File: packages/state-transition/src/util/seed.ts [hunk 2]
```diff
@@ -120,6 +120,8 @@ export function computeProposerIndex(
     const shuffledResult = new Map<number, number>();
 
     let i = 0;
+    const cachedHashInput = Buffer.allocUnsafe(32 + 8);
```
Comment (wemeetagain) [inline packages/state-transition/src/util/seed.ts:123]: added: reuse this buffer as the input for digest below

File: packages/state-transition/src/util/seed.ts [hunk 3]
```diff
@@ -402,7 +408,7 @@ export function getComputeShuffledIndexFn(indexCount: number, seed: Bytes32): Co
         //   bytesToBigInt(digest(Buffer.concat([_seed, intToBytes(i, 1)])).slice(0, 8)) % BigInt(indexCount)
         // );
         pivotBuffer[32] = i % 256;
-        pivot = Number(bytesToBigInt(digest(pivotBuffer).slice(0, 8)) % BigInt(indexCount));
+        pivot = Number(bytesToBigInt(digest(pivotBuffer).subarray(0, 8)) % BigInt(indexCount));
```
Comment (wemeetagain) [inline packages/state-transition/src/util/seed.ts:413]: added: use subarray instead of slice

**Review by wemeetagain — DISMISSED** [review]
Added a few small things, lgtm

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.27.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.27.0) :tada:

**Comment by dapplion** [comment]
GG 👏

**Comment by shanghan345** [comment]
为何寄给我？

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________
