### PR TITLE
Use custom HTTP client

### LINKED ISSUE #1041: Error: could not detect network
**Describe the bug**
Got this issue in my environment after upgrading ethers to 5.0.2 when I run e2e chain.test.ts:

```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.0.2)
      at Logger.makeError (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/logger/lib/index.js:179:21)
      at Logger.throwError (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/logger/lib/index.js:188:20)
      at JsonRpcProvider.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:335:54)
      at step (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
      at Object.throw (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
      at rejected (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:19:65)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
**Expected behavior**
Tests should pass in any environment

**Steps to Reproduce**
+ Go to packages/lodestar
+ `yarn test:e2e`

### LINKED ISSUE #1552: eth1: stop flooding too much log
when there is eth1 error, it shows too much log
```
...
...
...
159":57,"65160":51,"65161":97,"65162":54,"65163":54,"65164":48,"65165":57,"65166":99,"65167":101,"65168":53,"65169":54,"65170":102,"65171":102,"65172":99,"65173":48,"65174":50,"65175":57,"65176":101,"65177":51,"65178":55,"65179":57,"65180":57,"65181":54,"65182":49,"65183":56,"65184":57,"65185":49,"65186":56,"65187":100,"65188":54,"65189":56,"65190":54,"65191":48,"65192":98,"65193":51,"65194":34,"65195":44,"65196":34,"65197":108,"65198":111,"65199":103,"65200":73,"65201":110,"65202":100,"65203":101,"65204":120,"65205":34,"65206":58,"65207":34,"65208":48,"65209":120,"65210":48,"65211":34,"65212":44,"65213":34,"65214":114,"65215":101,"65216":109},"error":{}}, requestBody="{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x2fd8aa\",\"toBlock\":\"0x2fdc91\",\"address\":\"0x07b39f4fde4a38bace212b546dac87c58dfe3fdc\",\"topics\":[\"0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5\"]}],\"id\":537,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://goerli.prylabs.net", code=SERVER_ERROR, version=web/5.0.7)
    at Logger.makeError (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at /Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/web/lib/index.js:264:32
    at step (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/web/lib/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-09-19 07:35:15  [CHAIN]            info: Epoch 9899 is justified at root     0x62002b32bf2ea0f1020df32410c257ab1e26406a9a2fa7c4d83b6c4545585d0e!
```

it should only show a short meaningful error message instead

### PR DESCRIPTION
**Pull request by dapplion**
Use `cross-fetch` to perform requests to the Eth1 node. This gives us much more control over request than what ethers offer:
- Support for abort signals
- Better error handling. `packages/lodestar/test/e2e/eth1/jsonRpcHttpClient.test.ts` tests many error cases to produce useful messages
- Batch request support
`ethers` is still used in Lodestar for parsing the DepositEvent log and computing its topic.

Most of the changes are due to a re-organization of the eth1 client classes:
- `IJsonRpcClient`: formats and parses JSON RPC requests
  - `JsonRpcHttpClient`: Wrapper around `cross-fetch`
  - `JsonRpcIpcClient`: TBD
- `Eth1JsonRpcClient`: Implements the Eth1 JSON RPC methods that are necessary. Uses `IJsonRpcClient`
- `Eth1Provider`: Main consumable class which extends `Eth1JsonRpcClient` and interacts with the deposit contract

Fixes https://github.com/ChainSafe/lodestar/issues/1041
Fixes https://github.com/ChainSafe/lodestar/issues/1552 (or gives us the opportunity to fix it if necessary)

### CODE REVIEW

File: packages/lodestar/src/eth1/jsonRpcHttpClient.ts [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+      throw Error(res.error.message);
+    } else if (res.error.code) {
+      throw Error(`JSON RPC error ${res.error.code}`);
+    }
+    throw Error("JSON RPC error");
+  } else if (res.result === undefined) {
+    throw Error("No JSON RPC result");
+  } else {
+    return res.result;
+  }
```
Comment (mpetrunic) [inline packages/lodestar/src/eth1/jsonRpcHttpClient.ts]: It might be better to add rpc request payload to error messages, otherwise we will be clueless about what failed

**Review by mpetrunic — DISMISSED** [review]

File: packages/lodestar/src/eth1/eth1JsonRpcClient.ts [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+    return logsRaw.map((logRaw) => ({
+      blockNumber: parseInt(logRaw.blockNumber, 16),
+      data: logRaw.data,
+      topics: logRaw.topics,
+    }));
+  }
+}
+
+function toHex(n: number): string {
+  return "0x" + n.toString(16);
```
Comment (wemeetagain) [inline packages/lodestar/src/eth1/eth1JsonRpcClient.ts:89]: This can create "invalid" hex strings, as hex strings must always have length % 2 === 0

File: packages/lodestar/src/eth1/utils/depositContract.ts [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+import {ethers} from "ethers";
+import {fromHexString} from "@chainsafe/ssz";
+import {DepositEvent} from "@chainsafe/lodestar-types";
+import {IBeaconConfig} from "@chainsafe/lodestar-config";
+
+const depositEventFragment =
+  "event DepositEvent(bytes pubkey, bytes withdrawal_credentials, bytes amount, bytes signature, bytes index)";
+
+const depositContractInterface = new ethers.utils.Interface([depositEventFragment]);
```
Comment (wemeetagain) [inline packages/lodestar/src/eth1/utils/depositContract.ts]: If we're just using ethers for this, we might just use the subpackage: https://github.com/ethers-io/ethers.js/tree/master/packages/abi

File: packages/lodestar/src/eth1/eth1JsonRpcClient.ts (hunk 2 above)
Comment (dapplion) [reply packages/lodestar/src/eth1/eth1JsonRpcClient.ts:89]: @wemeetagain Seems that nodes don't like padded hex strings
```
1) eth1 / httpEth1Client
     getBlocksByNumber: Should fetch a block range:
   Error: JSON RPC error: invalid argument 0: hex number with leading zero digits, method=eth_getBlockByNumber, params=["0x01",false]
    at parseRpcResponse (src/eth1/jsonRpcHttpClient.ts:60:9)
    at /home/runner/work/lodestar/lodestar/packages/lodestar/src/eth1/jsonRpcHttpClient.ts:54:35
    at Array.map (<anonymous>)
    at JsonRpcHttpClient.fetchBatch (src/eth1/jsonRpcHttpClient.ts:54:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Eth1JsonRpcClient.getBlocksByNumber (src/eth1/eth1JsonRpcClient.ts:42:23)
    at Context.<anonymous> (test/e2e/eth1/eth1JsonRpcClient.test.ts:36:20)
```
The spec says otherwise. Should I revert https://github.com/ChainSafe/lodestar/pull/1553/commits/c44b593820e58b8ca0ba33d244839e4ea277e57c ?

Comment (wemeetagain) [reply packages/lodestar/src/eth1/eth1JsonRpcClient.ts:89]: I guess so? thats weird

**Comment by wemeetagain** [comment]
file conflict

**Review by wemeetagain — APPROVED** [review]
