### PR TITLE
Handle request timeout

### LINKED ISSUE #1667: Network req/resp timeout without error
**Describe the bug**
This is not the `dialProtocol` timeout issue in #1597 since we got the stream (I applied my hot fix #1600 for my local branch). After that we receive no response from the peer and regular sync stalled.

```
2020-10-15 14:13:49 [SYNC]             info: Regular Sync: Requesting blocks from slot 501677 to slot 501740
2020-10-15 14:13:49 [SYNC]             info: Regular Sync: Synced up to slot 501676  currentSlot=516668, gossipParentBlockRoot=undefined
2020-10-15 14:13:50 [NETWORK]       ^[[36mverbose^[[39m: sending beacon_blocks_by_range request to 16Uiu2HAmBHHixkAU7ikai94zvxWgbJS4J9BBNr2ZsHkAt4ghWCBd requestId=f69141a4794db63f, encoding=ssz_snappy
2020-10-15 14:13:59 [NETWORK]       ^[[36mverbose^[[39m: got stream to 16Uiu2HAmBHHixkAU7ikai94zvxWgbJS4J9BBNr2ZsHkAt4ghWCBd requestId=f69141a4794db63f, encoding=ssz_snappy
```

**Expected behavior**
We should either receive/trigger an error or the log `receive beacon_blocks_by_range request from` with same requestId.

I still saw the peer stay connected to us after that:
```
2020-10-15 14:14:17 [NETWORK]       ^[[36mverbose^[[39m: receive ping request from 16Uiu2HAmBHHixkAU7ikai94zvxWgbJS4J9BBNr2ZsHkAt4ghWCBd requestId=d7c30682f8f20c01, encoding=ssz_snapp
```
and after that we did do beacon_blocks_by_root request to the same peer successfully too:
```
2020-10-15 14:14:24 [NETWORK]       ^[[36mverbose^[[39m: sending beacon_blocks_by_root request to 16Uiu2HAmBHHixkAU7ikai94zvxWgbJS4J9BBNr2ZsHkAt4ghWCBd requestId=8a24e9262bff231f, encoding=ssz_snappy
2020-10-15 14:14:25 [NETWORK]       ^[[36mverbose^[[39m: got stream to 16Uiu2HAmBHHixkAU7ikai94zvxWgbJS4J9BBNr2ZsHkAt4ghWCBd requestId=8a24e9262bff231f, encoding=ssz_snappy
2020-10-15 14:14:26 [NETWORK]       ^[[36mverbose^[[39m: receive beacon_blocks_by_root response with 1 chunks from 16Uiu2HAmBHHixkAU7ikai94zvxWgbJS4J9BBNr2ZsHkAt4ghWCBd requestId=8a24e9262bff231f, encoding=ssz_snappy, body=["0xe653c0f2da2a8edd3d8cc6e9301896d306246064d3baa3503388433c6421b8e2"]
```

This is the 1st time I see the issue, it's so rare.

### PR DESCRIPTION
**Pull request by twoeths**
resolves #1667

### CODE REVIEW

**Comment by twoeths** [comment]
now we can catch some "request timeout" in the log like:
```
2020-10-21 11:50:12 [NETWORK]          ^[[33mwarn^[[39m: failed to send request e38fb8239168c668 to peer 16Uiu2HAmLhpqke8knxp3B6Hnw6zsmmAfFdVvqDtnn7cBJyZdastf method=beacon_blocks_by_range, reason=request timeout
```

File: packages/lodestar/src/network/reqResp.ts [hunk 1]
```diff
@@ -364,8 +365,18 @@ export class ReqResp extends (EventEmitter as IReqEventEmitterClass) implements
       }
       logger.verbose(`got stream to ${peerId.toB58String()}`, {requestId, encoding});
       const controller = new AbortController();
-      await pipe(body != null ? [body] : [null], eth2RequestEncode(config, logger, method, encoding), conn.stream);
+      // write
+      await Promise.race([
+        pipe(body != null ? [body] : [null], eth2RequestEncode(config, logger, method, encoding), conn.stream),
+        new Promise((_, reject) => {
+          setTimeout(() => {
+            reject(new Error(REQUEST_TIMEOUT_ERR));
```
Comment (mpetrunic) [inline packages/lodestar/src/network/reqResp.ts:375]: Don't we need to close stream?

**Review by mpetrunic — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]
