### PR TITLE
cli/options: remove preset flag

### LINKED ISSUE #2576: Validator CLI handler ignores --preset option
**Describe the bug**

Working on https://github.com/ChainSafe/lodestar/pull/2575 and due the bug fixed with https://github.com/ChainSafe/lodestar/pull/2574 the validator client was using fork version 0x00000000 when the minimal is 0x00000001.

**Expected behavior**

When running the validator CLI with --preset minimal the fork must be 0x00000001.

### LINKED ISSUE #2854: Wrong preset choices for cli option in dev command
**Describe the bug**

When I append `-h` for CLI option help, I noticed the choices in the `preset` option for the dev command are currently: `[choices: "mainnet", "minimal", "mainnet", "minimal"]`

**Expected behavior**

The choices should be be `[choices: "mainnet", "minimal"]` just like the `beacon` command.

### PR DESCRIPTION
**Pull request by q9f**
**Motivation**

Preset is not really relevant for users as this is something every network should depend on.

**Description**

Related to and discussed in: #2854

This removes globally the `--preset` flag and assumes that every `--network` depends on either `minimal` or `mainnet` preset implicitly.

Notably, I kept the ability to use `LODESTAR_PRESET` environment variable if anyone wants to try overriding it.

- Closes #2854 
- Closes #2576

### CODE REVIEW

**Comment by dapplion** [comment]
@q9f #2991 merged :+1:

**Review by dapplion — APPROVED** [review]

File: packages/config/presets.d.ts [hunk 1]
```diff
@@ -1 +1 @@
-export * from "./lib/networks";
+export * from "./lib/presets";
```
Comment (dapplion) [inline packages/config/presets.d.ts:1]: f7b

**Review by dapplion — APPROVED** [review]
