### PR TITLE
fix: improve compute new state root when producing block

### LINKED ISSUE #6194: computeNewStateRoot performance issue at slot 0 of epoch
### Describe the bug

At slot 0 of epoch, computeNewStateRoot somehow has a very big `hashTreeRoot()` time

Screenshot 2023-12-15 at 13 47 46

[produce_block_holesky.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/13682039/produce_block_holesky.cpuprofile.zip)

This happens a long time ago since https://github.com/ChainSafe/lodestar/issues/5793#issuecomment-1647133160

### Expected behavior

Fast `hashTreeRoot()` call in `computeNewStateRoot()` as the pre state there should cache a lot of hash objects already

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.12.1

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Improve "computeNewStateRoot" function

**Description**

- `computeNewStateRoot` was so slow because we didn't compute hash tree root to cache in "prepareNextSlot". The main fix for this is to do it in "prepareNextSlot"
- Also track `state.hashTreeRoot()` call in 3 places: `verifyBlocksStateTransitionOnly()`, `prepareNextSlot()` and `computeNewStateRoot()`
- Also correct the bucket of that metrics as current values are not suitable for different networks
  - in holesky, it could be up to 1.8s, see #6194
  - in mainnet, if the value is <50ms we're good so no need to track values less than that. Need to track more values between 0.5s and 1.5s

Closes #6194

### CODE REVIEW

File: packages/beacon-node/src/chain/prepareNextSlot.ts [hunk 1]
```diff
@@ -104,6 +104,12 @@ export class PrepareNextSlotScheduler {
         RegenCaller.precomputeEpoch
       );
 
+      // cache HashObjects for faster hashTreeRoot() later, especially for computeNewStateRoot() if we need to produce a block at slot 0 of epoch
+      // see https://github.com/ChainSafe/lodestar/issues/6194
+      const hashTreeRootTimer = this.metrics?.stateHashTreeRootTime.startTimer({source: "prepare_next_slot"});
```
Comment (nflaig) [inline packages/beacon-node/src/chain/prepareNextSlot.ts:109]: What should be the naming convention we use for source?

e.g. here we use camelCase (function names)
https://github.com/ChainSafe/lodestar/blob/465834846a18619a30d7b0e11dfcac512248c0ec/packages/state-transition/src/stateTransition.ts#L61

and recently added (https://github.com/ChainSafe/lodestar/pull/6143) step metrics also use camelCase
https://github.com/ChainSafe/lodestar/blob/465834846a18619a30d7b0e11dfcac512248c0ec/packages/state-transition/src/stateTransition.ts#L183

I kinda like the function names and might be better for consistency, but maybe not always applicable (i.e. if there is no function call specific to the metric)

**Comment by twoeths** [comment]
- On mainnet, `state.hashTreeRoot()` for `computeNewStateRoot()` runs mostly < 50ms

Screenshot 2023-12-15 at 19 25 12

- On holesky, `state.hashTreeRoot()` for `computeNewStateRoot()` runs mostly 200ms to 500ms

Screenshot 2023-12-15 at 19 26 10

File: packages/beacon-node/src/chain/prepareNextSlot.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/prepareNextSlot.ts:109]: > What should be the naming convention we use for source?

agree to have some naming convention, we used snake case as suggested by @dapplion and that's my preference. Agree there are consistencies so need some agreement to work on

I don't want to use function names, just which whatever name that makes sense in the context because:
- some function names are so long so it's not nice to render in grafana, for example `verifyBlocksStateTransitionOnly`
- one function could call a metric multiple times

so this one should be more dynamic to me, as long as a PR gets through review process we're fine I think

**Review by wemeetagain — APPROVED** [review]
lgtm

File: packages/beacon-node/src/chain/prepareNextSlot.ts (hunk 1 above)
Comment (nflaig) [reply packages/beacon-node/src/chain/prepareNextSlot.ts:109]: > I don't want to use function names, just which whatever name that makes sense in the context because:

Makes sense to not be to strict here then, also I guess those labels are mostly used to visualize and separate metric values in a panel. As long as it is visually readable and makes sense in the context of the metrics the naming convention (camelCase vs snake_case) should not matter that much.

**Review by nflaig — APPROVED** [review]

File: packages/beacon-node/src/chain/prepareNextSlot.ts (hunk 1 above)
Comment (dapplion) [reply packages/beacon-node/src/chain/prepareNextSlot.ts:109]: snake case just reads better in grafana :)

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.13.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.13.0) :tada:
