### PR TITLE
fix: improve regen state

### LINKED ISSUE #7002: Performance issue regen state
### Describe the bug

Reload state + regen takes ~13s on mainnet

Screenshot 2024-08-05 at 09 48 35

`Received gossip block` should be logged before the validation time, it showed 13.2s as validation time

```
126079:Jul-30 01:41:31.895[network]         debug: Received gossip block slot=9623304, root=0x0954…7537, curentSlot=9623305, peerId=16Uiu2HAmNCh2yBozfk5dujuWpUWCXzQdXbUK3VoVcHg1S8ZRW4Rt, delaySec=7.585000038146973, pending=null, haveBlobs=6, expectedBlobs=6, recvToValLatency=0.07299995422363281, recvToValidation=13.309999942779541, validationTime=13.236999988555908
```

it mean the validation started at ~`01:41:18.658`

2s was for reloading state
```
125805:Jul-30 01:41:19.084[chain]           debug: Reload: read state successful persistedKey=0xb796040000000000d572d4cf29fadad5ee3bd7fcfe2d9e8ab762d44d3fb58d36ac06682b36b34a42
125822:Jul-30 01:41:19.084[chain]         verbose: Reload: use block state as seed state slot=9623302
125823:Jul-30 01:41:19.084[chain]           debug: Reload: found seed state persistedKey=0xb796040000000000d572d4cf29fadad5ee3bd7fcfe2d9e8ab762d44d3fb58d36ac06682b36b34a42, seedSlot=9623302
125824:Jul-30 01:41:20.945[chain]           debug: Reload: cached state load successful persistedKey=0xb796040000000000d572d4cf29fadad5ee3bd7fcfe2d9e8ab762d44d3fb58d36ac06682b36b34a42, stateSlot=9623264, stateRoot=0xcdbc3aa5ffa8e44273870bf29cb4686bddcb4448d7b12f715a77d2b8f7d41ce7, seedSlot=9623302
```

8.6s was for regen state by running through 23 blocks
```
125825:Jul-30 01:41:20.945[chain]           debug: Replaying blocks to get state stateRoot=0x49871dd7b44f68e98c7cb0677a1b25bdac0ab05fe62dada2aa0ccdcb37f7884f, replaySlots=9623287,9623286,9623285,9623284,9623283,9623282,9623281,9623280,9623279,9623278,9623277,9623276,9623275,9623274,9623273,9623272,9623271,9623270,9623269,9623268,9623267,9623266,9623265
126064:Jul-30 01:41:29.532[chain]           debug: Replayed blocks to get state stateRoot=0x49871dd7b44f68e98c7cb0677a1b25bdac0ab05fe62dada2aa0ccdcb37f7884f, replaySlots=9623287,9623286,9623285,9623284,9623283,9623282,9623281,9623280,9623279,9623278,9623277,9623276,9623275,9623274,9623273,9623272,9623271,9623270,9623269,9623268,9623267,9623266,9623265
```

remaining time (~4.1s) was to run through epoch transition because block slot 9623287 and 9623304 stay on different epoch
```
126107:Jul-30 01:41:33.645[chain]         verbose: Block processed slot=9623304, root=0x09548c9b217164e5386eb45c9324918f4b5407670cbcd8e7fa5b806dbcc57537, delaySec=22.644999980926514
```

part of #5968

### Expected behavior

- Separate the log `Received gossip block` to `Received gossip block` and `Validated gossip block`
- Average block processed time is 8.6s/23 = 374ms which is too much. Normally it should be <= 70ms
- All of the above information should be tracked by metrics

### Steps to reproduce

Run with minimal config of n-historical state: `'chain.nHistoricalStates: true','chain.maxBlockStates: 1','chain.maxCPStateEpochsInMemory: 0'`

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.20.0

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- improve regen state
- more metrics when regen state

**Description**
- most of the time to regen state is due to loading block from db. At this time there are a lot of gossip attestation messages coming so we need to save time to load all blocks in a single call using `Promise.all()` , see #7002
- add more metrics in `regen.getState()`:
  - time to get seed state
  - block count
  - time to load blocks from db
  - time to run state transition

will have follow-up PR for Grafana dashboard once this is merged

closes #7002

### CODE REVIEW

File: packages/beacon-node/src/chain/regen/regen.ts [hunk 1]
```diff
@@ -181,25 +183,49 @@ export class StateRegenerator implements IStateRegeneratorInternal {
...
+
+    const logCtx = {stateRoot, replaySlots: replaySlots.join(",")};
+    this.modules.logger.debug("Replaying blocks to get state", logCtx);
+
+    const loadBlocksTimer = this.modules.metrics?.regenGetState.loadBlocks.startTimer();
+    const blockOrNulls = await Promise.all(blockPromises);
+    loadBlocksTimer?.();
+
+    const blocksByRoot = new Map<RootHex, SignedBeaconBlock | null>();
+    for (const [i, blockOrNull] of blockOrNulls.entries()) {
```
Comment (wemeetagain) [inline packages/beacon-node/src/chain/regen/regen.ts:230]: can we error here (instead of L229) if the block doesn't exist?

File: packages/beacon-node/src/chain/regen/regen.ts [hunk 2]
```diff
@@ -238,17 +264,16 @@ export class StateRegenerator implements IStateRegeneratorInternal {
           // also with allowDiskReload flag, we "reload" it to the state cache too
           this.modules.blockStateCache.add(state);
         }
-
-        // this avoids keeping our node busy processing blocks
-        await nextEventLoop();
```
Comment (wemeetagain) [inline packages/beacon-node/src/chain/regen/regen.ts:243]: Is removing this intentional?

Comment (twoeths) [reply packages/beacon-node/src/chain/regen/regen.ts:243]: yes, similar to the purpose of `Promise.all()` above, we want to save I/O time here. This line was added when we didn't have worker thread

File: packages/beacon-node/src/chain/regen/regen.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/regen/regen.ts:230]: so I applied the change to check for `null` in this for loop. Then at line 229 I have to check for `undefined` again due to the `Map.get()`

I think it's more convenient to have single check and throw error at line 229

Comment (wemeetagain) [reply packages/beacon-node/src/chain/regen/regen.ts:230]: If we throw before, then we can prevent doing unnecessary state transitions in the case that an intermediary block isn't found

Comment (twoeths) [reply packages/beacon-node/src/chain/regen/regen.ts:230]: good point, will do that 👍

**Comment by twoeths** [comment]
latest update is to load `balances` + `validators` to cache, and transfer cache (`dontTransferCache = false`) when process block to save time

block reprocess time is around 120ms which is similar to processing a regular block. This is on feat4 mainnet node (with minimal nHistorical state config so that it has to reload state + reprocess blocks frequently)

Screenshot 2024-08-26 at 09 34 17

originally it is ~375ms as in #7002

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.22.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.22.0) :tada:
