### PR TITLE
Avoid signing conflicting attestation

### LINKED ISSUE #1549: E2e test error - avoided signing conflicting attestation
**Describe the bug**

Validator client stores attestations under "attester index" key, which our internal index in array
of validators in validator client. When we have 2 validator clients (example multi threaded tests),
two different validators will have same "attester index" and thus second validator thinks he is about to produce 
slashable attestation.

**Expected behavior**

We should either store validator published attestation under pubkey or obtain real validator index and use that.

**Steps to Reproduce**

Run e2e tests.

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20
 - Branch: master

### PR DESCRIPTION
**Pull request by mpetrunic**
resolves #1549

### CODE REVIEW

File: packages/lodestar-validator/src/services/attestation.ts [hunk 1]
```diff
@@ -354,19 +354,33 @@ export class AttestationService {
...
+          targetEpoch: other.target.epoch,
+          conflictx: JSON.stringify(potentialAttestationConflicts),
+        });
+      }
+      return result;
     });
   }
 
   private async storeAttestation(attesterIndex: number, attestation: Attestation): Promise<void> {
+    // this.logger.error("storing attestation", {
```
Comment (wemeetagain) [inline packages/lodestar-validator/src/services/attestation.ts]: maybe logger.verbose or logger.debug?

**Review by wemeetagain — DISMISSED** [review]
:+1:

File: packages/lodestar-validator/src/services/attestation.ts (hunk 1 above)
Comment (mpetrunic) [reply packages/lodestar-validator/src/services/attestation.ts]: Ill remove, i started planting logs to debug behavior 😅

**Review by wemeetagain — APPROVED** [review]
