### PR TITLE
Handle wrong fork/finalization on hello

### LINKED ISSUE #478: Handle wrong fork/finalization on hello
Lodestar should disconnect on hello:
1. If `fork_version` doesn’t match the local fork version, since the client’s chain is on another fork. `fork_version` can also be used to segregate testnets.
2. If the (`finalized_root`, `finalized_epoch`) shared by the peer is not in the client's chain at the expected epoch. For example, if Peer 1 sends (root, epoch) of (A, 5) and Peer 2 sends (B, 3) but Peer 1 has root C at epoch 3, then Peer 1 would disconnect because it knows that their chains are irreparably disjoint.

### PR DESCRIPTION
**Pull request by twoeths**
## Goal
+ Close #478

### CODE REVIEW

File: packages/lodestar/src/sync/reqResp/reqResp.ts [hunk 1]
```diff
@@ -97,7 +99,31 @@ export class SyncReqResp implements ISyncReqResp {
...
-    // TODO handle incorrect forkVersion or disjoint finalizedCheckpoint
+    if (await this.shouldDisconnectOnHello(peerInfo, request)) {
+      this.network.reqResp.goodbye(peerInfo, 0n);
+    }
+  }
+
+  public async shouldDisconnectOnHello(peerInfo: PeerInfo, request: Hello): Promise<boolean> {
+    const headBlock = await this.db.block.getChainHead();
+    const state = await this.db.state.get(headBlock.stateRoot);
+    const fork = state.fork;
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/reqResp/reqResp.ts]: I think chain module should expose getFork method

File: packages/lodestar/src/sync/reqResp/reqResp.ts [hunk 2]
```diff
@@ -97,7 +99,31 @@ export class SyncReqResp implements ISyncReqResp {
...
+    const epoch = computeEpochOfSlot(this.config, request.headSlot);
+    const forkVersionHeadSlot = (epoch < fork.epoch)? fork.previousVersion : fork.currentVersion;
+    if (!forkVersionHeadSlot.equals(request.headForkVersion)) {
+      return true;
+    }
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/reqResp/reqResp.ts:118]: I think we just need to check 
```javascript
fork.currentVersion.equals(request.headForkVersion) && request.finalizedRoot.equals(getBlockRoot(this.config, state, request.finalizedEpoch))
//maybe check if we have finalized that epoch
```

**Review by mpetrunic — CHANGES_REQUESTED** [review]

File: packages/lodestar/src/sync/reqResp/reqResp.ts (hunk 1 above)
Comment (twoeths) [reply packages/lodestar/src/sync/reqResp/reqResp.ts]: I also need state for subsequence calls, the new code looks better anyway.

File: packages/lodestar/src/sync/reqResp/reqResp.ts [hunk 3]
```diff
@@ -97,7 +98,25 @@ export class SyncReqResp implements ISyncReqResp {
...
-    // TODO handle incorrect forkVersion or disjoint finalizedCheckpoint
+    if (await this.shouldDisconnectOnHello(peerInfo, request)) {
+      this.network.reqResp.goodbye(peerInfo, 0n);
+    }
+  }
+
+  public async shouldDisconnectOnHello(peerInfo: PeerInfo, request: Hello): Promise<boolean> {
+    const headBlock = await this.db.block.getChainHead();
+    if (!headBlock) {
+      return true;
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/reqResp/reqResp.ts]: We should always have chain head at this point. Might be better to throw exception as we shouldn't proceed after this,.

File: packages/lodestar/src/sync/reqResp/reqResp.ts [hunk 4]
```diff
@@ -97,7 +98,25 @@ export class SyncReqResp implements ISyncReqResp {
...
+    }
+    const state = await this.db.state.get(headBlock.stateRoot);
+    if (!state.fork.currentVersion.equals(request.headForkVersion)) {
+      return true;
+    }
+    if (state.finalizedCheckpoint.epoch >= request.finalizedEpoch &&
+       !request.finalizedRoot.equals(getBlockRoot(this.config, state, request.finalizedEpoch))) {
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/reqResp/reqResp.ts]: if I'm not mistaken `getBlockRoot` only contains root for recent slots. I think it's safer to fetch block from database by request.finalizedEpoch start slot.

You should try to avoid fetching entire state here as that call isn't cheap, especially considering that this method will be called on each peer connect.

File: packages/lodestar/src/sync/reqResp/reqResp.ts [hunk 5]
```diff
@@ -97,7 +98,25 @@ export class SyncReqResp implements ISyncReqResp {
     } catch (e) {
       this.network.reqResp.sendResponse(id, e, null);
     }
-    // TODO handle incorrect forkVersion or disjoint finalizedCheckpoint
+    if (await this.shouldDisconnectOnHello(peerInfo, request)) {
+      this.network.reqResp.goodbye(peerInfo, 0n);
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/reqResp/reqResp.ts]: as per spec it should be 2n

**Review by mpetrunic — DISMISSED** [review]

File: packages/lodestar/src/sync/reqResp/reqResp.ts (hunk 5 above)
Comment (twoeths) [reply packages/lodestar/src/sync/reqResp/reqResp.ts]: I correct the one in `stop()` too

File: packages/lodestar/src/sync/reqResp/reqResp.ts (hunk 3 above)
Comment (twoeths) [reply packages/lodestar/src/sync/reqResp/reqResp.ts]: Ah I had to do that earlier because of my unit test, now we don't have that anymore.
Let's remove it to make it consistent to other places.

File: packages/lodestar/src/sync/reqResp/reqResp.ts (hunk 4 above)
Comment (twoeths) [reply packages/lodestar/src/sync/reqResp/reqResp.ts]: I replaced getBlockRoot by getting block root from database as you said.

Regarding the state, I still need it for other calculations.

File: packages/lodestar/src/sync/reqResp/reqResp.ts [hunk 6]
```diff
@@ -65,7 +66,7 @@ export class SyncReqResp implements ISyncReqResp {
     this.network.reqResp.removeListener("request", this.onRequest);
     await Promise.all(
       this.network.getPeers().map((peerInfo) =>
-        this.network.reqResp.goodbye(peerInfo, 0n)));
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/reqResp/reqResp.ts:67]: I would extract reason codes to enum

File: packages/lodestar/src/sync/reqResp/reqResp.ts [hunk 7]
```diff
@@ -98,22 +99,21 @@ export class SyncReqResp implements ISyncReqResp {
...
     const headBlock = await this.db.block.getChainHead();
-    if (!headBlock) {
-      return true;
-    }
     const state = await this.db.state.get(headBlock.stateRoot);
     if (!state.fork.currentVersion.equals(request.headForkVersion)) {
       return true;
     }
+    const startSlot = computeStartSlotOfEpoch(this.config, request.finalizedEpoch);
+    const startBlock = await this.db.block.get(startSlot);
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/reqResp/reqResp.ts]: If that block is finalized it will be in `this.db.blockArchive`

**Review by wemeetagain — APPROVED** [review]
:+1:
