### PR TITLE
Preventing MaxListenersExceededWarning

### LINKED ISSUE #3569: Investigate possible EventEmitter memory leak
**Describe the bug**

While trying to run lodestar on local testnet following the documentation [here](https://chainsafe.github.io/lodestar/usage/local/), I ran into complications which led to me to create this issue [here](https://github.com/ChainSafe/lodestar/issues/3568).

Part of what I noticed, while trying to get Lodestar running in the logs was this error:

> (node:15159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 chainHead listeners added to [ValidatorEventEmitter]. Use emitter.setMaxListeners() to increase limit

On a quick investigation, the issue seems to be coming from [this part](https://github.com/ChainSafe/lodestar/blob/c384b36a1b52d8607842b363e1f07f6ccc5d6004/packages/validator/src/services/attestation.ts#L50) of the code.

Two promises are being raced. One of the promises `this.waitForBlockSlot(slot)`, sets event listeners. As can be seen [here](https://github.com/ChainSafe/lodestar/blob/c384b36a1b52d8607842b363e1f07f6ccc5d6004/packages/validator/src/services/attestation.ts#L64). 

On my local, it seems the promise with the event listener never wins this race, and never is the one that gets resolved, hence the listener is never removed, hence leads to the the warning message that pops up in the log.

**Expected behavior**

Preferably not have the EventEmitter memory leak warning. 

Hence:

- Confirm if this is indeed an issue
- Confirm if this can only practically show up in the local testnet - hence severity will be low
- If need be, see how this can be resolved.

### PR DESCRIPTION
**Pull request by dadepo**
**Motivation**

See #3569 and # #4394 for bug report

**Description**

The waitForBlockSlot should execute once per slot and per slot there should be a ValidatorEvent.chainHead event emitted In the unexpected situation where ValidatorEvent.chainHead is never emitted or is emitted but takes longer to propagate to the validator, to prevent accumulating listeners for ValidatorEvent.chainHead and triggering MaxListenersExceededWarning. 

This PR clears listener for ValidatorEvent.chainHead if any before setting a new one.

Closes #3569

**Beacon Node**
- [ ] Leak Related to use of Any-signal in Res/Req
```
  (node:56301) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
    at AbortSignal.[kNewListener] (node:internal/event_target:426:17)
    at AbortSignal.[kNewListener] (node:internal/abort_controller:173:24)
    at AbortSignal.addEventListener (node:internal/event_target:535:23)
    at anySignal (/Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/node_modules/any-signal/index.js:27:12)
    at withTimeout (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/utils/src/timeout.ts:11:34)
    at sendRequest (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/reqresp/request/index.ts:87:50)
    at ReqResp.sendRequest (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/reqresp/reqResp.ts:154:28)
    at ReqResp.status (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/reqresp/reqResp.ts:92:23)
    at PeerManager.requestStatus (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/peers/peerManager.ts:359:46)
    at file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/peers/peerManager.ts:368:56
```

- [ ] Leak Related to jsonRpcHttpClient
```
(node:56301) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
    at AbortSignal.[kNewListener] (node:internal/event_target:426:17)
    at AbortSignal.[kNewListener] (node:internal/abort_controller:173:24)
    at AbortSignal.addEventListener (node:internal/event_target:535:23)
    at JsonRpcHttpClient.fetchJsonOneUrl (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:194:24)
    at JsonRpcHttpClient.fetchJson (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:160:27)
    at retry.retries._b (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:125:27)
    at retry (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/utils/src/retry.ts:33:20)
    at JsonRpcHttpClient.fetchWithRetries (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:119:23)
    at ExecutionEngineHttp.exchangeTransitionConfigurationV1 (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/execution/engine/http.ts:298:27)
    at BeaconChain.exchangeTransitionConfiguration (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/chain/chain.ts:573:62)
Aug-17 21:32:00.064[CHAI
```

**Validator Client**
Spent some time trying to reproducing the warning for the validator client but could not. Even though back in January I observed the warning emanating from `ValidatorEventEmitter` see #3569

### CODE REVIEW

File: packages/validator/src/services/attestation.ts [hunk 1]
```diff
@@ -94,6 +94,16 @@ export class AttestationService {
...
+      // And per slot there should be a ValidatorEvent.chainHead event emitted
+      // In the unexpected situation where ValidatorEvent.chainHead is never emitted
+      // or is emitted but takes longer to propagate to the validator,
+      // to prevent accumulating listeners for ValidatorEvent.chainHead and triggering
+      // MaxListenersExceededWarning clear listener for ValidatorEvent.chainHead
+      // if any before setting a new one.
+      if (this.emitter.listenerCount(ValidatorEvent.chainHead) > 0) {
+        this.emitter.off(ValidatorEvent.chainHead, headListener);
+      }
       this.emitter.on(ValidatorEvent.chainHead, headListener);
```
Comment (dapplion) [inline packages/validator/src/services/attestation.ts]: This solution looks very strange, I don't follow the argument. The handler `headListener` is created in this scope so it can be proven that `headListener` has never been subscribed to this event, it's impossible. So the line `this.emitter.off(ValidatorEvent.chainHead, headListener)` is useless.

I also want see first a hard proof that the MaxListenersExceededWarning comes actually from this specific listener, and not from sleep()

**Review by dapplion — CHANGES_REQUESTED** [review]

File: packages/validator/src/services/attestation.ts (hunk 1 above)
Comment (dadepo) [reply packages/validator/src/services/attestation.ts]: > The handler headListener is created in this scope so it can be proven that headListener has never been subscribed to this event, it's impossible

In the case where `waitForBlockSlot` is called multiple times (before the unsubscribe), it is possible to have `headListener` subscribed multiple times. The intention of the check is to prevent this. But I will look into this again to ascertain your concern.

> I also want see first a hard proof that the MaxListenersExceededWarning comes actually from this specific listener, and not from sleep()

I am almost certain it does not come from the `sleep` as no where in the `sleep` code path is `EventEmitter` used. The `sleep` code path makes use of `AbortSignal` and from what I see, that uses a different API. But will try and reproduce and confirm this.

File: packages/beacon-node/src/chain/chain.ts [hunk 2]
```diff
@@ -156,6 +157,12 @@ export class BeaconChain implements IBeaconChain {
 
     const signal = this.abortController.signal;
     const emitter = new ChainEventEmitter();
+
+    // We set infinity to prevent MaxListenersExceededWarning which get logged when listeners > 10
+    // Since it is perfectly fine to have listeners > 10
+    emitter.setMaxListeners(Infinity);
+    setMaxListeners(Infinity, signal);
```
Comment (dapplion) [inline packages/beacon-node/src/chain/chain.ts]: Can you commit as comment the stack trace proving that this very specific event emitter gets more that 10 listeners?

File: packages/beacon-node/src/network/reqresp/reqResp.ts [hunk 3]
```diff
@@ -67,10 +68,13 @@ export class ReqResp implements IReqResp {
...
     this.options = options;
     this.metrics = modules.metrics;
+    this.controller = new AbortController();
+    // We set infinity to prevent MaxListenersExceededWarning which get logged when listeners > 10
+    // Since it is perfectly fine to have listeners > 10
+    setMaxListeners(Infinity, this.controller.signal);
   }
 
   async start(): Promise<void> {
-    this.controller = new AbortController();
```
Comment (dapplion) [inline packages/beacon-node/src/network/reqresp/reqResp.ts:73]: Why did you remove it from start? Once a signal is aborted it can't be used anymore

File: packages/beacon-node/src/node/nodejs.ts [hunk 4]
```diff
@@ -118,6 +119,9 @@ export class BeaconNode {
     metricsRegistries = [],
   }: IBeaconNodeInitModules): Promise<T> {
     const controller = new AbortController();
+    // We set infinity to prevent MaxListenersExceededWarning which get logged when listeners > 10
+    // Since it is perfectly fine to have listeners > 10
+    setMaxListeners(Infinity, controller.signal);
```
Comment (dapplion) [inline packages/beacon-node/src/node/nodejs.ts:124]: Can you commit as comment the stack trace proving that this very specific event emitter gets more that 10 listeners?

File: packages/validator/src/services/attestation.ts [hunk 5]
```diff
@@ -52,7 +52,7 @@ export class AttestationService {
     // A validator should create and broadcast the attestation to the associated attestation subnet when either
     // (a) the validator has received a valid block from the expected block proposer for the assigned slot or
     // (b) one-third of the slot has transpired (SECONDS_PER_SLOT / 3 seconds after the start of slot) -- whichever comes first.
-    await Promise.race([sleep(this.clock.msToSlot(slot + 1 / 3), signal), this.waitForBlockSlot(slot)]);
+    await Promise.race([this.waitForBlockSlot(slot), sleep(this.clock.msToSlot(slot + 1 / 3), signal)]);
```
Comment (dapplion) [inline packages/validator/src/services/attestation.ts]: Why is it necessary to change the order here?

File: packages/cli/src/cmds/beacon/handler.ts [hunk 6]
```diff
@@ -41,6 +42,10 @@ export async function beaconHandler(args: IBeaconArgs & IGlobalArgs): Promise<vo
   const options = beaconNodeOptions.getWithDefaults();
 
   const abortController = new AbortController();
+  // We set infinity to prevent MaxListenersExceededWarning which get logged when listeners > 10
+  // Since it is perfectly fine to have listeners > 10
+  setMaxListeners(Infinity, abortController.signal);
```
Comment (dapplion) [inline packages/cli/src/cmds/beacon/handler.ts]: Can you commit as comment the stack trace proving that this very specific event emitter gets more that 10 listeners?

File: packages/validator/src/validator.ts [hunk 7]
```diff
@@ -85,6 +86,10 @@ export class Validator {
     } = opts;
     const config = createIBeaconConfig(dbOps.config, genesis.genesisValidatorsRoot);
     this.controller = new AbortController();
+    // We set infinity to prevent MaxListenersExceededWarning which get logged when listeners > 10
+    // Since it is perfectly fine to have listeners > 10
+    setMaxListeners(Infinity, this.controller.signal);
```
Comment (dapplion) [inline packages/validator/src/validator.ts]: Can you commit as comment the stack trace proving that this very specific event emitter gets more that 10 listeners? Same for below

File: packages/beacon-node/src/chain/chain.ts (hunk 2 above)
Comment (dadepo) [reply packages/beacon-node/src/chain/chain.ts]: I could not create a situation where the warning is triggered locally. So I have removed the changes.

File: packages/beacon-node/src/node/nodejs.ts (hunk 4 above)
Comment (dadepo) [reply packages/beacon-node/src/node/nodejs.ts:124]: The signal here was what was passed down and triggered this:

```
(node:56301) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
    at AbortSignal.[kNewListener] (node:internal/event_target:426:17)
    at AbortSignal.[kNewListener] (node:internal/abort_controller:173:24)
    at AbortSignal.addEventListener (node:internal/event_target:535:23)
    at JsonRpcHttpClient.fetchJsonOneUrl (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:194:24)
    at JsonRpcHttpClient.fetchJson (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:160:27)
    at retry.retries._b (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:125:27)
    at retry (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/utils/src/retry.ts:33:20)
    at JsonRpcHttpClient.fetchWithRetries (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:119:23)
    at ExecutionEngineHttp.exchangeTransitionConfigurationV1 (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/execution/engine/http.ts:298:27)
    at BeaconChain.exchangeTransitionConfiguration (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/chain/chain.ts:573:62)
Aug-17 21:32:00.064[CHAI
```

File: packages/validator/src/services/attestation.ts (hunk 5 above)
Comment (dadepo) [reply packages/validator/src/services/attestation.ts]: It was not a necessity. It was changed to align with the text of the spec, which was placed as a comment

File: packages/validator/src/validator.ts (hunk 7 above)
Comment (dadepo) [reply packages/validator/src/validator.ts]: I removed the changes for the abort controller, as I could find a situation where it triggered the warning. I left the one for ValidatorEventEmitter, even though I could not recreate the situation that triggered it, I did observe by chance back in January. See  #3569. The log reproduced here


> (node:15159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 chainHead listeners added to [ValidatorEventEmitter]. Use emitter.setMaxListeners() to increase limit

File: packages/beacon-node/src/network/reqresp/reqResp.ts [hunk 8]
```diff
@@ -71,6 +72,9 @@ export class ReqResp implements IReqResp {
 
   async start(): Promise<void> {
     this.controller = new AbortController();
+    // We set infinity to prevent MaxListenersExceededWarning which get logged when listeners > 10
+    // Since it is perfectly fine to have listeners > 10
+    setMaxListeners(Infinity, this.controller.signal);
```
Comment (dadepo) [inline packages/beacon-node/src/network/reqresp/reqResp.ts:77]: Responsible for the warning observed in the trace:

```
(node:56301) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
    at AbortSignal.[kNewListener] (node:internal/event_target:426:17)
    at AbortSignal.[kNewListener] (node:internal/abort_controller:173:24)
    at AbortSignal.addEventListener (node:internal/event_target:535:23)
    at anySignal (/Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/node_modules/any-signal/index.js:27:12)
    at withTimeout (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/utils/src/timeout.ts:11:34)
    at sendRequest (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/reqresp/request/index.ts:87:50)
    at ReqResp.sendRequest (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/reqresp/reqResp.ts:154:28)
    at ReqResp.status (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/reqresp/reqResp.ts:92:23)
    at PeerManager.requestStatus (file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/peers/peerManager.ts:359:46)
    at file:///Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/beacon-node/src/network/peers/peerManager.ts:368:56
```

File: packages/beacon-node/src/network/reqresp/reqResp.ts (hunk 3 above)
Comment (dadepo) [reply packages/beacon-node/src/network/reqresp/reqResp.ts:73]: Undone

File: packages/cli/src/cmds/beacon/handler.ts (hunk 6 above)
Comment (dadepo) [reply packages/cli/src/cmds/beacon/handler.ts]: I could not create a situation where the warning is triggered locally. So I have removed the changes

File: packages/beacon-node/src/network/reqresp/reqResp.ts [hunk 9]
```diff
@@ -45,12 +45,12 @@ export class ReqResp implements IReqResp {
   private libp2p: LibP2p;
   private readonly peersData: PeersData;
   private logger: ILogger;
-  private controller: AbortController;
   private reqRespHandlers: ReqRespHandlers;
   private metadataController: MetadataController;
   private peerRpcScores: IPeerRpcScoreStore;
   private inboundRateLimiter: IRateLimiter;
   private networkEventBus: INetworkEventBus;
+  private controller = new AbortController();
```
Comment (dapplion) [inline packages/beacon-node/src/network/reqresp/reqResp.ts]: Why do you need to initialize the AbortController on constructor?

File: packages/validator/src/services/attestation.ts (hunk 5 above)
Comment (dapplion) [reply packages/validator/src/services/attestation.ts]: What do you mean the spec? Where does the spec specify the order of promises in javascript?

File: packages/validator/src/validator.ts [hunk 10]
```diff
@@ -121,6 +121,10 @@ export class Validator {
     }
 
     const emitter = new ValidatorEventEmitter();
+    // Validator event emitter can have more than 10 listeners in a normal course of operation
+    // We set infinity to prevent MaxListenersExceededWarning which get logged when listeners > 10
+    emitter.setMaxListeners(Infinity);
```
Comment (dapplion) [inline packages/validator/src/validator.ts:126]: Can you add proof with stack trace that this event listener triggers warnings?

Comment (dadepo) [reply packages/validator/src/validator.ts:126]: Already responded to the diff in the comment [here](https://github.com/ChainSafe/lodestar/pull/4421#discussion_r953578392)

File: packages/beacon-node/src/network/reqresp/reqResp.ts (hunk 9 above)
Comment (dadepo) [reply packages/beacon-node/src/network/reqresp/reqResp.ts]: Not sure why this is showing as a diff here, but this is not newly introduced. See it on `unstable` branch. See [here](https://github.com/ChainSafe/lodestar/blob/f48bef0d7a2e6009cb8d4fbef9f5c2d1fc2ff264/packages/beacon-node/src/network/reqresp/reqResp.ts#L52)

**Review by dapplion — APPROVED** [review]

File: packages/beacon-node/src/network/reqresp/reqResp.ts [hunk 11]
```diff
@@ -1,3 +1,4 @@
+import {setMaxListeners} from "node:events";
```
Comment (wemeetagain) [inline packages/beacon-node/src/network/reqresp/reqResp.ts:1]: Shame we have to introduce a nodejs specific api here.

Later we can pass down a signal from the top-level beacon node and avoid creating a new signal here.

**Review by wemeetagain — APPROVED** [review]
LGTM
