### PR TITLE
sync: Handle beaconBlocksByRange returning null

### LINKED ISSUE #976: Syncing Witti: fetching/importing blocks without processing
Syncing progresses until some point where processing blocks fails silently, and fetching/importing blocks via sync continues.

Visible by no longer seeing logs like:
```
2020-05-28 11:28:40  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x56666dd066288ba8f395aa5620b9947e31681ce812db4e7c739013ede98c778e, slot=1440, epoch=45
```
and instead, only seeing:
```
2020-05-28 11:28:51  [SYNC]             info: Imported blocks for slots: 1483,1484,1485,1486,
1487,1488,1492,1493,1496,1497,1498,1499,1500,1501,1502,1503,1506,1507,1508,1510,1512,1513 
2020-05-28 11:28:51  [SYNC]             info: Fetching blocks for 1514...1577 slot range 
2020-05-28 11:28:56  [SYNC]             info: Imported blocks for slots: 1514,1515,1516,1517,
1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,153
6,1537,1538,1539,1540,1543,1544,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1
559,1560,1561,1562,1563,1564,1565,1567,1568,1569,1570,1572,1573,1574,1575,1576,1577 
2020-05-28 11:28:56  [SYNC]             info: Fetching blocks for 1578...1641 slot range 
2020-05-28 11:28:57  [SYNC]             info: Imported blocks for slots: 1578,1579,1580,1581,
1582,1583,1584,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1600,1601,1602,160
3,1604,1605,1606,1607,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1622,1623,1
624,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641 

```

### PR DESCRIPTION
**Pull request by twoeths**
## Goal
+ resolves #976

### CODE REVIEW

File: packages/lodestar/src/sync/utils/blocks.ts [hunk 1]
```diff
@@ -73,16 +73,13 @@ export async function getBlockRange(
...
+        const chunkBlocks = await getBlockRangeFromPeer(rpc, peer, chunk);
+        if(chunkBlocks) {
+          blocks = blocks.concat(chunkBlocks);
           return null;
-        } catch (e) {
-          logger.debug(`Failed to obtain chunk ${JSON.stringify(chunk)} `
-              +`from peer ${peer.id.toB58String()}. Error: ${e.message}`
-          );
+        } else {
+          logger.warn(`Failed to obtain chunk ${JSON.stringify(chunk)} `
```
Comment (twoeths) [inline packages/lodestar/src/sync/utils/blocks.ts:81]: error was logged in network reqresp.ts

**Review by mpetrunic — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]
