### PR TITLE
Gossip attestation validation review

### LINKED ISSUE #2771: Don't re-index attestations
**Describe the bug**

At least in event handlers we re-index attestations that have already been indexed for signature verification.

**Expected behavior**

Don't re-index attestations if not necessary

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

Our synced nodes struggle to process the attestations and aggregates received through gossip. Metrics show that the node may reject between 30-99% of those objects when connected to +16 subnets.

To start addressing the problem I did an in-depth review of the gossip validation conditions focusing on performance.

**Description**

 I've refactored the gossip validation logic completely basing it heavily on Lighthouse approach. I've ensured that we satisfy all spec conditions by adding a comment for each condition.

**Important changes**

- Deleted the future / unknown target attestation cache. I strongly believe it's very unsafe, since it's completely unbounded. Our implementation is dangerous and we will be better off without anything. In the short term we should look at implementing a DOS resistant cache. There is this great write-up by Paul (Lighthouse) about the complexities of a safe attestation cache https://hackmd.io/@CzkIH-W1R42R-S4vdcDJeQ/rJmmumLPu
- Since there are no pending / cached attestations the entire processor architecture + job wrappers can be deleted for simplicity

- I've changed the validation unit tests from using stubs to using real data. The tests are much shorter now and easier to follow. They run pretty fast also, taking 40-70ms for all 10 validation tests. I strongly argue in favor of phasing out stubbing where possible, circling back to this discussion https://github.com/ChainSafe/lodestar/issues/1523

Closes https://github.com/ChainSafe/lodestar/issues/2771

### CODE REVIEW

File: packages/lodestar/src/chain/validation/aggregateAndProof.ts [hunk 1]
```diff
@@ -1,143 +1,122 @@
...
-  // TODO: once we have pool, check if aggregate block is seen and has target as ancestor
-
-  // verifySignature = false, verified in batch above
-  if (!phase0.isValidIndexedAttestation(attestationTargetState, indexedAttestation, false)) {
-    throw new AttestationError({
-      code: AttestationErrorCode.INVALID_INDEXED_ATTESTATION,
-      job: attestationJob,
-    });
+  if (chain.seenAggregators.isKnown(targetEpoch, aggregatorIndex)) {
+    throw new AttestationError({code: AttestationErrorCode.AGGREGATOR_ALREADY_KNOWN, targetEpoch, aggregatorIndex});
```
Comment (twoeths) [inline packages/lodestar/src/chain/validation/aggregateAndProof.ts:109]: why is aggregator unique per target epoch?

File: packages/lodestar/src/chain/validation/attestation.ts [hunk 2]
```diff
@@ -1,177 +1,286 @@
...
-    throw new AttestationError({
-      code: AttestationErrorCode.BAD_TARGET_EPOCH,
-      job: attestationJob,
-    });
+  // Now that the attestation has been fully verified, store that we have received a valid attestation from this validator.
+  //
+  // It's important to double check that the attestation still hasn't been observed, since
+  // there can be a race-condition if we receive two attestations at the same time and
+  // process them in different threads.
+  if (chain.seenAttesters.isKnown(targetEpoch, validatorIndex)) {
```
Comment (twoeths) [inline packages/lodestar/src/chain/validation/attestation.ts:144]: this is a duplicate, checked above already

File: packages/lodestar/src/chain/validation/attestation.ts [hunk 3]
```diff
@@ -1,177 +1,286 @@
...
-    const signatureSet = allForks.getIndexedAttestationSignatureSet(attestationTargetState, indexedAttestation);
-    if (!(await chain.bls.verifySignatureSets([signatureSet]))) {
-      throw new AttestationError({
-        code: AttestationErrorCode.INVALID_SIGNATURE,
-        job: attestationJob,
-      });
-    }
+  // [IGNORE] There has been no other valid attestation seen on an attestation subnet that has an
+  // identical attestation.data.target.epoch and participating validator index.
+  if (chain.seenAttesters.isKnown(targetEpoch, validatorIndex)) {
```
Comment (twoeths) [inline packages/lodestar/src/chain/validation/attestation.ts:124]: seems like this cache strategy is a great improvement compared to our current one 👍 
confirm that each validator is a unique attester for an epoch as in `computeEpochShuffling`

File: packages/lodestar/src/chain/validation/aggregateAndProof.ts (hunk 1 above)
Comment (twoeths) [reply packages/lodestar/src/chain/validation/aggregateAndProof.ts:109]: an aggregator index is just a validator index so it's unique per epoch as confirmed by `computeEpochShuffling`

File: packages/lodestar/src/chain/validation/aggregateAndProof.ts [hunk 4]
```diff
@@ -1,143 +1,122 @@
...
 
-  // TODO: once we have pool, check if aggregate block is seen and has target as ancestor
-
-  // verifySignature = false, verified in batch above
-  if (!phase0.isValidIndexedAttestation(attestationTargetState, indexedAttestation, false)) {
-    throw new AttestationError({
-      code: AttestationErrorCode.INVALID_INDEXED_ATTESTATION,
-      job: attestationJob,
-    });
+  if (chain.seenAggregators.isKnown(targetEpoch, aggregatorIndex)) {
```
Comment (twoeths) [inline packages/lodestar/src/chain/validation/aggregateAndProof.ts:108]: this is a lightweight check, should we move it to the early stage?

File: packages/lodestar/src/chain/validation/attestation.ts [hunk 5]
```diff
@@ -1,177 +1,286 @@
...
-}
+/**
+ * Verifies that the `attestation.data.target.root` is indeed the target root of the block at
+ * `attestation.data.beacon_block_root`.
+ */
+function verifyAttestationTargetRoot(headBlock: IBlockSummary, targetRoot: Root, attestationEpoch: Epoch): void {
+  // Check the attestation target root.
+  const headBlockEpoch = computeEpochAtSlot(headBlock.slot);
+
+  if (headBlockEpoch > attestationEpoch) {
```
Comment (twoeths) [inline packages/lodestar/src/chain/validation/attestation.ts:226]: this does not go with the comment, please double check

Comment (twoeths) [reply packages/lodestar/src/chain/validation/attestation.ts:226]: ok so headBlock here is not the head of our forkchoice, the name is misleading

File: packages/lodestar/src/chain/validation/aggregateAndProof.ts (hunk 4 above)
Comment (twoeths) [reply packages/lodestar/src/chain/validation/aggregateAndProof.ts:108]: this is a duplicate, checked above

File: packages/beacon-state-transition/src/util/aggregationBits.ts [hunk 6]
```diff
@@ -134,3 +135,55 @@ export function bitsToUint8Array<BitArr extends BitList | BitVector>(
   // the last chunk has 32 bytes but we don't use all of them
   return Buffer.concat(chunks).subarray(0, Math.ceil(bits.length / BITS_PER_BYTE));
 }
+
+/**
+ * Variant to extract a single bit (for un-aggregated attestations)
+ */
+export function getSingleBitIndex(bits: BitList | TreeBacked<BitList>): number {
```
Comment (twoeths) [inline packages/beacon-state-transition/src/util/aggregationBits.ts:142]: missing unit test for this

File: packages/lodestar/src/chain/clock/LocalClock.ts [hunk 7]
```diff
@@ -9,6 +9,10 @@ import {ChainEvent, ChainEventEmitter} from "../emitter";
 import {IBeaconClock} from "./interface";
 import {MAXIMUM_GOSSIP_CLOCK_DISPARITY} from "../../constants";
 
+// let latest_permissible_slot = chain
```
Comment (twoeths) [inline packages/lodestar/src/chain/clock/LocalClock.ts]: remove this?

File: packages/lodestar/src/chain/eventHandlers.ts [hunk 8]
```diff
@@ -244,32 +236,19 @@ export async function onBlock(
...
-
-    if (this.metrics) {
-      // Register attestations in metrics
-      for (const attestation of indexedAttestations) {
-        if (attestation) {
-          this.metrics.registerAttestationInBlock(attestation, block.message);
-        }
+    for (const attestation of attestations) {
+      try {
+        const indexedAttestation = postState.epochCtx.getIndexedAttestation(attestation);
```
Comment (twoeths) [inline packages/lodestar/src/chain/eventHandlers.ts:245]: we did get indexed attestation to verify signatures. I wonder if we could get it from some caches to avoid creating it again?

File: packages/lodestar/src/chain/validation/attestation.ts [hunk 9]
```diff
@@ -1,177 +1,286 @@
...
-      job: attestationJob,
+      code: AttestationErrorCode.BAD_TARGET_EPOCH,
     });
   }
 
-  // No need to check if `attestation.data.beaconBlockRoot` is a badBlock
-  // If it is, the ForkChoice won't know about it so the `chain.forkChoice.hasBlock` is sufficient
+  // Ensure attestation is within the last ATTESTATION_PROPAGATION_SLOT_RANGE slots (within a MAXIMUM_GOSSIP_CLOCK_DISPARITY allowance).
+  //
+  // TODO (LH): Do not queue future attestations for later processing. Investigate why LH doesn't do it
```
Comment (twoeths) [inline packages/lodestar/src/chain/validation/attestation.ts]: I think this is because they have `toleranceSec` check per slot range validation, that should be enough (far future slot should be invalid)

Comment (twoeths) [reply packages/lodestar/src/chain/validation/attestation.ts]: so we can remove this 2 `TODO` concern

File: packages/lodestar/src/chain/validation/attestation.ts [hunk 10]
```diff
@@ -1,177 +1,286 @@
...
-    });
+/**
+ * Verify that the `attestation` is within the acceptable gossip propagation range, with reference
+ * to the current slot of the `chain`.
+ *
+ * Accounts for `MAXIMUM_GOSSIP_CLOCK_DISPARITY`.
+ */
+export function verifyPropagationSlotRange(chain: IBeaconChain, attestationSlot: Slot): void {
+  // TODO (LH): Do not queue future attestations for later processing. Investigate why LH doesn't do it
+  // TODO: use MAXIMUM_GOSSIP_CLOCK_DISPARITY to compute the clock.currentSlot
```
Comment (twoeths) [inline packages/lodestar/src/chain/validation/attestation.ts]: remove these 2 TODOs as we count on `MAXIMUM_GOSSIP_CLOCK_DISPARITY_SEC` already

File: packages/lodestar/src/chain/validation/attestation.ts (hunk 2 above)
Comment (dapplion) [reply packages/lodestar/src/chain/validation/attestation.ts:144]: > this is a duplicate, checked above already

The duplication is intentional, since there as async call before to the bls verification there's a race condition.

```
// It's important to double check that the attestation still hasn't been observed, since
  // there can be a race-condition if we receive two attestations at the same time and
  // process them in different threads.
```

File: packages/lodestar/src/chain/validation/aggregateAndProof.ts (hunk 4 above)
Comment (dapplion) [reply packages/lodestar/src/chain/validation/aggregateAndProof.ts:108]: The duplication is intentional, since there as async call before to the bls verification there's a race condition.

I should add a comment there tho

File: packages/lodestar/src/chain/validation/attestation.ts (hunk 5 above)
Comment (dapplion) [reply packages/lodestar/src/chain/validation/attestation.ts:226]: What name would you use here?

File: packages/lodestar/src/chain/eventHandlers.ts (hunk 8 above)
Comment (dapplion) [reply packages/lodestar/src/chain/eventHandlers.ts:245]: Right! I though about this optimization too, it should be doable but I would tackle in another PR for sure.

Comment (twoeths) [reply packages/lodestar/src/chain/eventHandlers.ts:245]: agree 👍

File: packages/lodestar/src/chain/validation/attestation.ts (hunk 5 above)
Comment (twoeths) [reply packages/lodestar/src/chain/validation/attestation.ts:226]: just read it again, `headBlock` means the head block the attester voted for so it's still valid, but in lodestar we mean the current head of our forkchoice
maybe just adding a comment in the method header would be enough

File: packages/lodestar/src/chain/eventHandlers.ts (hunk 8 above)
Comment (dapplion) [reply packages/lodestar/src/chain/eventHandlers.ts:245]: https://github.com/ChainSafe/lodestar/issues/2771

**Review by twoeths — DISMISSED** [review]
looks good to me. Something I notice from this PR
+ we'll not have the issue in #2748
+ the simple cache of validator index/aggregator index is really an improvement to us

for gossip `AggregatedAndProof`, we need to be prepared to process ~600 messages per slot (1 slot = 64 committee indices, each committee has 8-9 aggregators), we'll see if we can handle that well with this update

**Comment by dapplion** [comment]
Huge difference in our throughput of gossip objects. Ran this branch from 15:00 in the chart below (note it's logarithmic)

Screenshot from 2021-06-30 17-03-18

**Comment by dapplion** [comment]
Been running overnight, still showing a massive improvement in throughput. Ran this branch after 06/30 15:00

Screenshot from 2021-07-01 12-11-11

**Review by wemeetagain — APPROVED** [review]
