### PR TITLE
fix: make light client events spec compliant

### LINKED ISSUE #6197: Eventstream API light client events spec compatibility
### Describe the bug

Currently Lodestar does not return light client events as defined in spec examples [beacon-APIs/#/Events/eventstream](https://ethereum.github.io/beacon-APIs/#/Events/eventstream).

The [spec example](https://github.com/ethereum/beacon-APIs/blob/6559c852193b14a33ddcb1ba770db29d62a52878/apis/eventstream/index.yaml#L98-L102) has an additional version field and wrapps the actual light client updates into data layer (similar to REST API)
```yaml
            light_client_finality_update:
              description: The node's latest known `LightClientFinalityUpdate` has been updated
              value: |
                event: light_client_finality_update
                data: {"version":"phase0", "data": {"attested_header": {"beacon": { ... }}
```

This incompatibility causes issues as Lodestar and Nimbus beacon node return different data formats.
- https://lodestar-mainnet.chainsafe.io/eth/v1/events?topics=light_client_optimistic_update
- http://testing.mainnet.beacon-api.nimbus.team/eth/v1/events?topics=light_client_optimistic_update

This was brought up by @rdvorkin at the Light Client Summit at Devconnect in [Building a trustless light-client assistant in your browser](https://app.streameth.org/devconnect/light_client_summit/session/remote_presenter_building_a_trustless_lightclient_assistant_in_your_browser) around 11:30

image

Other issues that @jeluard brought up about the light client event examples
- version is `phase0` whereas light client was introduced in `altair` (fails our spec tests)
- `sync_committee_bits` too short

We should clarify if the current format as outlined in the spec should be the standard or we want to omit version and data layer. Other events do not use a data layer in the serialized json which makes the light client events a bit of an outlier.

### Additional context

We currently just calculate the fork version based on slot in attested header
```python
compute_fork_version(compute_epoch_at_slot(data.attested_header.beacon.slot))
```

https://github.com/ChainSafe/lodestar/blob/c044d4cdd484a7e5ac90e83169955bd6e4697063/packages/api/src/beacon/routes/events.ts#L213

### Related

Testing Lodestar events API against the spec examples causes issues as well and we have to ignore those topics during testing
- https://github.com/ChainSafe/lodestar/issues/6170

Beacon-API spec PR (there was no discussion around events format)
- https://github.com/ethereum/beacon-APIs/pull/247

### PR DESCRIPTION
**Pull request by jeluard**
**Motivation**

Make sure returned eventstreams follow the [spec](https://github.com/ethereum/beacon-APIs/blob/master/apis/eventstream/index.yaml#L98)

**Description**

Current implementation of some eventstream values do not follow the spec (missing data indirection and version field).  

Closes #6197

### CODE REVIEW

File: packages/api/test/unit/beacon/testData/events.ts [hunk 1]
```diff
@@ -93,16 +93,56 @@ export const eventTestData: EventData = {
...
+        "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
+        "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2"]),
+      syncAggregate: ssz.altair.SyncAggregate.fromJson({
+        "sync_committee_bits": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001",
+        "sync_committee_signature": "0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505"
+      }),
+      signatureSlot: 1,
+    }
   },
   [EventType.lightClientUpdate]: ssz.altair.LightClientUpdate.defaultValue(),
```
Comment (jeluard) [inline packages/api/test/unit/beacon/testData/events.ts]: It is unclear if this event should follow the same pattern (not part of the spec examples).

**Review by wemeetagain — DISMISSED** [review]
lgtm

File: packages/api/src/beacon/routes/events.ts [hunk 2]
```diff
@@ -208,28 +208,28 @@ export function getTypeByEvent(config: ChainForkConfig): {[K in EventType]: Type
...
-        )["LightClientOptimisticUpdate"].fromJson(data),
-    },
-    [EventType.lightClientFinalityUpdate]: {
-      toJson: (data) =>
-        getLightClientTypeFromHeader((data as unknown as allForks.LightClientFinalityUpdate).attestedHeader)[
+        )["LightClientOptimisticUpdate"]
+    ),
+    [EventType.lightClientFinalityUpdate]: WithVersion(
+      (_, data) =>
+        getLightClientTypeFromHeader((data as allForks.LightClientFinalityUpdate).attestedHeader)[
```
Comment (nflaig) [inline packages/api/src/beacon/routes/events.ts]: The benefit of this having the version as part of the data is that we can now use the version from there instead of having to calculate it based on the attestedHeader

**Review by nflaig — CHANGES_REQUESTED** [review]
Have not yet fully reviewed this but how the version is determined is not correct

File: packages/api/src/beacon/routes/events.ts (hunk 2 above)
Comment (jeluard) [reply packages/api/src/beacon/routes/events.ts]: Right, I can probably make the change for reasons of symmetry.

My understanding is that those events will be produced only, never consumed from external sources (as in as HTTP body payload). And the `version` info is useful for event consumers to properly handle them.
Both `from`/`to` JSON are required for technical reasons (e.g. are used for our tests). Out of curiosity, is there any scenario involving consumption of those events?

Comment (nflaig) [reply packages/api/src/beacon/routes/events.ts]: > Out of curiosity, is there any scenario involving consumption of those events?

The light client uses these events, if nobody would consume them what would be the reason to produce them?

> never consumed from external sources (as in as HTTP body payload)

Those are not classical http requests / responses here as the eventstream uses [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events)

You can easily test this in the browser when running the node and calling `http://localhost:9596/eth/v1/events?topics=light_client_optimistic_update`

Comment (jeluard) [reply packages/api/src/beacon/routes/events.ts]: My question was in the context of the lodestar codebase. As in, what triggers the `fromJSON` function. I understand lodestar light-client does?

Comment (nflaig) [reply packages/api/src/beacon/routes/events.ts]: > My question was in the context of the lodestar codebase. As in, what triggers the `fromJSON` function. I understand lodestar light-client does?

See light client
https://github.com/ChainSafe/lodestar/blob/d7ca290d173dfa82b2977f3e94df6e5e8d12ef3e/packages/light-client/src/transport/rest.ts#L77-L91

Our http client library is generic and needs to be able to handle all responses

File: packages/api/test/unit/beacon/testData/events.ts (hunk 1 above)
Comment (jeluard) [reply packages/api/test/unit/beacon/testData/events.ts]: Assuming it does.

Comment (nflaig) [reply packages/api/test/unit/beacon/testData/events.ts]: `light_client_update` is not part of the spec but I'd suggest to follow same format as other light client events

File: packages/api/test/unit/beacon/testData/events.ts [hunk 3]
```diff
@@ -93,18 +92,68 @@ export const eventTestData: EventData = {
       "0xac118511474a94f857300b315c50585c32a713e4452e26a6bb98cdb619936370f126ed3b6bb64469259ee92e69791d9e12d324ce6fd90081680ce72f39d85d50b0ff977260a8667465e613362c6d6e6e745e1f9323ec1d6f16041c4e358839ac",
   }),
   [EventType.lightClientOptimisticUpdate]: {
-    syncAggregate: ssz.altair.SyncAggregate.defaultValue(),
-    attestedHeader: ssz.altair.LightClientHeader.defaultValue(),
-    signatureSlot: ssz.Slot.defaultValue(),
+    version: ForkName.altair,
+    data: {
+      syncAggregate: ssz.altair.SyncAggregate.fromJson({
```
Comment (nflaig) [inline packages/api/test/unit/beacon/testData/events.ts]: Can't we use `LightClientOptimisticUpdate` container to parse the example data?

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 4]
```diff
@@ -294,7 +294,8 @@ export async function importBlock(
           this.lightClientServer.onImportBlockHead(
             block.message as allForks.AllForksLightClient["BeaconBlock"],
             postState as CachedBeaconStateAltair,
-            parentBlockSlot
+            parentBlockSlot,
+            this.config.getForkName(block.message.slot)
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: I don't think this is correct, the fork digest/version for light client updates needs to be determined based on `attested_header.beacon.slot`

[specs/altair/light-client/p2p-interface.md?plain=1#L102](https://github.com/ethereum/consensus-specs/blob/3727a757450feb6110e2d4e403604572a478343d/specs/altair/light-client/p2p-interface.md?plain=1#L102)

> The gossip `ForkDigest`-context is determined based on `compute_fork_version(compute_epoch_at_slot(optimistic_update.attested_header.beacon.slot))`.

There is another reference in the beacon api spec as well
[apis/beacon/light_client/updates.yaml#L55](https://github.com/ethereum/beacon-APIs/blob/c458197bb5529b2169fe51888f66f3581380b94f/apis/beacon/light_client/updates.yaml#L55)
> For each `response_chunk`, a `ForkDigest`-context based on `compute_fork_version(compute_epoch_at_slot(update.attested_header.beacon.slot))` is used to select the fork namespace of the Response type.

File: packages/beacon-node/src/chain/lightClient/index.ts [hunk 5]
```diff
@@ -227,7 +227,8 @@ export class LightClientServer {
   onImportBlockHead(
     block: allForks.AllForksLightClient["BeaconBlock"],
     postState: CachedBeaconStateAltair,
-    parentBlockSlot: Slot
+    parentBlockSlot: Slot,
+    fork: ForkName
```
Comment (nflaig) [inline packages/beacon-node/src/chain/lightClient/index.ts]: Passing the fork in like this is not ideal, we can just determine it when actually emitting the event

File: packages/api/test/unit/beacon/testData/events.ts (hunk 1 above)
Comment (nflaig) [reply packages/api/test/unit/beacon/testData/events.ts]: Event has been removed as it is not part of the spec and was not emitted either

**Review by nflaig — COMMENTED** [review]
Looks good to me now, I pushed a few minor updates.

@jeluard it might be worth to test locally if it passes the spec tests now with the version on your branch https://github.com/ethereum/beacon-APIs/pull/418

**Review by nflaig — DISMISSED** [review]

**Comment by nflaig** [comment]
From reviewing the spec, I noticed that is states that `sync_aggregate` fork might be different and is based on `signature_slot`

[specs/altair/light-client/p2p-interface.md?plain=1#L245](https://github.com/ethereum/consensus-specs/blob/3727a757450feb6110e2d4e403604572a478343d/specs/altair/light-client/p2p-interface.md?plain=1#L245)
> A `ForkDigest`-context based on `compute_fork_version(compute_epoch_at_slot(optimistic_update.attested_header.beacon.slot))` is used to select the fork namespace of the Response type. Note that this `fork_version` may be different from the one used to verify the `optimistic_update.sync_aggregate`, which is based on `optimistic_update.signature_slot`.

I don't think we are following the spec here, but based on our current design of spec types it is difficult to use a different fork type for nested properties. 

This seems to be mostly relevant during a hard fork and only if the `SyncAggregate` changes between those forks.

@wemeetagain @g11tech any thoughts?

**Review by nflaig — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
unrelated e2e test failed due to timeout

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.15.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.15.0) :tada:
