### PR TITLE
Fix getSyncCommitteeDuties api

### LINKED ISSUE #2738: Incorrect SyncCommittee duties
**Describe the bug**

This log shows that we consistently have all validators stay in sync committee which does not seem right
```
Jun-23 09:16:37.121 []                 info: Published SyncCommitteeSignature slot=152878, count=400
Jun-23 09:16:40.055 []                 info: Published aggregateAndProofs slot=152878, index=0, count=2
Jun-23 09:16:40.060 []                 info: Published SyncCommitteeContribution slot=152878, index=0, count=1
Jun-23 09:16:40.061 []                 info: Published SyncCommitteeContribution slot=152878, index=1, count=2
Jun-23 09:16:44.207 []                 info: Published block slot=152879, validator=0xa105…8aa8, graffiti=chainsafe/lodestar-0.24.3
Jun-23 09:16:49.030 []                 info: Published attestations slot=152879, index=0, count=14
Jun-23 09:16:49.243 []                 info: Published SyncCommitteeSignature slot=152879, count=400
```

**Expected behavior**

Just some validators stay in sync committee.

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

On oonoonba, we always have all validators stay in sync committee which does not seem right.

**Description**

At api side, we should not return anything without sync duty, see https://ethereum.github.io/eth2.0-APIs/#/Validator/getSyncCommitteeDuties
Closes #2738

### CODE REVIEW

File: packages/lodestar/src/api/impl/validator/index.ts [hunk 1]
```diff
@@ -279,11 +280,18 @@ export function getValidatorApi({
...
+          const validatorSyncCommitteeIndices = syncComitteeValidatorIndexMap.get(validatorIndex);
+          return validatorSyncCommitteeIndices
+            ? {
+                pubkey: state.validators[validatorIndex].pubkey,
+                validatorIndex,
+                validatorSyncCommitteeIndices,
+              }
+            : null;
+        })
+        .filter(notNullish);
```
Comment (dapplion) [inline packages/lodestar/src/api/impl/validator/index.ts]: Refactor with 
```ts
const arr = []
for (a of b) {
  if (a) arr.push(a)
}
```
to prevent having to loop twice and using notNullish

**Review by dapplion — DISMISSED** [review]

**Comment by twoeths** [comment]
Tested with contabo-1
```
Jun-23 10:20:24.591 []                 info: Published SyncCommitteeSignature slot=153197, count=73
```

**Review by dapplion — APPROVED** [review]

**Review by mpetrunic — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]
