### PR TITLE
Prevent MaxListenersExceededWarning observed in validator's abort controller

### LINKED ISSUE #3569: Investigate possible EventEmitter memory leak
**Describe the bug**

While trying to run lodestar on local testnet following the documentation [here](https://chainsafe.github.io/lodestar/usage/local/), I ran into complications which led to me to create this issue [here](https://github.com/ChainSafe/lodestar/issues/3568).

Part of what I noticed, while trying to get Lodestar running in the logs was this error:

> (node:15159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 chainHead listeners added to [ValidatorEventEmitter]. Use emitter.setMaxListeners() to increase limit

On a quick investigation, the issue seems to be coming from [this part](https://github.com/ChainSafe/lodestar/blob/c384b36a1b52d8607842b363e1f07f6ccc5d6004/packages/validator/src/services/attestation.ts#L50) of the code.

Two promises are being raced. One of the promises `this.waitForBlockSlot(slot)`, sets event listeners. As can be seen [here](https://github.com/ChainSafe/lodestar/blob/c384b36a1b52d8607842b363e1f07f6ccc5d6004/packages/validator/src/services/attestation.ts#L64). 

On my local, it seems the promise with the event listener never wins this race, and never is the one that gets resolved, hence the listener is never removed, hence leads to the the warning message that pops up in the log.

**Expected behavior**

Preferably not have the EventEmitter memory leak warning. 

Hence:

- Confirm if this is indeed an issue
- Confirm if this can only practically show up in the local testnet - hence severity will be low
- If need be, see how this can be resolved.

### LINKED ISSUE #4394: MaxListenersExceededWarning: Possible EventTarget memory leak detected.
**Describe the bug**

I'm running lodestar from the unstable branch to test mev-boost.

I'm following these instructions: https://github.com/flashbots/mev-boost/wiki/Testing/fa8b3f72058255fe394066bab285a3e6a9be92fd#lodestar

When I start it to run the beacon node, this error appears:

```
$ ./lodestar beacon --network kiln --builder.enabled --builder.urls http://127.0.0.1:18550 --jwt-secret=/home/$USER/workspace/sec
ret                                                                                                                                                                         
Aug-11 00:59:44.258[]                 info: Lodestar network=kiln, version=v0.41.0/0de0144, commit=0de01443f1f4cfa6efc12783c5783f0035e4e29f                                 
Aug-11 00:59:44.293[]                 info: Connected to LevelDB database name=/home/ubuntu/.local/share/lodestar/kiln/peerstore                                            
Aug-11 00:59:44.319[DB]               info: Connected to LevelDB database name=/home/ubuntu/.local/share/lodestar/kiln/chain-db                                             
Aug-11 00:59:51.145[]                 info: Initializing beacon state from anchor state slot=5280, epoch=165, stateRoot=0x0a100f221de872f1f39758d1fac3673beb367f07333ca7fe36
6c28123be187af
Aug-11 00:59:51.425[ETH1]             info: Starting search for terminal POW block TERMINAL_TOTAL_DIFFICULTY=20000000000000
(node:4021308) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase l
imit
(Use `node --trace-warnings ...` to show where the warning was created)
```

It is now syncing, so this error does not seem problematic so far.

**Expected behavior**

The beacon node runs with no errors shown.

**Steps to Reproduce**

Follow this instructions to compile and run:
https://github.com/flashbots/mev-boost/wiki/Testing/fa8b3f72058255fe394066bab285a3e6a9be92fd#lodestar

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version: 22.04
- Branch: unstable
- Commit hash: 0de01443f1f4cfa6efc12783c5783f0035e4e29f

```
$ ./lodestar --version
🌟 Lodestar: TypeScript Implementation of the Ethereum Consensus Beacon Chain.
  * Version: v0.41.0/0de0144
  * by ChainSafe Systems, 2018-2022
```

### PR DESCRIPTION
**Pull request by dadepo**
**Motivation**

See https://github.com/ChainSafe/lodestar/issues/3569 and # https://github.com/ChainSafe/lodestar/issues/4394 for bug report

**Description**

While running the validator client I noticed the following lines in the log:

```
Sep-06 11:51:38.076[]                 info: Genesis available
Sep-06 11:51:38.084[]                 info: Verified node and validator have same config
Sep-06 11:51:38.084[]                 info: Verified node and validator have same genesisValidatorRoot
Sep-06 11:51:38.133[]                 info: Discovered new validators count=3
(node:46338) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
    at AbortSignal.[kNewListener] (node:internal/event_target:426:17)
    at AbortSignal.[kNewListener] (node:internal/abort_controller:173:24)
    at AbortSignal.addEventListener (node:internal/event_target:535:23)
    at file:///Users/dadepoaderemi/Documents/work/testing_remote_signer/lodestar/packages/utils/src/sleep.ts:26:24
    at new Promise (<anonymous>)
    at sleep (file:///Users/dadepoaderemi/Documents/work/testing_remote_signer/lodestar/packages/utils/src/sleep.ts:12:10)
    at Clock.runAtMostEvery (file:///Users/dadepoaderemi/Documents/work/testing_remote_signer/lodestar/packages/validator/src/util/clock.ts:101:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This PR prevents this by setting the max event listener for the abort controller that trigger the log to infinity.

resolves #3569 
resolves #4394

### CODE REVIEW

File: packages/cli/src/cmds/validator/handler.ts [hunk 1]
```diff
@@ -66,9 +67,19 @@ export async function validatorHandler(args: IValidatorCliArgs & IGlobalArgs): P
...
   logSigners(logger, signers);
 
-  // This AbortController interrupts the sleep() calls when waiting for genesis
-  const controller = new AbortController();
-  onGracefulShutdownCbs.push(async () => controller.abort());
+  const abortControllers: ValidatorAbortController = {
+    // This AbortController interrupts the sleep() calls when waiting for genesis
+    genesisReqController: new AbortController(),
+    // This AbortController interrupts the validators ops: clients call, clock etc
+    validatorOpsController: new AbortController(),
```
Comment (dapplion) [inline packages/cli/src/cmds/validator/handler.ts]: It looks like you could only need 1 AbortController, can you try that?

**Review by wemeetagain — APPROVED** [review]

**Comment by dapplion** [comment]
_note this was merged before I had time to review_

Having to pass an AbortController to the validator class is a very weird API. Consumers would be asking why? And the only justification is that we don't want to print a log. The tradeoff here doesn't make sense IMO. Is this really the only way to suppress such log in NodeJS? I think there must be a better solution.
