### PR TITLE
fix: support eth_getBlockByNumber

### LINKED ISSUE #6032: lodestar/prover eth_getBlockByNumber doesn't work correctly
### Describe the bug

getExecutionPayloadForBlockNumber gets called here https://github.com/ChainSafe/lodestar/blob/unstable/packages/prover/src/proof_provider/payload_store.ts#L97
with min blocknumber stored and the requested blocknumber
But getExecutionPayloadForBlockNumber seems to accept a beacon slot and not min block as parameter, therefore later in the code it tries to fetch a beacon block for an el block number and fails
https://github.com/ChainSafe/lodestar/blob/unstable/packages/prover/src/utils/consensus.ts#L82
https://github.com/ChainSafe/lodestar/blob/unstable/packages/prover/src/utils/consensus.ts#L14

### Expected behavior

using the verified provider to call eth_getBlockByNumber should work 

### Steps to reproduce

```typescript
import Web3 from “web3”;
import { createVerifiedExecutionProvider, LCTransport } from “@lodestar/prover”;
import { LogLevel } from “@lodestar/logger”;
const network = “mainnet”;
const beaconApiUrl = “https://lodestar-mainnet.chainsafe.io”;
const elRpcUrl = “https://lodestar-mainnetrpc.chainsafe.io”;
const checkpoint =
 “0xcc8251d86c07d31c2afd7edda6df5896d7b8b721b4402557f1a8de4a5965ae09”;
const { provider, proofProvider } = createVerifiedExecutionProvider(
 new Web3.providers.HttpProvider(elRpcUrl),
 {
  transport: LCTransport.Rest,
  urls: [beaconApiUrl],
  network: network,
  wsCheckpoint: checkpoint,
  logLevel: LogLevel.info,
 }
);
const verifiedWeb3 = new Web3(provider);
const blockNum = 17956161;
const verifiedBlock = await verifiedWeb3.eth.getBlock(blockNum);
console.log(verifiedBlock);

```

### Additional context

_No response_

### Operating system

macOS

### Lodestar version or commit hash

1.11.1

### PR DESCRIPTION
**Pull request by jeluard**
**Motivation**

Make sure the web3 provider `prover` wrapper correctly handles `eth_getBlockByNumber`

**Description**

During verification, wrapped calls to `eth_getBlockByNumber` try to access EL blocks using block numbers, which is incorrect. Issue is fixed by keeping track of slots numbers when new light-client header are received.

Note that when trying to access older blocks it might get slow, as current implementation tries to find matching EL blocks by querying CL slots one by one starting from freshly finalized slots.  

Closes #6032

### CODE REVIEW

**Review by nazarhussain — CHANGES_REQUESTED** [review]
As this PR is addressing a user facing bug, let's extract the refactoring to a separate PR. 

1. Changes of `Record` to `Map`, have no objection just keep in separate PR. 
2. Would be nice to add an E2E test for the fianlized block root, it will be easy to test in the current e2e test setup.

**Review by nazarhussain — APPROVED** [review]

File: packages/prover/src/utils/consensus.ts [hunk 1]
```diff
@@ -6,14 +6,21 @@ import {Logger} from "@lodestar/utils";
 import {MAX_PAYLOAD_HISTORY} from "../constants.js";
 import {hexToBuffer} from "./conversion.js";
 
+export async function fetchBlock(api: Api, slot: number): Promise<capella.SignedBeaconBlock | undefined> {
+  const res = await api.beacon.getBlockV2(slot);
```
Comment (nflaig) [inline packages/prover/src/utils/consensus.ts:10]: are we fine with throwing here if there is a network error?

Comment (jeluard) [reply packages/prover/src/utils/consensus.ts:10]: If an error is thrown here then a light-client header is not processed (that error will be logged).

I think that it's ok in the context of this PR as it doesn't change this behavior. If required a proper solution could be implemented separately.

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada:
