### PR TITLE
Filter out files that has data_store in name when resolving keystore path

### LINKED ISSUE #3611: Validator handler is expecting objects only in /keystores
**Describe the bug**

When other files, including the deposit_data.json are in the lodestar/keystores folder, the validator client returns the following error on startup:

```
Jan-13 04:43:12.373 []                 info: Lodestar version=v0.33.0 (npm), network=prater
 ✖ Error: : should be object
    at Object.validateKeystore (/usr/app/node_modules/@chainsafe/bls-keystore/lib/functional.js:111:15)
    at Function.fromObject (/usr/app/node_modules/@chainsafe/bls-keystore/lib/class.js:46:22)
    at Function.parse (/usr/app/node_modules/@chainsafe/bls-keystore/lib/class.js:53:25)
    at /usr/app/node_modules/@chainsafe/lodestar-cli/src/cmds/validator/keys.ts:65:44
    at Array.map (<anonymous>)
    at getSecretKeys (/usr/app/node_modules/@chainsafe/lodestar-cli/src/cmds/validator/keys.ts:64:21)
    at Object.validatorHandler [as handler] (/usr/app/node_modules/@chainsafe/lodestar-cli/src/cmds/validator/handler.ts:32:79)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Expected behavior**

Lodestar validator should ignore files other than the keystore-m.json files, rather than crash with an error if other files are detected.

**Steps to Reproduce**
1. Put other files, specifically the `deposit_data.json` files in the /keystores folder. 
2. Run the validator client
3. Receive object expected error.

**Desktop (please complete the following information):**

- OS: Ubuntu Server 20.04.3
- Version: v0.33.0
- Branch: v0.33.0 release branch
- Commit hash: 56de734

### PR DESCRIPTION
**Pull request by dadepo**
**Motivation**

Prevents lodestar from crashing if deposit data files are encountered when resolving keystore path.

**Description**

Filtering out file names that contains deposit_data, when solving keystore path so as to prevent crashing on start up.

Closes #3611

**Steps to test or reproduce**

- Put deposit_data.json files in the /keystores folder.
- Run the validator client with `--importKeystoresPath` flag
- Receive object expected error.

### CODE REVIEW

File: packages/cli/src/cmds/validator/keys.ts [hunk 1]
```diff
@@ -88,8 +88,8 @@ function resolveKeystorePaths(fileOrDirPath: string): string[] {
   if (fs.lstatSync(fileOrDirPath).isDirectory()) {
     return fs
       .readdirSync(fileOrDirPath)
-      .map((file) => path.join(fileOrDirPath, file))
-      .filter((filepath) => filepath.endsWith(".json"));
+      .filter((file) => file.indexOf("deposit_data") === -1 && file.endsWith(".json"))
```
Comment (dapplion) [inline packages/cli/src/cmds/validator/keys.ts]: A Regex expression is typically much faster than indexOf and endsWith and much more idiomatic

Comment (dadepo) [reply packages/cli/src/cmds/validator/keys.ts]: > A Regex expression is typically much faster than indexOf  and endsWith

I think that is debatable. The benchmarks I see (not ones I run myself) suggests this is not the case.

> and much more idiomatic

Using regex is definitely more succinct, and since this is not a hot code path, I guess it is fine to go with the regex. 

I have updated.

Comment (dapplion) [reply packages/cli/src/cmds/validator/keys.ts]: Good point I haven't benchmarked it :laughing:

**Comment by dapplion** [comment]
Can you add a couple unit tests for resolveKeystorePaths()?

**Review by dapplion — APPROVED** [review]
Looks good! :heart:
