### PR TITLE
Log expected api errors as warning instead of error

### LINKED ISSUE #5265: Log `Validator pubkey not found` as a warning
**Describe the bug**

In situations where a user's validator client may be running inactive validators, they may get a `404` error when trying to [get the state validator index](https://github.com/ChainSafe/lodestar/blob/15a9035ad030aaee303f13a5bbc0b409cc63385f/packages/beacon-node/src/api/impl/beacon/state/index.ts#L67)  this error case should perhaps be logged as a warning.

See [discussion here](https://discord.com/channels/593655374469660673/743858262864167062/1084527788435976323)

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Expected API errors (`ApiError`) should be logged as warnings instead of errors to not unnecessarily scare users. Printing out the stacktrace does not help here either, it just creates noise.

**Description**

Check if error is `ApiError` and just log it as `warn` and only print out the `err.message`.

Unexpected errors (non `ApiError`) will still be logged as `error` including the stacktrace.

Closes https://github.com/ChainSafe/lodestar/issues/5265, related [discussion](https://discord.com/channels/593655374469660673/743858262864167062/1084567242437558292)

### CODE REVIEW

File: packages/beacon-node/src/api/rest/base.ts [hunk 1]
```diff
@@ -97,7 +97,12 @@ export class RestApiServer {
       if (err instanceof ErrorAborted || err instanceof NodeIsSyncing) return;
 
       const {operationId} = res.context.config as RouteConfig;
-      this.logger.error(`Req ${req.id} ${operationId} error`, {}, err);
+
+      if (err instanceof ApiError && err.statusCode < 500) {
```
Comment (maschad) [inline packages/beacon-node/src/api/rest/base.ts]: Are you sure that all **400 codes** should not be logged as errors? I would think particular instances such as a [404 for resolving a block ID](https://github.com/ChainSafe/lodestar/blob/unstable/packages/beacon-node/src/api/impl/beacon/blocks/utils.ts#L34) it should be thrown as an error, otherwise we can't fetch a block root for example.

Also [if we fail to provide a set of sync committee duties for a particular epoch](https://github.com/ChainSafe/lodestar/blob/unstable/packages/beacon-node/src/api/impl/validator/index.ts#L479) , a `400` error is thrown. Perhaps what could be considered is optionally returning the stack trace as suggested in the [spec](https://github.com/ethereum/beacon-APIs/blob/master/types/http.yaml#L141)

**Review by maschad — CHANGES_REQUESTED** [review]
I am not sure all non-500 error codes are just warnings

File: packages/beacon-node/src/api/rest/base.ts (hunk 1 above)
Comment (nflaig) [reply packages/beacon-node/src/api/rest/base.ts]: > Are you sure that all 400 codes should not be logged as errors?

pretty much, in fact, could even remove the `err.statusCode < 500` in my opinion, there is anyway just one error at the moment were this would make a difference https://github.com/ChainSafe/lodestar/blob/cd2ec2ee9878a12c09742c76fb2681a4e7d551e2/packages/beacon-node/src/api/impl/validator/index.ts#L356

> [404 for resolving a block ID](https://github.com/ChainSafe/lodestar/blob/unstable/packages/beacon-node/src/api/impl/beacon/blocks/utils.ts#L34) it should be thrown as an error, otherwise we can't fetch a block root for example.

I am not really sure how this change affects what you mentioned, all that changed now is that we log it as a warning with less verbosity (no stacktrace) instead of an error. The API response is still the same.
The two examples you linked just further enforce the change I want to introduce, there is no reason at all we should log a stacktrace when those errors happen.


> Perhaps what could be considered is optionally returning the stack trace as suggested in the [spec](https://github.com/ethereum/beacon-APIs/blob/master/types/http.yaml#L141)

For some unexpected errors it could make sense to also include the stacktrace in the HTTP error response but might as well just look at the logs instead. Maybe someone else in the team has an opinion on this, but I would not implement this unless there is a specific use case for it.

**Comment by nflaig** [comment]
> I am not sure all non-500 error codes are just warnings

regarding this, if there are non-500 error codes which are not considered a warning but something critical then the error code must be changed

File: packages/beacon-node/src/api/rest/base.ts (hunk 1 above)
Comment (nflaig) [inline packages/beacon-node/src/api/rest/base.ts]: consider logging all api errors as warning

```suggestion
      if (err instanceof ApiError) {
```

Comment (wemeetagain) [reply packages/beacon-node/src/api/rest/base.ts]: I'm in favor of this change

File: packages/beacon-node/src/api/rest/base.ts [hunk 2]
```diff
@@ -97,7 +97,12 @@ export class RestApiServer {
       if (err instanceof ErrorAborted || err instanceof NodeIsSyncing) return;
 
       const {operationId} = res.context.config as RouteConfig;
-      this.logger.error(`Req ${req.id} ${operationId} error`, {}, err);
+
+      if (err instanceof ApiError) {
+        this.logger.warn(`Req ${req.id} ${operationId} failed`, {reason: err.message});
```
Comment (nflaig) [inline packages/beacon-node/src/api/rest/base.ts:102]: @wemeetagain I want to establish this pattern that for non-critical issues we use the terms "failed"  and "reason" instead of "error" as based on my observations the term "error" scares a lot of users, especially less technical ones. What do you think?

Comment (wemeetagain) [reply packages/beacon-node/src/api/rest/base.ts:102]: :+1: :+1:

**Review by wemeetagain — APPROVED** [review]

File: packages/beacon-node/src/api/rest/base.ts (hunk 2 above)
Comment (g11tech) [reply packages/beacon-node/src/api/rest/base.ts:102]: i think the stack trace is very useful, but we can move the log to `debug` will full trace, an additional `warn` log in this format is acceptable

Comment (nflaig) [reply packages/beacon-node/src/api/rest/base.ts:102]: > but we can move the log to debug will full trace, an additional warn log in this format is acceptable

that's also what I was considering, sounds like a reasonable compromise. Not sure if it makes sense here though in case of `ApiError`, if someone feels strongly about having a stack trace for those we should probably log it as well to `debug`

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.7.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.7.0) :tada:
