### PR TITLE
Fetch weakSubjectivityState timeout

### LINKED ISSUE #4190: Timeout downloading weak subjectivity state
**Describe the bug**

Got this error when trying to download a weak subjectivity state:

```
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:  ✖ Error: Unable to fetch weak subjectivity state: Timeout request
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at fetchWeakSubjectivityState (file:///usr/src/lodestar/packages/cli/src/networks/index.ts:190:11)
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at initFromWSState (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:153:37)
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at initBeaconState (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:94:12)
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at Object.beaconHandler [as handler] (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/handler.ts:68:41)
```

**Expected behavior**

Since the state is big, we should be able to increase the timeout at client api when downloading a state

**Steps to Reproduce**

Use below param:
```
weakSubjectivitySyncLatest: "true"
weakSubjectivityServerUrl: "https://some-server.io"
weakSubjectivityCheckpoint: "checkpoint:epoch"
```

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

It may take up to 3m to download a weaksubjectivity state, see https://github.com/ChainSafe/lodestar/issues/4190#issuecomment-1173486780

**Description**

+ Extend timeout for `getState()` client api to 3m
+ Periodically log "Download in progress" per 30s
+ Add "Download completed" log
+ If it fails to download, instruct user to download the state manually in the error message

Closes #4190

**Test**

```
Jul-05 15:22:42.543[]                 info: Fetching weak subjectivity state weakSubjectivityServerUrl=https://eth2-beacon-prater.infura.io

Jul-05 15:23:13.695[]                 info: Download in progress, please wait ...
Jul-05 15:23:43.696[]                 info: Download in progress, please wait ...
Jul-05 15:23:49.662[]                 info: Download completed

Jul-05 15:23:58.612[]                 info: Initializing beacon state from anchor state slot=3375040, epoch=105470, stateRoot=0x2e6950f96e6adbbdb227dbcf4224d7d11df2c846a43e04971c3a08bc30c9a4e8
```

### CODE REVIEW

**Comment by g11tech** [comment]
@tuyennhv I think you will need to do rebase as unstable has been force pushed.

Also I suggest kicking it to 5minutes, just to have 50% margin for speed + state growth (in one of your runs you reported 2m something..)

File: packages/api/src/beacon/client/debug.ts [hunk 1]
```diff
@@ -2,6 +2,9 @@ import {IChainForkConfig} from "@chainsafe/lodestar-config";
 import {Api, ReqTypes, routesData, getReqSerializers, getReturnTypes, StateFormat} from "../routes/debug.js";
 import {IHttpClient, getFetchOptsSerializers, generateGenericJsonClient} from "../../utils/client/index.js";
 
+// As Jul 2022, it takes up to 3 minutes to download states
+const GET_STATE_TIMEOUT_MS = 3 * 60 * 1000;
```
Comment (g11tech) [inline packages/api/src/beacon/client/debug.ts]: lets just make it 5 min to accommodate some hefty margin as well as future state growth?

Comment (twoeths) [reply packages/api/src/beacon/client/debug.ts]: I updated it 👍

File: packages/cli/src/networks/index.ts [hunk 2]
```diff
@@ -181,13 +185,26 @@ export async function fetchWeakSubjectivityState(
...
-      ? api.debug.getState(`${stateSlot}`, "ssz")
-      : api.debug.getStateV2(`${stateSlot}`, "ssz"));
+    const getStatePromise =
+      config.getForkName(stateSlot) === ForkName.phase0
+        ? api.debug.getState(`${stateSlot}`, "ssz")
+        : api.debug.getStateV2(`${stateSlot}`, "ssz");
+
+    const stateBytes = await callFnWhenAwait(
+      getStatePromise,
+      () => logger.info("Download in progress, please wait ..."),
```
Comment (wemeetagain) [inline packages/cli/src/networks/index.ts]:
```suggestion
      () => logger.info("Download in progress, please wait..."),
```

File: packages/cli/src/networks/index.ts [hunk 3]
```diff
@@ -181,13 +185,26 @@ export async function fetchWeakSubjectivityState(
...
+
+    logger.info("Download completed");
 
     return {wsState: getStateTypeFromBytes(config, stateBytes).deserializeToViewDU(stateBytes), wsCheckpoint};
   } catch (e) {
-    throw new Error("Unable to fetch weak subjectivity state: " + (e as Error).message);
+    throw new Error(
+      "Unable to fetch weak subjectivity state: " +
+        (e as Error).message +
+        ". Consider downloading the state manually using debug api and use --weakSubjectivityStateFile option."
```
Comment (wemeetagain) [inline packages/cli/src/networks/index.ts]:
```suggestion
        ". Consider downloading a state manually and using the --weakSubjectivityStateFile option."
```

File: packages/api/src/utils/client/httpClient.ts [hunk 4]
```diff
@@ -23,6 +23,7 @@ export type FetchOpts = {
   headers?: ReqGeneric["headers"];
   /** Optional, for metrics */
   routeId?: string;
+  timeoutMs?: number;
```
Comment (wemeetagain) [inline packages/api/src/utils/client/httpClient.ts:26]: :+1:

**Review by wemeetagain — APPROVED** [review]
