### PR TITLE
Fix the terminal validations of the merge block

### LINKED ISSUE #3982: Lodestar BN never validates the `assertValidTerminalPowBlock` checks in forkchoice
Context: While doing the PR for PoS banner transition, stumbled upon an issue:

In the forkchoice we are supposed to `assertValidTerminalPowBlock` in case the block is a merge transition block. This happens via
```typescript
if (
      preCachedData?.isMergeTransitionBlock ||
      (bellatrix.isBellatrixStateType(state) &&
        bellatrix.isBellatrixBlockBodyType(block.body) &&
        bellatrix.isMergeTransitionBlock(state, block.body))
    )
      assertValidTerminalPowBlock(this.config, (block as unknown) as bellatrix.BeaconBlock, preCachedData);
```

But the issue here is that `isMergeTransitionBlock` flag being passed never comes to be true even in case of merge transition block because it is evaluated on postState in `importBlock` from where the `forkChoice.onBlock` is being called.
Furthermore the second part of the condition also evaluates to `false` as the state here is also postState as well (again passed from `importBlock`

Suggested Fix:
Lighthose runs these validations in the block verification module where we have access to preState to proposerly evaluate `isMergeTransitionBlock`. So the assertions should move over there.

Note: Check if there are any spec tests which directly pass an invalid terminal block to forkchoice for validation. If so discuss and implement appropriate resolution.

### LINKED ISSUE #3986: Modify spec runner's `fork_choice.test.ts` to include testcases for `on_merge_block` scenario
Seems like the tests for merge block transitions have been included in the specs, but our `fork_choice.test.ts` doesn't yet address them.

Modify and make the spec runner run these tests successfully.

### PR DESCRIPTION
**Pull request by g11tech**
**Motivation**
It was discovered that terminal block validations weren't running on the merge block because of incorrect evaluation of the merge transition block on postState 

This PR fixes the evaluation on preState as well as move the assertions into the verifyBlock instead of forkChoice. The `assertValidTerminalPowBlock` still stays in forkchoice because it might be required to validate terminal conditions if it imported a merge transition block in syncing status, which later becomes valid

Closes #3982, Closes #3986

### CODE REVIEW

**Comment by twoeths** [comment]
@g11tech did you find out any spec test covering the `is_valid_terminal_pow_block()` function? Otherwise I think we should ask for a spec test for it

**Comment by g11tech** [comment]
> 

I can see some tests that could be pertaining to them. I can create an issue and pursue it as a separate PR :thinking: 

Update: https://github.com/ChainSafe/lodestar/issues/3986

**Comment by g11tech** [comment]
> @g11tech did you find out any spec test covering the `is_valid_terminal_pow_block()` function? Otherwise I think we should ask for a spec test for it

added

File: packages/lodestar/src/chain/blocks/verifyBlock.ts [hunk 1]
```diff
@@ -272,6 +279,15 @@ export async function verifyBlockStateTransition(
           errorMessage: execResult.validationError,
         });
     }
+
+    if (isMergeTransitionBlock) {
```
Comment (dapplion) [inline packages/lodestar/src/chain/blocks/verifyBlock.ts:296]: Add nice long comment here like in Lighthouse explaining why we do this here and not in the forkchoice. Link also to the spec's location where this code should be.

Since this is not documenation for JSDocs use style
```ts
//
//
```

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 2]
```diff
@@ -328,14 +328,6 @@ export class ForkChoice implements IForkChoice {
...
     }
 
-    if (
-      preCachedData?.isMergeTransitionBlock ||
-      (bellatrix.isBellatrixStateType(state) &&
-        bellatrix.isBellatrixBlockBodyType(block.body) &&
-        bellatrix.isMergeTransitionBlock(state, block.body))
-    )
-      assertValidTerminalPowBlock(this.config, (block as unknown) as bellatrix.BeaconBlock, preCachedData);
-
```
Comment (dapplion) [inline packages/fork-choice/src/forkChoice/forkChoice.ts:338]: Add nice long comment here explaining why we do NOT do this here and where it's happening instead. Link also to the spec's code.

Since this is not documenation for JSDocs use style
```ts
//
//
```

**Review by dapplion — APPROVED** [review]
