### PR TITLE
Strict boolean expression

### LINKED ISSUE #3324: Disallow if coercion
**Describe the bug**

Coercing values in if statements can be problematic if the variable can be a 0 which should be truthy:

```ts
let num: number | null;
if (num) {}
```

Require

```ts
let num: number | null;
if (num !== null && num > 0) {}
```

Check: https://eslint.org/docs/rules/no-implicit-coercion

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ For if clause, we want to treat 0 and `null | undefined` differently case by case

**Description**

+ Apply `strict-boolean-expression` fule for nullable number (will consider applying for nullable string and nullable boolean later if we find it as an issue)
+ There is no configured rule for object so instead of `if (obj)` we have to do something like `if (obj !== undefined)`

Closes #3324

### CODE REVIEW

**Review by dapplion — CHANGES_REQUESTED** [review]
Looks great! Thanks for auditing all existing expressions

**Review by dapplion — APPROVED** [review]
Looks great! Thanks for auditing all existing expressions

File: packages/api/src/utils/urlFormat.ts [hunk 1]
```diff
@@ -23,22 +23,22 @@ export function compileRouteUrlFormater(path: string): (arg: Args) => string {
     const currentToken: Token | undefined = tokens[tokens.length - 1];
     switch (path[i]) {
       case ":": {
-        if (currentToken && currentToken.type === TokenType.Variable) {
+        if (currentToken !== undefined && currentToken.type === TokenType.Variable) {
```
Comment (filipesmedeiros) [inline packages/api/src/utils/urlFormat.ts:26]: wait why not `currentToken?.type`?

Comment (dapplion) [reply packages/api/src/utils/urlFormat.ts:26]: Good suggestion! Please do a PR if you want :+1:
