### PR TITLE
Assemble block: process epoch at most 1 time

### LINKED ISSUE #1838: Block Delay at epoch transition slot
**Describe the bug**
Following up the conversation in https://discord.com/channels/595666850260713488/598292067260825641/785242071857627147

when producing a block for `slot % 32 === 0`, we process epoch 2 times

**Expected behavior**
when producing a block, we want to process epoch at most 1 time

### PR DESCRIPTION
**Pull request by twoeths**
resolves #1838

### CODE REVIEW

**Review by mpetrunic — DISMISSED** [review]

**Review by mpetrunic — APPROVED** [review]

File: packages/lodestar/src/chain/factory/block/index.ts [hunk 1]
```diff
@@ -30,25 +31,22 @@ export async function assembleBlock(
     stateRoot: ZERO_HASH,
     body: await assembleBody(config, db, eth1, stateContext.state, randaoReveal, graffiti),
   };
-
-  const preStateContext = await chain.regen.getBlockSlotState(head.blockRoot, slot - 1);
```
Comment (wemeetagain) [inline packages/lodestar/src/chain/factory/block/index.ts:34]: Don't we still need this preStateContext?

Comment (twoeths) [reply packages/lodestar/src/chain/factory/block/index.ts:34]: no, we don't need to bc we only run `processBlock` instead of a `fastStateTransition` to leverage the 1st/initial `stateContext`
Current:
+ process head state up to slot
+ process head state up to (slot - 1) (which is redundant)
+ run `fastStateTransition` which is processing slot (epoch possibly) + process block

This PR changes to:
+ process head state up to slot
+ ~process head state up to (slot - 1)~
+ ~run `fastStateTransition` which is processing slot (epoch possibly) + process block~ => process block only

**Review by wemeetagain — APPROVED** [review]
