### PR TITLE
fix: prune oldest slots first in aggregator tracker

### LINKED ISSUE #6419: Vouch cannot attest via Lodestar
### Describe the bug

Our Vouch 1.7 shows the Lodestar CLs as not available for attestations. We haven't tracked this down as to which Lodestar version may have caused a change in behavior.

Please let us know what we can get you to narrow this down.

### Expected behavior

Vouch works with Lodestar

### Steps to reproduce

Configure Lodestar Ethereum node, and Vouch pointed at it and at least one other CL

### Additional context

Logs from Lodestar:
```
consensus-1  | Feb-09 10:03:05.000[]                 info: Synced - slot: 8387413 - head: 0xcf20…9930 - exec-block: valid(19189850 0xe5d8…) - finalized: 0x15f9…93f2:262104 - peers: 22
consensus-1  | Feb-09 10:03:07.073[rest]            error: Req req-43 getAggregatedAttestation error - No attestation for slot=8387413 dataRoot=0xcec0c9b1f76ab7e46ab74f654122c44c90ee97aa1356ad9b6777e5df0871835b
consensus-1  | Error: No attestation for slot=8387413 dataRoot=0xcec0c9b1f76ab7e46ab74f654122c44c90ee97aa1356ad9b6777e5df0871835b
consensus-1  |     at AttestationPool.getAggregate (file:///usr/app/packages/beacon-node/src/chain/opPools/attestationPool.ts:136:13)
consensus-1  |     at Object.getAggregatedAttestation (file:///usr/app/packages/beacon-node/src/api/impl/validator/index.ts:1040:47)
consensus-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
consensus-1  |     at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:45:23)
consensus-1  | Feb-09 10:03:17.020[]                 info: Synced - slot: 8387414 - head: 0x5d51…c772 - exec-block: valid(19189851 0xfe95…) - finalized: 0x15f9…93f2:262104 - peers: 25
consensus-1  | Feb-09 10:03:28.999[]                 info: Synced - slot: 8387415 - head: 0xeed8…ceb6 - exec-block: valid(19189852 0x2908…) - finalized: 0x15f9…93f2:262104 - peers: 24
consensus-1  | Feb-09 10:03:31.071[rest]            error: Req req-4n getAggregatedAttestation error - No attestation for slot=8387415 dataRoot=0x82c2090fec4d56f5176c183280f9d2f63a2ccf7b3ecb419510ef9e82c0f0a895
consensus-1  | Error: No attestation for slot=8387415 dataRoot=0x82c2090fec4d56f5176c183280f9d2f63a2ccf7b3ecb419510ef9e82c0f0a895
consensus-1  |     at AttestationPool.getAggregate (file:///usr/app/packages/beacon-node/src/chain/opPools/attestationPool.ts:136:13)
consensus-1  |     at Object.getAggregatedAttestation (file:///usr/app/packages/beacon-node/src/api/impl/validator/index.ts:1040:47)
consensus-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
consensus-1  |     at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:45:23)
consensus-1  | Feb-09 10:03:41.079[]                 info: Synced - slot: 8387416 - head: 0xd216…9251 - exec-block: valid(19189853 0xb04b…) - finalized: 0x15f9…93f2:262104 - peers: 37
consensus-1  | Feb-09 10:03:43.045[rest]            error: Req req-4y getAggregatedAttestation error - No attestation for slot=8387416 dataRoot=0xb7ec7ae44e848229f5431c67e7e9305b87c03654f43a1de3d9cc1c075d9f223d
consensus-1  | Error: No attestation for slot=8387416 dataRoot=0xb7ec7ae44e848229f5431c67e7e9305b87c03654f43a1de3d9cc1c075d9f223d
consensus-1  |     at AttestationPool.getAggregate (file:///usr/app/packages/beacon-node/src/chain/opPools/attestationPool.ts:136:13)
consensus-1  |     at Object.getAggregatedAttestation (file:///usr/app/packages/beacon-node/src/api/impl/validator/index.ts:1040:47)
consensus-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
consensus-1  |     at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:45:23)
```

### Operating system

Linux

### Lodestar version or commit hash

v1.5.0 and v1.5.1 tested

### LINKED ISSUE #6631: Nimbus VC to Lodestar BN shows attestation errors
### Describe the bug

We're running a Nimbus VC v24.3.0 in a cluster of several BNs, including a Lodestar BN 1.17.0, and are regularly seeing the following message in the VC logs: 

```
WRN 2024-04-04 20:14:55.043+00:00 Beacon node reports internal error         reason="Unable to decode error response: [Serialization error];500;getAggregatedAttestation(best);internal-issue" node=http://xx.xx.xx.xx:5052[Lodestar/v1.17.0/def26ac] node_index=2 node_roles=AGBSDT
NTC 2024-04-04 20:14:55.064+00:00 Aggregated attestation published           delay=64ms947us130ns service=attestation_service validator=831bb96c@785062 attestation="(aggregation_bits: 0b1111111111111111111111111101111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111101111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111, data: (slot: 8786472, index: 6, beacon_block_root: \"676aa960\", source: \"274576:b5e91a14\", target: \"274577:5b9344bd\"), signature: \"930cc3dc\")"
NTC 2024-04-04 20:14:55.514+00:00 Beacon node is online                      agent_version=Lodestar/v1.17.0/def26ac node=http://xx.xx.xx.xx:5052[Lodestar/v1.17.0/def26ac] node_index=2 node_roles=AGBSDT
NTC 2024-04-04 20:14:55.560+00:00 Beacon node is compatible                  node=http://xx.xx.xx.xx:5052[Lodestar/v1.17.0/def26ac] node_index=2 node_roles=AGBSDT
NTC 2024-04-04 20:14:55.582+00:00 Beacon node is in sync                     head_slot=8786472 sync_distance=0 is_optimistic=false node=http://xx.xx.xx.xx:5052[Lodestar/v1.17.0/def26ac] node_index=2 node_roles=AGBSDT
```

On the Lodestar BN it shows the following error: 

```
Apr 04 22:14:55 ethereum-v5-fr-2 lodestar[115637]: Error: No attestation for slot=8786472 dataRoot=0xbcf1127f79d3e25defb09d0108262aa08991fce8aaf788aa3481cb51e49ff925
Apr 04 22:14:55 ethereum-v5-fr-2 lodestar[115637]:     at AttestationPool.getAggregate (file:///usr/local/bin/lodestar/packages/beacon-node/src/chain/opPools/attestationPool.ts:136:13)
Apr 04 22:14:55 ethereum-v5-fr-2 lodestar[115637]:     at Object.getAggregatedAttestation (file:///usr/local/bin/lodestar/packages/beacon-node/src/api/impl/validator/index.ts:1041:47)
Apr 04 22:14:55 ethereum-v5-fr-2 lodestar[115637]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
Apr 04 22:14:55 ethereum-v5-fr-2 lodestar[115637]:     at Object.handler (file:///usr/local/bin/lodestar/packages/api/src/utils/server/genericJsonServer.ts:45:23)
```

This suggests that connecting a Nimbus VC to a Lodestar BN creates attestation issues. 

 

### Expected behavior

Attestations should work when running Nimbus VC with Lodestar BN. No errors should be logged on both services.

### Steps to reproduce

1. Run Lodestar BN
2. Attach Nimbus VC with active validators
3. Observe logs on both services

### Additional context

This issue seems to be related to #5553 and #6419 

### Operating system

Linux

### Lodestar version or commit hash

v1.17.0/def26ac

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Due to the fact the we are pruning based on FIFO it might happen that we prune a slot which is in the future and should not yet be pruned.

This is completely random as is depends on the order of which the validator client submits the subscriptions, current epoch vs. next epoch first, and the order of the items themselves. For example at the start of epoch 0, the client submits epoch 1 first, then epoch 0 and if there is an aggregator for each slot (likely with a lot of keys) then the cache is already full (64 items). Then at the start of epoch 1, some clients only submit for epoch 2 (next epoch) but this means we start pruning items of epoch 1, but that's the current epoch which should not yet be pruned.

While Lodestar calls [prepareBeaconCommitteeSubnet](https://github.com/ChainSafe/lodestar/blob/ae984f0f6079f78c2445f36ae2ac09c9e868197e/packages/beacon-node/src/api/impl/validator/index.ts#L1200) always for [current and next epoch](https://github.com/ChainSafe/lodestar/blob/ae984f0f6079f78c2445f36ae2ac09c9e868197e/packages/validator/src/services/attestationDuties.ts#L192-L196), other clients like Nimbus, Teku and Vouch do not, which might lead to the issue that Lodestar does not prepare an aggregated attestation (#6631, #6419), as at the time when the attestations are submitted via [submitPoolAttestations](https://github.com/ChainSafe/lodestar/blob/ae984f0f6079f78c2445f36ae2ac09c9e868197e/packages/beacon-node/src/api/impl/beacon/pool/index.ts#L53) the [aggregator check](https://github.com/ChainSafe/lodestar/blob/ae984f0f6079f78c2445f36ae2ac09c9e868197e/packages/beacon-node/src/api/impl/beacon/pool/index.ts#L75) will return false.

**Description**

Prune oldest slots first in aggregator tracker to ensure we only prune slots that are in the past.

**Alternative solution**

We could also increase the [max cache slots](https://github.com/ChainSafe/lodestar/blob/ae984f0f6079f78c2445f36ae2ac09c9e868197e/packages/beacon-node/src/network/processor/aggregatorTracker.ts#L8) to 3 epochs

Closes https://github.com/ChainSafe/lodestar/issues/6631
Closes https://github.com/ChainSafe/lodestar/issues/6419

### CODE REVIEW

**Review by twoeths — DISMISSED** [review]

File: packages/beacon-node/src/network/processor/aggregatorTracker.ts [hunk 1]
```diff
@@ -16,8 +16,12 @@ export class AggregatorTracker {
 
   addAggregator(subnet: SubnetId, slot: Slot): void {
     this.subnetAggregatorsBySlot.getOrDefault(slot).add(subnet);
-
-    pruneSetToMax(this.subnetAggregatorsBySlot, MAX_SLOTS_CACHED);
+    pruneSetToMax(
+      this.subnetAggregatorsBySlot,
```
Comment (jeluard) [inline packages/beacon-node/src/network/processor/aggregatorTracker.ts:34]: The alternative could be to keep `subnetAggregatorsBySlot` sorted at insertion time? We might not have the necessary data structure yet.

**Review by jeluard — COMMENTED** [review]
It might be nice to have unit tests to ensure no regression are introduced to those kind of expectations.

**Comment by nflaig** [comment]
> It might be nice to have unit tests to ensure no regression are introduced to those kind of expectations.

Could add unit tests for aggregator tracker but the logic is pretty simple, the problem with this issue is that it involves multiple parts of the code base, so only good way too test this is in an e2e or even better a sim test.

File: packages/beacon-node/src/network/processor/aggregatorTracker.ts (hunk 1 above)
Comment (nflaig) [reply packages/beacon-node/src/network/processor/aggregatorTracker.ts:34]: I had three options in mind
- sort keys when pruning (as implemented)
- switch to [`pruneBySlot`](https://github.com/ChainSafe/lodestar/blob/ae984f0f6079f78c2445f36ae2ac09c9e868197e/packages/beacon-node/src/chain/opPools/utils.ts#L10) logic, I am not sure if this strategy is correct here, although it could keep the cache size lower, maybe @tuyennhv has some thoughts
- as you suggested @jeluard always have keys sorted, I think we wanna keep a map for quick lookup times, although might not matter much since the array would have max 64 items

Comment (jeluard) [reply packages/beacon-node/src/network/processor/aggregatorTracker.ts:34]: Current approach is probably fine given the sizes involved, probably better not to over engineer yet :)

**Review by jeluard — DISMISSED** [review]

**Comment by jeluard** [comment]
@tuyennhv sorry I misclicked and re-requested your review

File: packages/beacon-node/src/network/processor/aggregatorTracker.ts (hunk 1 above)
Comment (nflaig) [reply packages/beacon-node/src/network/processor/aggregatorTracker.ts:34]: I overlooked this yesterday, we have a ordered map

https://github.com/ChainSafe/lodestar/blob/ae984f0f6079f78c2445f36ae2ac09c9e868197e/packages/beacon-node/src/util/map.ts#L6

This one keeps track of the keys which is the tradeoff I guess

Comment (nflaig) [reply packages/beacon-node/src/network/processor/aggregatorTracker.ts:34]: Alternative using an ordered map https://github.com/ChainSafe/lodestar/compare/unstable...nflaig/ordered-map-aggregator-tracker

**Comment by nflaig** [comment]
Keeping as draft for now, happy to elaborate on different approaches, and probably good idea to have a minimal set of units tests on aggregator tracker.

File: packages/beacon-node/src/network/processor/aggregatorTracker.ts (hunk 1 above)
Comment (nflaig) [reply packages/beacon-node/src/network/processor/aggregatorTracker.ts:34]: turns out our "ordered" map isn't actually ordered... added units tests now

Comment (twoeths) [reply packages/beacon-node/src/network/processor/aggregatorTracker.ts:34]: > Current approach is probably fine given the sizes involved, probably better not to over engineer yet :)

I agree with this considering the cache size is just 64, may want to add a note for the reasoning we choose this approach

**Review by twoeths — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada:
