### PR TITLE
fix: set consensus version header in state and block response

### LINKED ISSUE #6123: "Eth-Consensus-Version" header absent in eth/v2/debug/beacon/states/{state_id} response
### Describe the bug

```
curl -H "Accept: application/octet-stream;q=1,application/json;q=0.9" -Ssv "http://consensus:5052/eth/v2/debug/beacon/states/finalized" > /dev/null                          
*   Trying 172.21.0.12:5052...
* Connected to consensus (172.21.0.12) port 5052
> GET /eth/v2/debug/beacon/states/finalized HTTP/1.1
> Host: consensus:5052
> User-Agent: curl/8.4.0
> Accept: application/octet-stream;q=1,application/json;q=0.9
> 
< HTTP/1.1 200 OK
< vary: Origin
< access-control-allow-origin: *
< content-type: application/octet-stream
< content-length: 213503710
< Date: Thu, 23 Nov 2023 04:46:56 GMT
< Connection: keep-alive
< Keep-Alive: timeout=72
< 
{ [14263 bytes data]
* Connection #0 to host consensus left intact
```

### Expected behavior

`Eth-Consensus-Version` header should be set, as required by https://ethereum.github.io/beacon-APIs/#/Debug/getStateV2

image

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.12.0

### LINKED ISSUE #6124: Checkpointz v0.18.0 requires "Eth-Consensus-Version" header
### Describe the bug

Latest version of [checkpointz](https://github.com/ethpandaops/checkpointz) requires `Eth-Consensus-Version` header to be set in `eth/v2/debug/beacon/states/{state_id}` response.

Checkpointz errors
```
time="2023-11-15T14:48:17Z" level=error msg="No longer attempting to download historical block - too many failures" failure_count=5 module=beacon/default slot=346240
time="2023-11-15T14:48:29Z" level=error msg="Failed to check for genesis" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:48:32Z" level=error msg="Failed to check for new serving checkpoint" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:48:44Z" level=error msg="Failed to check for genesis" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:48:59Z" level=error msg="Failed to check for genesis" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:49:03Z" level=error msg="Failed to check for new serving checkpoint" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:49:14Z" level=error msg="Failed to check for genesis" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
2023/11/15 14:49:19 http: panic serving 51.159.85.94:21844: runtime error: invalid memory address or nil pointer dereference
goroutine 692 [running]:
net/http.(*conn).serve.func1()
```

Due to this issue we cannot upgrade the checkpoint sync providers to the latest version.

### Expected behavior

`Eth-Consensus-Version` header should be set

### Steps to reproduce

_No response_

### Additional context

Related [discussion with devops team](https://discord.com/channels/593655374469660673/1174355544350408805)

### Operating system

Linux

### Lodestar version or commit hash

v1.12.0

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Beacon-API spec requires to set `Eth-Consensus-Version` in [getStateV2](https://ethereum.github.io/beacon-APIs/#/Debug/getStateV2) and [getBlockV2](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockV2) response.

image

**Description**

Set consensus version header in state and block response in both json and ssz response as per spec both require the header.

Confirmed results manually as current API client design does not allow to access header values in tests.

```
 curl -s -o /dev/null -D - http://beacon:9596/eth/v2/debug/beacon/states/head -H "Accept: application/octet-stream"
HTTP/1.1 200 OK
...
eth-consensus-version: capella
content-type: application/octet-stream
...
```

**Note:** This is not a long-term solution, all the code here will be removed in API refactoring done in https://github.com/ChainSafe/lodestar/pull/6080

Closes https://github.com/ChainSafe/lodestar/issues/6123
Closes https://github.com/ChainSafe/lodestar/issues/6124

### CODE REVIEW

File: packages/api/src/beacon/server/beacon.ts [hunk 1]
```diff
@@ -30,15 +31,35 @@ export function getRoutes(config: ChainForkConfig, api: ServerApi<Api>): ServerR
     },
     getBlockV2: {
       ...serverRoutes.getBlockV2,
-      handler: async (req) => {
+      handler: async (req, res) => {
         const response = await api.getBlockV2(...reqSerializers.getBlockV2.parseReq(req));
         if (response instanceof Uint8Array) {
+          const slot = extractSlotFromBlockBytes(response);
+          const version = config.getForkName(slot);
+          void res.header("Eth-Consensus-Version", version);
```
Comment (nflaig) [inline packages/api/src/beacon/server/beacon.ts:39]: The `void` is required here because eslint warns about floating promises due to `header` return value being thenable but it does not return a promise. Using await here will keep the process stuck when calling the API. This is a known issue, see https://github.com/fastify/fastify/issues/4246 and https://github.com/fastify/help/issues/775.

File: packages/api/src/beacon/server/beacon.ts [hunk 2]
```diff
@@ -30,15 +31,35 @@ export function getRoutes(config: ChainForkConfig, api: ServerApi<Api>): ServerR
...
         } else {
+          void res.header("Eth-Consensus-Version", response.version);
           return returnTypes.getBlockV2.toJson(response);
         }
       },
     },
   };
 }
+
+function extractSlotFromBlockBytes(block: Uint8Array): number {
```
Comment (g11tech) [inline packages/api/src/beacon/server/beacon.ts:51]: we have these kind of

**Review by g11tech — APPROVED** [review]
lgtm

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.13.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.13.0) :tada:
