### PR TITLE
fix: improve jsonRPC error UX for eth1 + execution 

### LINKED ISSUE #4348: Improve jsonRPC error UX for eth1 + execution
As brought to notice by a discord user `seamonkey`, sometimes because of the nodejs engine intermittent loading or the execution engine's intermittent loading the json rpc api can throw harmless intermittent errors like `UNAVAILABLE`, `TIMEOUT` like these

image

However these give users not so good experience, and hence we need to have an error accumulator for such unavailable errors and log the throw only if counter surpasses.

### PR DESCRIPTION
**Pull request by nazarhussain**
**Motivation**

Manage the state transition for the eth1 provider to log the errors with right context.

**Description**

- Refactor the JSONRPCClient to allow events
- Updated the Execution Engine to use the events of rpc client
- Used the same pattern for the Eth1Provider as well

Closes #4348

**Steps to test or reproduce**

- Run all tests

### CODE REVIEW

**Review by g11tech — CHANGES_REQUESTED** [review]
overall looks really good to me :heart: 
could you generate some example logs by testing a few scenarios and how how they look before i approve

**Comment by nazarhussain** [comment]
The log format does not change. it still shows the error exactly like before. 

```
Sep-28 11:36:04.057[eth1]            error: Error updating eth1 chain cache  Request to https://lodestar-mainnetrpc.chainsafe.i failed, reason: getaddrinfo ENOTFOUND 
```

The only change would be the error will be shown **once** connection have any issue.

**Comment by g11tech** [comment]
can we have the "eth1 communication restored/online" etc kind of messages like how you did in the engine when state changes

**Comment by nazarhussain** [comment]
```
Sep-28 15:40:16.247[eth1]            error: Eth1Provider faced error state=OFFLINE, lastErrorAt=undefined Request to http://0.0.0.0:8080 failed, reason: connect ECONNREFUSED 0.0.0.0:8080
```

```
Sep-28 15:40:27.889[eth1]             info: Eth1Provider is back online oldState=OFFLINE, newState=ONLINE
```

File: packages/beacon-node/src/eth1/eth1DepositDataTracker.ts [hunk 1]
```diff
@@ -175,16 +176,16 @@ export class Eth1DepositDataTracker {
...
+        this.metrics?.eth1.depositTrackerUpdateErrors.inc(1);
+
         // From Infura: 429 Too Many Requests
         if (e instanceof HttpRpcError && e.status === 429) {
           this.logger.debug("Eth1 provider rate limited", {}, e);
           await sleep(RATE_LIMITED_WAIT_MS, this.signal);
-        } else if (!isErrorAborted(e)) {
-          this.logger.error("Error updating eth1 chain cache", {}, e as Error);
+          // only log error if state switched from online to some other state
+        } else if (!isErrorAborted(e) && this.eth1Provider.getState() !== oldState) {
```
Comment (g11tech) [inline packages/beacon-node/src/eth1/eth1DepositDataTracker.ts]: why are we comparing on oldstate since this is to wait `MIN_WAIT_ON_ERROR_MS` before retrying again if its some other error than aborted?

File: packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts [hunk 2]
```diff
@@ -170,21 +219,13 @@ export class JsonRpcHttpClient implements IJsonRpcHttpClient {
...
     }
-
-    if (lastError !== null) {
-      throw lastError;
-    } else if (this.urls.length === 0) {
-      throw Error("No url provided");
-    } else {
-      throw Error("Unknown error");
-    }
+    throw lastError ?? Error("Unknown error");
```
Comment (g11tech) [inline packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:228]: good cleanup :+1:

File: packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts [hunk 3]
```diff
@@ -107,58 +134,80 @@ export class JsonRpcHttpClient implements IJsonRpcHttpClient {
    * Perform RPC request
    */
   async fetch<R, P = IJson[]>(payload: RpcPayload<P>, opts?: ReqOpts): Promise<R> {
-    const res: RpcResponse<R> = await this.fetchJson({jsonrpc: "2.0", id: this.id++, ...payload}, opts);
-    return parseRpcResponse(res, payload);
+    return this.wrapWithEvents(
```
Comment (g11tech) [inline packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:137]: not sure if we want to wrap everything here (thinking of execution rpc calls)

Comment (g11tech) [reply packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:137]: ok, i see you have used in engine as well :+1:

File: packages/utils/src/waitFor.ts [hunk 4]
```diff
@@ -51,3 +51,45 @@ export function waitFor(condition: () => boolean, opts: WaitForOpts = {}): Promi
...
+type ElapsedTimeTrackerCaller = (data: ElapsedTimeTrackerAttributes) => void;
+export type ElapsedTimeTracker = (fn: ElapsedTimeTrackerCaller) => void;
+
+/**
+ * Create a tracker which keeps track of the last time a function was called
+ *
+ * @param durationMs
+ * @returns
+ */
+export function waitForElapsedTime({minElapsedTime, onError}: ElapsedTimeTrackerOptions): ElapsedTimeTracker {
```
Comment (g11tech) [inline packages/utils/src/waitFor.ts]:
```suggestion
export function createCallTracker(): ElapsedTimeTracker {
```
keep it simple, onError doesn't seemed to be being used, add functionality on usage basis

also pass `minElapsedTime` as options on the elapsedTimeTracker, again for simplicity and possibly dynamism (just an opinion but don't feel strongly about it)

File: packages/utils/src/waitFor.ts [hunk 5]
```diff
@@ -51,3 +51,45 @@ export function waitFor(condition: () => boolean, opts: WaitForOpts = {}): Promi
...
+  let lastTimeError: number | undefined = undefined;
+
+  return function elapsedTimeTracker(fn: ElapsedTimeTrackerCaller): void {
+    const now = Date.now();
+
+    const msSinceLastCall = lastTimeCalled === undefined ? undefined : now - lastTimeCalled;
+    const msSinceLastError = lastTimeError === undefined ? undefined : now - lastTimeError;
+
+    if (msSinceLastCall !== undefined && msSinceLastCall < minElapsedTime) {
+      if (onError) onError({now, msSinceLastError, msSinceLastCall});
```
Comment (g11tech) [inline packages/utils/src/waitFor.ts]: remove this callback since its not being in use now

**Review by g11tech — APPROVED** [review]
lgtm! great cleanup :heart: and hopefully clean UX

File: packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts [hunk 6]
```diff
@@ -107,58 +134,80 @@ export class JsonRpcHttpClient implements IJsonRpcHttpClient {
...
+      this.emitter.emit(JsonRpcHttpClientEvent.RESPONSE, {payload, response});
+      return response;
+    } catch (error) {
+      this.emitter.emit(JsonRpcHttpClientEvent.ERROR, {payload, error: error as Error});
+      throw error;
+    }
   }
 
   private async fetchJson<R, T = unknown>(json: T, opts?: ReqOpts): Promise<R> {
+    if (this.urls.length === 0) throw Error("No url provided");
```
Comment (nflaig) [inline packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:209]: I previously removed a similar check like this in  https://github.com/ChainSafe/lodestar/pull/5884 as we already check the URLs in the constructor
https://github.com/ChainSafe/lodestar/blob/3cfa9cd6b7161f883af4d456838b471ce1523625/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts#L115-L117

I don't think this error is reachable but if it is we should make sure to validate the URLs earlier.

File: packages/utils/test/unit/waitFor.test.ts [hunk 7]
```diff
@@ -35,3 +36,29 @@ describe("waitFor", () => {
     await expect(waitFor(() => true, {interval, timeout, signal: controller.signal})).to.be.rejectedWith(ErrorAborted);
   });
 });
+
+describe("waitForElapsedTime", () => {
```
Comment (nflaig) [inline packages/utils/test/unit/waitFor.test.ts:40]: Test case name does not match function name, looks like this was missed during renaming

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.12.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.12.0) :tada:

File: packages/beacon-node/src/eth1/eth1DepositDataTracker.ts [hunk 8]
```diff
@@ -175,16 +175,16 @@ export class Eth1DepositDataTracker {
...
       } catch (e) {
+        this.metrics?.eth1.depositTrackerUpdateErrors.inc(1);
+
         // From Infura: 429 Too Many Requests
         if (e instanceof HttpRpcError && e.status === 429) {
           this.logger.debug("Eth1 provider rate limited", {}, e);
           await sleep(RATE_LIMITED_WAIT_MS, this.signal);
+          // only log error if state switched from online to some other state
         } else if (!isErrorAborted(e)) {
-          this.logger.error("Error updating eth1 chain cache", {}, e as Error);
```
Comment (nflaig) [inline packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:183]: @nazarhussain can you please explain this change, does the comment relate to the removed log?

And is the log on line 183 supposed to be replaced by the error log added in the eth1 provider?
https://github.com/ChainSafe/lodestar/blob/4c09412ed2c8a94b585d5dba1fe94bc9e2d56a35/packages/beacon-node/src/eth1/provider/eth1Provider.ts#L112

File: packages/beacon-node/src/eth1/provider/eth1Provider.ts [hunk 9]
```diff
@@ -62,6 +78,44 @@ export class Eth1Provider implements IEth1Provider {
...
+      } else if ((error as unknown) instanceof HttpRpcError || (error as unknown) instanceof ErrorJsonRpcResponse) {
+        this.state = Eth1ProviderState.ERROR;
+      } else if (error && isFetchError(error) && HTTP_FATAL_ERROR_CODES.includes((error as FetchError).code)) {
+        this.state = Eth1ProviderState.OFFLINE;
+      } else if (error && isFetchError(error) && HTTP_CONNECTION_ERROR_CODES.includes((error as FetchError).code)) {
+        this.state = Eth1ProviderState.AUTH_FAILED;
+      }
+
+      if (this.state !== Eth1ProviderState.ONLINE) {
+        if (isOneMinutePassed()) {
```
Comment (nflaig) [inline packages/beacon-node/src/eth1/provider/eth1Provider.ts:103]: @nazarhussain can you please explain how this should behave

1. should it invoke the error log at most once a minute
2. or should it just invoke the error log once and never again, until there is a period of 1 minute where there are no errors?


See issue reported [on discord](https://discord.com/channels/593655374469660673/593655641445367808/1208096150557556779), we are not actually printing out any errors and just spam the logs with `info: Eth1Provider is back online oldState=ERROR, newState=ONLINE`.

I pushed a few changes that might partially solve this by fixing `createElapsedTimeTracker` function, see https://github.com/ChainSafe/lodestar/compare/unstable...nflaig/eth1-error-logging

Comment (nflaig) [reply packages/beacon-node/src/eth1/provider/eth1Provider.ts:103]: Another issue was reported to this, see [discord](https://discord.com/channels/593655374469660673/593655641445367808/1210095818925809724). Does not seem to happen if EL is still synincing but needs more investigation as they use [openexecution](https://github.com/tennisbowling/openexecution) and not directly connect to EL client.

Comment (nazarhussain) [reply packages/beacon-node/src/eth1/provider/eth1Provider.ts:103]: When ever `JsonRpcHttpClient` encounter an error, it bubbles up to this function. We log the the error once per minute because once the rpc encounter error it's usually because the RPC node is offline or some other issue then it's stay that way very long we end up tons of error logs with same error.

File: packages/beacon-node/src/eth1/eth1DepositDataTracker.ts (hunk 8 above)
Comment (nazarhussain) [reply packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:183]: Yes this log line should be replaced with eth1Provider error handling, but because we log the error once per minute so it could be the case you don't see the errors often.

File: packages/beacon-node/src/eth1/provider/eth1Provider.ts (hunk 9 above)
Comment (nflaig) [reply packages/beacon-node/src/eth1/provider/eth1Provider.ts:103]: > We log the the error once per minute

that's what it should do but the function has a bug, fixed in https://github.com/ChainSafe/lodestar/compare/unstable...nflaig/eth1-error-logging

The other issue I see is how we do the status logging, as single failed request will set the status to `ERROR` while a single success request sets it to `ONLINE`.

If some request succeed and some fail which is the cause if nethermind can't serve historical logs but it can serve other requests then what ends up happning is that the logs are spammed with

`info: Eth1Provider is back online oldState=ERROR, newState=ONLINE.`

It more of an issue of the intended behavior vs. the acutal behavior, if we fix the implementation it should be fine. I added more details in the issue https://github.com/ChainSafe/lodestar/issues/6469.

Comment (nazarhussain) [reply packages/beacon-node/src/eth1/provider/eth1Provider.ts:103]: I went over the discussions I had for it's implementation, that was the  inspiration or this change: 

> also maybe every minute log the error message as well if the eth1 is still down ... ( i.e. if we make the request and its still error and the last error display message > 60 seconds , log the message and update last error display time) 

So yes there is a bug in the implementation, but not in the `createElapsedTimeTracker`. That one seems to be good as what is intended for, it's just tracking time since first invocation. 

For `eth1` provider we should do via rate limiting helpers for rate limit error per minute.
