### PR TITLE
fix: use incrementing counter for prover request ids

### LINKED ISSUE #6266: Investigate prover request id generator
> Thanks for noticing this! Indeed the range of 10000 is improper for this application.

> Math.random is a bad generator regardless. Why not have an incrementing counter @nazarhussain ?

_Originally posted by @dapplion in https://github.com/ChainSafe/lodestar/pull/6115#discussion_r1399680072_

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Closes https://github.com/ChainSafe/lodestar/issues/6266

**Description**

Use incrementing counter for prover request ids

Based on reviewing the usage of the request id I don't see an issue with using an incrementing counter but would be good if @nazarhussain could confirm this.

### CODE REVIEW

File: packages/prover/src/utils/rpc.ts [hunk 1]
```diff
@@ -99,7 +101,6 @@ export class ELRpc {
   }
 
   getRequestId(): string {
-    // TODO: Find better way to generate random id
-    return (Math.random() * 100000000000000000).toFixed(0);
```
Comment (nazarhussain) [inline packages/prover/src/utils/rpc.ts:103]: In the current use case the `requestId` is not that important to be generated anyway. Even if we send same id every-time, it will still work fine as requests are processed sequentially. 



With incremental ids, the edge case will left is a long running proxy server. Though it will take really a long time to overflow the integer.

**Review by nazarhussain — APPROVED** [review]

File: packages/prover/src/utils/rpc.ts (hunk 1 above)
Comment (nflaig) [reply packages/prover/src/utils/rpc.ts:103]: > Even if we send same id every-time, it will still work fine as requests are processed sequentially.

According to https://github.com/ChainSafe/lodestar/pull/6115 sending same id twice will cause issues.


> With incremental ids, the edge case will left is a long running proxy server

Theoretically this is true but 2**53-1 is the maximum request id we can support which is enormous, we can never reach that number in reality.

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.15.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.15.0) :tada:
