### PR TITLE
fix: update PeerDAS log level

### LINKED ISSUE #8107: Inappropriate log level
I think this should be debug or verbose
```
warn: onPing seqNumber=205, metaSeqNumber=205, cond=false
```

### PR DESCRIPTION
**Pull request by KatyaRyazantseva**
**Motivation**

Some logs in the PeerDAS branch are inappropriate.

**Description**

This PR changes inappropriate PeerDAS log levels from `warn` and `error` to `debug` level.

Closes #8107

**Steps to test or reproduce**

Run beacon node locally using `./scripts/dev/node*.sh` with --logLevel `info` and `debug` and check the logs.

### CODE REVIEW

File: packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts [hunk 1]
```diff
@@ -220,7 +220,7 @@ export class SeenGossipBlockInput {
             // TODO: (@matthewkeil) add metrics collection point here
           })
           .catch((error) => {
-            this.logger.error("Error getting data columns from execution", {blockHex}, error);
+            this.logger.debug("Error getting data columns from execution", {blockHex}, error);
```
Comment (nflaig) [inline packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts]: is this error expected to happen frequently? if not we should keep it as `error` as it could indicate an issue with the EL client

File: packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts [hunk 2]
```diff
@@ -356,7 +356,7 @@ export class SeenGossipBlockInput {
               dataColumns: dataColumnsCache.size,
             };
             const recoverResult = await recoverDataColumnSidecars(dataColumnsCache, this.clock, metrics).catch((e) => {
-              this.logger.error("Error recovering data column sidecars", logCtx, e);
+              this.logger.debug("Error recovering data column sidecars", logCtx, e);
```
Comment (nflaig) [inline packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts]: same here, do we expect this to error, otherwise keep current log level

**Comment by nflaig** [comment]
> Run beacon node locally using ./scripts/dev/node*.sh with --logLevel info and debug and check the logs.

running this command doesn't really test it, best would be to run a peerdas node or observe logs on one of the ethpandaops nodes or our own devnet nodes, then see with logs are to verbose and adjust

File: packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts (hunk 1 above)
Comment (KatyaRyazantseva) [reply packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts]: @matthewkeil

File: packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts (hunk 2 above)
Comment (KatyaRyazantseva) [reply packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts]: @matthewkeil

Comment (matthewkeil) [reply packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts]: this should be an error

File: packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts (hunk 1 above)
Comment (matthewkeil) [reply packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts]: this is prob not an error because its not user actionable.  but also not a debug.  maybe `warn` is correct here?

File: packages/beacon-node/src/network/peers/discover.ts [hunk 3]
```diff
@@ -397,7 +397,7 @@ export class PeerDiscovery {
     const syncnetsBytes = enr.kvs.get(ENRKey.syncnets); // 4 bits
     const custodyGroupCountBytes = enr.kvs.get(ENRKey.cgc); // 64 bits
     if (custodyGroupCountBytes === undefined) {
-      this.logger.warn("peer discovered with no cgc assuming 4", exportENRToJSON(enr));
+      this.logger.debug("peer discovered with no cgc assuming 4", exportENRToJSON(enr));
```
Comment (matthewkeil) [inline packages/beacon-node/src/network/peers/discover.ts]: this should stay a warn

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 4]
```diff
@@ -482,7 +482,7 @@ export class PeerManager {
   private async requestMetadata(peer: PeerId): Promise<void> {
     const peerIdStr = peer.toString();
     try {
-      this.logger.warn("requestMetadata", {peer: prettyPrintPeerIdStr(peerIdStr)});
+      this.logger.debug("requestMetadata", {peer: prettyPrintPeerIdStr(peerIdStr)});
```
Comment (nflaig) [inline packages/beacon-node/src/network/peers/peerManager.ts]: As per suggestion from @wemeetagain we might wanna completely remove this, I tend to agree

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 5]
```diff
@@ -493,7 +493,7 @@ export class PeerManager {
   private async requestPing(peer: PeerId): Promise<void> {
     const peerIdStr = peer.toString();
     try {
-      this.logger.warn("requestPing", {peer: peer.toString()});
+      this.logger.debug("requestPing", {peer: peer.toString()});
```
Comment (nflaig) [inline packages/beacon-node/src/network/peers/peerManager.ts]: same here, consider completely removing this log, seems like an artifact of very early debugging?

File: packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts (hunk 1 above)
Comment (philknows) [reply packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts]: If it's not user actionable at all, it should remain as a debug if we're following the [logging policy](https://github.com/ChainSafe/lodestar/blob/unstable/CONTRIBUTING.md#logging-policy). If there's anything that a user can do to troubleshoot why they're getting errors from execution (e.g. maybe a config error on EL side), then I would argue it's a warn.

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 6]
```diff
@@ -456,7 +456,7 @@ export class PeerManager {
       const hasAllColumns = matchingSubnetsNum === sampleSubnets.length;
       const clientAgent = peerData?.agentClient ?? ClientKind.Unknown;
 
-      this.logger.warn(`onStatus ${custodyGroupCount === undefined ? "undefined custody count assuming 4" : ""}`, {
+      this.logger.debug(`onStatus ${custodyGroupCount === undefined ? "undefined custody count assuming 4" : ""}`, {
```
Comment (wemeetagain) [inline packages/beacon-node/src/network/peers/peerManager.ts]: remove the part after "onStatus". That variable is already in the log.

Comment (wemeetagain) [inline packages/beacon-node/src/network/peers/peerManager.ts]:
```suggestion
      this.logger.debug("onStatus", {
```

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.34.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.34.0) :tada:
