### PR TITLE
fix(api): allow duplicate columns/blobs in publishBlock for multi-BN setups

### LINKED ISSUE #8848: publishBlockV2 500 status code with `BLOCK_INPUT_ERROR_INVALID_CONSTRUCTION`
### Describe the bug

Hey team,

I just noticed these errors (`Cannot addColumn to BlockInputColumns with duplicate column index`) on our Hoodi deployment. We run a multi-node setup with Vero and Lodestar is the only CL client that errors out when publishing _a very small percentage_ of blocks.

I found two earlier issues with this error message in this repo, but those had to do with syncing whereas this issue I'm reporting happens on a synced node while publishing a block so I assume it's something else.

Lodestar version: `v1.39.0-rc.4` but also happened on `v1.38.0`

Logs:

```
consensus  | Feb-03 06:34:18.000[]                 info: Synced - slot: 2323921 - head: 0xeb76…c96d - exec-block: valid(2159682 0x4e16…) - finalized: 0x7df9…0dc7:72620 - peers: 103
consensus  | Feb-03 06:34:30.000[]                 info: Synced - slot: 2323922 - head: 0x5a88…77e1 - exec-block: valid(2159683 0x30e8…) - finalized: 0x7df9…0dc7:72620 - peers: 104
consensus  | Feb-03 06:34:42.000[]                 info: Synced - slot: 2323923 - head: 0x6907…208b - exec-block: valid(2159684 0xef42…) - finalized: 0x7df9…0dc7:72620 - peers: 100
consensus  | Feb-03 06:34:54.001[]                 info: Synced - slot: 2323924 - head: 0x3a5d…b9a3 - exec-block: valid(2159685 0x7c13…) - finalized: 0x7df9…0dc7:72620 - peers: 100
consensus  | Feb-03 06:35:06.000[]                 info: Synced - slot: 2323925 - head: 0x01b6…c062 - exec-block: valid(2159686 0xea81…) - finalized: 0x7df9…0dc7:72620 - peers: 100
consensus  | Feb-03 06:35:18.000[]                 info: Synced - slot: 2323926 - head: 0xb6f1…fdca - exec-block: valid(2159687 0x56aa…) - finalized: 0x7df9…0dc7:72620 - peers: 99
consensus  | Feb-03 06:35:30.000[]                 info: Synced - slot: 2323927 - head: 0x594e…b579 - exec-block: valid(2159688 0xed16…) - finalized: 0x7df9…0dc7:72620 - peers: 100
consensus  | Feb-03 06:35:42.000[]                 info: Synced - slot: 2323928 - head: 0x91f2…e5ea - exec-block: valid(2159689 0x00c4…) - finalized: 0x7df9…0dc7:72620 - peers: 101
consensus  | Feb-03 06:35:48.830[api]              info: Selected engine block reason=block_value, slot=2323929, parentSlot=2323928, parentBlockRoot=0x91f2e5aaaa69f8b52064aaf2fb6946867d7c1f9241f8d55c61a0e45486fbe5ea, fork=fulu, builderSelection=maxprofit, isBuilderEnabled=true, isEngineEnabled=true, strictFeeRecipientCheck=undefined, builderBoostFactor=90, engineDurationMs=396, engineExecutionPayloadValue=0.00598 ETH, engineConsensusBlockValue=0.04607 ETH, engineBlockTotalValue=0.05205 ETH, builderDurationMs=805, builderExecutionPayloadValue=0.00528 ETH, builderConsensusBlockValue=0.04607 ETH, builderBlockTotalValue=0.05136 ETH
consensus  | Feb-03 06:35:50.869[rest]            error: Req req-14x5z publishBlockV2 error code=BLOCK_INPUT_ERROR_INVALID_CONSTRUCTION, blockRoot=0x8293a42a5ef42974fd2c05746e101d9934a252addf1d86a5176cb98481f9b704
consensus  | Error: Cannot addColumn to BlockInputColumns with duplicate column index
consensus  |     at BlockInputColumns.addColumn (file:///usr/app/packages/beacon-node/src/chain/blocks/blockInput/blockInput.ts:757:13)
consensus  |     at publishBlock (file:///usr/app/packages/beacon-node/src/api/impl/beacon/blocks/index.ts:136:24)
consensus  |     at Object.publishBlockV2 (file:///usr/app/packages/beacon-node/src/api/impl/beacon/blocks/index.ts:620:13)
consensus  |     at Object.<anonymous> (file:///usr/app/packages/api/src/utils/server/handler.ts:105:28)
consensus  |     at preHandlerCallbackInner (/usr/app/node_modules/.pnpm/fastify@5.3.2/node_modules/fastify/lib/handleRequest.js:161:24)
consensus  |     at preHandlerCallback (/usr/app/node_modules/.pnpm/fastify@5.3.2/node_modules/fastify/lib/handleRequest.js:129:5)
consensus  |     at next (/usr/app/node_modules/.pnpm/fastify@5.3.2/node_modules/fastify/lib/hooks.js:236:9)
consensus  |     at handleResolve (/usr/app/node_modules/.pnpm/fastify@5.3.2/node_modules/fastify/lib/hooks.js:253:7)
consensus  |     at processTicksAndRejections (node:internal/process/task_queues:103:5)
consensus  | Feb-03 06:35:54.000[]                 info: Synced - slot: 2323929 - head: 0x8293…b704 - exec-block: valid(2159690 0x6e6b…) - finalized: 0x7df9…0dc7:72620 - peers: 104
consensus  | Feb-03 06:36:06.000[]                 info: Synced - slot: 2323930 - head: 0xf602…5fb0 - exec-block: valid(2159691 0xc0b5…) - finalized: 0x7df9…0dc7:72620 - peers: 100
```

### Expected behavior

publishBlockV2 should return with an OK status code

### Steps to reproduce

No reproduction steps available. In case it helps, the API call failed for the following Hoodi slots: 2323929 2309949 2224595 2234923 . The thing they have in common is that they are all locally-built blocks - `Selected engine block reason=block_value` is present before the error happens. This may have something to do with the fact that Vero chooses a block returned by a different beacon node, and then publishes it via the Lodestar beacon node.

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.39.0-rc.4

### PR DESCRIPTION
**Pull request by lodekeeper**
## Description

Fixes #8848

In multi-beacon-node setups (DVT, fallback configurations, high-availability validators), the same block may be published to multiple beacon nodes simultaneously. When this happens, a race condition can occur:

1. Validator client (e.g., Vero) requests an unsigned block from Node A
2. Validator signs the block
3. Validator publishes the signed block to **multiple nodes** (Node A and Node B)
4. Node A receives the publish first and starts gossiping the block + data columns
5. Node B receives columns via gossip from Node A
6. Node B's API publish handler tries to add columns that already exist in the cache
7. `publishBlockV2` throws `BLOCK_INPUT_ERROR_INVALID_CONSTRUCTION` with message "Cannot addColumn to BlockInputColumns with duplicate column index"

The same issue can occur with blobs in pre-Fulu forks.

## Solution

Pass `{throwOnDuplicateAdd: false}` to `addColumn()` and `addBlob()` in `publishBlock`. This option already exists and is used correctly in `seenGossipBlockInput.ts` when handling gossip-received data. Receiving the same columns/blobs from both gossip and API is valid behavior in multi-BN setups and should not throw an error.

## Testing

The fix uses an existing, well-tested code path. The `throwOnDuplicateAdd: false` option causes `addColumn`/`addBlob` to silently return when a duplicate is detected, which is the correct behavior when the same data arrives from multiple sources.

---

*This PR was developed with AI assistance (disclosure per project contribution guidelines).*

### CODE REVIEW

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts [hunk 1]
```diff
@@ -133,21 +133,33 @@ export function getBeaconBlockApi({
...
       for (const dataColumnSidecar of dataColumnSidecars) {
-        blockForImport.addColumn({
-          blockRootHex: blockRoot,
-          columnSidecar: dataColumnSidecar,
-          source: BlockInputSource.api,
-          seenTimestampSec,
-        });
+        // In multi-BN setups (DVT, fallback), the same block may be published to multiple nodes.
+        // Columns may arrive via gossip from another node before the API publish completes,
+        // so we allow duplicates here instead of throwing an error.
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: the comment should be above the options (L145), not here

**Comment by lodekeeper** [comment]
Moved the comment above the options parameter as requested.

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts [hunk 2]
```diff
@@ -133,21 +133,33 @@ export function getBeaconBlockApi({
...
+          {
+            blockRootHex: blockRoot,
+            columnSidecar: dataColumnSidecar,
+            source: BlockInputSource.api,
+            seenTimestampSec,
+          },
+          // In multi-BN setups (DVT, fallback), the same block may be published to multiple nodes.
+          // Columns may arrive via gossip from another node before the API publish completes,
+          // so we allow duplicates here instead of throwing an error.
+          {throwOnDuplicateAdd: false}
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/blocks/index.ts:146]: this makes sense to me, we have observed  a similar issue with duplicate blocks before when running in a multi-node setup

cc @matthewkeil in case you see any issue with this but I really don't see a reason why we would need to throw an error here

**Review by nflaig — DISMISSED** [review]

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 1 above)
Comment (lodekeeper) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: Moved comment above the if block. Single comment now covers both cases.

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts [hunk 3]
```diff
@@ -131,23 +131,32 @@ export function getBeaconBlockApi({
       dataColumnSidecars = [];
     }
 
+    // In multi-BN setups (DVT, fallback), the same block may be published to multiple nodes.
+    // Data columns/blobs may arrive via gossip from another node before the API publish completes,
+    // so we allow duplicates here instead of throwing an error.
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: this comment needs to be placed above ` {throwOnDuplicateAdd: false}`, otherwise it's out of context when reading the code

Comment (lodekeeper) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: Fixed - moved comment directly above `{throwOnDuplicateAdd: false}`

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts [hunk 4]
```diff
@@ -133,21 +133,31 @@ export function getBeaconBlockApi({
...
-        });
+        blockForImport.addColumn(
+          {
+            blockRootHex: blockRoot,
+            columnSidecar: dataColumnSidecar,
+            source: BlockInputSource.api,
+            seenTimestampSec,
+          },
+          // In multi-BN setups (DVT, fallback), the same block may be published to multiple nodes.
+          // Data columns/blobs may arrive via gossip from another node before the API publish completes,
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/blocks/index.ts]:
```suggestion
          // Data columns may arrive via gossip from another node before the API publish completes,
```

**Review by nflaig — APPROVED** [review]

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 4 above)
Comment (lodekeeper) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: Applied.

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 2 above)
Comment (matthewkeil) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts:146]: I don't things we would not need to here

**Review by matthewkeil — APPROVED** [review]
LGTM!! 🎸

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.40.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.40.0) :tada:
