### PR TITLE
Re-add voluntary exit cmd

### LINKED ISSUE #4214: Re-add voluntary exit command
- See https://github.com/ChainSafe/lodestar/pull/4212

- Add latter after merging https://github.com/ChainSafe/lodestar/pull/4201

### LINKED ISSUE #4472: voluntary-exit missing from validator
**Steps to Reproduce**

lodestar v1.x no longer supports `validator voluntary-exit`, and no obvious replacement can be found in the `--help` text for `lodestar` or `lodestar validator`.

This may be a bug, unless removal of voluntary-exit was deliberate.

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

- https://github.com/ChainSafe/lodestar/pull/4212 dropped voluntary exit as the account managment underwent a big refactor

**Description**

- Re-add voluntary exit cmd
- Add full e2e that exists validators with new command

Closes https://github.com/ChainSafe/lodestar/issues/4214
Closes https://github.com/ChainSafe/lodestar/issues/4472

### CODE REVIEW

**Review by twoeths — DISMISSED** [review]
lgtm!

File: packages/cli/src/cmds/validator/voluntaryExit.ts [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+    // Fetch genesisValidatorsRoot always from beacon node
+    // Do not use known networks cache, it defaults to mainnet for devnets
+    const chainForkConfig = getBeaconConfigFromArgs(args);
+    const client = getClient({baseUrl: args.server}, {config: chainForkConfig});
+    const {genesisValidatorsRoot} = (await client.beacon.getGenesis()).data;
+    const config = createIBeaconConfig(chainForkConfig, genesisValidatorsRoot);
+
+    // Fetch exitEpoch from latest header if unspecified
+    const exitEpoch =
+      args.exitEpoch ?? computeEpochAtSlot((await client.beacon.getBlockHeader("head")).data.header.message.slot);
```
Comment (wemeetagain) [inline packages/cli/src/cmds/validator/voluntaryExit.ts]: Doesn't practically matter, but we can use the clock slot (using above genesis data) instead of the head block slot. Then we don't need an additional api call.

Comment (dapplion) [reply packages/cli/src/cmds/validator/voluntaryExit.ts]: Good idea

**Review by wemeetagain — APPROVED** [review]
