### PR TITLE
Follow beacon HTTP API spec

### LINKED ISSUE #3852: /eth/v1/beacon/states/{state_id}/validators wrong query param names
**Describe the bug**
Making a request to /eth/v1/beacon/states/{state_id}/validators?id=<pubkey> returns the entire list of all validators.

**Expected behavior**
It should return one or no results filtered by the pubkey.

**Steps to Reproduce**
With a synced beacon node:
```
curl http://<lodestar-beacon-node>:9596/eth/v1/beacon/states/head/validators?id=0x92f1dd97f9eb66754108d786107a24a7b6eb6dd6d1b9de8424c8cf0dc4ec95f9f069797be7e3d2de9d71e0cad55deb17
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04 LTS
- Version: `chainsafe/lodestar:v0.34.1` via docker
- Branch: n/a
- Commit hash: n/a

**Additional Info**
It works if I use `?indicies=` (and `&statuses=`) as identified per https://github.com/ChainSafe/lodestar/blob/f532758a4d7db4a9dda6deef4a0c447fb5f88725/packages/api/src/routes/beacon/state.ts#L156 , however per the API spec at https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidators it should be `?id=<x>` (and `status`).

### PR DESCRIPTION
**Pull request by dadepo**
**Motivation**

Changes to adhere to the beacon node api spec

Closes #3852 #3846

### CODE REVIEW

**Review by dapplion — APPROVED** [review]
LGTM! Thank youu

**Review by g11tech — APPROVED** [review]

File: packages/api/src/routes/node.ts [hunk 1]
```diff
@@ -52,9 +52,9 @@ export type FilterGetPeers = {
 
 export type SyncingStatus = {
   /** Head slot node is trying to reach */
-  headSlot: Slot;
+  headSlot: string;
```
Comment (dapplion) [inline packages/api/src/routes/node.ts:55]: After merging ssz refactor this should not be necessary since uint in JSON form is a string
