### PR TITLE
Fix random subnet subscription

### LINKED ISSUE #4929: v1.3.0-rc.0: Not enough subnet mesh peers
**Describe the bug**

For a node of ~1k validators, we don't have enough subnet mesh peers

Screen Shot 2022-12-21 at 08 29 49

Some logs 

```
grep -e "to gossipsub" -rn beacon-2022-12-20.log

17928:Dec-20 00:14:00.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_50/ssz_snappy
290536:Dec-20 03:46:00.003[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_2/ssz_snappy
437464:Dec-20 05:40:36.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_16/ssz_snappy
544419:Dec-20 07:03:36.003[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_54/ssz_snappy
670745:Dec-20 08:40:00.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_1/ssz_snappy
870289:Dec-20 11:13:24.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_38/ssz_snappy
989328:Dec-20 12:45:24.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_25/ssz_snappy
1304720:Dec-20 16:48:24.011[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_37/ssz_snappy
1360323:Dec-20 17:31:12.073[network]       verbose: Subscribe to gossipsub topic topic=/eth2/c2ce3aa8/sync_committee_2/ssz_snappy
1671313:Dec-20 21:26:12.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_19/ssz_snappy
1840351:Dec-20 23:34:12.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_13/ssz_snappy

grep -e "to gossipsub" -rn beacon-2022-12-19.log

206645:Dec-19 02:39:48.003[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_28/ssz_snappy
612334:Dec-19 07:52:36.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_35/ssz_snappy
706957:Dec-19 09:05:00.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_62/ssz_snappy
755941:Dec-19 09:42:24.005[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_44/ssz_snappy
861797:Dec-19 11:03:24.005[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_4/ssz_snappy
1024619:Dec-19 13:08:24.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_63/ssz_snappy
1038932:Dec-19 13:19:24.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_43/ssz_snappy
1099597:Dec-19 14:05:48.003[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_3/ssz_snappy
1120266:Dec-19 14:21:36.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_24/ssz_snappy
1396987:Dec-19 17:54:24.004[network]       verbose: Unsubscribe to gossipsub topic topic=/eth2/c2ce3aa8/beacon_attestation_41/ssz_snappy
```

==> looks like we don't do a subscribe right after a unsubscribe when we rebalance random subnet subscriptions

This is not the same to #4818, now gossip score is great
Screen Shot 2022-12-21 at 08 32 32

**Expected behavior**

We should have 64 subnet mesh peers consistently

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- Random subscription starts at a random slot in epoch and unsubscribed per `onEpoch` check so there are some inactive slots. This is unexpected because for a node with >= 64 validators we want to always subscribe to all random subnets
- During the inactive slots, a committee subscription may be expired and we unsubscribe the subnet topic
- Due to this change in v1.3.0 #4829 we don't have a chance to rebalance random subscriptions

**Description**

- Check the random subscription per `onSlot` instead of `onEpoch`, do it before committee subscription
- Bring back attnetsService unit test, reproduce the issue in a test case. Since ESM support, there is `ES Modules cannot be stubbed` error so I have to put in `randBetweenFn, shuffleFn` to do the unit test
- Add metrics for future investigation if any issues happen

Closes #4929

### CODE REVIEW

File: packages/beacon-node/src/network/subnets/attnetsService.ts [hunk 1]
```diff
@@ -170,7 +192,8 @@ export class AttnetsService implements IAttnetsService {
    */
   private unsubscribeExpiredCommitteeSubnets(slot: Slot): void {
     const expired = this.subscriptionsCommittee.getExpired(slot);
-    this.unsubscribeSubnets(expired, slot);
+    if (expired.length === 0) return;
```
Comment (dapplion) [inline packages/beacon-node/src/network/subnets/attnetsService.ts]:
```suggestion
    if (expired.length > 0) {
          this.unsubscribeSubnets(expired, slot, SubnetSource.committee);
    }
```

File: packages/beacon-node/src/network/subnets/attnetsService.ts [hunk 2]
```diff
@@ -182,16 +205,18 @@ export class AttnetsService implements IAttnetsService {
     const expired = this.subscriptionsRandom.getExpired(slot);
     const currentSlot = this.chain.clock.currentSlot;
 
+    if (expired.length === 0) return;
```
Comment (dapplion) [inline packages/beacon-node/src/network/subnets/attnetsService.ts]:
```suggestion
    if (expired.length === 0) {
      return;
    }
```

File: packages/beacon-node/src/network/subnets/interface.ts [hunk 3]
```diff
@@ -23,6 +23,12 @@ export interface IAttnetsService extends ISubnetsService {
   shouldProcess(subnet: number, slot: Slot): boolean;
 }
 
+export type RandBetweenFn = (min: number, max: number) => number;
+export type ShuffleFn = <T>(arr: T[]) => T[];
+
 export type SubnetsServiceOpts = {
   subscribeAllSubnets?: boolean;
+  // For unit test
```
Comment (dapplion) [inline packages/beacon-node/src/network/subnets/interface.ts]:
```suggestion
  // For deterministic randomness in unit test after ESM prevents simple import mocking
```

File: packages/beacon-node/test/unit/network/attestationService.test.ts [hunk 4]
```diff
@@ -156,10 +187,10 @@ describe.skip("AttnetsService", function () {
   });
 
   it.skip("handle committee subnet the same to random subnet", () => {
```
Comment (dapplion) [inline packages/beacon-node/test/unit/network/attestationService.test.ts]: Still skipped

**Review by dapplion — DISMISSED** [review]

File: packages/beacon-node/test/unit/network/attestationService.test.ts (hunk 4 above)
Comment (twoeths) [reply packages/beacon-node/test/unit/network/attestationService.test.ts]: I added back

**Review by dapplion — APPROVED** [review]
