### PR TITLE
fix: resubscribe to beacon subnets on current epoch reorg

### LINKED ISSUE #6034: Resubscribe to beacon subnets if current epoch dependent root changed
### Describe the bug

We have this function `handleAttesterDutiesReorg` which is mostly called when head (`onNewHead`) is updated
- and dependent root for next epoch changed
- or dependent root for current epoch changed

https://github.com/ChainSafe/lodestar/blob/1aa656191c84e3b55281bb8f21c9f4a529282500/packages/validator/src/services/attestationDuties.ts#L348

In both those cases we handle the reorg by
- getting updated attestater duties (`getAttesterDuties`)
- update cached duties (`dutiesByIndexByEpoch`)
- recalculate proof (`is_aggregator`)

But I noticed we are not resubscribing to beacon subnets (`prepareBeaconCommitteeSubnet`). This is not an issue if the dependent root for the next epoch changed as we re-/subscribe to current (_N_) and next epoch (_N+1_) at the start of each epoch.
https://github.com/ChainSafe/lodestar/blob/1aa656191c84e3b55281bb8f21c9f4a529282500/packages/validator/src/services/attestationDuties.ts#L196

However, this is an issue if dependent root for current epoch changed as previous subscriptions are no longer valid
- validator duties changed (slot, committee index, etc.)
- `is_aggregator` results are different

### Expected behavior

Validators should be resubscribed to beacon committee subnets if current epoch dependent root changed.

Ideally, should just always resubscribe when `handleAttesterDutiesReorg` is called even if dependent root for next epoch changed as the subscriptions for epoch _N+1_ are outdated as well and the sooner we subscribe to subnets, the more likely it is to find good peers.

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.11.3 / unstable (1aa656191c84e3b55281bb8f21c9f4a529282500)

### PR DESCRIPTION
**Pull request by phertyameen**
**Motivation**

Not resubscribing to beacon subnets (prepareBeaconCommitteeSubnet) as dependent root for current epoch changes. When this happens, previous subscriptions are no longer valid

validator duties changed (slot, committee index, etc.)
is_aggregator results are different

**Description**

Added subnet resubscription logic to `handleAttesterDutiesReorg` that fetches updated attester duties, rebuild beaconCommitteeSubscriptions and resubscribe validators to the correct beacon subnets by calling the prepareBeaconCommitteeSubnet api

Added test to handle: 
- resubscribe to beacon subnets when current epoch dependent root changes,
- resubscribe when next epoch dependent root changes and
- not resubscribe when dependent root unchanged

There was intentional use of claude AI in writing the test.

Closes #6034

**Steps to test or reproduce**

### CODE REVIEW

**Comment by phertyameen** [comment]
@nflaig Can you please review this?

File: packages/validator/src/services/attestationDuties.ts [hunk 1]
```diff
@@ -371,6 +371,28 @@ export class AttestationDutiesService {
...
+        });
+      }
+    }
+
+    if (beaconCommitteeSubscriptions.length > 0) {
+      const subscriptionsBatches = batchItems(beaconCommitteeSubscriptions, {batchSize: SUBSCRIPTIONS_PER_REQUEST});
+      await Promise.all(
+        subscriptionsBatches.map((subscriptions) => this.api.validator.prepareBeaconCommitteeSubnet({subscriptions}))
+      );
+    }
```
Comment (nflaig) [inline packages/validator/src/services/attestationDuties.ts:397]: this is missing the asserts to make sure all requests succeeded, otherwise this could hide errors

```ts
      for (const res of responses) {
        res.assertOk();
      }
```

this is the same logic as we already have here

https://github.com/ChainSafe/lodestar/blob/5317389489e1553be2e98f79f0c0f8c74ff79f28/packages/validator/src/services/attestationDuties.ts#L222-L226

it makes sense to have a private method for this to make sure batching / error handling is the same

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 2]
```diff
@@ -241,4 +242,137 @@ describe("AttestationDutiesService", () => {
...
+        mockApiResponse({
+          data: [reorgedDuty],
+          meta: {dependentRoot: "0xNEW_ROOT", executionOptimistic: false},
+        })
+      );
+
+      await onNewHeadCallback({
+        slot,
+        head: "0xHEAD_BLOCK",
+        previousDutyDependentRoot: "0xOLD_ROOT",
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts]: instead using a value like `0xOLD_ROOT` rather declare a variable (same for other test values)

```ts
const oldDependentRoot = toRootHex(Buffer.alloc(32, 1));
```

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 3]
```diff
@@ -241,4 +242,137 @@ describe("AttestationDutiesService", () => {
...
+      const epoch = computeEpochAtSlot(slot);
+      const duty = setupDuty(slot);
+
+      const {clock, dutiesService, onNewHeadCallback} = await setupTestEnvironment(duty);
+      await clock.tickEpochFns(epoch, controller.signal);
+
+      expect(dutiesService["dutiesByIndexByEpoch"].get(epoch)).toBeDefined();
+      expect(api.validator.prepareBeaconCommitteeSubnet).toHaveBeenCalledTimes(1);
+
+      const reorgedDuty = {...duty, slot: slot + 1, committeeIndex: 3};
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts]: the reorged duty would have the same `slot` as the original duty, so incrementing that by 1 is not right

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 4]
```diff
@@ -241,4 +242,137 @@ describe("AttestationDutiesService", () => {
...
+          expect.objectContaining({
+            validatorIndex: index,
+            slot: reorgedDuty.slot,
+            committeeIndex: reorgedDuty.committeeIndex,
+          }),
+        ])
+      );
+    });
+
+    it("Should resubscribe when next epoch dependent root changes", async () => {
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts]: I don't think this test does what the title here says, please also make sure `prepareBeaconCommitteeSubnet` is called as expected

but to test next epoch attester duties reorg you need to have duties at that epoch, which this test does not, it just sets up a duty for current epoch

see code here https://github.com/ChainSafe/lodestar/blob/5317389489e1553be2e98f79f0c0f8c74ff79f28/packages/validator/src/services/attestationDuties.ts#L332-L334

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 5]
```diff
@@ -241,4 +242,137 @@ describe("AttestationDutiesService", () => {
...
+      slot,
+      committeeIndex: 1,
+      committeeLength: 120,
+      committeesAtSlot: 120,
+      validatorCommitteeIndex: 1,
+      validatorIndex: index,
+      pubkey: pubkeys[0],
+    });
+
+    async function setupTestEnvironment(duty: routes.validator.AttesterDuty, dependentRoot = "0xOLD_ROOT") {
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts]: instead of these setup functions it would be better to make use of `beforeEach` hook to setup data, it's fine to be a bit repetitive (more verbose) in tests as it makes it easier to read them, encapsulations make it harder to understand what the test is doing

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 6]
```diff
@@ -241,4 +242,137 @@ describe("AttestationDutiesService", () => {
...
+          meta: {dependentRoot, executionOptimistic: false},
+        })
+      );
+      api.validator.prepareBeaconCommitteeSubnet.mockResolvedValue(mockApiResponse({}));
+
+      const clock = new ClockMock();
+      const syncingStatusTracker = new SyncingStatusTracker(loggerVc, api, clock, null);
+
+      let onNewHeadCallback: ((headEvent: HeadEventData) => Promise<void>) | undefined;
+      chainHeadTracker.runOnNewHead.mockImplementation((callback) => {
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts:263]: There is an issue with bun mocking like this, see https://github.com/ChainSafe/lodestar/pull/7971#discussion_r2218489231. The bun CI tests are failing here https://github.com/ChainSafe/lodestar/actions/runs/18902688654/job/54262090873?pr=8570

adding this before fixes it
```ts
vi.spyOn(chainHeadTracker, "runOnNewHead");
```

you can run bun unit tests like this
```bash
bun run --bun test:unit packages/validator/test/unit/services/attestationDuties.test.ts
```

**Review by nflaig — COMMENTED** [review]
Thanks @phertyameen for taking a look at this, few remarks mostly regarding the tests as those do not follow the usual patterns we use, please take a look at existing tests and try to align test / mock data setup a bit more (see comments)

**Comment by phertyameen** [comment]
Understood. Will make these corrections right away. Thanks for the detailed review.

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 7]
```diff
@@ -241,4 +243,228 @@ describe("AttestationDutiesService", () => {
...
+
+      const dutiesService = new AttestationDutiesService(
+        loggerVc,
+        api,
+        clock,
+        validatorStore,
+        chainHeadTracker,
+        syncingStatusTracker,
+        null
+      );
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts]: these are not really specific to the test case and can be moved in a `beforeEach` hook

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 8]
```diff
@@ -241,4 +243,228 @@ describe("AttestationDutiesService", () => {
...
+        committeeLength: 120,
+        committeesAtSlot: 120,
+        validatorCommitteeIndex: 1,
+        validatorIndex: index,
+        pubkey: pubkeys[0],
+      };
+
+      api.validator.getAttesterDuties.mockResolvedValue(
+        mockApiResponse({
+          data: [currentEpochDuty],
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts]: this will return `currentEpochDuty` for current epoch and next epoch

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 9]
```diff
@@ -241,4 +243,228 @@ describe("AttestationDutiesService", () => {
...
+        validatorStore,
+        chainHeadTracker,
+        syncingStatusTracker,
+        null
+      );
+
+      await clock.tickEpochFns(currentEpoch, controller.signal);
+
+      expect(dutiesService["dutiesByIndexByEpoch"].get(currentEpoch)).toBeDefined();
+      expect(dutiesService["dutiesByIndexByEpoch"].get(nextEpoch)).toBeDefined();
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts]: these should make sure the duties are as we expect them, and not just if they are defined

File: packages/validator/test/unit/services/attestationDuties.test.ts [hunk 10]
```diff
@@ -241,4 +243,228 @@ describe("AttestationDutiesService", () => {
...
+
+      const reorgedNextEpochDuty = {...nextEpochDuty, committeeIndex: 4};
+      api.validator.getAttesterDuties.mockResolvedValue(
+        mockApiResponse({
+          data: [reorgedNextEpochDuty],
+          meta: {dependentRoot: newDependentRoot, executionOptimistic: false},
+        })
+      );
+
+      await onNewHeadCallback!({
```
Comment (nflaig) [inline packages/validator/test/unit/services/attestationDuties.test.ts]: this should never be needed

```suggestion
      await onNewHeadCallback({
```

**Review by nflaig — COMMENTED** [review]
Looks pretty good, few remarks on the unit tests, will push some minor updates then we are good to merge this

**Review by nflaig — DISMISSED** [review]

File: packages/validator/src/services/attestationDuties.ts [hunk 11]
```diff
@@ -371,6 +362,39 @@ export class AttestationDutiesService {
...
+          validatorIndex: duty.validatorIndex,
+          committeesAtSlot: duty.committeesAtSlot,
+          committeeIndex: duty.committeeIndex,
+          slot: duty.slot,
+          isAggregator: selectionProof !== null,
+        });
+      }
+    }
+
+    // Previous subscriptions are no longer valid and need to updated
```
Comment (nflaig) [inline packages/validator/src/services/attestationDuties.ts]:
```suggestion
    // Previous subscriptions are no longer valid and need to be updated
```

**Review by nflaig — APPROVED** [review]

**Comment by phertyameen** [comment]
Noted the corrections. Thank you again for the assistance. I have learned a lot from this 🙏

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.36.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.36.0) :tada:
