### PR TITLE
fix: update Beacon api impl to enforce unique array

### LINKED ISSUE #5271: getStateValidators does not dedupe validators
**Describe the bug**

Not sure if this should be considered a bug but I think it is better that we dedupe the result of [getStateValidators](https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidators) if the same validator index/pubkey is provided multiple times.

**Current behavior**

Returns the same validator multiple times if index or pubkey is provided multiple times.

See implementation https://github.com/ChainSafe/lodestar/blob/3e254d588ce5169a1fd08e2b6ea6b7f509695fbc/packages/beacon-node/src/api/impl/beacon/state/index.ts#L58

**Expected behavior**

Should dedupe the result and only return each unique validator once.

**Steps to Reproduce**

Start lodestar in dev mode

```sh
./lodestar dev  --genesisValidators 8 --startValidators 0..7
```

send http request to getStateValidators API

```sh
curl "http://localhost:9596/eth/v1/beacon/states/head/validators?id=1,1" | jq
```

be surprised that the validator with index 1 is returned twice

```json
{
  "data": [
    {
      "index": "1",
      "balance": "32000000000",
      "status": "active_ongoing",
      "validator": {
        "pubkey": "0xb89bebc699769726a318c8e9971bd3171297c61aea4a6578a7a4f94b547dcba5bac16a89108b6b6a1fe3695d1a874a0b",
        "withdrawal_credentials": "0x00ec7ef7780c9d151597924036262dd28dc60e1228f4da6fecf9d402cb3f3594",
        "effective_balance": "32000000000",
        "slashed": false,
        "activation_eligibility_epoch": "0",
        "activation_epoch": "0",
        "exit_epoch": "18446744073709551615",
        "withdrawable_epoch": "18446744073709551615"
      }
    },
    {
      "index": "1",
      "balance": "32000000000",
      "status": "active_ongoing",
      "validator": {
        "pubkey": "0xb89bebc699769726a318c8e9971bd3171297c61aea4a6578a7a4f94b547dcba5bac16a89108b6b6a1fe3695d1a874a0b",
        "withdrawal_credentials": "0x00ec7ef7780c9d151597924036262dd28dc60e1228f4da6fecf9d402cb3f3594",
        "effective_balance": "32000000000",
        "slashed": false,
        "activation_eligibility_epoch": "0",
        "activation_epoch": "0",
        "exit_epoch": "18446744073709551615",
        "withdrawable_epoch": "18446744073709551615"
      }
    }
  ],
  "execution_optimistic": false
}
```

### PR DESCRIPTION
**Pull request by mkermani144**
**Motivation**

Make sure array inputs to some Beacon APIs are unique, based on [Beacon APIs spec](https://github.com/ethereum/beacon-APIs).

**Description**

This change enhances the robustness of the API by ensuring that duplicate entries are not processed, aligning with schema definitions from Beacon API spec.

Closes #5271

**Steps to test or reproduce**
- Run a dev environment via `lodestar dev`
- Test the API with duplicate input (=query, body, etc.)
- Assert that a response with 400 status code is returned

### CODE REVIEW

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 1]
```diff
@@ -85,6 +86,9 @@ export function getBeaconStateApi({
     },
 
     async getStateValidators({stateId, validatorIds = [], statuses = []}) {
+      ensureUniqueItemsOrThrow(validatorIds, "Duplicate validator IDs provided");
+      ensureUniqueItemsOrThrow(statuses, "Duplicate statuses provided");
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: this only needs to be checked if `length > 0` which we do below for each, should move those there

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 2]
```diff
@@ -15,6 +15,7 @@ import {getValidatorStatus} from "@lodestar/types";
 import {fromHex} from "@lodestar/utils";
 import {ApiError} from "../../errors.js";
 import {ApiModules} from "../../types.js";
+import ensureUniqueItemsOrThrow from "../../utils.js";
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: we don't use default exports usually

File: packages/beacon-node/src/api/impl/utils.ts [hunk 3]
```diff
@@ -0,0 +1,22 @@
+import {ApiError} from "./errors.js";
+
+/**
+ * Ensures that the array contains unique values, and throws an ApiError
+ * otherwise.
+ * @param array - The array to check for uniqueness.
+ * @param message - The message to put in the ApiError if the array contains
+ * duplicates.
+ */
+const ensureUniqueItemsOrThrow = (array: unknown[] | undefined, message: string) => {
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/utils.ts]:
```suggestion
export function assertUniqueItems(array: unknown[] | undefined, message: string) {
```

File: packages/beacon-node/src/api/impl/utils.ts [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+  if (!array) {
+    return;
+  }
+
+  const containsDuplicates = new Set(array).size !== array.length;
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/utils.ts]: it would be kinda nice to be able to return the duplicate values are part of the error so it's easier for consumers to figure out what went wrong

File: packages/beacon-node/src/api/impl/utils.ts
Comment (nflaig) [inline packages/beacon-node/src/api/impl/utils.ts:1]: please try to follow current code structure here, ie. how the function is defined and exported does not align with our code style

File: packages/beacon-node/src/api/impl/beacon/state/index.ts (hunk 1 above)
Comment (mkermani144) [reply packages/beacon-node/src/api/impl/beacon/state/index.ts]: Moved to condition blocks ✅

File: packages/beacon-node/src/api/impl/beacon/state/index.ts (hunk 2 above)
Comment (mkermani144) [reply packages/beacon-node/src/api/impl/beacon/state/index.ts]: Changed to named export ✅

File: packages/beacon-node/src/api/impl/utils.ts (hunk 3 above)
Comment (mkermani144) [reply packages/beacon-node/src/api/impl/utils.ts]: ✅

File: packages/beacon-node/src/api/impl/utils.ts (hunk 4 above)
Comment (mkermani144) [reply packages/beacon-node/src/api/impl/utils.ts]: Switched to a diff-like method to find the duplicates, and introduced a new error type which concats the duplicates at the end of the error message ✅

File: packages/beacon-node/src/api/impl/utils.ts
Comment (mkermani144) [reply packages/beacon-node/src/api/impl/utils.ts:1]: - Switched to named exports
- Switched to function declaration (instead of arrow)
- Added return type

Let me know if I'm missing any other convention.

File: packages/beacon-node/src/api/impl/errors.ts [hunk 5]
```diff
@@ -47,4 +47,17 @@ export class IndexedError extends ApiError {
   }
 }
 
+/**
+ * Error thrown when an array input to an API (e.g. its body, params, etc.)
+ * contains duplicate items.
+ */
+export class ApiInputDuplicateItemsError<T> extends ApiError {
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/errors.ts]: why do we need a custom error for this?

Comment (mkermani144) [reply packages/beacon-node/src/api/impl/errors.ts]: I overlooked its redundancy. I first thought this will be reused for each validation, but after extracting the validation logic into a `ensureUniqueItemsOrThrow` function, it is of no use. Removed it.

**Comment by mkermani144** [comment]
@nflaig Any idea why sim tests constantly failing? Is it a problem caused by my changes?

File: packages/beacon-node/src/api/impl/utils.ts [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+
+  const duplicateItems = array.reduce((partialDuplicateItems: unknown[], item, index) => {
+    if (array.indexOf(item) !== index && !partialDuplicateItems.includes(item)) {
+      return partialDuplicateItems.concat(item);
+    }
+    return partialDuplicateItems;
+  }, []);
+
+  if (duplicateItems.length) {
+    throw new ApiError(400, `${message} (Duplicate Items: ${duplicateItems.join(", ")})`);
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/utils.ts]: message seems redundant, what about

```suggestion
    throw new ApiError(400, `${message}: ${duplicateItems.join(", ")}`);
```

File: packages/beacon-node/src/api/impl/utils.ts [hunk 7]
```diff
@@ -0,0 +1,25 @@
+import {ApiError} from "./errors.js";
+
+/**
+ * Ensures that the array contains unique values, and throws an ApiError
+ * otherwise.
+ * @param array - The array to check for uniqueness.
+ * @param message - The message to put in the ApiError if the array contains
+ * duplicates.
+ */
+export function ensureUniqueItemsOrThrow(array: unknown[] | undefined, message: string): void {
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/utils.ts]: can we rename this please (as suggested earlier)

```suggestion
export function assertUniqueItems(array: unknown[] | undefined, message: string): void {
```

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 8]
```diff
@@ -231,6 +238,8 @@ export function getBeaconStateApi({
     },
 
     async postStateValidatorBalances(args, context) {
+      ensureUniqueItemsOrThrow(args.validatorIds, "Duplicate validator IDs provided");
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: this should be enforced in `this.getStateValidatorBalances`, right now it's checking for unique items twice

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 9]
```diff
@@ -194,6 +199,8 @@ export function getBeaconStateApi({
     },
 
     async getStateValidatorBalances({stateId, validatorIds = []}) {
+      ensureUniqueItemsOrThrow(validatorIds, "Duplicate validator IDs provided");
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: this can be checked after `if (validatorIds.length)` at line 206

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 10]
```diff
@@ -142,6 +145,8 @@ export function getBeaconStateApi({
     },
 
     async postStateValidatorIdentities({stateId, validatorIds = []}) {
+      ensureUniqueItemsOrThrow(validatorIds, "Duplicate validator IDs provided");
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: can be moved to line 156

**Comment by nflaig** [comment]
> @nflaig Any idea why sim tests constantly failing? Is it a problem caused by my changes?

I ran the CI again, will check if it's still failing, I don't see why changes in the PR would cause issues though

**Review by nflaig — APPROVED** [review]
LGTM - thanks @mkermani144

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.31.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.31.0) :tada:
