### PR TITLE
Remove multiaddr in ENR if its not local network interface

### LINKED ISSUE #1141: Altona: Cannot detect new peers upon restart
**Describe the bug**
After we initialize a beacon folder and sync Altona, we can always detect peers very quickly. But upon a restart, sometimes we can detect peers, sometimes we cannot and we end up with setting up a new beacon folder by `beacon run init`.

**Expected behavior**
We can detect new peers at any time

### PR DESCRIPTION
**Pull request by twoeths**
resolves #1141 

image

### CODE REVIEW

File: packages/lodestar-cli/src/cmds/beacon/cmds/run/run.ts [hunk 1]
```diff
@@ -24,28 +25,26 @@ export async function run(options: Arguments<IBeaconArgs & Partial<IBeaconNodeOp
...
+  const logger = new WinstonLogger();
   const peerId = await readPeerId(options.network.peerIdFile);
   // read local enr from disk
-  options.network.discv5.enr = await readEnr(options.network.enrFile);
+  const enr = await readEnr(options.network.enrFile);
+  if (enr.multiaddrUDP && !isLocalMultiAddr(enr.multiaddrUDP)) {
+    logger.info(`MultiAddress of ${enr.multiaddrUDP.toString()} is not part of local network interface so removed it`);
+    clearMultiaddrUDP(enr);
+  }
+  options.network.discv5.enr = enr;
```
Comment (mpetrunic) [inline packages/lodestar-cli/src/cmds/beacon/cmds/run/run.ts]: How come we don't handle this in network module?

File: packages/lodestar-cli/src/cmds/beacon/cmds/run/util.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
+import Multiaddr from "multiaddr";
+import {networkInterfaces} from "os";
+import {ENR} from "@chainsafe/discv5";
+
+/**
+ * Check if multiaddr belongs to the local network interfaces.
+ */
+export function isLocalMultiAddr(multiaddr: Multiaddr | undefined): boolean {
```
Comment (mpetrunic) [inline packages/lodestar-cli/src/cmds/beacon/cmds/run/util.ts]: Feels like we should put this in lodestar/network/utils

File: packages/lodestar-cli/src/cmds/beacon/cmds/run/run.ts (hunk 1 above)
Comment (twoeths) [reply packages/lodestar-cli/src/cmds/beacon/cmds/run/run.ts]: I think it's just more clear to put it here because we want to handle this logic at startup time.
what do you think @wemeetagain ?

Comment (dapplion) [reply packages/lodestar-cli/src/cmds/beacon/cmds/run/run.ts]: This fix changes should not apply to the validator when it's run by a different consumer than our CLI?

Comment (wemeetagain) [reply packages/lodestar-cli/src/cmds/beacon/cmds/run/run.ts]: I'm not sure we want the same behavior with a browser node, at least, not the _exact_ same behavior.
(eg: we might want to explicitly set a relay IP, or have a more intricate ENR initialization procedure in that case)

I think we can leave this here for now, or maybe move it to `createNodeJsLibp2p`?

Comment (wemeetagain) [reply packages/lodestar-cli/src/cmds/beacon/cmds/run/run.ts]: I guess a bigger issue is figuring out a strategy for splitting network agnostic code from nodejs / browser specific code. We have done some work towards that end, eg: with a nodejs-specific libp2p bundle, but it there likely will be a need for better organization.

**Review by mpetrunic — DISMISSED** [review]

**Comment by wemeetagain** [comment]
file conflict

**Review by wemeetagain — APPROVED** [review]
