### PR TITLE
fix: only subscribe to sampled subnets

### LINKED ISSUE #8098: Dynamically subscribe to data column subnets
Right now we always subscribe to all data column sidecars which means no matter if you are supernode or not we receive and propagate all data columns.

https://github.com/ChainSafe/lodestar/blob/f124be0a30833918146d0123e5b92658166fdc84/packages/beacon-node/src/network/gossip/topic.ts#L245-L248

It should probably work similar to attestation / sync committee subnets which are dynamic, ie. in case of data column subnets we need to adapt based on validator custody requirement.

There might be one edge case if we are proposer as we need to publish columns for all subnets.

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- right now we always subscribe to all column subnets which is not necessary because we only need columns that we custody/sample
- that's why I see 128 logs like this per slot, and this could degrade performance. We only need 8 per slot

```
 debug: Received gossip dataColumn slot=198378, root=0x9945…49af, curentSlot=198378, peerId=16Uiu2HAm2J4ZRFnf7qWvu8VBRFT66E5XFWnRTwYTahB2oRJom5ji, delaySec=1.5910000801086426, gossipIndex=113, columnIndex=113, pending=data_column, haveColumns=31, expectedColumns=8, recvToValLatency=0.0009999275207519531, recvToValidation=0.0009999275207519531, validationTime=0
```

**Description**

- only subscribe to custody/sampling subnets
- track sent peers per data column subnet when publishing blocks

**Test result**
- tested successfully on a devnet node

- Resolves https://github.com/ChainSafe/lodestar/issues/8098

### CODE REVIEW

**Comment by twoeths** [comment]
with a regular node, we subscribed to only 8 columns:

```

2025-08-12 14:19:26.652 | Aug-12 07:19:26.575[network]       verbose: Subscribe to gossipsub topic topic=/eth2/132d87f6/data_column_sidecar_101/ssz_snappy |  
-- | -- | --
  |   | 2025-08-12 14:19:26.652 | Aug-12 07:19:26.574[network]       verbose: Subscribe to gossipsub topic topic=/eth2/132d87f6/data_column_sidecar_83/ssz_snappy |  
  |   | 2025-08-12 14:19:26.652 | Aug-12 07:19:26.574[network]       verbose: Subscribe to gossipsub topic topic=/eth2/132d87f6/data_column_sidecar_62/ssz_snappy |  
  |   | 2025-08-12 14:19:26.652 | Aug-12 07:19:26.574[network]       verbose: Subscribe to gossipsub topic topic=/eth2/132d87f6/data_column_sidecar_56/ssz_snappy |  
  |   | 2025-08-12 14:19:26.652 | Aug-12 07:19:26.573[network]       verbose: Subscribe to gossipsub topic topic=/eth2/132d87f6/data_column_sidecar_51/ssz_snappy |  
  |   | 2025-08-12 14:19:26.652 | Aug-12 07:19:26.573[network]       verbose: Subscribe to gossipsub topic topic=/eth2/132d87f6/data_column_sidecar_42/ssz_snappy |  
  |   | 2025-08-12 14:19:26.652 | Aug-12 07:19:26.573[network]       verbose: Subscribe to gossipsub topic topic=/eth2/132d87f6/data_column_sidecar_40/ssz_snappy |  
  |   | 2025-08-12 14:19:26.652 | Aug-12 07:19:26.572[network]       verbose: Subscribe to gossipsub topic topic=/eth2/132d87f6/data_column_sidecar_30/ssz_snappy


```

**Comment by twoeths** [comment]
for each slot we only need to receive/validate 8 DataColumnSidecar

```

2025-08-12 14:29:36.787 | Aug-12 07:29:36.787[network]         debug: Received gossip dataColumn slot=28648, root=0x4cfe…4de3, currentSlot=28648, peerId=16Uiu2HAmLF5Y9LjjCwv4rawA2nE8Pm7Nn72SkS9Li9fsuz7tNL4N, delaySec=0.7360000610351562, gossipSubnet=101, columnIndex=101, pending=null, haveColumns=8, expectedColumns=8, recvToValLatency=0.01399993896484375, recvToValidation=0.05099987983703613, validationTime=0.03699994087219238 |  
-- | -- | --
  |   | 2025-08-12 14:29:36.780 | Aug-12 07:29:36.780[network]         debug: Received gossip dataColumn slot=28648, root=0x4cfe…4de3, currentSlot=28648, peerId=16Uiu2HAmFazaaFBw2pWMjfs3kuxYJpwK4yi1p8qVKvHKuyX51N7m, delaySec=0.7249999046325684, gossipSubnet=56, columnIndex=56, pending=data_column, haveColumns=7, expectedColumns=8, recvToValLatency=0.00800013542175293, recvToValidation=0.05500006675720215, validationTime=0.04699993133544922 |  
  |   | 2025-08-12 14:29:36.774 | Aug-12 07:29:36.774[network]         debug: Received gossip dataColumn slot=28648, root=0x4cfe…4de3, currentSlot=28648, peerId=16Uiu2HAmLF5Y9LjjCwv4rawA2nE8Pm7Nn72SkS9Li9fsuz7tNL4N, delaySec=0.7079999446868896, gossipSubnet=30, columnIndex=30, pending=data_column, haveColumns=6, expectedColumns=8, recvToValLatency=0.02500009536743164, recvToValidation=0.06599998474121094, validationTime=0.0409998893737793 |  
  |   | 2025-08-12 14:29:36.768 | Aug-12 07:29:36.768[network]         debug: Received gossip dataColumn slot=28648, root=0x4cfe…4de3, currentSlot=28648, peerId=16Uiu2HAmFazaaFBw2pWMjfs3kuxYJpwK4yi1p8qVKvHKuyX51N7m, delaySec=0.6789999008178711, gossipSubnet=51, columnIndex=51, pending=data_column, haveColumns=5, expectedColumns=8, recvToValLatency=0.051000118255615234, recvToValidation=0.08899998664855957, validationTime=0.037999868392944336 |  
  |   | 2025-08-12 14:29:36.759 | Aug-12 07:29:36.759[network]         debug: Received gossip dataColumn slot=28648, root=0x4cfe…4de3, currentSlot=28648, peerId=16Uiu2HAmCH8RBkiq9PTTvKkGXfJkSjFPYz4hFMNqYdZcgVL4iNdM, delaySec=0.6740000247955322, gossipSubnet=83, columnIndex=83, pending=data_column, haveColumns=4, expectedColumns=8, recvToValLatency=0.0559999942779541, recvToValidation=0.08500003814697266, validationTime=0.029000043869018555 |  
  |   | 2025-08-12 14:29:36.749 | Aug-12 07:29:36.749[network]         debug: Received gossip dataColumn slot=28648, root=0x4cfe…4de3, currentSlot=28648, peerId=16Uiu2HAmRgBTEBFN3o9dwwUsKMJopT3TXeFxrpcHR9R4wSLKz1fh, delaySec=0.6679999828338623, gossipSubnet=42, columnIndex=42, pending=data_column, haveColumns=3, expectedColumns=8, recvToValLatency=0.06200003623962402, recvToValidation=0.08100008964538574, validationTime=0.01900005340576172 |  
  |   | 2025-08-12 14:29:36.649 | Aug-12 07:29:36.649[network]         debug: Received gossip dataColumn slot=28648, root=0x4cfe…4de3, currentSlot=28648, peerId=16Uiu2HAmLF5Y9LjjCwv4rawA2nE8Pm7Nn72SkS9Li9fsuz7tNL4N, delaySec=0.6389999389648438, gossipSubnet=40, columnIndex=40, pending=block, haveColumns=2, expectedColumns=null, recvToValLatency=0.002000093460083008, recvToValidation=0.009999990463256836, validationTime=0.007999897003173828 |  
  |   | 2025-08-12 14:29:36.589 | Aug-12 07:29:36.589[network]         debug: Received gossip dataColumn slot=28648, root=0x4cfe…4de3, currentSlot=28648, peerId=16Uiu2HAmLF5Y9LjjCwv4rawA2nE8Pm7Nn72SkS9Li9fsuz7tNL4N, delaySec=0.5799999237060547, gossipSubnet=62, columnIndex=62, pending=block, haveColumns=1, expectedColumns=null, recvToValLatency=0.0010001659393310547, recvToValidation=0.009000062942504883, validationTime=0.007999897003173828

```
verbose: Block processed slot=28648, root=0x4cfe3cc6ff33efc3684500ebf8e2e796cdfdc241079a7c3e62be21a9b2494de3, delaySec=0.7920000553131104
```

```

**Comment by nflaig** [comment]
> with a regular node, we subscribed to only 8 columns:

shouldn't a node without validators attached just have to custody 4 groups/columns?
https://github.com/ChainSafe/lodestar/blob/aac4d9d86498d0368648522ea10cef3489ef46ea/packages/config/src/chainConfig/configs/mainnet.ts#L129-L130

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts [hunk 1]
```diff
@@ -278,7 +278,25 @@ export function getBeaconBlockApi({
...
           }),
     ];
-    await promiseAllMaybeAsync<number | void>(publishPromises);
+    const sentPeersArr = await promiseAllMaybeAsync<number | void>(publishPromises);
+
+    if (isForkPostFulu(fork)) {
+      // sent peers per topic are logged in network.publishGossip(), here we only track metrics for it
+      // starting from fulu, we have to push to 128 subnets so need to make sure we have enough sent peers per topic
+      // + 1 because we publish to beacon_block first
+      if (sentPeersArr.length < dataColumnSidecars.length + 1) {
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: I wonder if this is too strict, technically if there are supernodes in the network it should be sufficient to just publish >=64 columns as they have to reconstruct and re-gossip the missing columns

**Comment by twoeths** [comment]
> > with a regular node, we subscribed to only 8 columns:
> 
> shouldn't a node without validators attached just have to custody 4 groups/columns?
> 
> https://github.com/ChainSafe/lodestar/blob/aac4d9d86498d0368648522ea10cef3489ef46ea/packages/config/src/chainConfig/configs/mainnet.ts#L129-L130

with `SAMPLES_PER_SLOT=8` we should at least get these 8 DataColumnSidecars accordingly in order to say data is available
so we have to subscribe to 8 subnets at least

File: packages/beacon-node/src/network/gossip/topic.ts [hunk 2]
```diff
@@ -244,13 +244,15 @@ export function getCoreTopicsAtFork(
   // After fulu also track data_column_sidecar_{index}
   if (ForkSeq[fork] >= ForkSeq.fulu) {
     // TODO: @matthewkeil check if this needs to be updated for custody groups
```
Comment (nflaig) [inline packages/beacon-node/src/network/gossip/topic.ts]: can be removed

**Review by nflaig — COMMENTED** [review]
also need to handle the case if are custody requirement increases

https://github.com/ChainSafe/lodestar/blob/aac4d9d86498d0368648522ea10cef3489ef46ea/packages/beacon-node/src/chain/chain.ts#L1312

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: there is a tiny chance that we reach non-supernodes first before supernodes
also the `recover_matrix` is optional, a new client can join the network and don't implement that at all

I don't see the benefit of not sending to all columns, and block proposal is rarely happen
also as a block proposer, we want to make sure our block is not reorged because data is so slow to become available

Comment (nflaig) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: > I don't see the benefit of not sending to all columns

we should ideally do that just wondering if throwing an error here if it's <128 is good, could just error if it's <64

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts [hunk 3]
```diff
@@ -278,7 +278,25 @@ export function getBeaconBlockApi({
...
+        // should not happen
+        throw Error(
+          `Not enough sent peers per data column subnet, sentPeersArr.length=${sentPeersArr.length}, expected at least ${dataColumnSidecars.length + 1}`
+        );
+      }
+
+      for (let i = 0; i < dataColumnSidecars.length; i++) {
+        // + 1 because we publish to beacon_block first
+        const sentPeers = sentPeersArr[i + 1] as number;
+        metrics?.dataColumns.sentPeersPerSubnet.observe(sentPeers);
```
Comment (wemeetagain) [inline packages/beacon-node/src/api/impl/beacon/blocks/index.ts:291]: should we track this metric before the error?

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: it should always be an array with at least 129 items, first one for `beacon_block` and remaining ones for `DataColumnSidecars`
it's an issue if I hard coded it as 129 (or 128 + 1), here I only compared with `dataColumnSidecars.length + 1)` which should be fine. Notice that for each DataColumnSidecar we send to a topic at line 265 above

it should never reach this line

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 3 above)
Comment (twoeths) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts:291]: the error should never happen as commented

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 1 above)
Comment (matthewkeil) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: I think warn for less than 128 and error if less than 64

Comment (matthewkeil) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: ~~I'm not sure if `sentPeersArr` is tracking what we think it will so wanted to bring it up just in case.  There may be some peers we send multiple things to and there is no guarantee that the peer distribution (128 peer means all 128 were on different columns subnets) is accurately represented.~~

~~We may need to do something like~~

```
...dataColumnSidecars.map((dataColumnSidecar) => () => network.publishDataColumnSidecar(dataColumnSidecar).then(res => /* parse res for peer and track it relative to  dataColumnSidecar.index */))
```

~~so that we know which columns were sent to which peers and can be sure that each column was actually published.~~  Also, don't we get an error if there are no peers subscribed to a subnet that we publish to?  It could be that we do not have a peer for a given subnet, right?

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 3 above)
Comment (matthewkeil) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts:291]: Does the send promise error if there is not a peer subscribed to a column topic?

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 1 above)
Comment (wemeetagain) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: > don't we get an error if there are no peers subscribed to a subnet that we publish to? It could be that we do not have a peer for a given subnet, right?

Yeah, currently configured js-libp2p-gossipsub is to throw if there are no connected peers listening on a topic.

We should not rely on optional behavior here (reconstruction). Imo just kiss, error if we didn't publish to all.

Based on the current behavior, we can remove this conditional (which will never be executed anyways since the `promiseAllMaybeAsync` call will reject/throw when something is published w/o peers on that topic.)

Comment (twoeths) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts]: > Based on the current behavior, we can remove this conditional (which will never be executed anyways since the promiseAllMaybeAsync call will reject/throw when something is published w/o peers on that topic.)

agree, removing will avoid all the confusion. But this shows a concern that if there are 1/2 topics with 0 peers it'll throw but the overall publish is still a success because supernode will rebuild all columns and publish for us

I think we should allow publishing to 0 peers in this case in order to track this `sentPeersPerSubnet` metric

File: packages/beacon-node/src/api/impl/beacon/blocks/index.ts (hunk 3 above)
Comment (twoeths) [reply packages/beacon-node/src/api/impl/beacon/blocks/index.ts:291]: it depends on `allowPublishToZeroTopicPeers` option
in the last commit I set it to true so it'll not throw error and return 0 sent peer in that case

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.34.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.34.0) :tada:
