### PR TITLE
Process gossip block asap

### LINKED ISSUE #4789: Missed attestations due to delayed block process
**Describe the bug**

In the last 3 days, there are 3 missed attestations on mainnet nodes, all of them are due to delayed block process, block came early enough but got processed only after 4s, validator submitted wrong heads and no aggregator/block include them

- Slot 5175706: block is received 2.5s after slot but only became head after 4.4s => it took 1.9s to process

```
Nov-20 08:21:35.000[chain]         ^[[36mverbose^[[39m: Clock slot slot=5175706
Nov-20 08:21:38.263[network]       ^[[36mverbose^[[39m: Received gossip block slot=5175706, root=0xc7b3…8f0a, curentSlot=5175706, peerId=16Uiu2HAmAQLr32DoW9iBiNKdyLp4nCUGWvfCixZSs7eZra3GPk1C, delaySec=2.49399995803833
Nov-20 08:21:39.435[chain]         ^[[36mverbose^[[39m: New chain head headSlot=5175706, headRoot=0xc7b31a3bfa3c435f851e62b0a491489aa33ac05c344982e194889644a2df8f0a, delaySec=4.434999942779541
Nov-20 08:21:39.435[chain]         ^[[36mverbose^[[39m: Block processed slot=5175706, root=0xc7b31a3bfa3c435f851e62b0a491489aa33ac05c344982e194889644a2df8f0a, delaySec=4.434999942779541
```

- Slot 5176963: block was received 2s after the slot but became head only after 4.9s => it took 2.9s to process
```
Nov-20 12:32:59.000[chain]         ^[[36mverbose^[[39m: Clock slot slot=5176963
Nov-20 12:33:01.044[network]       ^[[36mverbose^[[39m: Received gossip block slot=5176963, root=0xa68b…7508, curentSlot=5176963, peerId=16Uiu2HAkuVTNVU2stE4sg71eE8mSs9TNEg126SQbyV9VhGoP68RK, delaySec=1.997999906539917
Nov-20 12:33:03.934[chain]         ^[[36mverbose^[[39m: New chain head headSlot=5176963, headRoot=0xa68bf57f9ec614fcca59c461e25ff5801b585acbe622a540482bf80e62537508, delaySec=4.934000015258789
Nov-20 12:33:03.934[chain]         ^[[36mverbose^[[39m: Block processed slot=5176963, root=0xa68bf57f9ec614fcca59c461e25ff5801b585acbe622a540482bf80e62537508, delaySec=4.934000015258789
```

- Slot 5177951: block was received 3.1s after the slot but became head only after 4.3s => it took 1.2s to process
```
Nov-20 15:50:38.317[network]       ^[[36mverbose^[[39m: Received gossip block slot=5177951, root=0xc6a1…71e5, curentSlot=5177951, peerId=16Uiu2HAkvafBgXW7xdhPk9VJqxAha8bUzA9kyh1AiLjkKB3bhfLo, delaySec=3.0920000076293945
Nov-20 15:50:39.320[chain]         ^[[36mverbose^[[39m: New chain head headSlot=5177951, headRoot=0xc6a161f431cf038c4fb60e67db537467bf32fcc9c8225c0e26ba5cd8f21d71e5, delaySec=4.319999933242798
Nov-20 15:50:39.321[chain]         ^[[36mverbose^[[39m: Block processed slot=5177951, root=0xc6a161f431cf038c4fb60e67db537467bf32fcc9c8225c0e26ba5cd8f21d71e5, delaySec=4.3210000991821
```

**Expected behavior**

Should take less delay time after we receive block to process, make sure all blocks are processed within 4s.

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

There are wrong head votes and missed attestations due to processing gossip blocks end in > 1/3 of slot. There are 2 reasons for it:
- There are some delays when we put block jobs in our queues (see Job Wait Time metrics in https://github.com/ChainSafe/lodestar/issues/4789#issuecomment-1336970334)
- `notifyNewPayload` engine api job time some times > 1s or 2s or even 5s => we can only track this time => see #4859

**Description**

- Add option to process job immediately if there is only 1 job at a time to reduce Job Wait Time
- Apply that to 3 queues: Block Gossip Validation queue, Block Processor queue, Execution Engine queue
- Add some more logs and metrics to track timing of each task when we process block since `seenTimestampSec`

Closes #4789

**Test result on feat1 mainnet node**

- Gossip Validation Job Wait Time >1s ratio

Screen Shot 2022-12-06 at 10 45 33

- Block Processor Job Wait Time >1s ratio

Screen Shot 2022-12-06 at 10 46 07

- Execution Engine Job wait time >1s ratio

Screen Shot 2022-12-06 at 10 46 37

- Block Process Time >1s ratio

Screen Shot 2022-12-06 at 10 44 50

### CODE REVIEW

File: packages/beacon-node/src/chain/blocks/verifyBlock.ts [hunk 1]
```diff
@@ -66,16 +66,30 @@ export async function verifyBlocksInEpoch(
   const abortController = new AbortController();
 
   try {
-    const [{postStates, proposerBalanceDeltas}, , segmentExecStatus] = await Promise.all([
+    const [segmentExecStatus, {postStates, proposerBalanceDeltas}] = await Promise.all([
+      // Execution payloads
+      verifyBlocksExecutionPayload(
+        {...this, metrics: this.metrics},
```
Comment (dapplion) [inline packages/beacon-node/src/chain/blocks/verifyBlock.ts]: Not sure if spreading `this` is a good idea, that's the entire BeaconChain object. Can you find a different pattern?

File: packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts [hunk 2]
```diff
@@ -236,6 +239,16 @@ export async function verifyBlocksExecutionPayload(
     }
   }
 
+  if (blocks.length === 1 && opts.seenTimestampSec !== undefined) {
+    const delaySec = chain.clock.secFromSlot(blocks[0].message.slot, opts.seenTimestampSec);
+    const recvToVerifiedExecPayload = chain.clock.secFromSlot(blocks[0].message.slot, Date.now() / 1000) - delaySec;
```
Comment (dapplion) [inline packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts]: Isn't this value equivalent to `const recvToVerifiedExecPayload = Date.now() / 1000 - opts.seenTimestampSec`? Same for `packages/beacon-node/src/chain/blocks/importBlock.ts:340` and others

File: packages/beacon-node/src/metrics/metrics/lodestar.ts [hunk 3]
```diff
@@ -609,6 +609,31 @@ export function createLodestarMetrics(
         help: "Time elapsed between block slot time and the time block processed",
         buckets: [0.5, 1, 2, 4, 6, 12],
       }),
+      receivedToGossipValidate: register.histogram({
+        name: "lodestar_gossip_block_received_to_gossip_validate",
+        help: "Time elapsed between block received and block validated",
+        buckets: [0.2, 0.5, 1, 1.5, 2, 4],
```
Comment (dapplion) [inline packages/beacon-node/src/metrics/metrics/lodestar.ts]: I would add more granularity in all buckets: `[0.05, 0.1, 0.2, 0.5, 1, 1.5, 2, 4]`

**Comment by dapplion** [comment]
Looks good! Just some minor comments

File: packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts (hunk 2 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts]: yeah that'd make it simpler 👍

File: packages/beacon-node/src/chain/blocks/verifyBlock.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/blocks/verifyBlock.ts]: I'd make `metrics` as public in `IBeaconChain`, similar to `logger`

**Review by wemeetagain — APPROVED** [review]
