### PR TITLE
Separate API implementation from REST server

### LINKED ISSUE #1497: Cannot read property 'headStateRoot' of undefined
**Describe the bug**
After updating, I'm seeing this error repeatedly while syncing.
```
2020-09-01 22:17:02  [API]             error: Request 512 failed with unexpected error:  Cannot read property 'headStateRoot' of undefined TypeError: Cannot read property 'headStateRoot' of undefined
    at resolveStateId (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/api/impl/beacon/state/utils.js:17:98)
    at BeaconStateApi.getState (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/api/impl/beacon/state/state.js:26:38)
    at Object.handler (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/api/rest/controllers/beacon/state/getStateFinalityCheckpoints.js:13:49)
    at preHandlerCallback (/home/seamonkey/Downloads/lodestar/node_modules/fastify/lib/handleRequest.js:117:30)
    at preValidationCallback (/home/seamonkey/Downloads/lodestar/node_modules/fastify/lib/handleRequest.js:103:5)
    at handler (/home/seamonkey/Downloads/lodestar/node_modules/fastify/lib/handleRequest.js:69:5)
    at handleRequest (/home/seamonkey/Downloads/lodestar/node_modules/fastify/lib/handleRequest.js:18:5)
    at onRunMiddlewares (/home/seamonkey/Downloads/lodestar/node_modules/fastify/lib/middleware.js:22:5)
    at middlewareCallback (/home/seamonkey/Downloads/lodestar/node_modules/fastify/lib/route.js:381:5)
    at next (/home/seamonkey/Downloads/lodestar/node_modules/fastify/lib/hooks.js:145:7)
```

**Expected behavior**
no errors

**Steps to Reproduce**
Run beacon node

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 20
 - Branch: Master
 - Commit hash: 78b3764349b12651ddfc0fb15ff537aea9231217

### PR DESCRIPTION
**Pull request by wemeetagain**
Separate API implementation from REST server.
BeaconNode now has `api` and `restApi`. `api` is the javascript implementation. `restApi` is the http server.

`RestApi` no longer has `start`/`stop`, instead has `init`/`close`.

Resolves #1497  by initializing the api and rest server after `await chain.start()`.

### CODE REVIEW

File: packages/lodestar/src/api/impl/api.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+export class Api implements IApi {
+  public beacon: IBeaconApi;
+  public node: INodeApi;
+  public validator: IValidatorApi;
+
+  public constructor(opts: Partial<IApiOptions>, modules: IApiModules) {
+    this.beacon = new BeaconApi({}, modules);
+    this.node = new NodeApi({}, modules);
+    this.validator = new ValidatorApi({}, modules);
```
Comment (mpetrunic) [inline packages/lodestar/src/api/impl/api.ts]: arent' you suppose to pass opts var instead of {}

Comment (wemeetagain) [reply packages/lodestar/src/api/impl/api.ts]: :+1: I'd copied what we had before, but you're right.

**Review by mpetrunic — APPROVED** [review]
