### PR TITLE
Persist temp states to not lose sync progress

### LINKED ISSUE #2048: Sudden crash cause synced progress lost
Testing mainnet in Digital Ocean the node suddenly crashed without any cause.

The node was synced to the head when the crash happened, and the node started syncing from many epochs behind indicating that sync progress was lost. What can cause this?

Screenshot from 2021-02-16 14-38-10

```
2021-02-16 02:04:29 [NETWORK]         debug: Req  request sent method=ping, encoding=ssz_snappy, peer=16Uiu2HAmEspe2SSFjyK9pum6wh2H4gU6bouFTRKoGva9SnQWBmvi, requestId=127810
2021-02-16 02:04:29 [NETWORK]       verbose: Received valid gossip aggregate and proof attestationSlot=551419, aggregatorIndex=55255, aggregateRoot=0xe0f2f4dca976ec5a17e39cf7c7d0b43b7aacbcfe76e94b371566f1d519b9f42a, attestationRoot=0xb2850050c7eef652bf7d602a899942232b05b57726109780a990d23848bee239, targetEpoch=17231
2021-02-16 02:04:29 [GOSSIP]        verbose: Received AggregateAndProof validator=55255, target=0x451b77e8bdcd07f14657a3ce29ed677c61611e3e07e0978241c1d7ff8a7e73c6
  <<< Crashed here >>>
2021-02-16 02:04:35 [DB]               info: Connected to LevelDB database name=/root/.local/share/lodestar/mainnet/chain-db
2021-02-16 02:04:44 []                 info: Initializing beacon state from db slot=524800, epoch=16400, stateRoot=0x10f35611f49959671cea4ecaf31d4e66afaa60762dbe5e463b1d64a545ff6d16
2021-02-16 02:04:44 [DB]               info: Connected to LevelDB database name=/root/.local/share/lodestar/mainnet/chain-db
2021-02-16 02:04:55 [API]              warn: Server listening at http://127.0.0.1:9596
2021-02-16 02:04:55 [API]              info: Started rest api server address=http://127.0.0.1:9596
2021-02-16 02:04:55 [METRICS]          info: Starting metrics HTTP server port=8008
2021-02-16 02:04:59 [GOSSIP]        verbose: Gossip is started
2021-02-16 02:04:59 [NETWORK]          info: PeerId 16Uiu2HAm8ysp1GJzop1D5L6XkBTdVnwcvnGwdN2iaGn8D1wFo2Kn, Multiaddrs /ip4/127.0.0.1/tcp/9000,/ip4/172.23.0.2/tcp/9000
2021-02-16 02:04:59 []                 warn: Low peer count peers=0
2021-02-16 02:04:59 []                 info: Searching for peers - peers: 0 - finalized: 16398 0x7e4a…e149 - head: 524800 0xb076…3ed4 - currentSlot: 551423
2021-02-16 02:05:05 []                 info: Searching for peers - peers: 0 - finalized: 16398 0x7e4a…e149 - head: 524800 0xb076…3ed4 - currentSlot: 551423
2021-02-16 02:05:17 []                 info: Searching for peers - peers: 0 - finalized: 16398 0x7e4a…e149 - head: 524800 0xb076…3ed4 - currentSlot: 551424
2021-02-16 02:05:25 [NETWORK]         debug: Dialing discovered peer peer=16Uiu2HAmMyUXQ2rfCwu4zpUNW9Ax6gkkn75K2GitnxAFnXvdCFgU
2021-02-16 02:05:25 [NETWORK]         debug: Dialing discovered peer peer=16Uiu2HAmKaba5hmtcqXcVPjFD6sUyqyQuQbygRCa6bRoT9M8KHX5
2021-02-16 02:05:25 [NETWORK]         debug: Dialing discovered peer peer=16Uiu2HAm2Pn9chFUBG3MbkFf6oK3Rf5GpVq1e7FvNnCeutfjVUfL
2021-02-16 02:05:25 [NETWORK]         debug: Dialing discovered peer peer=16Uiu2HAmNVLJ18CZsMJGFVhPpBhZgeL6rNiXQmyWtVy1FmWCQpkN
2021-02-16 02:05:25 [NETWORK]         debug: Dialing discovered peer peer=16Uiu2HAkzd9Fi5tLiCCf6CbuxNNzMDxACKG1EQY3u6vC6cHHmRNw
```

---

### Extra 

Most external memory gets wiped out on reset, memory leak still?

Screenshot from 2021-02-16 14-33-46

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

Currently, we store a state every 1024 epochs. At slow sync speeds of 4 slots / second, that's +2 hours of sync progress lost. Fixes https://github.com/ChainSafe/lodestar/issues/2048

Screenshot from 2021-03-09 10-24-59

**Proposed solution**

Store state more frequently, every 32 epochs. Then, after a successful store, keep only the first state every 1024 epochs and delete the rest. In normal conditions, only 0 or 1 states will be deleted. The resulting layout of store states will look like
```
    |         |       |    .
 x-1024*2  x-1024   x-32   x
```

### CODE REVIEW

File: packages/lodestar/src/tasks/tasks/archiveStates.ts [hunk 1]
```diff
@@ -2,53 +2,108 @@
...
+   * ```
+   */
+  async maybeArchiveState(finalized: phase0.Checkpoint): Promise<void> {
+    const lastStoredSlot = await this.db.stateArchive.lastKey();
+    const lastStoredEpoch = computeEpochAtSlot(this.config, lastStoredSlot || 0);
+
+    if (finalized.epoch - lastStoredEpoch > PERSIST_TEMP_STATE_EVERY_EPOCHS) {
+      await this.archiveState(finalized);
+
+      const storedEpochs = await this.db.stateArchive.keys({lt: finalized.epoch});
```
Comment (twoeths) [inline packages/lodestar/src/tasks/tasks/archiveStates.ts]: could we add a `gt` condition here? otherwise we keep checking `computeEpochsToDelete` from epoch 0.

Comment (dapplion) [reply packages/lodestar/src/tasks/tasks/archiveStates.ts]: Agree, tho what value would you think would be appropriate for `gt`?

Comment (twoeths) [reply packages/lodestar/src/tasks/tasks/archiveStates.ts]: I think `{gte: Math.floor(finalized.epoch/1024)}`, assuming all epochs less than that were checked by this same task previously

File: packages/lodestar/src/tasks/tasks/archiveStates.ts [hunk 2]
```diff
@@ -2,53 +2,108 @@
...
+  /**
+   * Persist states every some epochs to
+   * - Minimize disk space, storing the least states possible
+   * - Minimize the sync progress lost on unexpected crash, storing temp state every few epochs
+   *
+   * At epoch `x` there will be states peristed at intervals of `MIN_EPOCHS_PER_DB_STATE`
+   * and one at `MIN_EPOCHS_PER_DB_STATE / LATEST_STATE_FACTOR`
+   * ```
+   *    |         |       |    |
+   * x-1024*2  x-1024   x-32   x
```
Comment (3xtr4t3rr3str14l) [inline packages/lodestar/src/tasks/tasks/archiveStates.ts]: can you add a clarifying comment to say that what 1024 and 32 represent here (e.g. if they are MIN_EPOCHS_PER_DB_STATE=1024 and LATEST_STATE_FACTOR=32) since they may not be that values in the future (or maybe one or both of them will become cli configurable)?

File: packages/lodestar/src/tasks/tasks/archiveStates.ts [hunk 3]
```diff
@@ -2,53 +2,108 @@
...
-  public async run(): Promise<void> {
-    // store the state of finalized checkpoint
-    const stateCache = this.chain.checkpointStateCache.get(this.finalized);
+  /**
+   * Persist states every some epochs to
+   * - Minimize disk space, storing the least states possible
+   * - Minimize the sync progress lost on unexpected crash, storing temp state every few epochs
+   *
+   * At epoch `x` there will be states peristed at intervals of `MIN_EPOCHS_PER_DB_STATE`
+   * and one at `MIN_EPOCHS_PER_DB_STATE / LATEST_STATE_FACTOR`
```
Comment (3xtr4t3rr3str14l) [inline packages/lodestar/src/tasks/tasks/archiveStates.ts]: are these old names?  i notice you have PERSIST_STATE_EVERY_EPOCHS and PERSIST_TEMP_STATE_EVERY_EPOCHS elsewhere.

**Comment by dapplion** [comment]
Bump, until we fix all our memory issues the problem this PR mitigates is very annoying, in this case the node is spending 10% of the time re-syncing lost progress

Screenshot from 2021-03-16 13-47-48

**Review by wemeetagain — APPROVED** [review]
