### PR TITLE
fix: remove index label from validator_monitor_prev_epoch_on_chain_balance metric

### LINKED ISSUE #8740: High cardinality Prometheus metric
### Describe the bug

We are seeing high series cardinality from `validator_monitor_prev_epoch_on_chain_balance` because of the `index` label and no flag to disable per‑validator metric. This is generally an anti-pattern in Prometheus as it treats each label value as a new time series.

Code:
- metric registration: https://github.com/ChainSafe/lodestar/blob/b79f41e05427f9ce5f5371a93ad0a9f6b89d6f2b/packages/beacon-node/src/chain/validatorMonitor.ts#L1106-L1112
- metric set each epoch: https://github.com/ChainSafe/lodestar/blob/b79f41e05427f9ce5f5371a93ad0a9f6b89d6f2b/packages/beacon-node/src/chain/validatorMonitor.ts#L392-L395
- validator monitor created when metrics enabled: https://github.com/ChainSafe/lodestar/blob/b79f41e05427f9ce5f5371a93ad0a9f6b89d6f2b/packages/beacon-node/src/node/nodejs.ts#L188-L196

Request: have some way of limiting this cardinality / gate the registration of this metric.

In other clients, this has been solved via flags, where anything above some configurable threshold will return aggregates, not high cardinality metrics.

### Expected behavior

Metrics to be of manageable cardinality.

### Steps to reproduce

Running thousands of validators per client.

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.38.0

### PR DESCRIPTION
**Pull request by lodekeeper**
## Description

This PR fixes the high cardinality issue with the `validator_monitor_prev_epoch_on_chain_balance` metric by removing the `index` label.

### Changes

1. **Removed `index` label** from the metric definition
2. **Track total balance** instead of per-validator balances - the metric now reports the sum of balances of all monitored validators
3. **Updated dashboards** to divide by `validator_monitor_validators` count to maintain the same average balance visualization

### Why this approach?

As discussed in the issue, the `index` label was the only metric using per-validator labels, and it was not being used in dashboards (which always averaged). By tracking total balance instead:

- Cardinality is reduced from O(n) to O(1) where n = number of validators
- Average balance can still be computed: `total_balance / validator_count`
- Rate of change still works: `rate(total_balance) / validator_count`

Closes #8740

---

> [!NOTE]
> This PR was authored by Lodekeeper (AI assistant) under supervision of @nflaig.

### CODE REVIEW

**Comment by lodekeeper** [comment]
Good catch! Fixed in ea1f1c7 — now checking `if (balances)` instead of `if (totalBalance > 0)` to ensure we report the metric even when total balance is 0.

File: packages/beacon-node/src/chain/validatorMonitor.ts [hunk 1]
```diff
@@ -420,6 +423,11 @@ export function createValidatorMonitor(
           });
         }
       }
+
+      // Set total balance of all monitored validators
+      if (balances) {
```
Comment (nflaig) [inline packages/beacon-node/src/chain/validatorMonitor.ts]:
```suggestion
      if (balances !== undefined) {
```

**Comment by lodekeeper** [comment]
Thanks for the review! Updated to use explicit `balances !== undefined` check in 67aad49.

File: packages/beacon-node/src/chain/validatorMonitor.ts [hunk 2]
```diff
@@ -347,6 +347,9 @@ export function createValidatorMonitor(
         return;
       }
 
+      // Track total balance of all monitored validators to avoid high cardinality
```
Comment (nflaig) [inline packages/beacon-node/src/chain/validatorMonitor.ts]: this comment is vague, might not be clear that this refers to high cardinality in the metric, either keep the comment simpler or add the fact that you mean the metric here

**Comment by lodekeeper** [comment]
Updated the comment to be clearer: "Track total balance instead of per-validator balance to reduce metric cardinality" in 41bf437

File: packages/beacon-node/src/chain/validatorMonitor.ts [hunk 3]
```diff
@@ -420,6 +423,11 @@ export function createValidatorMonitor(
           });
         }
       }
+
+      // Set total balance of all monitored validators
```
Comment (nflaig) [inline packages/beacon-node/src/chain/validatorMonitor.ts]: this comment seem redundant, please remove it

**Comment by lodekeeper** [comment]
Removed the redundant comment in 97d0d31

**Review by nflaig — DISMISSED** [review]

File: packages/beacon-node/src/chain/validatorMonitor.ts (hunk 1 above)
Comment (lodekeeper) [reply packages/beacon-node/src/chain/validatorMonitor.ts]: Applied.

File: packages/beacon-node/src/chain/validatorMonitor.ts (hunk 2 above)
Comment (lodekeeper) [reply packages/beacon-node/src/chain/validatorMonitor.ts]: Updated to be more specific: 'Track total balance for prevEpochOnChainBalance metric instead of per-validator to avoid high cardinality'

File: packages/beacon-node/src/chain/validatorMonitor.ts (hunk 3 above)
Comment (lodekeeper) [reply packages/beacon-node/src/chain/validatorMonitor.ts]: Removed.

File: packages/beacon-node/src/chain/validatorMonitor.ts [hunk 4]
```diff
@@ -347,7 +347,7 @@ export function createValidatorMonitor(
         return;
       }
 
-      // Track total balance instead of per-validator balance to reduce metric cardinality
+      // Track total balance for prevEpochOnChainBalance metric instead of per-validator to avoid high cardinality
```
Comment (nflaig) [inline packages/beacon-node/src/chain/validatorMonitor.ts]: the previous comment was fine

Comment (lodekeeper) [reply packages/beacon-node/src/chain/validatorMonitor.ts]: Reverted to the simpler version.

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.40.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.40.0) :tada:
