### PR TITLE
Fix onBeaconBlocksByRoot

### LINKED ISSUE #728: Sync - BeaconBlockByRoot issue
Got this when trying to sync in `mpetrunic/regular-sync-v2` branch:

```
2020-03-23 14:56:40  [NETWORK]       verbose: send beacon_blocks_by_root request to 16Uiu2HAkyjwFDk7Qr6jo4J7dP9Pn7kDVB3KjvsGPnVai3q2m2Ryt
(node:17651) UnhandledPromiseRejectionWarning: Error: 
    at Timeout.setTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqResp.ts:188:51)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

### PR DESCRIPTION
**Pull request by twoeths**
## Goal
+ Close #728 
## Test
image

### CODE REVIEW

**Comment by twoeths** [comment]
Common failed unit tests like in #689

File: packages/lodestar/src/sync/reqResp/reqResp.ts [hunk 1]
```diff
@@ -166,10 +166,12 @@ export class SyncReqResp implements ISyncReqResp {
     request: BeaconBlocksByRootRequest
   ): Promise<void> {
     try {
-      const getBlock = this.db.block.get;
+      const getBlock = this.db.block.get.bind(this.db.block);
+      const getBlockArchieve = this.db.blockArchive.get.bind(this.db.blockArchive);
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/reqResp/reqResp.ts]:
```suggestion
      const getBlockArchive = this.db.blockArchive.get.bind(this.db.blockArchive);
```

**Review by mpetrunic — CHANGES_REQUESTED** [review]

**Comment by mpetrunic** [comment]
Oh man, awesome, you figured out why mocha is misbehaving. 

It was my error, I didn't clean after myself in clock tests, sorry :disappointed:
