### PR TITLE
fix: log errors setting agent version as debug

### LINKED ISSUE #6365: Error setting agentVersion for the peer
### Describe the bug

Reported by @nflaig in #6315 but is unrelated.  There is an issue with `metadata.get("AgentVersion") potentially or one of the other functions in https://github.com/ChainSafe/lodestar/blob/2eea2d60707a3bc5c150a7a0da261a8e7da079d1/packages/beacon-node/src/network/peers/peerManager.ts#L614-L619

### Expected behavior

Should not throw an error

### Steps to reproduce

_No response_

### Additional context

```
Jan-17 09:17:23.039[network]         error: Error setting agentVersion for the peer peerId=16Uiu2HAmKpgbkNA2AKYvt4qfdwFsSwuM7NwE8aMMHoMJiCBAxKAL - NotFound: 
Error: NotFound: 
```

### Operating system

Linux

### Lodestar version or commit hash

v1.14.0-rc.1

### PR DESCRIPTION
**Pull request by matthewkeil**
**Motivation**

Seeing an error when attempting to setAgent for a peer that is no longer in the peerStore

@wemeetagain @tuyennhv Do you think this error should be skipped because its just a result of peer churn and the info already being removed from the DB or do you think its worth making it a `debug` statement?

Resolves https://github.com/ChainSafe/lodestar/issues/6365

**Description**

Log errors setting agent version as debug

~~Add check for leveldb `NotFound` error and do not log as its an anticipated error.~~

~~**NOTE:** Double checking the leveldb code where this originates to see if there is a better way to filter for the error.  Will move to readyToReveiw once complete~~

### CODE REVIEW

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 1]
```diff
@@ -620,7 +620,10 @@ export class PeerManager {
       },
       {retries: 3, retryDelay: 1000}
     ).catch((err) => {
-      this.logger.error("Error setting agentVersion for the peer", {peerId: peerData.peerId.toString()}, err);
+      // Ignore Not Found error if peer was disconnected
+      if (err instanceof Error && !err.message.includes("NotFound")) {
+        this.logger.error("Error setting agentVersion for the peer", {peerId: peerData.peerId.toString()}, err);
```
Comment (twoeths) [inline packages/beacon-node/src/network/peers/peerManager.ts]: I think we only want to log with debug level here, and no need to check for "NotFound"

I think the cause is https://github.com/ChainSafe/lodestar/issues/6382

should work on that instead

File: packages/beacon-node/src/network/peers/peerManager.ts [hunk 2]
```diff
@@ -619,7 +619,12 @@ export class PeerManager {
...
       },
       {retries: 3, retryDelay: 1000}
-    ).catch((err) => {
+    ).catch((err: Error) => {
+      if (err.message.includes("NotFound")) {
+        return this.logger.debug("Peer not found when attempting to set agentVersion", {
+          peerId: peerData.peerId.toString(),
+        });
+      }
       this.logger.error("Error setting agentVersion for the peer", {peerId: peerData.peerId.toString()}, err);
```
Comment (nflaig) [inline packages/beacon-node/src/network/peers/peerManager.ts]: As I understood Tuyen and based on my own understanding of this error, we should move this log to debug. I honestly do not think we need to handle the NotFound error separately in this case, especially as it seems to be a more recent bug and might be resolved soon

```suggestion
    ).catch((err) => {
      this.logger.debug("Error setting agentVersion for the peer", {peerId: peerData.peerId.toString()}, err);
```

**Review by nflaig — APPROVED** [review]

**Review by twoeths — APPROVED** [review]

**Comment by twoeths** [comment]
there are so great benchmark statistics in this PR although there's nothing to do with it. I think at least we need to switch validator size to 1.5M instead of 250k for a lot of tests.

**Comment by matthewkeil** [comment]
> there are so great benchmark statistics in this PR although there's nothing to do with it. I think at least we need to switch validator size to 1.5M instead of 250k for a lot of tests.

LOL!!! Nope... that was me just having "the 🥷 touch" like you do @tuyennhv .... those are all REAL i tell you!! ARE EEE AYE ELLE REAL!!!!

OK maybe you are right....

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.16.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.16.0) :tada:
