### PR TITLE
fix: pass user credentials to events http client

### LINKED ISSUE #4521: API base url parsing does not work for eventstream
**Describe the bug**

If someone using a **base url** ending with `/` that make the `api.events.` namespace to not work. All other namespaces works fine. 

**Expected behavior**

It should work fine without any error by parsing the base url correctly. If not then it should throw some error to users to tell them base url format is not valid. 

**Steps to Reproduce**

```ts
import {getClient} from "@lodestar/api";

const api =  getClient({baseUrl: "http://127.0.0.1:5001/"});
```

**Desktop (please complete the following information):**

- Branch: [unstable]
- Commit hash: [e8232]

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Eventstream API does not work with rescue node at the moment because user credentials are removed from URL which is passed to events client.

https://github.com/ChainSafe/lodestar/blob/959a8af1b757c46a0e57450788fb72773a372608/packages/api/src/beacon/client/index.ts#L31

**Description**

Pass user credentials to events http client. The `EventSource` node implementation will parse the credentials, remove them from the URL and set them in Authorization header. The browser implementation does not support credentials via URL and headers are generally not supported (https://github.com/whatwg/html/issues/2177). We don't expect anyone to use the rescue node from browser, but it is possible to pass authentication tokens as part of cookies.

Closes https://github.com/ChainSafe/lodestar/issues/4521, this was previously already fixed by calling `new URL(...).origin` on the URL as it removed the extra `/` but I am now calling `urlJoin` which we also use in http client to join urls/paths.

### CODE REVIEW

File: packages/api/src/utils/client/httpClient.ts [hunk 1]
```diff
@@ -109,8 +109,7 @@ export class HttpClient implements IHttpClient {
   private readonly urlsScore: number[];
 
   get baseUrl(): string {
-    // Don't leak username/password to caller
```
Comment (nflaig) [inline packages/api/src/utils/client/httpClient.ts:112]: - addressed by https://github.com/ChainSafe/lodestar/pull/6175, the `baseUrl` is really only used by the events client which requires the username/password

File: packages/validator/src/services/chainHeaderTracker.ts [hunk 2]
```diff
@@ -31,8 +31,10 @@ export class ChainHeaderTracker {
   ) {}
 
   start(signal: AbortSignal): void {
-    void this.api.events.eventstream([EventType.head], signal, this.onHeadUpdate);
-    this.logger.verbose("Subscribed to head event");
+    this.logger.verbose("Subscribing to head event");
+    this.api.events
+      .eventstream([EventType.head], signal, this.onHeadUpdate)
+      .catch((e) => this.logger.error("Failed to subscribe to head event", {}, e));
```
Comment (nflaig) [inline packages/validator/src/services/chainHeaderTracker.ts:37]: Unrelated change but noticed that currently errors (400 and 500) result in an uncaught exception.

We are currently not throwing an error if server responds with 401 (or 404), might be something to consider in this PR but I think it's safer to retry in case those errors happen, see https://github.com/ChainSafe/lodestar/issues/4521#issuecomment-1851788363

Comment (jeluard) [reply packages/validator/src/services/chainHeaderTracker.ts:37]: Caller won't receive the exception anymore, so any code after the call to `start` will be executed now.
I understand from your comment that it's fine?

Comment (nflaig) [reply packages/validator/src/services/chainHeaderTracker.ts:37]: The caller never received the error as the promise was not handled (see `void` in previous implementation).

The `eventstream` method does not resolve until connection is aborted which effectively happens if you shut down the validator client
https://github.com/ChainSafe/lodestar/blob/959a8af1b757c46a0e57450788fb72773a372608/packages/api/src/beacon/client/events.ts#L48-L49

But there are cases where it rejects if server responds with 400 or 500 error
https://github.com/ChainSafe/lodestar/blob/959a8af1b757c46a0e57450788fb72773a372608/packages/api/src/beacon/client/events.ts#L36

Previously due to `void`, these errors would cause an uncaught exception while now the errors are caught and properly logged

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.13.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.13.0) :tada:
