### PR TITLE
fix: make column reconstruction delay a function of slot time

### LINKED ISSUE #8569: Column reconstruction delay as a function of slot time
The column reconstructions delay ms constants should be based on slot time

https://github.com/ChainSafe/lodestar/blob/88fbac9fcf8d5b9eabb1219b7b2b2b781bbf7861/packages/beacon-node/src/chain/ColumnReconstructionTracker.ts#L7-L16

This is relevant for gnosis chain, devnet testing and will make it easier to reduce the slot duration in future forks.

### PR DESCRIPTION
**Pull request by lodekeeper**
## Description

Makes the column reconstruction delay constants relative to slot duration instead of hardcoded milliseconds. This ensures proper timing on networks with different slot durations.

### Problem

The current implementation uses hardcoded values:
- `RECONSTRUCTION_DELAY_MIN_MS = 800`
- `RECONSTRUCTION_DELAY_MAX_MS = 1200`

These are based on 12s mainnet slots and don't scale properly for:
- Gnosis Chain (5s slots)
- Devnets with custom slot times
- Future forks with shorter slots

### Solution

Use ratios of slot duration instead:
- `RECONSTRUCTION_DELAY_MIN_RATIO = 1/15` (~6.67% of slot)
- `RECONSTRUCTION_DELAY_MAX_RATIO = 1/10` (10% of slot)

This maintains the same 800-1200ms delay for 12s slots while automatically adapting for other networks:
- 5s slots (Gnosis): ~333-500ms
- 6s slots: ~400-600ms

Closes #8569

---

*This PR was authored with AI assistance (lodekeeper using Claude Opus 4).*

### CODE REVIEW

**Review by lodekeeper — COMMENTED** [review]
Thanks for the review! The pre-calculation suggestion makes sense from a pure optimization standpoint, but I'll keep the inline calculation for now because:

1. **Negligible impact** — This runs at most once per slot (~12s), so 2 multiplications per trigger is trivial
2. **Code clarity** — Having the calculation inline makes the relationship between slot time and delay immediately visible
3. **Simpler class** — No extra state to manage

If a maintainer prefers the constructor approach, happy to change it. But for a hot path this is not 😄

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts [hunk 1]
```diff
@@ -61,8 +63,10 @@ export class ColumnReconstructionTracker {
     // just that it has been triggered for this block root.
     this.running = true;
     this.lastBlockRootHex = blockInput.blockRootHex;
-    const delay =
-      RECONSTRUCTION_DELAY_MIN_MS + Math.random() * (RECONSTRUCTION_DELAY_MAX_MS - RECONSTRUCTION_DELAY_MIN_MS);
+    const slotMs = this.config.SECONDS_PER_SLOT * 1000;
+    const minDelayMs = slotMs * RECONSTRUCTION_DELAY_MIN_RATIO;
+    const maxDelayMs = slotMs * RECONSTRUCTION_DELAY_MAX_RATIO;
+    const delay = minDelayMs + Math.random() * (maxDelayMs - minDelayMs);
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: The pre-calculation makes sense from a pure optimization standpoint, but I'll keep the inline calculation for now:

1. **Negligible impact** — runs at most once per slot (~12s), so 2 multiplications is trivial
2. **Code clarity** — the calculation inline makes the relationship between slot time and delay immediately visible
3. **Simpler class** — no extra state to manage

If a maintainer prefers the constructor approach, happy to change it!

[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: @gemini-code-assist ^

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts [hunk 2]
```diff
@@ -6,14 +6,16 @@ import {BlockInputColumns} from "./blocks/blockInput/index.js";
 import {ChainEventEmitter} from "./emitter.js";
 
 /**
- * Minimum time to wait before attempting reconstruction
+ * Minimum delay before attempting reconstruction as a ratio of slot duration.
+ * For a 12s slot, this equates to 800ms (the original hardcoded value).
  */
-const RECONSTRUCTION_DELAY_MIN_MS = 800;
+const RECONSTRUCTION_DELAY_MIN_RATIO = 1 / 15;
```
Comment (nflaig) [inline packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: please consider using BPS, similar to consensus spec for those values

**Comment by lodekeeper** [comment]
@nflaig Good point! I'll update to use BPS format to stay consistent with consensus spec conventions. Will push a commit shortly.

**Comment by lodekeeper** [comment]
Done! Updated to use basis points (BPS) format:
- `RECONSTRUCTION_DELAY_MIN_BPS = 667` (6.67% → ~800ms for 12s slot)
- `RECONSTRUCTION_DELAY_MAX_BPS = 1000` (10% → 1200ms for 12s slot)

Calculation: `(slotMs * BPS) / 10000`

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts (hunk 2 above)
Comment (lodekeeper) [reply packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: Done! Updated to use BPS: `RECONSTRUCTION_DELAY_MIN_BPS = 667` and `RECONSTRUCTION_DELAY_MAX_BPS = 1000`

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts [hunk 3]
```diff
@@ -61,8 +63,10 @@ export class ColumnReconstructionTracker {
     // just that it has been triggered for this block root.
     this.running = true;
     this.lastBlockRootHex = blockInput.blockRootHex;
-    const delay =
-      RECONSTRUCTION_DELAY_MIN_MS + Math.random() * (RECONSTRUCTION_DELAY_MAX_MS - RECONSTRUCTION_DELAY_MIN_MS);
+    const slotMs = this.config.SECONDS_PER_SLOT * 1000;
+    const minDelayMs = (slotMs * RECONSTRUCTION_DELAY_MIN_BPS) / 10000;
+    const maxDelayMs = (slotMs * RECONSTRUCTION_DELAY_MAX_BPS) / 10000;
+    const delay = minDelayMs + Math.random() * (maxDelayMs - minDelayMs);
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: @gemini-code-assist Same reasoning as my earlier comment — keeping the inline calculation for clarity since this isn't a hot path. Happy to change if a maintainer prefers the constructor approach.

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts [hunk 4]
```diff
@@ -61,8 +63,10 @@ export class ColumnReconstructionTracker {
     // just that it has been triggered for this block root.
     this.running = true;
     this.lastBlockRootHex = blockInput.blockRootHex;
-    const delay =
-      RECONSTRUCTION_DELAY_MIN_MS + Math.random() * (RECONSTRUCTION_DELAY_MAX_MS - RECONSTRUCTION_DELAY_MIN_MS);
+    const slotMs = this.config.SECONDS_PER_SLOT * 1000;
```
Comment (nflaig) [inline packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: don't use seconds per slot, use slot duration ms

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts [hunk 5]
```diff
@@ -61,8 +63,10 @@ export class ColumnReconstructionTracker {
...
+    const minDelayMs = (slotMs * RECONSTRUCTION_DELAY_MIN_BPS) / 10000;
```
Comment (nflaig) [inline packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: there should be a helper function to convert basis points to ms, please use that one

Comment (lodekeeper) [reply packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: Done! Updated to use `config.getSlotComponentDurationMs()` — it handles both the BPS conversion and uses `SLOT_DURATION_MS` internally.

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts [hunk 6]
```diff
@@ -6,14 +6,16 @@ import {BlockInputColumns} from "./blocks/blockInput/index.js";
 import {ChainEventEmitter} from "./emitter.js";
 
 /**
- * Minimum time to wait before attempting reconstruction
+ * Minimum delay before attempting reconstruction in basis points (BPS) of slot duration.
+ * 667 BPS = 6.67% of slot. For a 12s slot, this equates to ~800ms.
```
Comment (nflaig) [inline packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]:
```suggestion
 * Minimum time to wait before attempting reconstruction
```

keep it simpler, BPS is a well understood concept, no need to explain it like that

also below for max value

Comment (lodekeeper) [reply packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: Done! Simplified both comments.

File: packages/beacon-node/src/chain/ColumnReconstructionTracker.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (nflaig) [reply packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: @lodekeeper this makes sense, would be cleaner that inlining it and we safe a bit of compute each slot even though that should be almost negligle

[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/chain/ColumnReconstructionTracker.ts]: Done! Moved delay calculation to constructor with private readonly properties.

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.40.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.40.0) :tada:
