### PR TITLE
fix: track rate limited errors

### LINKED ISSUE #8065: Cannot track rate limited error
### Describe the bug

on the log it appears a lot
```
grep -e "rate limited" -rn beacon-2025-07-17.log | wc -l
12734
```
but on Grafana dashboard it shows almost nothing
Image

### Expected behavior

should be able to catch rate limit errors and sync that with metrics

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

unstable

### LINKED ISSUE #8110: Reqresp not parsing error message properly
Error messages (from response chunks with non-zero response code) are snappy-framed. It appears that we're not unwrapping the snappy frame and so not able to properly parse the error message.

```
2025-08-04 14:30:03.132    Aug-04 18:30:03.131[network]    verbose: Req  error method=ping, version=1, encoding=ssz_snappy, client=Lodestar, peer=16...kQN4LG, requestId=206976, status=2, errorMessage=sNaPpY,jTimeout 
```
```
2025-07-31 00:29:07.702    Jul-31 04:29:07.702[network]    verbose: Req  error method=ping, version=1, encoding=ssz_snappy, client=NA, peer=16...MLYa4P, requestId=289880, status=139, errorMessage=sNaPpYf2qWait 2.816488536s
```
(Search logs for `sNaPpY`)

See https://github.com/ethereum/consensus-specs/blob/master/specs/phase0/p2p-interface.md#responding-side

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- when we end request to peers, they may respond with rate limit error and we don't track it
- this is a prerequisite for rate limit prevention that I'll implement later. We want to make sure `REQUEST_RATE_LIMITED` does not happen in that branch

**Description**

- fix the malformed extracted error message, see the unit test
- throw `REQUEST_RATE_LIMITED` if message contains "rate limit", see rate limited error messages of all clients [here](https://github.com/ChainSafe/lodestar/issues/8065#issuecomment-3157266196)
- new metric to track out going error by reason

Closes #8065
Closes #8110

**Test on dev nodes**

Screenshot 2025-08-06 at 15 52 46

### CODE REVIEW

**Comment by twoeths** [comment]
new rate limited error messages with this branch:
- Prysm: `verbose: Req  error method=beacon_blocks_by_range, version=2, encoding=ssz_snappy, client=Prysm, peer=16...iQxcdU, requestId=96163, status=1, errorMessage=rate limited`
- Lighthouse: `verbose: Req  error method=beacon_blocks_by_range, version=2, encoding=ssz_snappy, client=Lighthouse, peer=16...xwThs6, requestId=75188, status=139, errorMessage=Rate limited. There are already 2 active requests with the same protocol`
- NA: `verbose: Req  error method=data_column_sidecars_by_range, version=1, encoding=ssz_snappy, client=NA, peer=16...evfBuU, requestId=74333, status=1, errorMessage=rate limited`

File: packages/reqresp/src/request/errors.ts [hunk 1]
```diff
@@ -73,6 +73,13 @@ export class RequestError extends LodestarError<RequestErrorType> {
  */
 export function responseStatusErrorToRequestError(e: ResponseError): RequestErrorType {
   const {errorMessage, status} = e;
+  // rate limited error from clients have different status, for example: lighthouse responds with 139, teku responds with 1
+  // but all of them has "rate limit" in the error message
+  // refer to https://github.com/ChainSafe/lodestar/issues/8065#issuecomment-3157266196
+  if (errorMessage.toLowerCase().includes("rate limit")) {
```
Comment (wemeetagain) [inline packages/reqresp/src/request/errors.ts]: There's also messages that look like "Wait 2.816488536s", code 139, (See the second log here - https://github.com/ChainSafe/lodestar/issues/8110)

File: packages/beacon-node/src/network/reqresp/score.ts [hunk 2]
```diff
@@ -63,5 +63,6 @@ export function onOutgoingReqRespError(e: RequestError, method: ReqRespMethod):
     }
   }
 
+  // other errors like RequestErrorCode.REQUEST_RATE_LIMITED could come from ourself, not the peer so we should not penalize them
```
Comment (matthewkeil) [inline packages/beacon-node/src/network/reqresp/score.ts]: I'm confused about this.  Wouldnt an outgoing request that we "rate limit" mean that we are not making the request.  How would the error "come from ourself"?

Comment (twoeths) [reply packages/beacon-node/src/network/reqresp/score.ts]: per spec we should not send more than 2 requests per protocol to the same peer
in the future we should implement that at client side, ie do not send more requests to the same peer/protocol
then we can avoid that error

File: packages/reqresp/src/request/errors.ts (hunk 1 above)
Comment (twoeths) [reply packages/reqresp/src/request/errors.ts]: yeah I do see this errorMessage from Grandine, was able to parse it using this branch: `Req  error method=status, version=2, encoding=ssz_snappy, client=Grandine, peer=16...gjzNA8, requestId=251194, status=139, errorMessage=Wait 1.094802952s`

will map it to `RATE_LIMITED` error

File: packages/reqresp/src/request/errors.ts [hunk 3]
```diff
@@ -73,6 +75,19 @@ export class RequestError extends LodestarError<RequestErrorType> {
...
+  if (errorMessageLowercase.includes("rate limit")) {
+    return {code: RequestErrorCode.RESP_RATE_LIMITED};
+  }
+
+  // Grandine may return this without standard RespStatus, see https://github.com/ChainSafe/lodestar/issues/8110
+  if (errorMessageLowercase.includes("wait ")) {
+    return {code: RequestErrorCode.RESP_TIMEOUT};
+  }
+
   switch (status) {
```
Comment (wemeetagain) [inline packages/reqresp/src/request/errors.ts:91]: Can we also add a RespStatus.RATE_LIMITED (which == 139) and check in this switch?
This will help in case error messages in clients change.

File: packages/beacon-node/src/network/reqresp/score.ts (hunk 2 above)
Comment (matthewkeil) [reply packages/beacon-node/src/network/reqresp/score.ts]: ahh... as in we throw `RequestErrorCode.REQUEST_RATE_LIMITED` from the client instead of just not making the request?

File: packages/reqresp/test/unit/utils/errorMessage.test.ts [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+      errorMessage: "rate limited",
+    },
+    {
+      name: "Teku - rate limited",
+      errorMessage: "Peer has been rate limited",
+    },
+    {
+      name: "NA - rate limited",
+      errorMessage: "rate limited",
+    },
```
Comment (matthewkeil) [inline packages/reqresp/test/unit/utils/errorMessage.test.ts:24]: Do you think we should add a test case for the "wait #.###" condition?

File: packages/reqresp/src/request/errors.ts (hunk 3 above)
Comment (twoeths) [reply packages/reqresp/src/request/errors.ts:91]: rate limited error is not specified in the response code https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#responding-side

lighthouse returned 139 but other clients returned 1

I don't think we can improve unless it's specified in the spec

File: packages/beacon-node/src/network/reqresp/score.ts (hunk 2 above)
Comment (twoeths) [reply packages/beacon-node/src/network/reqresp/score.ts]: right now it'll throw `RESP_RATE_LIMITED`, ie we makes a request and peer returns that error. We don't have self rate limiter yet, the strategy for now is to control at the client side, ie in SyncChain (I have a local branch for it, will create a PR soon but want some more testings)

I'll also implement self rate limiter soon, in that case it'll throw `REQUEST_RATE_LIMITED`. Then we'll track this error and see which module needs to control active requests like in SyncChain

File: packages/reqresp/test/unit/utils/errorMessage.test.ts (hunk 4 above)
Comment (twoeths) [reply packages/reqresp/test/unit/utils/errorMessage.test.ts:24]: I added more test cases in https://github.com/ChainSafe/lodestar/pull/8116/commits/7624a603176dcade759b927f94cf44193fc89e7c

**Review by wemeetagain — APPROVED** [review]

**Comment by nflaig** [comment]
seems like since we merged this PR our [unit tests are failing](https://github.com/ChainSafe/lodestar/actions/runs/16838970640/job/47705659688#step:5:3142) consistently

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.34.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.34.0) :tada:
