### PR TITLE
Use createValidatorFlat instead of createFlat

### LINKED ISSUE #2325: Investigate createFlat() function
**Describe the bug**

The createFlat was implemented in a generic way
```ts
export function createFlat<T = ObjectLike>(value: T): T {
  const flat = {} as Record<string, T[keyof T]>;
  for (const [k, v] of readonlyEntries(value)) {
    // eslint-disable-next-line @typescript-eslint/ban-types
    flat[k as string] = ((v as unknown) as object).valueOf() as T[keyof T];
  }
  return (flat as unknown) as T;
}
```

but I found it's much better (in term of performance) if we use this

```ts
export function createValidatorFlat(v: Validator): Validator {
  return {
    pubkey: v.pubkey.valueOf() as BLSPubkey,
    withdrawalCredentials: v.withdrawalCredentials.valueOf() as Bytes32,
    effectiveBalance: v.effectiveBalance,
    slashed: v.slashed,
    activationEligibilityEpoch: v.activationEligibilityEpoch,
    activationEpoch: v.activationEpoch,
    exitEpoch: v.exitEpoch,
    withdrawableEpoch: v.withdrawableEpoch,
  };
}
```

here's the performance test

```ts
it.only("Array[createFlat] vs Array[createValidatorFlat", () => {
    const numValidators = 114038;
    const numKeyPairs = 100;
    const secretKeys = interopSecretKeys(numKeyPairs);
    const validators = Array.from({length: numValidators}, (_, i) => {
      return config.types.phase0.Validator.createTreeBackedFromStruct ({
        pubkey: secretKeys[i % numKeyPairs].toPublicKey().toBytes(),
        withdrawalCredentials: Buffer.alloc(32, i),
        effectiveBalance: BigInt(31000000000),
        slashed: false,
        activationEligibilityEpoch: 0,
        activationEpoch: 0,
        exitEpoch: Infinity,
        withdrawableEpoch: Infinity,
      });
    });
    const flatValidators = validators.map((v) => createFlat(v));
    const flatValidators2 = validators.map((v) => createValidatorFlat(v));
    expect(flatValidators).to.be.deep.equal(flatValidators2);
    let start = Date.now();
    for (let i = 0; i < 16; i++) {
      flatValidators.map((v) => v.exitEpoch);
    }
    console.log("@@@ map using createFlat in ", Date.now() - start);
    start = Date.now();
    for (let i = 0; i < 16; i++) {
      flatValidators2.map((v) => v.exitEpoch);
    }
    console.log("@@@ map using createValidatorFlat in ", Date.now() - start);
  });
```

the result is
```
@@@ map using createFlat in  242
@@@ map using createValidatorFlat in  77
```

**Expected behavior**

The performance of the 2 functions should be the same.
part of #2322, this simulate processing 16 validator exits per block.

**Steps to Reproduce**

Run the above test.

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Due to #2331 , all flow looping through `state.validators` and access validator properties takes so much time (>= 3x) like `processValidatorExit`, `getEffectiveBalances` ...

**Description**

Drop the generic version `createFlat` in favor of `createValidatorFlat`.

Closes #2325

### CODE REVIEW

**Review by dapplion — DISMISSED** [review]

File: packages/beacon-state-transition/src/fast/util/flat.ts [hunk 1]
```diff
@@ -1,13 +1,16 @@
-import {ObjectLike, readonlyEntries} from "@chainsafe/ssz";
+import {BLSPubkey, Bytes32, Validator} from "@chainsafe/lodestar-types/phase0";
```
Comment (wemeetagain) [inline packages/beacon-state-transition/src/fast/util/flat.ts]: Can you import `phase0` and use it?
eg: `import {..., phase0} from "@chainsafe/lodestar-types";`

File: packages/beacon-state-transition/src/fast/util/cachedValidatorList.ts [hunk 2]
```diff
@@ -13,11 +12,18 @@ export class CachedValidatorList<T extends phase0.Validator> implements List<T>
...
   type: CompositeListType<List<T>>;
   persistent: MutableVector<T>;
+  createFlat: (t: TreeBacked<T>) => T;
 
-  constructor(type: CompositeListType<List<T>>, tree: Tree, persistent: MutableVector<T>) {
+  constructor(
+    type: CompositeListType<List<T>>,
+    tree: Tree,
+    persistent: MutableVector<T>,
+    createFlat: (t: TreeBacked<T>) => T
```
Comment (wemeetagain) [inline packages/beacon-state-transition/src/fast/util/cachedValidatorList.ts]: I don't think we need this to be passed in, just use `createValidatorFlat` directly.

**Review by wemeetagain — CHANGES_REQUESTED** [review]

**Review by wemeetagain — APPROVED** [review]
