### PR TITLE
fix: use CheckpointBalancesCache to help update cgc

### LINKED ISSUE #8136: Enhance effective balance cache
- we have an effective balance cache that was built in https://github.com/ChainSafe/lodestar/pull/4290
- we just merged https://github.com/ChainSafe/lodestar/pull/8105 which fetches effective balances from the finalized state
- we can enhance the cache to store the finalized effective balances and then use it for the purposes of #8105

### PR DESCRIPTION
**Pull request by wemeetagain**
**Motivation**

- Resolve https://github.com/ChainSafe/lodestar/issues/8136

**Description**

- use `CheckpointBalancesCache` to help update cgc. This prevents the much more expensive state lookup.
- In extremely forky scenarios, the finalized balances won't be found in the cache. In that case, use the strategy from before (fetch state from disk, parse out the effective balances)
- If neither case works don't throw, rather return. This allows the rest of the important onForkChoiceFinalized work to continue

### CODE REVIEW

File: packages/beacon-node/src/chain/chain.ts [hunk 1]
```diff
@@ -1233,23 +1233,38 @@ export class BeaconChain implements IBeaconChain {
...
+          finalizedEpoch: finalizedCheckpoint.epoch,
+          finalizedRoot: finalizedCheckpoint.rootHex,
+        });
+        return;
+      }
+
+      if (stateOrBytes instanceof Uint8Array) {
+        effectiveBalances = getEffectiveBalancesFromStateBytes(this.config, stateOrBytes, validatorIndices);
+      } else {
+        effectiveBalances = validatorIndices.map((index) => stateOrBytes.validators.get(index).effectiveBalance ?? 0);
```
Comment (nflaig) [inline packages/beacon-node/src/chain/chain.ts:1266]: why is that needed?

```suggestion
        effectiveBalances = validatorIndices.map((index) => stateOrBytes.validators.get(index).effectiveBalance);
```

File: packages/beacon-node/src/chain/chain.ts [hunk 2]
```diff
@@ -1233,23 +1233,38 @@ export class BeaconChain implements IBeaconChain {
...
+      // If there's no cached effective balances, get the state from disk and parse them out
+      this.logger.debug("No cached finalized effective balances to update target custody group count", {
+        finalizedEpoch: finalizedCheckpoint.epoch,
+        finalizedRoot: finalizedCheckpoint.rootHex,
+      });
+
+      const stateOrBytes = (await this.getStateOrBytesByCheckpoint(finalizedCheckpoint))?.state;
+      if (!stateOrBytes) {
+        // If even the state is not available, we cannot update the custody group count
+        this.logger.debug("No finalized state or bytes available to update target custody group count", {
```
Comment (nflaig) [inline packages/beacon-node/src/chain/chain.ts:1256]: I think this should never happen, maybe @twoeths can confirm, there might be some edge case. In any case logging to debug is ok I'd assume as updating cgc isn't really time sensitive

Comment (wemeetagain) [reply packages/beacon-node/src/chain/chain.ts:1256]: it should never happen, but for type-safety its there

Comment (nflaig) [reply packages/beacon-node/src/chain/chain.ts:1256]: yeah that's why I was just throwing but need to be sure it actually can't happen, your approach is safer

File: packages/beacon-node/src/chain/chain.ts (hunk 1 above)
Comment (wemeetagain) [reply packages/beacon-node/src/chain/chain.ts:1266]: Short answer: type safety. Didn't look too deeply into how we're selecting attached validators, but if they've recently been inducted and aren't in the finalized state, then there would be a problem. In any case, its a small thing to avoid a potential NaN.

**Review by nflaig — APPROVED** [review]

**Review by twoeths — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.34.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.34.0) :tada:
