### PR TITLE
fix: ignore already known errors in API

### LINKED ISSUE #6021: Ignore known attestations submitted through API
I think we should implement `ignoreIfKnown` flag, it's to be `true` for api validation but `false` for gossip validation https://github.com/ChainSafe/lodestar/blob/325734518cf024869fb8a7d33cb75b665438a83b/packages/beacon-node/src/chain/validation/attestation.ts#L79

even when we use Lodestar as the primary node, submitted attestations can reach our node by gossip before the api since `vc` can published to fallback node already

_Originally posted by @tuyennhv in https://github.com/ChainSafe/lodestar/issues/5323#issuecomment-1646771999_

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Attestations might already be published by another node as part of a fallback setup or DVT cluster
and can reach our node by gossip before the api. The error can be ignored and should not result in a 500 response.

There are also other errors related to that like known aggregates which should be ignored as well (see previous PR https://github.com/ChainSafe/lodestar/pull/2598)

**Description**

Ignore already known (`_ALREADY_KNOWN`) errors in API and return 200 response.

Closes https://github.com/ChainSafe/lodestar/issues/6021

### CODE REVIEW

File: packages/beacon-node/src/api/impl/validator/index.ts [hunk 1]
```diff
@@ -1128,15 +1132,21 @@ export function getValidatorApi({
...
+            const logCtx = {
+              slot: contributionAndProof.message.contribution.slot,
+              subcommitteeIndex: contributionAndProof.message.contribution.subcommitteeIndex,
+            };
+
+            if (
+              e instanceof SyncCommitteeError &&
+              e.type.code === SyncCommitteeErrorCode.SYNC_COMMITTEE_AGGREGATOR_ALREADY_KNOWN
+            ) {
+              logger.debug("Ignoring known contributionAndProof", logCtx);
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/validator/index.ts:1144]: This error was already ignored previously (added in https://github.com/ChainSafe/lodestar/pull/2598) but it got removed again by https://github.com/ChainSafe/lodestar/pull/2816 as the PR changed the error behavior.

In https://github.com/ChainSafe/lodestar/pull/4019 it was introduced again that the error is thrown during validation but the handling on the API was not re-added.

The error was recently observed (https://github.com/ChainSafe/lodestar/issues/6021#issuecomment-1766438390)  and should be ignored again.

File: packages/beacon-node/src/api/impl/beacon/pool/index.ts [hunk 2]
```diff
@@ -224,7 +234,7 @@ export function getBeaconPoolApi({
       );
 
       if (errors.length > 1) {
-        throw Error("Multiple errors on publishAggregateAndProofs\n" + errors.map((e) => e.message).join("\n"));
+        throw Error("Multiple errors on submitPoolSyncCommitteeSignatures\n" + errors.map((e) => e.message).join("\n"));
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/pool/index.ts:237]: This just fixes a typo but it is worth highlighting that we don't need to handle already known errors in submitPoolSyncCommitteeSignatures as the api only verifies the signature
https://github.com/ChainSafe/lodestar/blob/d7ca290d173dfa82b2977f3e94df6e5e8d12ef3e/packages/beacon-node/src/api/impl/beacon/pool/index.ts#L184-L186

**Review by nflaig — COMMENTED** [review]
I have tested this PR by running multiple Lodestar nodes and configured Teku VC to publish to all of them.  The error can be easily reproduced by adding an artifical delay to the api as attestations will frequently reach the node by gossip before the api.

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.15.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.15.0) :tada:
