### PR TITLE
Fix processChainSegment

### LINKED ISSUE #1993: Could not start initial sync
this is what I get from the log when I try to sync Pyrmont
```
node --inspect lib/index.js beacon --network pyrmont --root-dir .pyrmont.master > .pyrmont.master.log
```

```
2021-01-26 13:34:52 [DB]               info: Connected to LevelDB database name=.pyrmont.master/chain-db
2021-01-26 13:35:03 []                 info: Initializing beacon state slot=0, epoch=0, stateRoot=0x2bb257ca66d05a047a65fe43a5f457b674de445d917cca029efb09b3ba4758c4
2021-01-26 13:35:04 [DB]               info: Connected to LevelDB database name=.pyrmont.master/chain-db
2021-01-26 13:35:14 [API]              warn: Server listening at http://127.0.0.1:9596
2021-01-26 13:35:14 [API]              info: Started rest api server address=http://127.0.0.1:9596
2021-01-26 13:35:14 [METRICS]          info: Starting metrics HTTP server port=8008
2021-01-26 13:35:14 [NETWORK]          info: PeerId 16Uiu2HAm8ajN7N8AZi4K5AvE2agpS4yCsQJwGrzvcjfGtyCx1HxX, Multiaddrs /ip4/127.0.0.1/tcp/9000,/ip4/172.16.217.23/tcp/9000
2021-01-26 13:35:14 [SYNC]             info: Waiting for minPeers: 0/3
2021-01-26 13:35:14 [SYNC]             info: Waiting for minPeers: 0/3
```

### PR DESCRIPTION
**Pull request by twoeths**
fix #1993

### CODE REVIEW

File: packages/lodestar/src/chain/blocks/process.ts [hunk 1]
```diff
@@ -117,8 +117,8 @@ export async function processChainSegment({
     // Split off the first section blocks that are all either within the current epoch of
     // the first block. These blocks can all be signature-verified with the same
     // `BeaconState`.
-    const blocksInEpoch = blocks.slice(0, lastIndex);
```
Comment (twoeths) [inline packages/lodestar/src/chain/blocks/process.ts:120]: 2nd param of `slice` is exclusive so we should use `lastIndex + 1`

**Comment by twoeths** [comment]
I can see some sync progress in my logs like
```
2021-01-26 14:29:24 [SYNC]             info: Sync progress 140/15480 - 17 hours left - 8.11 slots/s
```

**Review by dapplion — APPROVED** [review]
