### PR TITLE
Validate SyncCommitteeSignatureSet

### LINKED ISSUE #2610: Add SyncCommittee signature set in all block sigs
**Describe the bug**

We do not include the SyncCommittee signature in this all blocks sig bundle

https://github.com/ChainSafe/lodestar/blob/13bb12031c31a2fe2d1af9b5ff9c7436e914e5e7/packages/beacon-state-transition/src/allForks/signatureSets/index.ts#L33-L43

**Expected behavior**

We must verify all signatures in a block

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

See https://github.com/ChainSafe/lodestar/issues/2610

**Description**

Closes https://github.com/ChainSafe/lodestar/issues/2610

### CODE REVIEW

**Review by twoeths — APPROVED** [review]

File: packages/beacon-state-transition/src/altair/block/processSyncCommittee.ts [hunk 1]
```diff
@@ -1,59 +1,86 @@
...
+
+export function getSyncCommitteeSignatureSet(
+  state: CachedBeaconState<altair.BeaconState>,
+  syncAggregate: altair.SyncAggregate,
+  /** Optional parameter to prevent computing it twice */
+  participantIndices?: number[]
+): ISignatureSet | null {
+  const {config, epochCtx} = state;
+
+  const previousSlot = Math.max(state.slot, 1) - 1;
```
Comment (twoeths) [inline packages/beacon-state-transition/src/altair/block/processSyncCommittee.ts:48]: @dapplion previousSlot should be from `Math.max(block.slot, 1) - 1`

Comment (dapplion) [reply packages/beacon-state-transition/src/altair/block/processSyncCommittee.ts:48]: Good pick!
