### PR TITLE
fix: improve sync aggregate participation

### LINKED ISSUE #8294: Bad sync aggregates in small devnets
Running a local devnet with 4 lodestar nodes (64 validators each) results in bad sync aggregates

Image

The interesting part is that is exactly `63.87%` each block.

Looking at the validator clients I confirmed that we publish 64 messages each slot, so there is either an issue with our sync messages aggregation or sync aggregate packing in the block

Might be similar issue as Prysm noticed https://github.com/OffchainLabs/prysm/pull/15608

### PR DESCRIPTION
**Pull request by lodekeeper**
## Motivation

Fixes #8294 — Two gossip-layer bugs reduce sync aggregate participation. The effect is most visible in small devnets (~64% instead of 100%) but also affects mainnet, just with lower probability due to the larger validator set.

### 1. `fastMsgIdFn` cross-topic dedup

gossipsub's `fastMsgIdFn` only hashes `rpcMsg.data` without the topic. `SyncCommitteeMessage` is published to multiple `sync_committee_{subnet}` topics with identical data, so receiving nodes deduplicate the message after processing it on the first topic — dropping it for all other subnets.

**Fix:** Use a topic-derived xxhash seed (cached per topic) to differentiate identical data across topics. Zero allocation on the hot path.

### 2. `getIndexInSubcommittee` returns first match only

When a validator appears multiple times in the same subcommittee, only the first position is tracked in the gossip handler. The API path (`submitPoolSyncCommitteeSignatures`) correctly iterates all positions, but the gossip path does not.

**Fix:** Return all matching positions and add the message to the pool for each one.

## Kurtosis Results (4 nodes × 64 validators)

| Metric | Before | After |
|--------|--------|-------|
| Participation | 328/512 (64.1%) | 512/512 (100.0%) |
| Consistency | Every block identical | Every block identical |

Equivalent fix in Prysm: [OffchainLabs/prysm#15608](https://github.com/OffchainLabs/prysm/pull/15608)

> **Note:** This is an AI-generated PR created with assistance from Lodekeeper 🌟

### CODE REVIEW

File: packages/beacon-node/src/network/gossip/encoding.ts [hunk 1]
```diff
@@ -30,6 +30,17 @@ const sharedMsgIdBuf = Buffer.alloc(20);
...
+    if (rpcMsg.topic) {
+      // Include topic in hash to prevent cross-topic deduplication of identical messages.
+      // SyncCommitteeMessages are published to multiple sync_committee_{subnet} topics with
+      // identical data, so hashing only the data incorrectly deduplicates across subnets.
+      // See https://github.com/ChainSafe/lodestar/issues/8294
+      const topicBuf = Buffer.from(rpcMsg.topic);
+      const combined = new Uint8Array(rpcMsg.data.length + topicBuf.length);
+      combined.set(rpcMsg.data);
+      combined.set(topicBuf, rpcMsg.data.length);
+      return xxhash.h64Raw(combined, h64Seed).toString(16);
```
Comment (nflaig) [inline packages/beacon-node/src/network/gossip/encoding.ts]: @lodekeeper does this change have any impact on other topics?

File: packages/beacon-node/src/chain/opPools/syncContributionAndProofPool.ts [hunk 2]
```diff
@@ -116,15 +117,15 @@ export class SyncContributionAndProofPool {
...
+  getAggregate(slot: Slot, prevBlockRoot: Root, messagePool?: SyncCommitteeMessagePool): altair.SyncAggregate {
     const opPoolMetrics = this.metrics?.opPool.syncContributionAndProofPool;
     const bestContributionBySubnetByRoot = this.bestContributionBySubnetRootBySlot.getOrDefault(slot);
     opPoolMetrics?.getAggregateRoots.set(bestContributionBySubnetByRoot.size);
     const prevBlockRootHex = toRootHex(prevBlockRoot);
     const bestContributionBySubnet = bestContributionBySubnetByRoot.get(prevBlockRootHex) ?? new Map();
     opPoolMetrics?.getAggregateSubnets.set(bestContributionBySubnet.size);
 
-    if (bestContributionBySubnet.size === 0) {
+    if (bestContributionBySubnet.size === 0 && !messagePool) {
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/chain/opPools/syncContributionAndProofPool.ts]: This comment was against the previous revision that included a message pool merge (passing `messagePool` to `getAggregate`). That code has been stripped from the PR — this file is now unchanged from `unstable`. The `getAggregateReturnsEmpty` metric and warning log are fully preserved as-is.

**Comment by nflaig** [comment]
@codex review

File: packages/beacon-node/src/network/gossip/encoding.ts (hunk 1 above)
Comment (lodekeeper) [reply packages/beacon-node/src/network/gossip/encoding.ts]: **Functionally, no.** `sync_committee` is the only gossip topic where identical message bytes are published to multiple subnet topics — the same `SyncCommitteeMessage` (`{slot, beaconBlockRoot, validatorIndex, signature}`) goes to all assigned subnets. All other subnet-based topics have unique data per topic:
- `beacon_attestation`: includes `committee_bits`, unique per committee
- `blob_sidecar`: includes blob index
- `data_column_sidecar`: includes column index

So the hash change doesn't affect dedup behavior for anything except `sync_committee`.

**One concern:** the current implementation allocates `Buffer.from(topic)` + `new Uint8Array(data.length + topic.length)` per incoming message. On mainnet that's thousands of msgs/sec. I can optimize this by hashing the topic separately and mixing it into the seed instead:

```ts
// Zero-allocation approach: use topic hash as seed modifier
const topicSeed = xxhash.h64Raw(Buffer.from(rpcMsg.topic), h64Seed);
return xxhash.h64Raw(rpcMsg.data, topicSeed).toString(16);
```

This avoids the buffer concat entirely. Want me to switch to that approach?

Comment (nflaig) [reply packages/beacon-node/src/network/gossip/encoding.ts]: yes, please update this to use zero-allocation approach

Comment (nflaig) [reply packages/beacon-node/src/network/gossip/encoding.ts]: > Functionally, no. sync_committee is the only gossip topic where identical message bytes are published to multiple subnet topics

so does it make sense to only use this approach for sync committee, what do you think?

Comment (lodekeeper) [reply packages/beacon-node/src/network/gossip/encoding.ts]: Done — switched to cached topic-seed approach. Topic → seed is computed once and cached in a `Map<string, bigint>`, so the hot path is just a Map lookup + one `xxhash.h64Raw` call with zero allocation. Re-verified with Kurtosis: still 512/512 = 100.0%.

[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/network/gossip/encoding.ts]: Good catch on the ambiguity — moot now since the updated approach hashes topic and data independently (topic hash is used as the xxhash seed for the data hash). No concatenation, no ambiguity.

File: packages/beacon-node/src/network/gossip/encoding.ts [hunk 3]
```diff
@@ -28,8 +28,24 @@ const sharedMsgIdBuf = Buffer.alloc(20);
...
+      // Use topic-derived seed to prevent cross-topic deduplication of identical messages.
+      // SyncCommitteeMessages are published to multiple sync_committee_{subnet} topics with
+      // identical data, so hashing only the data incorrectly deduplicates across subnets.
+      // See https://github.com/ChainSafe/lodestar/issues/8294
+      let topicSeed = topicSeedCache.get(rpcMsg.topic);
+      if (topicSeed === undefined) {
+        topicSeed = xxhash.h64Raw(Buffer.from(rpcMsg.topic), h64Seed);
+        topicSeedCache.set(rpcMsg.topic, topicSeed);
+      }
+      return xxhash.h64Raw(rpcMsg.data, topicSeed).toString(16);
```
Comment (nflaig) [inline packages/beacon-node/src/network/gossip/encoding.ts:47]: do it makes sense to use topic seed for all topics, also shouldn't the data be part of the h64Raw, or is that not needed to dedupe messages on the same topic?

Comment (lodekeeper) [reply packages/beacon-node/src/network/gossip/encoding.ts:47]: Good questions:

**1. Topic seed for all topics:** Yes, it makes sense. It's a general correctness improvement — no reason to special-case only sync_committee topics. The cost is identical (one cached Map lookup per message), and it's future-proof in case another topic ever has the same pattern. The current code already does this for all topics (the `if (rpcMsg.topic)` branch).

**2. Data IS being hashed:** `xxhash.h64Raw(rpcMsg.data, topicSeed)` — the first argument is the data, the second is the seed. xxhash hashes the data using the seed as initialization, so:
- Same data + same topic → same hash ✅ (deduped within topic)
- Same data + different topic → different hash ✅ (not deduped across topics)
- Different data + same topic → different hash ✅ (not deduped)

The topic-derived seed effectively makes each topic its own hash namespace while still hashing the full message data for within-topic dedup.

**Review by nflaig — DISMISSED** [review]

**Comment by nflaig** [comment]
worth noting this is not just a bug in small devnets but also affect mainnet, it's just much more unlikely to have a high impact there

**Comment by lodekeeper** [comment]
Good point — updated the PR title and description to reflect broader scope. The `fastMsgIdFn` dedup affects any validator whose `SyncCommitteeMessage` bytes are identical across subnet topics (which is all of them), and `getIndexInSubcommittee` drops bits for any validator with multiple positions in the same subcommittee. On mainnet the probability of duplicate positions is lower but nonzero.

File: packages/beacon-node/src/network/gossip/encoding.ts [hunk 4]
```diff
@@ -28,8 +28,24 @@ const sharedMsgIdBuf = Buffer.alloc(20);
  * The function used to generate a gossipsub message id
  * We use the first 8 bytes of SHA256(data) for content addressing
  */
+// Cache topic -> seed to avoid per-message allocations on the hot path.
+// Topics are a fixed set per fork (changes only at fork boundaries).
+const topicSeedCache = new Map<string, bigint>();
```
Comment (wemeetagain) [inline packages/beacon-node/src/network/gossip/encoding.ts:29]: the singleton cache is a little dirty, but also changing that is a much bigger diff.

Comment (lodekeeper) [reply packages/beacon-node/src/network/gossip/encoding.ts:29]: Agreed — the module-level `Map` is pragmatic but not ideal architecturally. Moving it into a class instance would mean threading it through the gossip handler setup, which touches a lot of surface area for little functional gain. Happy to take that on as a follow-up if you'd prefer, but keeping it here for now since the cache is bounded (fixed topic set per fork, ~50 entries max) and the tradeoff seems worth it.

Comment (nflaig) [inline packages/beacon-node/src/network/gossip/encoding.ts:29]: this should be moved above the function comment at least, right now it's in-between

Comment (lodekeeper) [reply packages/beacon-node/src/network/gossip/encoding.ts:29]: Good catch — moved the cache declaration + comment above the JSDoc. Fixed in 1915869.

**Review by nflaig — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.42.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.42.0) :tada:
