### PR TITLE
Drop flat validators cache

### LINKED ISSUE #2885: Research reducing memory footprint
Tracking issue for various research efforts into reducing Lodestar beacon node memory footprint.

### LINKED ISSUE #3063: Prater altair fork: ATTESTATION_ERROR_INVALID_SIGNATURE
**Describe the bug**

A single beacon node with one validator errors sometimes with

```
beacon_node_1  | Sep-02 12:43:16.941 [API]             error: Error on submitPoolAttestations [0] slot=1173216, index=50 code=ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  | Error: ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  |     at Object.validateGossipAttestation (/usr/app/packages/lodestar/src/chain/validation/attestation.ts:146:11)
beacon_node_1  |     at /usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:52:50
beacon_node_1  |     at async Promise.all (index 0)
beacon_node_1  |     at Object.submitPoolAttestations (/usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:49:7)
beacon_node_1  |     at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
beacon_node_1  | Sep-02 12:43:17.034 [API]             error: Req req-4e submitPoolAttestations error code=ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  | Error: ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  |     at Object.validateGossipAttestation (/usr/app/packages/lodestar/src/chain/validation/attestation.ts:146:11)
beacon_node_1  |     at /usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:52:50
beacon_node_1  |     at async Promise.all (index 0)
beacon_node_1  |     at Object.submitPoolAttestations (/usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:49:7)
beacon_node_1  |     at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
validator_1    | Sep-02 12:43:17.042 []                error: Error publishing attestations slot=1173216, index=50 message=Internal Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
validator_1    | Error: Internal Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
validator_1    |     at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:91:15)
validator_1    |     at runMicrotasks (<anonymous>)
validator_1    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
validator_1    |     at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:58:12)
validator_1    |     at Object.request [as submitPoolAttestations] (/usr/app/packages/api/src/client/utils/client.ts:72:19)
validator_1    |     at AttestationService.produceAndPublishAttestations (/usr/app/packages/validator/src/services/attestation.ts:110:9)
validator_1    |     at AttestationService.publishAttestationsAndAggregates (/usr/app/packages/validator/src/services/attestation.ts:57:25)
validator_1    |     at /usr/app/packages/validator/src/services/attestation.ts:43:9
validator_1    |     at async Promise.all (index 0)
validator_1    |     at AttestationService.runAttestationTasks (/usr/app/packages/validator/src/services/attestation.ts:40:5)
```

CPU is not too high, < 80%

**Expected behavior**

Validator should agree with beacon node on correct signature

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

A Lodestar beacon node uses too much memory compared to what is strictly necessary. See this issue for the analysis https://github.com/ChainSafe/lodestar/issues/2885

We must:
- Not duplicate expensive data = drop flat caches where possible
- Represent the validators registry in a memory efficient manner

**Description**

- Drop flat validators array from CacheBeaconState. In normal network conditions it will not affect performance. Only when the validator registry drastically changes it will slow the node a bit. See performance tests for actual numbers
- Use new SSZ type ContainerLeafNodeStructType to represent the leafs of the state.validators tree as regular JS values. Much less memory, fast reads but slow hashing. The tradeoff is worth it it normal network conditions.

**Performance cost**

Surprisingly it has very little!
- Hashing many validator objects is a bit more expensive ~ x2, but it a rare operation. For example, it increases epoch processing time by 8ms if all block are fulled with deposits.
- getPubkeys (for duties API) is more expensive, extra 0.5ms when requesting duties for 1000 validators
- beforeProcessingEpoch takes extra 30ms to traverse the tree and grab all the root nodes.

**Memory gains**

current master
```
getPubkeys()         rss +106.91 MB       heapTotal +41.41 MB        heapUsed +39.16 MB        external +11.47 MB        arrayBuffers +11.47 MB       
.defaultValue()      rss +14.16 MB        heapTotal +14 MB           heapUsed +15.1 MB         external -259.28 KB       arrayBuffers -259.28 KB      
build raw state      rss +97.44 MB        heapTotal +97.32 MB        heapUsed +103.35 MB       external  0 B             arrayBuffers  0 B            
addPendingAtt        rss +138.94 MB       heapTotal +144 MB          heapUsed +127.61 MB       external  0 B             arrayBuffers  0 B            
toTreeBacked         rss +457.91 MB       heapTotal +450.48 MB       heapUsed +461.4 MB        external -13.3 KB         arrayBuffers -12.69 KB       
CachedBeaconState    rss +814.43 MB       heapTotal +749.26 MB       heapUsed +746.37 MB       external +36.39 KB        arrayBuffers +36.39 KB  
```

this branch
```
getPubkeys()         rss +96.79 MB        heapTotal +33.91 MB        heapUsed +40.16 MB        external +11.44 MB        arrayBuffers +11.44 MB       
.defaultValue()      rss +17.75 MB        heapTotal +17.25 MB        heapUsed +17.07 MB        external  0 B             arrayBuffers  0 B            
build raw state      rss +91.24 MB        heapTotal +93.82 MB        heapUsed +94.21 MB        external  0 B             arrayBuffers  0 B            
addPendingAtt        rss +127.2 MB        heapTotal +134.5 MB        heapUsed +127.45 MB       external  0 B             arrayBuffers  0 B            
toTreeBacked         rss +111.71 MB       heapTotal +98.75 MB        heapUsed +106.14 MB       external  0 B             arrayBuffers  0 B            
CachedBeaconState    rss +493.89 MB       heapTotal +433.62 MB       heapUsed +430.64 MB       external  0 B             arrayBuffers  0 B 
```

658MB less per state (1593MB -> 935MB)

- 346MB less on tree data per state
- 321MB less on caches per state 

------

Closes https://github.com/ChainSafe/lodestar/issues/3063
Closes https://github.com/ChainSafe/lodestar/issues/2885

### CODE REVIEW

File: packages/lodestar/src/api/impl/validator/utils.ts [hunk 1]
```diff
@@ -43,25 +54,46 @@ export function computeSubnetForCommitteesAtSlot(
...
-      const validator = validators.get(validatorIndex);
-      if (!validator) throw new ApiError(400, `Validator index ${validatorIndex} not in state`);
-      return [validatorIndex, validator.pubkey];
-    })
-  );
+  validators: allForks.BeaconState["validators"],
+  indexes: ValidatorIndex[]
+): BLSPubkey[] {
+  const validatorsLen = validators.length; // Get once, it's expensive
+  const validatorsTree = ((validators as unknown) as TreeValue<phase0.Validator>).tree;
```
Comment (wemeetagain) [inline packages/lodestar/src/api/impl/validator/utils.ts]: Not that its being used here, but the correct type is `TreeValue<List<phase0.Validator>>`, same below

**Review by wemeetagain — CHANGES_REQUESTED** [review]
LGTM! very minor cosmetic type issue

**Review by wemeetagain — APPROVED** [review]
🌟
