### PR TITLE
fix: reduce verbosity of gossip block errors

### LINKED ISSUE #6402: BLOCK_ERROR_DATA_UNAVAILABLE errors if blobs are late
### Describe the bug

We currently log errors if our node receives blobs late (>4s)
```
[network]         error: Error receiving block slot=950303, peer=16Uiu2HAm2X8z2WNtF59uA4RTvk7D1qWdhq1wCRFaX9KQZon36KLM, code=BLOCK_ERROR_DATA_UNAVAILABLE
Error: BLOCK_ERROR_DATA_UNAVAILABLE
    at raceWithCutoff (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksDataAvailability.ts:122:11)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at maybeValidateBlobs (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksDataAvailability.ts:84:13)
    at verifyBlocksDataAvailability (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksDataAvailability.ts:41:36)
    at async Promise.all (index 1)
    at BeaconChain.verifyBlocksInEpoch (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlock.ts:97:9)
    at BeaconChain.processBlocks (file:///usr/app/packages/beacon-node/src/chain/blocks/index.ts:72:7)
    at JobItemQueue.runJob (file:///usr/app/packages/beacon-node/src/util/queue/itemQueue.ts:101:22)
```

### Expected behavior

Should consider reducing verbosity of these logs as they are not critical as Lodestar will try to pull them from other peers instead of waiting for them.

Possible solutions
- log as warn instead of error
- remove stacktrace
- or maybe even move to debug

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.15.0

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Follow [logging-policy](https://github.com/ChainSafe/lodestar/blob/unstable/CONTRIBUTING.md#logging-policy) and avoid user concerns by reducing verbosity of non-critical errors.

**Description**

- Adjust verbosity based on error type
- ~~Log gossip block errors as warnings~~
- ~~Only log to debug if blobs are unavailable within cutoff time~~

**TODO**
- [x] come up with a better approach to determine log verbosity (based on error type / code)

Closes https://github.com/ChainSafe/lodestar/issues/6402

### CODE REVIEW

File: packages/beacon-node/src/network/processor/gossipHandlers.ts [hunk 1]
```diff
@@ -279,7 +280,7 @@ function getDefaultHandlers(modules: ValidatorFnsModules, options: GossipHandler
           }
         }
         metrics?.gossipBlock.processBlockErrors.inc({error: e instanceof BlockError ? e.type.code : "NOT_BLOCK_ERROR"});
-        logger.error("Error receiving block", {slot: signedBlock.message.slot, peer: peerIdStr}, e as Error);
+        logger.warn("Error receiving block", {slot: signedBlock.message.slot, peer: peerIdStr}, e as Error);
```
Comment (nflaig) [inline packages/beacon-node/src/network/processor/gossipHandlers.ts]: We could also consider `debug` here but these logs are really rare and might indicate an issue with the network as a whole, e.g. if there is an issue in another client producing invalid blocks. Also see Lion's comment on this previously https://github.com/ChainSafe/lodestar/pull/5457#discussion_r1184514672.

File: packages/beacon-node/src/network/processor/gossipHandlers.ts [hunk 2]
```diff
@@ -263,8 +263,9 @@ function getDefaultHandlers(modules: ValidatorFnsModules, options: GossipHandler
               const forkTypes = config.getForkTypes(slot);
               const rootHex = toHexString(forkTypes.BeaconBlock.hashTreeRoot(signedBlock.message));
 
+              logger.debug("Blobs are unavailable within cutoff time", {slot, root: rootHex, peer: peerIdStr});
               events.emit(NetworkEvent.unknownBlock, {rootHex, peer: peerIdStr});
-              break;
+              return;
```
Comment (nflaig) [inline packages/beacon-node/src/network/processor/gossipHandlers.ts]: Returning here means we won't track this in metrics as a process block error and also not prune `seenGossipBlockInput`
https://github.com/ChainSafe/lodestar/blob/c52c7bd6614c622f77913e85ec435bf0f50e2558/packages/beacon-node/src/network/processor/gossipHandlers.ts#L281-L283

Maybe someone can clarify this, based on [seenGossipBlockInput.ts#L31-L42](https://github.com/ChainSafe/lodestar/blob/c52c7bd6614c622f77913e85ec435bf0f50e2558/packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts#L31-L42), I am not sure if it correct to even prune the cache?

Comment (g11tech) [reply packages/beacon-node/src/network/processor/gossipHandlers.ts]: why don't we want to track it as an error in metric?
Also cache needs to be pruned in case there is some sort of DOS attack

File: packages/beacon-node/src/network/processor/gossipHandlers.ts (hunk 1 above)
Comment (g11tech) [reply packages/beacon-node/src/network/processor/gossipHandlers.ts]: its better to debug/warn/error in case of conditions that we see, and would by default error so that its very visible unless its a scenario we have analyzed and hence put it to debug/warn

Comment (nflaig) [reply packages/beacon-node/src/network/processor/gossipHandlers.ts]: I do agree with that, we should be very careful with moving log to less verbosity but this is a clear case to me as the log is triggered based on data we receive from the network, so at most is should be a warning as the user / operator cannot be expected to do something about it.

It is also quite clear based on the definition of log level in our logging policy
image


What about we adapt the log level (verbosity) based on the error we receive here?
- unknown error (not a BlockError) = `error`
- `e instanceof BlockError` = `warn`
- `BlockErrorCode.DATA_UNAVAILABLE` = `debug`

File: packages/beacon-node/src/network/processor/gossipHandlers.ts (hunk 2 above)
Comment (nflaig) [reply packages/beacon-node/src/network/processor/gossipHandlers.ts]: > why don't we want to track it as an error in metric?

We throw an error but it used to trigger unknown block sync upstream
https://github.com/ChainSafe/lodestar/blob/83d7d701728ac70ad01cd80074b8537632ac0a23/packages/beacon-node/src/chain/blocks/verifyBlocksDataAvailability.ts#L121-L122
But that's based on my limited understanding, will revert that change to track an error

> Also cache needs to be pruned in case there is some sort of DOS attack

My thought process was we might prune a block input which was valid but just didn't receive blobs for it yet, but you are probably right that this might be unsafe to not prune always

https://github.com/ChainSafe/lodestar/blob/83d7d701728ac70ad01cd80074b8537632ac0a23/packages/beacon-node/src/chain/seenCache/seenGossipBlockInput.ts#L71

File: packages/beacon-node/src/network/processor/gossipHandlers.ts [hunk 3]
```diff
@@ -255,6 +255,9 @@ function getDefaultHandlers(modules: ValidatorFnsModules, options: GossipHandler
         chain.seenGossipBlockInput.prune();
       })
       .catch((e) => {
+        // Any unexpected error
+        let logLevel = LogLevel.error;
```
Comment (g11tech) [inline packages/beacon-node/src/network/processor/gossipHandlers.ts]: do not initialize with anything, this way typescript will tell you if any case or switch has not been covered and is helpful in things being a bit more declarative, rest looks good :+1:

Comment (nflaig) [reply packages/beacon-node/src/network/processor/gossipHandlers.ts]: Good point, this ensures we have to explicitly handle each case

**Review by g11tech — APPROVED** [review]
lgtm

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.16.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.16.0) :tada:
