### PR TITLE
Start gossip on boot

### LINKED ISSUE #1531: Start gossip protocol when network starts
**Describe the bug**
I believe we're being dropped by lighthouse because we don't 'support' gossipsub until we get past initial sync.

**Expected behavior**
We should start gossipsub **but not subscribe to any topics** on network start.
Then when we finish initial sync, we can subscribe to topics.
This will allow us to stay connected to clients which require peers to be gossipsub peers while we sync.

### PR DESCRIPTION
**Pull request by wemeetagain**
Resolves #1531

### CODE REVIEW

File: packages/lodestar/src/network/network.ts [hunk 1]
```diff
@@ -78,13 +78,15 @@ export class Libp2pNetwork extends (EventEmitter as {new (): NetworkEventEmitter
     await this.reqResp.start();
     const enr = this.getEnr();
     await this.metadata.start(enr!);
+    await this.gossip.pubsub.start();
```
Comment (twoeths) [inline packages/lodestar/src/network/network.ts]: How about having `pubsub` as part of network instead of gossip? So `pubsub` could be created/started/stopped inside network, gossip just use it. We have `pubsub` as part of `IGossipModules` anyway.

So this could become: `this.pubsub.start()`

Comment (wemeetagain) [reply packages/lodestar/src/network/network.ts]: :+1: sounds good

Comment (wemeetagain) [reply packages/lodestar/src/network/network.ts]: In fact, libp2p already comes with a pubsub attached! We might look into just using that one in a later PR

**Review by twoeths — DISMISSED** [review]

File: packages/lodestar/src/network/gossip/gossip.ts [hunk 2]
```diff
@@ -63,7 +63,6 @@ export class Gossip extends (EventEmitter as {new (): GossipEventEmitter}) imple
   }
 
   public async start(): Promise<void> {
-    await this.pubsub.start();
```
Comment (twoeths) [inline packages/lodestar/src/network/gossip/gossip.ts]: still need to keep this?

File: packages/lodestar/src/network/gossip/gossip.ts [hunk 3]
```diff
@@ -75,7 +74,6 @@ export class Gossip extends (EventEmitter as {new (): GossipEventEmitter}) imple
     this.emit("gossip:stop");
     this.unregisterHandlers();
     this.chain.emitter.removeListener("forkDigest", this.handleForkDigest);
-    await this.pubsub.stop();
```
Comment (twoeths) [inline packages/lodestar/src/network/gossip/gossip.ts]: same

**Review by twoeths — DISMISSED** [review]

**Review by twoeths — APPROVED** [review]
