### PR TITLE
Optimize UX loading for keystores

### LINKED ISSUE #4179: Optimize UX loading +100 keystores on vc
**Describe the bug**

After fixing https://github.com/ChainSafe/lodestar/issues/4166 now it takes a long time to load secure scrypt keystores.

Note that this UX improvement only affects whales and institutional players:
- Home stakers are likely to have < 10 keys
- Testnets + Kurtosis are run with either insecure scrypt keystores or mnemonics

Next steps:
- [x] There's a bug currently where memory is not released after decrypting the keystores. Must investigate and ensure memory is released
- [x] Instead of decrypting 100 keystores at once, decrypting 5-10 is fine, which provides a significant speed up. A good number would be to decrypt thread count at once
- [x] Implement similar strategy to Prysm and Lighthouse where private keys are stored in a single keystore such that subsequent start-ups are fast

### PR DESCRIPTION
**Pull request by nazarhussain**
**Motivation**

Improve the UX for the keystores loading. 

**Description**

Add key caching to the keystore loading logic. 

Closes #4179

**Steps to test or reproduce**

- Run all unit tests

### CODE REVIEW

File: packages/cli/src/cmds/validator/keymanager/keystoreCache.ts [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+  if (!fs.existsSync(cacheFilepath)) {
+    throw new Error(`Cache file ${cacheFilepath} does not exists.`);
+  }
+
+  lockFilepath(cacheFilepath);
+
+  const password = passwords.join("");
+  // We can't use Keystore.parse as it validates the `encrypted message` to be only 32 bytes.
+  const keystore = new Keystore(JSON.parse(fs.readFileSync(cacheFilepath, "utf8")));
+  const secretKeyConcatenatedBytes = await keystore.decrypt(password);
```
Comment (nflaig) [inline packages/cli/src/cmds/validator/keymanager/keystoreCache.ts:36]: What's the point of encrypting the keystore at all if we store the passwords in the same place? I assume the decrypting still takes a long time if the keystore is big but probably still better then decryption every single key separately as it was done before

It does not seem ideal to me that we store passwords in plain text at all which is currently done by Lodestar as we have a `keystore` and a `secrets` (with passwords) file. Those files are stored on the same device (and even the same folder) so it pointless in terms of security.

In my opinion, we should **never** store the password, only the first time the user imports a encrypted keystore the password should be interactively provided through the cli or keymanager API. After keystores are imported they should be stored unecrypted which makes subsequently loading them much faster and we never store passwords in plain text.

File: packages/cli/src/cmds/validator/keymanager/persistedKeys.ts [hunk 2]
```diff
@@ -246,11 +247,32 @@ export class PersistedKeysBackend implements IPersistedKeysBackend {
...
 ): Promise<Signer[]> {
-  const signers: Signer[] = [];
+  if (opts.cacheFilePath) {
+    try {
+      const signers = await loadKeystoreCache(opts.cacheFilePath, keystoreDefinitions);
+      if (opts?.onDecrypt) {
+        opts?.onDecrypt(signers.length - 1, signers[signers.length - 1]);
+      }
+      return signers;
+    } catch (e) {
```
Comment (nflaig) [inline packages/cli/src/cmds/validator/keymanager/persistedKeys.ts]: `e` seems to be unused

if we want to keep it for debugging purposes

```suggestion
    } catch (_e) {
```

or could just completely remove it

```suggestion
    } catch {
```

File: packages/cli/test/unit/util/progress.test.ts [hunk 3]
```diff
@@ -53,6 +53,26 @@ describe("progress", () => {
       expect(progress.secondCall.args[0]).to.eql({total, current: total, ratePerSec: 0, percentage: 100});
     });
 
+    it("should call progress with correct values directly reaches to total", () => {
+      const progress = sandbox.spy();
+      const frequencyMs = 50;
+      const total = 8;
+      const needle = showProgress({total, signal: new AbortController().signal, frequencyMs, progress});
```
Comment (nflaig) [inline packages/cli/test/unit/util/progress.test.ts:60]: if we only need to abort signal could consider the following to save some resources

```suggestion
      const needle = showProgress({total, signal: new AbortSignal(), frequencyMs, progress});
```

File: packages/cli/src/cmds/validator/keymanager/keystoreCache.ts (hunk 1 above)
Comment (nazarhussain) [reply packages/cli/src/cmds/validator/keymanager/keystoreCache.ts:36]: 1. Local keystores is a feature, which is consistent across all CL clients. As you mentioned it's not the best way in terms of security. 
2. To overcome security issue, there is a feature of remote key manager, which does not involve storing passing in local file. 

It's upto user to use one feature or other. In regard to decryption, for cache decryption it will take time upto one keystore. So if we have 100 validators keys we can save upto 99% of time with the cache.

Comment (nflaig) [reply packages/cli/src/cmds/validator/keymanager/keystoreCache.ts:36]: That's what I figured, looks like all CLs implement it like this. We also quickly discussed this topic in the standup, I will create a separate issue for this to get some ideas how we could improve the current security model but it might just be the case that a remoter signer/key manager is the only solution.

> So if we have 100 validators keys we can save upto 99% of time with the cache.

that's a great performance improvement, I was assuming it will be much faster but having constant time is really a big deal if you have a lot of validators

File: packages/cli/src/cmds/validator/signers/index.ts [hunk 4]
```diff
@@ -91,7 +91,11 @@ export async function getSignersFromArgs(
         );
       },
     });
-    return await decryptKeystoreDefinitions(keystoreDefinitions, {...args, onDecrypt: needle});
+    return await decryptKeystoreDefinitions(keystoreDefinitions, {
```
Comment (nflaig) [inline packages/cli/src/cmds/validator/signers/index.ts]: just minor thing I missed earlier, the `await` here should not be needed. Could consider adding the [no-return-await](https://eslint.org/docs/latest/rules/no-return-await) eslint rule to detect this

```suggestion
    return decryptKeystoreDefinitions(keystoreDefinitions, {
```

File: packages/cli/src/util/progress.ts [hunk 5]
```diff
@@ -16,6 +16,7 @@ export function showProgress({
   let current = 0;
   let last = 0;
   let lastProcessTime: number = Date.now();
+  let internalId: NodeJS.Timeout;
```
Comment (nflaig) [inline packages/cli/src/util/progress.ts]: could use a more descriptive name for the interval, I think it will also not be just an ID but the whole `Timeout` object

File: packages/cli/test/unit/cmds/validator/keymanager/keystoreCache.test.ts [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+
+const numberOfSigners = 10;
+
+describe("keystoreCache", () => {
+  let definitions: LocalKeystoreDefinition[];
+  let signers: SignerLocal[];
+  let secretKeys: Uint8Array[];
+  let passwords: string[];
+  let keystoreCacheFile: string;
+  // tmp.setGracefulCleanup();
```
Comment (nflaig) [inline packages/cli/test/unit/cmds/validator/keymanager/keystoreCache.test.ts]: commented out code

File: packages/cli/test/unit/cmds/validator/keymanager/keystoreCache.test.ts [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+      definitions.push({password: secretKey.toHex(), keystorePath});
+      passwords.push(password);
+      secretKeys.push(secretKey.toBytes());
+    }
+  });
+
+  describe("writeKeystoreCache", () => {
+    it("should write a valid keystore cache file", async () => {
+      await expect(writeKeystoreCache(keystoreCacheFile, signers, passwords)).to.fulfilled;
+      expect(fs.existsSync(keystoreCacheFile)).to.be.true;
```
Comment (nflaig) [inline packages/cli/test/unit/cmds/validator/keymanager/keystoreCache.test.ts:63]: is there an easy way to do some basic sanitiy checks on the written file? I guess the proper check happens in the others test were the file is written and then loaded, so maybe should not bother too much here

**Review by nflaig — DISMISSED** [review]
LGTM! Really good UX and performance improvement!

File: packages/cli/src/util/progress.ts (hunk 5 above)
Comment (nazarhussain) [reply packages/cli/src/util/progress.ts]: It's common convention among JS community to suffix output of `setTimeout` or `setInterval` as `Ids` because these are just the pointers to v8 internal timers.

Comment (nazarhussain) [reply packages/cli/src/util/progress.ts]: I changed the name to be more descriptive.

File: packages/cli/test/unit/cmds/validator/keymanager/keystoreCache.test.ts (hunk 7 above)
Comment (nazarhussain) [reply packages/cli/test/unit/cmds/validator/keymanager/keystoreCache.test.ts:63]: The authenticity of files could better be checked in e2e tests.

**Review by nflaig — APPROVED** [review]

File: packages/cli/src/util/progress.ts (hunk 5 above)
Comment (nflaig) [reply packages/cli/src/util/progress.ts]: > It's common convention among JS community to suffix output of setTimeout or setInterval as Ids because these are just the pointers to v8 internal timers

gotcha, thanks for pointing that out, I didn't know about that

**Review by wemeetagain — APPROVED** [review]

File: packages/cli/src/cmds/validator/signers/index.ts [hunk 8]
```diff
@@ -91,7 +91,11 @@ export async function getSignersFromArgs(
         );
       },
     });
-    return await decryptKeystoreDefinitions(keystoreDefinitions, {...args, onDecrypt: needle});
+    return decryptKeystoreDefinitions(keystoreDefinitions, {
+      ...args,
+      onDecrypt: needle,
+      cacheFilePath: `${args.importKeystores[0]}.cache`,
```
Comment (nflaig) [inline packages/cli/src/cmds/validator/signers/index.ts:97]: @nazarhussain I noticed that the `validator_keys.cache` is stored in the same directory as my `validator_keys` folder which I set via `--importKeystores`. This is a not ideal in a containerized environment as the cache file is likely not mounted to the container or persistent in a volume. Maybe it would be better to store the cache file in the data directory (`dataDir`).

In our `docker-compose.validator.yml` file we also only mount the `/keystores` which would not include the cache file.

https://github.com/ChainSafe/lodestar/blob/2042c3b1c1916ceed6bc825057515a4456c33a08/docker-compose.validator.yml#L4-L11

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.6.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.6.0) :tada:
