### PR TITLE
p2p: stream bytes from db

### LINKED ISSUE #2490: In ReqResp block method stream bytes from db
**Describe the bug**

Right now when serving ReqResp block methods we read from DB, deserialize from bytes to struct and then re-serialize to send over the wire.

**Expected behavior**

We could just serve the bytes stream directly from db, prevent any serdes and require no memory.

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ When serving p2p `beacon_blocks_by_range` or `beacon_blocks_by_roots`, it's not necessary to deserialize bytes from db to SignedBeaconBlock struct and serialize it back to bytes before doing ssz snappy and response to the the other node
+ In some cases, it takes 20% of our cpu time and our validators missed chain head root due to that

**Description**

+ No need to convert to temporary `SignedBeaconBlock` objects  for `beacon_blocks_by_range` and `beacon_blocks_by_roots` requests
+ Model `P2pBlockResponse` type which contains slot and bytes data of `SignedBeaconBlock`. We need `slot` because we use it when fetching from db and to determine correct forkdigest for p2p
+ New `LodestarResponseBodyByMethod` type which use `P2pBlockResponse`  for `beacon_blocks_by_range` and `beacon_blocks_by_roots`

Closes #2490

### CODE REVIEW

File: packages/lodestar/src/db/repositories/blockArchive.ts [hunk 1]
```diff
@@ -101,14 +101,21 @@ export class BlockArchiveRepository extends Repository<Slot, allForks.SignedBeac
     ]);
   }
 
+  async *p2pBlockStream(opts?: IBlockFilterOptions): AsyncIterable<P2pBlockResponse> {
+    const firstSlot = this.getFirstSlot(opts);
+    const binaryValuesStream = super.binaryValuesStream(opts);
```
Comment (dapplion) [inline packages/lodestar/src/db/repositories/blockArchive.ts]: You can stream entries as bytes and get the slot from the key and well as the value in bytes. This should prevent the need for `getSlotFromBytes` on the archive repository

File: packages/types/src/types.ts [hunk 2]
```diff
@@ -7,3 +9,10 @@ export {ts as allForks} from "./allForks";
 
 /** Common non-spec type to represent roots as strings */
 export type RootHex = string;
+
+/** This type helps response to beacon_block_by_range and beacon_block_by_root more efficiently */
+export type P2pBlockResponse = {
```
Comment (dapplion) [inline packages/types/src/types.ts]: Since this is restricted to ReqResp only and not gossip you can rename to `ReqRespBlockResponse`

File: packages/lodestar/src/network/reqresp/types.ts [hunk 3]
```diff
@@ -141,20 +141,33 @@ export function getResponseSzzTypeByMethod(protocol: Protocol, forkName: ForkNam
...
+type CommonResponseBodyByMethod = {
   [Method.Status]: phase0.Status;
   [Method.Goodbye]: phase0.Goodbye;
   [Method.Ping]: phase0.Ping;
   [Method.Metadata]: phase0.Metadata;
+};
+
+// Used internally by lodestar to response to beacon_blocks_by_range and beacon_blocks_by_root
+// without having to deserialize and serialize from/to bytes
+export type LodestarResponseBodyByMethod = CommonResponseBodyByMethod & {
```
Comment (dapplion) [inline packages/lodestar/src/network/reqresp/types.ts]: Instead of Lodestar you can denote this with `Incoming` vs `Outgoing` responses.
- On an `Incoming` response we deserialize
- On an `Outgoing` response we do not deserialize

File: packages/lodestar/src/network/reqresp/encodingStrategies/sszSnappy/encode.ts [hunk 4]
```diff
@@ -1,21 +1,23 @@
...
  * ```
  */
-export async function* writeSszSnappyPayload<T extends RequestOrResponseBody>(
+export async function* writeSszSnappyPayload<T extends RequestOrLodestarResponseBody>(
   body: T,
-  type: RequestOrResponseType
+  type: RequestOrResponseType | null
 ): AsyncGenerator<Buffer> {
-  const serializedBody = serializeSszBody(body, type);
+  const serializedBody = type === null ? (body as P2pBlockResponse).bytes : serializeSszBody(body, type);
```
Comment (dapplion) [inline packages/lodestar/src/network/reqresp/encodingStrategies/sszSnappy/encode.ts]: Instead of nulling the type you can define the type as an object that
```ts
const reqRespOutgoingResponseBlockType = {
  serialize(serializedBlockWrapper: SerializedBlockWrapper) {
    return serializedBlockWrapper.bytes
  }
}
```

File: packages/lodestar/src/network/reqresp/encoders/responseEncode.ts [hunk 5]
```diff
@@ -26,20 +27,23 @@ import {
...
+      // <context-bytes> - from altair
       const forkName = getForkNameFromResponseBody(config, protocol, chunk);
       yield* writeContextBytes(config, contextBytesType, forkName);
 
       // <encoding-dependent-header> | <encoded-payload>
-      const type = getResponseSzzTypeByMethod(protocol, forkName);
+      const type =
+        protocol.method === Method.BeaconBlocksByRange || protocol.method === Method.BeaconBlocksByRoot
+          ? null
+          : getResponseSzzTypeByMethod(protocol, forkName);
```
Comment (dapplion) [inline packages/lodestar/src/network/reqresp/encoders/responseEncode.ts]: Adding this information here breaks the abstracting layer of the encoders decoders. I would propose to move this info inside `getResponseSzzTypeByMethod`, and here do
```ts
getResponseSzzTypeByMethod(protocol, forkName, Direction.Outgoing)
```

Then edit
```ts
export function getResponseSzzTypeByMethod(protocol: Protocol, forkName: ForkName, direction: Direction) {
  switch (protocol.method) {
    ....
    case Method.BeaconBlocksByRange:
    case Method.BeaconBlocksByRoot:
      // SignedBeaconBlock type is changed in altair
      switch (Direction.Outgoing) {
        case Direction.Incoming:
          return ssz[forkName].SignedBeaconBlock;
        case Direction.Outgoing:
          return null;
          // or
          return bytesToBytesType
  }
}
```
This way the definition is packed together in `packages/lodestar/src/network/reqresp/types.ts`. If you think this approach is more convoluted let me know.

File: packages/lodestar/src/db/repositories/blockArchive.ts [hunk 6]
```diff
@@ -101,14 +101,21 @@ export class BlockArchiveRepository extends Repository<Slot, allForks.SignedBeac
...
+    const step = (opts && opts.step) || 1;
+
+    for await (const bytes of binaryValuesStream) {
+      const slot = getSlotFromBytes(bytes);
+      if ((slot - firstSlot) % step === 0) {
+        yield {bytes, slot};
```
Comment (dapplion) [inline packages/lodestar/src/db/repositories/blockArchive.ts]: The reasoning for attaching the slot here is to get the fork latter when constructing the response? Or is there other usages

Comment (twoeths) [reply packages/lodestar/src/db/repositories/blockArchive.ts]: @dapplion  it's just to get the fork later

File: packages/lodestar/src/network/reqresp/encoders/responseEncode.ts (hunk 5 above)
Comment (twoeths) [reply packages/lodestar/src/network/reqresp/encoders/responseEncode.ts]: Modifying `getResponseSzzTypeByMethod()` would escalate the change to `responseDecode` and other type definition that get return type from this method so I implement the change to a new method `getOutgoingSerializerByMethod()`

File: packages/types/src/types.ts [hunk 7]
```diff
@@ -7,3 +9,10 @@ export {ts as allForks} from "./allForks";
 
 /** Common non-spec type to represent roots as strings */
 export type RootHex = string;
+
+/** This type helps response to beacon_block_by_range and beacon_block_by_root more efficiently */
+export type ReqRespBlockResponse = {
```
Comment (dapplion) [inline packages/types/src/types.ts]: The `types` package should only contain types defined in the spec. `RootHex` is the exception since it's used in lodestar, fork-choice and validator. Since `ReqRespBlockResponse` is a type that only exist and makes sense in reqResp, I would define it in `network/reqResp`.

**Review by dapplion — COMMENTED** [review]
Looks great! Thank you!

Just a minor comment

**Review by dapplion — APPROVED** [review]
Excellent!
