### PR TITLE
Validator: validate genesisValidatorsRoot

### LINKED ISSUE #3211: ERR_INVALID_ATTESTATION_DOUBLE_VOTE
**Describe the bug**

A user in discord reported  https://discord.com/channels/593655374469660673/593655641445367808/889555125448892427

```
error: Error signing attestation slot=1304012, index=17, head=0xdca5…3d80, validator=0xa87e…afb1 code=ERR_INVALID_ATTESTATION_DOUBLE_VOTE, attestation={"sourceEpoch":40749,"targetEpoch":40750,"signingRoot":"0x667cbb5b329650705425bddc216491a059be6e4e4dcab96727b5f1989a7bd847"}, prev={"sourceEpoch":40749,"targetEpoch":40750,"signingRoot":"0x4818486efdecad5d700e2b048c7ca3c4f85132cfbc929fc5f932b85199a952c3"}
```

Lodestar version=v0.30.0 (npm), network=prater
Neither my vc or bn node were restarting. I am running both in cli. I couldn't find any grafana dashboards for metrics. Can you please link it?
I plan on running  lodestar using systemd but will probably do that later on today. Unfortunately, I don't have any saved logs.

Perhaps it's my network settings? I have a lighthouse node running on port 9000 so I switched lodestar to use 9001. These are the settings I'm using. 

```
lodestar beacon --network prater --network.localMultiaddrs /ip4/0.0.0.0/tcp/9001 --network.discv5.bindAddr /ip4/0.0.0.0/udp/9001 --eth1.providerUrls https://goerli.infura.io/v3/XXX --network.targetPeers 50 --network.maxPeers 55
```

**Expected behavior**

Ǹot happen

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ On some setup, for example Docker, validator db is always fixed at /var/lib/docker/volumes/lodestar_validator/_data/validator-db
+ This makes the ERR_INVALID_ATTESTATION_DOUBLE_VOTE when user switches from one network to another

**Description**

+ Validate and store `genesisValidatorsRoot` when we start validator

Closes #3211

### CODE REVIEW

File: packages/db/src/schema.ts [hunk 1]
```diff
@@ -61,6 +61,7 @@ export enum Bucket {
   altair_lightClientSyncCommitteeProof = 35, // SyncPeriod ->
 
   merge_totalTerminalDifficulty = 40, // Single item -> Uint256
+  validator_metaData = 41,
```
Comment (dapplion) [inline packages/db/src/schema.ts:64]: If it only contains the genesisValidatorsRoot could you be explicit in naming in the bucket name + repository name?

File: packages/validator/src/validator.ts [hunk 2]
```diff
@@ -80,17 +83,34 @@ export class Validator {
...
+          expected: toHexString(genesis.genesisValidatorsRoot),
+          actual: toHexString(genesisValidatorsRoot),
+        });
+        throw new NotEqualParamsError("Not the same genesisValidatorRoot");
+      }
+      opts.logger.info("Verified node and validator have same genesisValidatorRoot");
+    } else {
+      await metaDataRepository.setGenesisValidatorsRoot(genesis.genesisValidatorsRoot);
+      opts.logger.info("Persisted genesisValidatorRoot", toHexString(genesis.genesisValidatorsRoot));
+    }
```
Comment (dapplion) [inline packages/validator/src/validator.ts]: Could you abstract this into a function to keep this clean?

```ts
await assertEqualGenesisValidatorsRoot(...)
opts.logger.info("Verified node and validator have same genesisValidatorRoot")
```

**Review by dapplion — APPROVED** [review]
