### PR TITLE
fix: network worker not shutting down

### LINKED ISSUE #5775: Network worker not shutting down
### Describe the bug

The network worker thread is not shutting down in some cases.

Force closing (`kill`) does not help either because worker does receive signal.
```
Jul-17 17:08:54.000[]                 info: Synced - slot: 6092144 - head: 0xe00e…5e94 - exec-block: valid(9361504 0x8772…) - finalized: 0x7710…765c:190377 - peers: 51
^CJul-17 17:09:01.307[]                 info: Stopping gracefully, use Ctrl+C again to force process exit
Jul-17 17:09:06.176[]                 info: Synced - slot: 6092145 - head: (slot -1) 0xe00e…5e94 - exec-block: valid(9361504 0x8772…) - finalized: 0x7710…765c:190377 - peers: 50
^CJul-17 17:09:10.028[]                 info: Forcing process exit
^C^C^C^C^C./lodestar: line 7: 2357120 Killed                  node --trace-deprecation --max-old-space-size=4096 ./packages/cli/bin/lodestar.js "$@
```

It is pretty clear based on observed logs that the issue is the network worker.

"terminating network worker" is logged
https://github.com/ChainSafe/lodestar/blob/5116493e87a9fe2102ebc7a3ff77677c90da3ddf/packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts#L129

but "terminated network worker" is not
https://github.com/ChainSafe/lodestar/blob/5116493e87a9fe2102ebc7a3ff77677c90da3ddf/packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts#L131

I checked the log files, there is nothing that peaks out, likely just the same issue we see on the main thread with libp2p
- https://github.com/ChainSafe/lodestar/issues/5642

Can likely be resolved by calling `process.exit` on worker explicitly or force closing it using another approach.

### Expected behavior

Network worker should shut down cleanly and not hang the main process.

### Steps to reproduce

Run Lodestar beacon node with `--network.useWorker true` flag.

### Additional context

The problem seems to be with [libp2p](https://github.com/libp2p/js-libp2p) which in the end must take care of closing all connections / removing tcp listeners. There are several closed but also open issues regarding connections not being closed properly.
- https://github.com/libp2p/js-libp2p/issues/433
- https://github.com/libp2p/js-libp2p/issues/436

This comment https://github.com/libp2p/js-libp2p/issues/436#issuecomment-432624680 summarizes open tasks but there was no progress in a while.

### Operating system

Linux

### Lodestar version or commit hash

ec8153153c83d082cb89fca682d502e709e3f415

### PR DESCRIPTION
**Pull request by nazarhussain**
**Motivation**

Gracefully shutdown the node. 

**Description**

- It's observed that the network worker thread didn't shutdown properly 
- Semantic observation leads to fact that it take more time to cleanup event handlers 
- Added retry for exit strategy  

Closes #5775

**Steps to test or reproduce**

Run all tests.

### CODE REVIEW

File: packages/beacon-node/src/network/core/networkCoreWorker.ts [hunk 1]
```diff
@@ -120,9 +120,9 @@ wireEventsOnWorkerThread<ReqRespBridgeEventData>(
 );
 
 const libp2pWorkerApi: NetworkWorkerApi = {
-  close: () => {
+  close: async () => {
```
Comment (nflaig) [inline packages/beacon-node/src/network/core/networkCoreWorker.ts:123]: does this change make a difference? I would assume this just creates an extra promise without any benefit

File: packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts [hunk 2]
```diff
@@ -47,10 +47,13 @@ export type WorkerNetworkCoreInitModules = {
 };
 
 type WorkerNetworkCoreModules = WorkerNetworkCoreInitModules & {
-  workerApi: NetworkWorkerApi;
+  networkApiThread: ModuleThread<NetworkWorkerApi>;
   worker: Worker;
 };
 
+const networkWorkerExitTimeoutMs = 1000;
```
Comment (nflaig) [inline packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts]: could consider using CONSTANT_CASE for those values

File: packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts [hunk 3]
```diff
@@ -81,6 +84,10 @@ export class WorkerNetworkCore implements INetworkCore {
       reqRespBridgeEventDirection
     );
 
+    Thread.errors(modules.networkApiThread).subscribe((err) => {
+      this.modules.logger.error("Network worker thread error", undefined, err);
```
Comment (nflaig) [inline packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts]: I think we usually pass an empty object if there is no context, result would be the same but for consistency reasons might wanna update this

```suggestion
      this.modules.logger.error("Network worker thread error", {}, err);
```

File: packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts [hunk 4]
```diff
@@ -124,24 +131,29 @@ export class WorkerNetworkCore implements INetworkCore {
     } as ConstructorParameters<typeof Worker>[1]);
 
     // eslint-disable-next-line @typescript-eslint/no-explicit-any
-    const workerApi = (await spawn<any>(worker, {
+    const networkApiThread = (await spawn<any>(worker, {
```
Comment (nflaig) [inline packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts]: This is the api object of the network thread, would suggest renaming it

```suggestion
    const networkThreadApi = (await spawn<any>(worker, {
```

File: packages/beacon-node/src/network/core/types.ts [hunk 5]
```diff
@@ -87,6 +87,9 @@ export type NetworkWorkerData = {
  * API exposed by the libp2p worker
  */
 export type NetworkWorkerApi = INetworkCorePublic & {
+  // To satisfy the constraint of `ModuleThread` type
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  [string: string]: (...args: any[]) => Promise<any> | any;
```
Comment (nflaig) [inline packages/beacon-node/src/network/core/types.ts:92]: don't we lose type safety when consuming the API? Type casting in some other place might be preferable

File: packages/beacon-node/src/network/core/networkCoreWorker.ts (hunk 1 above)
Comment (nazarhussain) [reply packages/beacon-node/src/network/core/networkCoreWorker.ts:123]: It's always better to await a promise instead of returning promise from a non-async function. As we don't know the library implementation may be handling based on `AsyncFunction` constructor type. If we return promise from a non-async function it's constructor type remains `Function`. This could lead to some weird edge cases.

File: packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts (hunk 4 above)
Comment (nazarhussain) [reply packages/beacon-node/src/network/core/networkCoreWorkerHandler.ts:134]: It's actually a thread object. So I felt this name is more accurate.

File: packages/beacon-node/src/network/core/types.ts (hunk 5 above)
Comment (nazarhussain) [reply packages/beacon-node/src/network/core/types.ts:92]: No we still have type safety, just that we don't have to do `as unknown as ` when using in threads library.

**Review by nflaig — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.12.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.12.0) :tada:
