### PR TITLE
Correct the validation of AggregateAndProof

### LINKED ISSUE #691: AggregateAndProof gossip validation isn't working
To reproduce:
- uncomment validation
- run and connect two beacon nodes as per readme

My best guess is that we should fetch state/advance state matching attestation slot or something

### PR DESCRIPTION
**Pull request by twoeths**
## Goal
+ Close #691 
+ Replace #709

### CODE REVIEW

File: packages/lodestar/src/network/gossip/validator.ts [hunk 1]
```diff
@@ -101,48 +106,49 @@ export class GossipMessageValidator implements IGossipMessageValidator {
...
+    const attestorIndices = getAttestingIndices(this.config, state,
+      aggregationAndProof.aggregate.data, aggregationAndProof.aggregate.aggregationBits);
+    if (!attestorIndices.includes(aggregationAndProof.aggregatorIndex)) {
+      return false;
+    }
+    if (!isAggregator(
+      this.config,
+      state,
+      slot,
+      aggregationAndProof.aggregate.data.index,
```
Comment (twoeths) [inline packages/lodestar/src/network/gossip/validator.ts:136]: the main fix

**Review by wemeetagain — APPROVED** [review]
