### PR TITLE
Regular sync: find best peer at startup and use it

### LINKED ISSUE #1234: Regular Sync: some peers are out-of-sync
**Describe the bug**
In my environment, I can sync to gossip parent blocks 5-6 times. However there are 1-2 times I cannot do that because we sent `beacon_block_by_range` requests to out-of-date peers. 
```
2020-07-26 21:56:28  [SYNC]             info: Requesting blocks from slot 194977 to slot 195131
2020-07-26 21:56:28  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmUghihDaHutopxWPoxjUedJZBLVuuP1NBDq2LfpQZTnad requestId=3fb6e9d3489b0875, encoding=ssz_snappy
2020-07-26 21:56:28  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAm2BfJQmNSNdAtGfJLH1CyQKKRVr425uJgrSq9ps8TLJe2 requestId=c618c049d122bcee, encoding=ssz_snappy
...
2020-07-26 21:56:29  [NETWORK]       verbose: receive beacon_blocks_by_range response with 0 chunks from 16Uiu2HAmUghihDaHutopxWPoxjUedJZBLVuuP1NBDq2LfpQZTnad requestId=3fb6e9d3489b0875, encoding=ssz_snappy, body={"startSlot":194977,"step":1,"count":78}
2020-07-26 21:56:31  [NETWORK]       verbose: receive beacon_blocks_by_range response with 52 chunks from 16Uiu2HAm2BfJQmNSNdAtGfJLH1CyQKKRVr425uJgrSq9ps8TLJe2 requestId=c618c049d122bcee, encoding=ssz_snappy, body={"startSlot":195055,"step":1,"count":77}
```

Since the 1st peer above returned 0 chunk because it's not up to date, we cannot process any blocks. So we have to filter to up-to-date peers only.

There are 2 ways I can think of:
+ Filter based on headSlot of Status message, send status messages at init time of regular sync. This maybe does not work if peers have `headSlot` not equal to `currentSlot`
+ Find a way to keep peerIds of gossip blocks and just get peers based on that - but a peer's chain may not be up to date even it published gossip blocks

### PR DESCRIPTION
**Pull request by twoeths**
+ resolves #1234 
+ remove `onNewSlot` as it may cause missing blocks and we can process chain up to head()

At regular sync, if we query blocks from multiple peers we may get blocks from different forkchoice branch so we'll *not* be able to sync to head in that case.
This PR helps find best peer at Regular Sync start time and use it as the only peer.

image

### CODE REVIEW

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 1]
```diff
@@ -154,12 +166,39 @@ export class NaiveRegularSync implements IRegularSync {
...
+      // bestPeer disconnected
+      this.bestPeer = undefined;
+      await this.waitForBestPeer();
+    }
+    return [this.bestPeer];
+  };
+
+  private waitForBestPeer = async (): Promise<void> => {
+    // check 2 times per slot
+    const waitingTime = this.config.params.SECONDS_PER_SLOT * 1000 / 2;
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/regular/naive/naive.ts]: Isn't this too often? How often does other clients refresh sync status?

Maybe we should run status update as daemon somewhere else?

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 2]
```diff
@@ -154,12 +171,41 @@ export class NaiveRegularSync implements IRegularSync {
...
+    if (!this.network.getPeers().includes(this.bestPeer)) {
+      // bestPeer disconnected
+      this.bestPeer = undefined;
+      await this.waitForBestPeer();
+    }
+    return [this.bestPeer];
+  };
+
+  private waitForBestPeer = async (): Promise<void> => {
+    // check every slot
```
Comment (wemeetagain) [inline packages/lodestar/src/sync/regular/naive/naive.ts]: Can we only send a status if our head slot is < getCurrentSlot to avoid spamming peers?

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 3]
```diff
@@ -154,12 +171,41 @@ export class NaiveRegularSync implements IRegularSync {
...
+      const peers = this.network.getPeers();
+      const previousSlot = getCurrentSlot(this.config, state.genesisTime) - 1;
+      await syncPeersStatus(this.reps, this.network, status);
+      const maxHeadSlot = Math.max(...peers.map(
+        (peerId) => this.reps.get(peerId.toB58String()).latestStatus?.headSlot || 0));
+      this.bestPeer = peers.find(peerId => {
+        const headSlot = this.reps.get(peerId.toB58String()).latestStatus?.headSlot;
+        return headSlot >= previousSlot && headSlot === maxHeadSlot;
+      });
+      await sleep(waitingTime);
```
Comment (wemeetagain) [inline packages/lodestar/src/sync/regular/naive/naive.ts:189]: should we be waiting _before_ we send statuses, so we get a more current status?

File: packages/lodestar/src/sync/regular/naive/naive.ts (hunk 2 above)
Comment (twoeths) [reply packages/lodestar/src/sync/regular/naive/naive.ts]: I checked that in start() so if we detect genesis at the same time with other peer we don't call `waitForBestPeer` and finish RegularSync immediately

File: packages/lodestar/src/sync/regular/naive/naive.ts (hunk 1 above)
Comment (twoeths) [reply packages/lodestar/src/sync/regular/naive/naive.ts]: I changed `waitingTime` to per slot as it's more reasonable.

I'm not sure the need to create a daemon for now unless we want to prepare something for the future. In that case we'll decide the waitingTime depending on different use cases for it.

For this use case, we just need this for a short period, created `syncPeersStatus()` util for it.

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 4]
```diff
@@ -154,12 +169,43 @@ export class NaiveRegularSync implements IRegularSync {
...
-        validPeers.push(peer);
+    if (!this.network.getPeers().includes(this.bestPeer)) {
+      // bestPeer disconnected
+      this.bestPeer = undefined;
+      await this.waitForBestPeer();
+    }
+    return [this.bestPeer];
+  };
+
+  private waitForBestPeer = async (): Promise<void> => {
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/regular/naive/naive.ts]: Can we make this cleaner like have two functions:
getBestHead(currentSlot, peers, reps): {root, slot} // highest slot
getBestPeer(root, reps): PeerId // takes all peers with this headRoot and get one with best score (once we land new gossipsub, take random for now)



Those methods should be standalone so we can test them properly

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 5]
```diff
@@ -154,12 +169,43 @@ export class NaiveRegularSync implements IRegularSync {
...
+    this.controller.signal.addEventListener("abort", () => {
+      this.logger.verbose("RegularSync: Abort waitForBestPeer");
+      isAborted = true;
+    });
+    while (!this.bestPeer && !isAborted) {
+      // wait first to make sure we have latest status
+      await sleep(waitingTime);
+      const status = createStatus(this.chain);
+      const previousSlot = getCurrentSlot(this.config, state.genesisTime) - 1;
+      await syncPeersStatus(this.reps, this.network, status);
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/regular/naive/naive.ts]: I would separate process of obtaining status so it's running during both initial and regular sync on some time interval

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 6]
```diff
@@ -154,12 +169,43 @@ export class NaiveRegularSync implements IRegularSync {
...
+      await this.waitForBestPeer();
+    }
+    return [this.bestPeer];
+  };
+
+  private waitForBestPeer = async (): Promise<void> => {
+    // check every slot
+    const waitingTime = this.config.params.SECONDS_PER_SLOT * 1000;
+    const state = await this.chain.getHeadState();
+    this.controller = new AbortController();
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/regular/naive/naive.ts]: this method should just take signal

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 7]
```diff
@@ -52,9 +57,17 @@ export class NaiveRegularSync implements IRegularSync {
     this.logger.info("Started regular syncing");
     this.chain.on("processedBlock", this.onProcessedBlock);
     this.currentTarget = this.chain.forkChoice.headBlockSlot();
+    const state = await this.chain.getHeadState();
+    this.slotAtStart = getCurrentSlot(this.config, state.genesisTime);
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/regular/naive/naive.ts]: Does this work if there are a lot of skip slots?

Why not start gossip as soon as regular sync starts?

Comment (twoeths) [reply packages/lodestar/src/sync/regular/naive/naive.ts]: Gossip is started as soon as regular sync starts, this is all about listen for its event.
I'll change to listen in start bc I removed `onNewSlot` already, this would make it simpler

File: packages/lodestar/src/sync/utils/sync.ts [hunk 8]
```diff
@@ -213,4 +213,18 @@ export async function syncPeersStatus(reps: IReputationStore, network: INetwork,
...
+}
+
+export function getBestHead(peers: PeerId[], reps: IReputationStore): number {
+  return Math.max(...peers.map(
+    (peerId) => reps.get(peerId.toB58String()).latestStatus?.headSlot || 0));
+}
+
+// should add peer score later
+export function getBestPeer(peers: PeerId[], reps: IReputationStore): PeerId {
+  const bestHead = getBestHead(peers, reps);
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/utils/sync.ts]: receive targetHead as param and compare root, not slot

File: packages/lodestar/src/sync/regular/naive/naive.ts [hunk 9]
```diff
@@ -58,16 +58,18 @@ export class NaiveRegularSync implements IRegularSync {
     this.chain.on("processedBlock", this.onProcessedBlock);
     this.currentTarget = this.chain.forkChoice.headBlockSlot();
```
Comment (mpetrunic) [inline packages/lodestar/src/sync/regular/naive/naive.ts]: can we store it in const headSlot, so code below is more clearer.

I was so confused that target larger than current slot means we are synced :smile:

**Review by wemeetagain — DISMISSED** [review]

**Comment by wemeetagain** [comment]
file conflict

**Review by wemeetagain — APPROVED** [review]
