### PR TITLE
fix: add slot and epoch validation to epoch committees endpoint

### LINKED ISSUE #7882: Inconsistent Response of Endpoint `/eth/v1/beacon/states/{state_id}/committees`
### Describe the bug

Hello developers,

I am conducting API differential testing on an Electra PoS devnet chain and noticed inconsistencies in the Beacon-API responses across Prysm, Lighthouse, Nimbus, Teku, Lodestar and Grandine. 

Specifically, when calling the endpoint `/eth/v1/beacon/states/{state_id}/committees` with invalid epoch and slot, Lodestar will return `500` instead of `400` defined as `Invalid state ID, index, epoch, slot, or combination thereof` in the [schema](https://ethereum.github.io/beacon-APIs/#/Beacon/getEpochCommittees).

Thanks for your time!

### Expected behavior

Return `400` 

### Steps to reproduce

Call `/eth/v1/beacon/states/{state_id}/committees` with slot not in given epoch, e.g.,`{'epoch': 2, 'index': 16, 'slot': 118}`.

```shell
{"data": [], "execution_optimistic": false, "finalized": false, "server": "http://127.0.0.1:8147"} # Prysm
{"code":400,"message":"BAD_REQUEST: 118 is not in epoch 2","stacktraces":[]} # lighthouse
{"code":400,"message":"Slot 118 is not in epoch 2"} # teku
{"code":400,"message":"Invalid slot value","stacktraces":["Slot does not match requested epoch"]} # nimbus
{"code":500,"message":"EPOCH_CONTEXT_ERROR_DECISION_ROOT_EPOCH_OUT_OF_RANGE"} # lodestar
{"code":400,"message":"slot does not belong in epoch"} # grandine
```

### Additional context

Similar to #7843, it seems that Lodestar defines many domain-specific error types that differ from the standardized error formats used by other clients.

### Operating system

Linux

### Lodestar version or commit hash

Lodestar/v1.30.0/1a34f98

### PR DESCRIPTION
**Pull request by bomanaps**
**Motivation**

**Description**
This PR fixes an inconsistency in Lodestar's Beacon-API behavior when querying:
```
curl "http://127.0.0.1:9596/eth/v1/beacon/states/head/committees?epoch=2&slot=118"
```
Previously, Lodestar would return a `500 Internal Server Error` when the provided slot did not belong to the given epoch (e.g., `epoch=2&slot=118`), due to an unhandled `EPOCH_CONTEXT_ERROR_DECISION_ROOT_EPOCH_OUT_OF_RANGE` error.

Screenshot 2025-06-10 at 08 15 05

Screenshot 2025-06-10 at 08 14 33

Closes https://github.com/ChainSafe/lodestar/issues/7882

**Steps to test or reproduce**

### CODE REVIEW

**Comment by bomanaps** [comment]
Hello @nflaig Could you please review this when you have time?

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 1]
```diff
@@ -252,8 +252,31 @@ export function getBeaconStateApi({
...
-      const decisionRoot = stateCached.epochCtx.getShufflingDecisionRoot(epoch);
+      let decisionRoot: string;
+      try {
+        decisionRoot = stateCached.epochCtx.getShufflingDecisionRoot(epoch);
+      } catch (error) {
+        if (error instanceof Error && error.message?.includes("EPOCH_CONTEXT_ERROR_DECISION_ROOT_EPOCH_OUT_OF_RANGE")) {
+          throw new ApiError(400, `Invalid epoch value: epoch ${epoch} is out of range`);
+        }
+        if (typeof error === "string" && error.includes("EPOCH_CONTEXT_ERROR_DECISION_ROOT_EPOCH_OUT_OF_RANGE")) {
+          throw new ApiError(400, `Invalid epoch value: epoch ${epoch} is out of range`);
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: why would error be type of `string`?

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 2]
```diff
@@ -252,8 +252,31 @@ export function getBeaconStateApi({
...
+        const epochStartSlot = computeStartSlotAtEpoch(epoch);
+        const epochEndSlot = epochStartSlot + 32 - 1;
+
+        if (filters.slot < epochStartSlot || filters.slot > epochEndSlot) {
+          throw new ApiError(400, `Slot ${filters.slot} is not in epoch ${epoch}`);
+        }
+      }
+      if (Math.abs(epoch - currentEpoch) > 2) {
+        throw new ApiError(400, `Invalid epoch value: epoch ${epoch} is out of range`);
+      }
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: does this api always throw if you request more than 2 epochs in the past?

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 3]
```diff
@@ -252,8 +252,31 @@ export function getBeaconStateApi({
...
+      const currentEpoch = computeEpochAtSlot(state.slot);
+      if (filters.slot !== undefined) {
+        const epochStartSlot = computeStartSlotAtEpoch(epoch);
+        const epochEndSlot = epochStartSlot + 32 - 1;
+
+        if (filters.slot < epochStartSlot || filters.slot > epochEndSlot) {
+          throw new ApiError(400, `Slot ${filters.slot} is not in epoch ${epoch}`);
+        }
+      }
+      if (Math.abs(epoch - currentEpoch) > 2) {
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: why do we need `Math.abs` here?

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 4]
```diff
@@ -252,8 +252,31 @@ export function getBeaconStateApi({
       }
 
       const epoch = filters.epoch ?? computeEpochAtSlot(state.slot);
+      const currentEpoch = computeEpochAtSlot(state.slot);
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: can potentially avoid call to `computeEpochAtSlot` here

```suggestion
      const stateEpoch = computeEpochAtSlot(state.slot);
      const epoch = filters.epoch ?? stateEpoch;
```

also this is the epoch of the state, not the current epoch (based on clock)

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 5]
```diff
@@ -252,8 +252,31 @@ export function getBeaconStateApi({
...
+      }
+      if (Math.abs(epoch - currentEpoch) > 2) {
+        throw new ApiError(400, `Invalid epoch value: epoch ${epoch} is out of range`);
+      }
       const startSlot = computeStartSlotAtEpoch(epoch);
-      const decisionRoot = stateCached.epochCtx.getShufflingDecisionRoot(epoch);
+      let decisionRoot: string;
+      try {
+        decisionRoot = stateCached.epochCtx.getShufflingDecisionRoot(epoch);
+      } catch (error) {
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: I don't really understand why we need to catch the error here, what queries trigger this code path?

**Comment by nflaig** [comment]
@bomanaps are you planning to continue working on this? it resolves an error we see on the devnet as well and would be good to get this in soon

File: packages/beacon-node/src/api/impl/beacon/state/index.ts (hunk 2 above)
Comment (bomanaps) [reply packages/beacon-node/src/api/impl/beacon/state/index.ts]: Yes, the API always throws if you request more than 2 epochs in the past or future.

File: packages/beacon-node/src/api/impl/beacon/state/index.ts (hunk 3 above)
Comment (bomanaps) [reply packages/beacon-node/src/api/impl/beacon/state/index.ts]: Without Math.abs(), the check would only allow future epochs.

Comment (nflaig) [reply packages/beacon-node/src/api/impl/beacon/state/index.ts]: ah right was reading this wrong, you are checking here if epoch is within range (-2,+2)

I am not sure we can support -2 and +2 of current epoch though as `getShufflingDecisionRoot` only has previous decision root (current epoch -1) and not for 2 epochs in the past

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 6]
```diff
@@ -254,8 +254,28 @@ export function getBeaconStateApi({
...
+        if (error instanceof Error && error.message?.includes("EPOCH_CONTEXT_ERROR_DECISION_ROOT_EPOCH_OUT_OF_RANGE")) {
+          throw new ApiError(400, `Invalid epoch value: epoch ${epoch} is out of range`);
+        }
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: as noted in https://github.com/ChainSafe/lodestar/pull/7941#discussion_r2215850764 I don't see why this is necessary, we check the epoch above to make sure it's within one epoch of state epoch

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 7]
```diff
@@ -254,8 +254,28 @@ export function getBeaconStateApi({
       }
 
       const epoch = filters.epoch ?? computeEpochAtSlot(state.slot);
+      const stateEpoch = computeEpochAtSlot(state.slot);
+      if (filters.slot !== undefined) {
+        const epochStartSlot = computeStartSlotAtEpoch(epoch);
+        const epochEndSlot = epochStartSlot + 32 - 1;
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: this will break with minimal preset as an epoch only has 8 slots, always need to use `SLOTS_PER_EPOCH`

File: packages/beacon-node/src/api/impl/beacon/state/index.ts [hunk 8]
```diff
@@ -254,8 +254,28 @@ export function getBeaconStateApi({
...
+
+        if (filters.slot < epochStartSlot || filters.slot > epochEndSlot) {
+          throw new ApiError(400, `Slot ${filters.slot} is not in epoch ${epoch}`);
+        }
+      }
+      if (Math.abs(epoch - stateEpoch) > 1) {
+        throw new ApiError(400, `Invalid epoch value: epoch ${epoch} is out of range`);
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/beacon/state/index.ts]: would be useful to return state epoch and explain in the error that the epoch needs to be within one epoch, "out of range" doesn't provide enough details imo

**Review by nflaig — DISMISSED** [review]
LGTM - I addressed all comments from above, the change is much simpler now as well, thanks @bomanaps for looking into this

**Review by nflaig — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.34.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.34.0) :tada:
