### PR TITLE
fix: use expected withdrawals from state when parent is empty

### LINKED ISSUE #8953: Update expected withdrawals in gloas payload attributes
this seems like a valid finding, need to revisit after merging fork choice changes to unstable

_Originally posted by @nflaig in https://github.com/ChainSafe/lodestar/pull/8947#discussion_r2847524448_

### PR DESCRIPTION
**Pull request by nflaig**
See https://github.com/ethereum/consensus-specs/pull/5069, we already handle this correctly on `epbs-devnet-0` branch but we haven't brought this change to `unstable` branch yet.

Closes https://github.com/ChainSafe/lodestar/issues/8953

### CODE REVIEW

File: packages/state-transition/src/stateView/beaconStateView.ts [hunk 1]
```diff
@@ -361,7 +362,7 @@ export class BeaconStateView implements IBeaconStateViewLatestFork {
 
   get executionPayloadAvailability(): BitArray {
     if (this.config.getForkSeq(this.cachedState.slot) < ForkSeq.gloas) {
-      throw new Error("executionPayloadAvailability is not available before GLOAS");
+      throw new Error("executionPayloadAvailability is not available before Gloas");
```
Comment (nflaig) [inline packages/state-transition/src/stateView/beaconStateView.ts:365]: unrelated change but aligns with existing fork casing (in this file), and all caps felt a bit off

File: packages/state-transition/src/util/gloas.ts [hunk 2]
```diff
@@ -167,6 +168,6 @@ export function isAttestationSameSlotRootCache(rootCache: RootCache, data: Attes
   return isMatchingBlockRoot && isCurrentBlockRoot;
 }
 
-export function isParentBlockFull(state: CachedBeaconStateGloas): boolean {
+export function isParentBlockFull(state: CachedBeaconStateGloas | IBeaconStateViewGloas): boolean {
```
Comment (nflaig) [inline packages/state-transition/src/util/gloas.ts:171]: since this is part of `state-transition` package, the union type feels like the right solution

**Review by matthewkeil — COMMENTED** [review]
Looked at this but think its best for @twoeths to review this

**Review by ensi321 — APPROVED** [review]

**Review by twoeths — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.43.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.43.0) :tada:
