### PR TITLE
fix: no state id finalized

### LINKED ISSUE #6583: No state found for id 'finalized'
### Describe the bug

Got this error
```
curl http://localhost:9596/eth/v1/beacon/states/finalized/validators/1
{"statusCode":404,"error":"Not Found","message":"No state found for id 'finalized'"}
```

but this works fine
```
curl http://localhost:9596/eth/v1/beacon/states/head/validators/1
{"data":{"index":"1","balance":"32001746428","status":"active_ongoing","validator":{"pubkey":"0xa1d1ad0714035353258038e964ae9675dc0252ee22cea896825c01458e1807bfad2f9969338798548d9858a571f7425c","withdrawal_credentials":"0x01000000000000000000000015f4b914a0ccd14333d850ff311d6dafbfbaa32b","effective_balance":"32000000000","slashed":false,"activation_eligibility_epoch":"0","activation_epoch":"0","exit_epoch":"18446744073709551615","withdrawable_epoch":"18446744073709551615"}},"execution_optimistic":false}
```

cc @Faithtosin 

### Expected behavior

No error

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.17.0

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- Right now we get the finalized state from block state cache but it's not guaranteed we have it there because it ranges between 96 states - 128 states

**Description**

- Get from the checkpoint state cache instead, this does not work with n-historical state flag but will address that later in a separate issue
- Rename the current/old checkpoint state cache file to `inMemoryCheckpointsCache.ts` to reflect the class name

Closes #6583

### CODE REVIEW

**Comment by twoeths** [comment]
deployed to a node, this works fine

```
curl http://localhost:9596/eth/v1/beacon/states/finalized/validators/1
{"data":{"index":"1","balance":"32002032576","status":"active_ongoing","validator":{"pubkey":"0xa1d1ad0714035353258038e964ae9675dc0252ee22cea896825c01458e1807bfad2f9969338798548d9858a571f7425c","withdrawal_credentials":"0x01000000000000000000000015f4b914a0ccd14333d850ff311d6dafbfbaa32b","effective_balance":"32000000000","slashed":false,"activation_eligibility_epoch":"0","activation_epoch":"0","exit_epoch":"18446744073709551615","withdrawable_epoch":"18446744073709551615"}},"execution_optimistic":false}
```

File: packages/beacon-node/src/chain/stateCache/inMemoryCheckpointsCache.ts [hunk 1]
```diff
@@ -21,11 +21,15 @@ export class InMemoryCheckpointStateCache implements CheckpointStateCache {
...
+  /**
+   * Max number of epochs allowed in the cache
+   */
+  private readonly maxEpochs: number;
   private readonly metrics: Metrics["cpStateCache"] | null | undefined;
   private preComputedCheckpoint: string | null = null;
   private preComputedCheckpointHits: number | null = null;
 
-  constructor({metrics}: {metrics?: Metrics | null}) {
+  constructor({maxEpochs = MAX_EPOCHS, metrics}: {maxEpochs?: number; metrics?: Metrics | null}) {
```
Comment (nflaig) [inline packages/beacon-node/src/chain/stateCache/inMemoryCheckpointsCache.ts]: could consider separating options from modules here

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada:
