### PR TITLE
Fix inconsistent block import

### LINKED ISSUE #4700: headState does not exist
Report from discord: https://discord.com/channels/593655374469660673/743858262864167062/1035585735983644702

`version=v1.1.1/9d07393, commit=9d07393709f6a870f9eeda9bca7a9
5196ca67c68`

```
Oct-28 15:55:18.000[]                error: Node notifier error  headState does not exist
Error: headState does not exist
    at BeaconChain.getHeadState (file:///usr/app/packages/beacon-node/src/chain/chain.ts:319:27)
    at runNodeNotifier (file:///usr/app/packages/beacon-node/src/node/notifier.ts:55:31)
```

We thought this was fixed in v1.1.0:
- https://github.com/ChainSafe/lodestar/issues/4523

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- Block was imported to forkchoice but not to hot db and state cache
- The issue is old head was removed from forkchoice, hence got error in `forkChoice.getCommonAncestorDistance`

**Description**

- Cache error of this call `forkChoice.getCommonAncestorDistance`

Closes #4700

### CODE REVIEW

File: packages/beacon-node/src/chain/chain.ts [hunk 1]
```diff
@@ -330,7 +330,7 @@ export class BeaconChain implements IBeaconChain {
     const head = this.forkChoice.getHead();
     const headState =
       this.checkpointStateCache.getLatest(head.blockRoot, Infinity) || this.stateCache.get(head.stateRoot);
-    if (!headState) throw Error("headState does not exist");
+    if (!headState) throw Error("headState does not exist, headSlot=" + head.slot);
```
Comment (dapplion) [inline packages/beacon-node/src/chain/chain.ts]:
```suggestion
    if (!headState) {
      throw Error(`headState does not exist for head root=${head.root} slot=${head.slot}`);
    }
```

**Review by wemeetagain — DISMISSED** [review]

File: packages/beacon-node/src/chain/chain.ts [hunk 2]
```diff
@@ -330,7 +330,9 @@ export class BeaconChain implements IBeaconChain {
     const head = this.forkChoice.getHead();
     const headState =
       this.checkpointStateCache.getLatest(head.blockRoot, Infinity) || this.stateCache.get(head.stateRoot);
-    if (!headState) throw Error("headState does not exist");
+    if (!headState) {
+      throw Error(`headState does not exist for head root=${head.root} slot=${head.slot}`);
```
Comment (wemeetagain) [inline packages/beacon-node/src/chain/chain.ts]:
```suggestion
      throw Error(`headState does not exist for head root=${head.blockRoot} slot=${head.slot}`);
```

**Review by dapplion — APPROVED** [review]
Changed getCommonAncestorDepth to not throw, instead return an enum status. That way the try catch is not necessary.
