### PR TITLE
fix: return available light client updates instead of throwing on missing periods

### LINKED ISSUE #8902: "No partialUpdate available" error for light client update period in the future
### Describe the bug

When light client updates are requested for a range that includes some future periods, Lodestar responds with status 500 and a message "No partialUpdate available for `<period>`"

I have stumbled upon this error it using a public node for Sepolia https://lodestar-sepolia.chainsafe.io/ and also another Lodestar node. I'm not running a node myself so can't really debug further.

The request I used: `GET 
https://lodestar-sepolia.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=1172&count=2`, 1172 is latest period at the moment of request.

### Expected behavior

Client should provide a status 200 response with light client updates it is able to, omitting future periods. According to spec:
> They MUST respond with at least the earliest known result within the requested range 

### Steps to reproduce

1. Identify latest sync committee period on Sepolia
2. send GET request to a lodestar node as follows `https://lodestar-sepolia.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=<latest_period>&count=<2 or more>`

Error is also reproducible on mainnet.

### Additional context

Please note that I am reporting this problem I stumbled upon while working on Helios light client and it has been reported by some of users. Helios basically always requests updates with `count=128`. Although it might not be the best idea, it's doesn't make the request invalid.

### PR DESCRIPTION
**Pull request by lodekeeper**
## Description

When `getLightClientUpdatesByRange` is called with a range that extends beyond the current sync committee period (e.g., `start_period=1172&count=128` where 1172 is the latest period), it returns a 500 error because `Promise.all` rejects when any period throws `No partialUpdate available`.

Per the [beacon API spec](https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/light_client/updates.yaml):
> Servers MUST respond with at least the earliest known result within the requested range, and MUST send results in consecutive order (by period).

### Changes

**`getUpdate()` — consistent error type:**
- Now throws `LightClientServerError(RESOURCE_UNAVAILABLE)` instead of generic `Error`, consistent with all other light client server methods (`getBootstrap`, `getCommitteeRoot`)

**REST API handler (`/eth/v1/beacon/light_client/updates`):**
- Replaces `Promise.all` with sequential iteration
- Skips leading unavailable periods to find the earliest known result in the range
- Collects consecutive updates until a gap is hit
- Only catches `RESOURCE_UNAVAILABLE`; unexpected errors are rethrown (no silent swallowing)
- Returns empty array (not 500) if no updates exist in range

**P2P req/resp handler (`light_client_updates_by_range`):**
- Stops yielding gracefully on unavailable periods instead of throwing `RESOURCE_UNAVAILABLE` error response
- Also skips leading gaps, matching the spec semantics

### Before
```
GET /eth/v1/beacon/light_client/updates?start_period=1172&count=2
→ 500: "No partialUpdate available for 1173"
```

### After
```
GET /eth/v1/beacon/light_client/updates?start_period=1172&count=2
→ 200: [update for period 1172]
```

Closes #8902

> [!NOTE]
> This PR was authored with AI assistance 🤖

### CODE REVIEW

File: packages/beacon-node/src/api/impl/lightclient/index.ts [hunk 1]
```diff
@@ -16,8 +17,22 @@ export function getLightclientApi({
...
+        } catch (_e) {
+          // Stop collecting once we hit a period with no available update.
+          // Spec: results MUST be sent in consecutive order (by period).
+          break;
+        }
+      }
+
+      if (updates.length === 0) {
+        throw Error("No light client updates available in requested range");
+      }
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/api/impl/lightclient/index.ts]: The `Promise.allSettled` suggestion wouldn't work here for two reasons:

1. **Skipping leading gaps**: The spec says to return "at least the earliest known result within the requested range." If `start_period` is unavailable but `start_period+1` exists, we need to skip the gap — `allSettled` + break-on-first-failure would return empty instead.

2. **Error discrimination**: We only want to treat `RESOURCE_UNAVAILABLE` as "missing period." `allSettled` loses the ability to distinguish that from unexpected errors (DB corruption, etc.) that should propagate as 500s.

The sequential approach also avoids wasting work fetching periods we'll never use (e.g., `count=128` but only 1 period exists). Each `getUpdate()` is a single DB read so the overhead is negligible.

[the remark this answers is not in the document]
Comment (nflaig) [reply packages/beacon-node/src/api/impl/lightclient/index.ts]: @gemini-code-assist ^^

File: packages/beacon-node/src/api/impl/lightclient/index.ts [hunk 2]
```diff
@@ -16,8 +18,23 @@ export function getLightclientApi({
...
+          const update = await lightClientServer.getUpdate(startPeriod + i);
+          updates.push(update);
+        } catch (e) {
+          if ((e as LightClientServerError).type?.code === LightClientServerErrorCode.RESOURCE_UNAVAILABLE) {
+            // Period not available — if we already have results, stop to preserve
+            // consecutive order. If not, skip and try the next period.
+            if (updates.length > 0) break;
+            continue;
+          }
+          // Unexpected error — rethrow
```
Comment (nflaig) [inline packages/beacon-node/src/api/impl/lightclient/index.ts]:
```suggestion
          if ((e as LightClientServerError).type?.code === LightClientServerErrorCode.RESOURCE_UNAVAILABLE) {
            // Period not available, if we already have results, stop to preserve
            // consecutive order. If not, skip and try the next period.
            if (updates.length > 0) break;
            continue;
          }
          // Unexpected error
```

Comment (lodekeeper) [reply packages/beacon-node/src/api/impl/lightclient/index.ts]: Applied, thanks!

File: packages/beacon-node/src/network/reqresp/handlers/lightClientUpdatesByRange.ts [hunk 3]
```diff
@@ -29,9 +30,13 @@ export async function* onLightClientUpdatesByRange(
         data: type.serialize(update),
         boundary,
       };
+      started = true;
     } catch (e) {
       if ((e as LightClientServerError).type?.code === LightClientServerErrorCode.RESOURCE_UNAVAILABLE) {
-        throw new ResponseError(RespStatus.RESOURCE_UNAVAILABLE, (e as Error).message);
+        // Period not available — if we already started yielding, stop to
+        // preserve consecutive order. Otherwise skip leading gaps.
```
Comment (nflaig) [inline packages/beacon-node/src/network/reqresp/handlers/lightClientUpdatesByRange.ts]:
```suggestion
        // Period not available, if we already started yielding, stop to
        // preserve consecutive order. Otherwise skip leading gaps.
```

Comment (lodekeeper) [reply packages/beacon-node/src/network/reqresp/handlers/lightClientUpdatesByRange.ts]: Applied, thanks!

File: packages/beacon-node/src/api/impl/lightclient/index.ts [hunk 4]
```diff
@@ -16,8 +18,23 @@ export function getLightclientApi({
...
+          if ((e as LightClientServerError).type?.code === LightClientServerErrorCode.RESOURCE_UNAVAILABLE) {
+            // Period not available, if we already have results, stop to preserve
+            // consecutive order. If not, skip and try the next period.
+            if (updates.length > 0) break;
+            continue;
+          }
+          // Unexpected error
+          throw e;
+        }
+      }
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/src/api/impl/lightclient/index.ts:36]: @gemini-code-assist This is the same suggestion addressed earlier in this thread — sequential fetching is intentional here for three reasons:

1. **Leading gap skipping**: If `start_period` is unavailable but `start_period+1` exists, we skip the gap. `allSettled` + break-on-first-rejected would return empty instead of the available updates.

2. **Error discrimination**: We only treat `RESOURCE_UNAVAILABLE` as a missing period. `allSettled` loses the ability to distinguish that from unexpected errors (DB corruption, etc.) that should propagate as 500s.

3. **Avoiding wasted work**: Each `getUpdate()` is a single DB read. If only 1 period exists out of 128 requested, sequential stops immediately rather than issuing 127 unnecessary reads.

You acknowledged these points on the earlier comment — the sequential approach is more robust and spec-compliant for this use case.

**Review by nflaig — APPROVED** [review]

**Comment by nflaig** [comment]
@codex review

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.41.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.41.0) :tada:
