### PR TITLE
fix: avoid recomputing indexed attestations during block import

### LINKED ISSUE #8625: Duplicate getIndexedAttestation() during verifying/importing blocks
### Describe the bug

from profile https://github.com/ChainSafe/lodestar/issues/8619#issuecomment-3559444831
we see that `getIndexedAttestation` takes some time in `importBlock()`, and this is a very hot time

Image

that time need to be 0 because we did that during verifying block signature https://github.com/ChainSafe/lodestar/blob/194afd5582965f9742cccc7c0254e433498b25b2/packages/beacon-node/src/chain/blocks/verifyBlock.ts#L130

### Expected behavior

enhance `FullyVerifiedBlock` to also include indexed attestations there so that it takes 0 time extracting it in `importBlock`

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.36.0

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

- https://github.com/ChainSafe/lodestar/issues/8625

**Description**

Store indexed attestations for each block during block/signature verification to avoid recomputing them during import
- compute `indexedAttestationsByBlock` once during verification
- enhance `FullyVerifiedBlock` to include indexed attestations for block import

Closes https://github.com/ChainSafe/lodestar/issues/8625

### CODE REVIEW

**Review by twoeths — DISMISSED** [review]
looks good to me
- on feat4 mainnet node

Image

- same type of node on unstable

Image

- same type of node on stable

Image

File: packages/beacon-node/src/chain/blocks/verifyBlock.ts [hunk 1]
```diff
@@ -89,6 +90,16 @@ export async function verifyBlocksInEpoch(
...
 
+  // Store indexed attestations for each block to avoid recomputing them during import
+  const indexedAttestationsByBlock: IndexedAttestation[][] = [];
+
+  for (const [i, block] of blocks.entries()) {
+    const fork = this.config.getForkSeq(block.message.slot);
+    indexedAttestationsByBlock[i] = block.message.body.attestations.map((attestation) =>
+      preState0.epochCtx.getIndexedAttestation(fork, attestation)
+    );
+  }
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/verifyBlock.ts]: possible concern computing indexed attestations here is that it's executed before batching I/O operations
https://github.com/ChainSafe/lodestar/blob/c75b47955a02b7b29e45814d78a69b1f45110813/packages/beacon-node/src/chain/blocks/verifyBlock.ts#L112

we could move it inside `verifyBlocksSignatures` and return `indexedAttestationsByBlock` from there. I am not really sure it makes a difference as it's a synchronous operation. 

@twoeths wdyt?

Comment (twoeths) [reply packages/beacon-node/src/chain/blocks/verifyBlock.ts]: yes it makes sense to do it, we should extract IndexedAttestation it after we call `verifyBlockExecutionPayload()` if possible

Comment (wemeetagain) [reply packages/beacon-node/src/chain/blocks/verifyBlock.ts]: imo fine here, no strong opinion tho

Comment (nflaig) [reply packages/beacon-node/src/chain/blocks/verifyBlock.ts]: resolved by https://github.com/ChainSafe/lodestar/pull/8637/commits/7ddf54585f3866f05fb2c74ed302a0729f94207e

**Review by wemeetagain — APPROVED** [review]

**Review by twoeths — APPROVED** [review]

**Comment by nflaig** [comment]
I redeployed this yesterday to `feat4`, import block time is reduced which is what this PR should improve

image

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.38.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.38.0) :tada:
