### PR TITLE
Do not check for know attesters when publishing AggregateAndProof

### LINKED ISSUE #4089: API rejects valid aggregates
**Describe the bug**

In hetzner-ropsten-0 we are running 2000 keys out of a 100,000 network. So the same beacon node is aggregating multiple times in the same subnet. This error happens frequently

- Probably caused by https://github.com/ChainSafe/lodestar/pull/4019

```
May-31 02:48:32.070[]                error: Error publishing aggregateAndProofs slot=3542, index=20 Internal Server Error: ATTESTATION_ERROR_ATTESTERS_ALREADY_KNOWN
Error: Internal Server Error: ATTESTATION_ERROR_ATTESTERS_ALREADY_KNOWN
    at HttpClient.request (file:///usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:108:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.json (file:///usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:70:12)
    at Object.request [as publishAggregateAndProofs] (file:///usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:74:19)
    at AttestationService.produceAndPublishAggregates (file:///usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:230:9)
    at async Promise.all (index 9)
    at AttestationService.runAttestationTasks (file:///usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:85:5)
    at Clock.runAtMostEvery (file:///usr/app/node_modules/@chainsafe/lodestar-validator/src/util/clock.ts:79:7)
```

**Expected behavior**

Should not error for valid aggregates but just return OK.

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Fix ropsten error
```
Error publishing aggregateAndProofs slot=3542, index=20 Internal Server Error: ATTESTATION_ERROR_ATTESTERS_ALREADY_KNOWN
Error: Internal Server Error: ATTESTATION_ERROR_ATTESTERS_ALREADY_KNOWN
```

**Description**

Due to #4019, we filter a lot of AggregateAndProof with known attesters. We should not have that check at api side.

Closes #4089

### CODE REVIEW

File: packages/lodestar/src/chain/validation/aggregateAndProof.ts [hunk 1]
```diff
@@ -14,7 +14,8 @@ import {getCommitteeIndices, verifyHeadBlockAndTargetRoot, verifyPropagationSlot
 
 export async function validateGossipAggregateAndProof(
   chain: IBeaconChain,
-  signedAggregateAndProof: phase0.SignedAggregateAndProof
+  signedAggregateAndProof: phase0.SignedAggregateAndProof,
+  validateKnownAttesters: boolean = true,
```
Comment (dapplion) [inline packages/lodestar/src/chain/validation/aggregateAndProof.ts]: I think it's best to have a default that's the falsy value. For example use as variable: `skipValidationKnownAttesters`

**Review by g11tech — APPROVED** [review]
