### PR TITLE
fix: genesis sync in peerDAS

### LINKED ISSUE #7754: peerDAS - cannot sync hoodi
### Describe the bug

I use `peerDAS` branch to sync from genesis, there are so many checkpoint states persisted and at some points disk run out of space

Image

`No space left on device`

```
ls checkpoint_states/ | wc -l
1243
```

### Expected behavior

no error, should be able to use peerDAS to sync hoodi from genesis

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

peerDAS

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- right now we cannot sync hoodi using `peerDAS`, this PR fixes it

**Description**

- when `archiveBlocks` if data is out of `MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS`, no need to archive blobs/data columns
Closes #7754

Screenshot 2025-04-29 at 09 19 09

### CODE REVIEW

File: packages/beacon-node/src/chain/archiveStore/utils/archiveBlocks.ts [hunk 1]
```diff
@@ -212,8 +218,15 @@ async function migrateBlobSidecarsFromHotToColdDb(
...
-          const blkSeq = config.getForkSeq(block.slot);
-          return blkSeq >= ForkSeq.deneb && blkSeq < ForkSeq.fulu;
+          const blockSlot = block.slot;
+          const blockEpoch = computeEpochAtSlot(blockSlot);
+          const forkSeq = config.getForkSeq(blockSlot);
+          return (
+            forkSeq >= ForkSeq.deneb &&
+            forkSeq < ForkSeq.fulu &&
+            // if block is out of ${config.MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS}, skip this step
+            blockEpoch >= currentEpoch - config.MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS
```
Comment (twoeths) [inline packages/beacon-node/src/chain/archiveStore/utils/archiveBlocks.ts:233]: this is main fix, refer to this in [unstable](https://github.com/ChainSafe/lodestar/blob/6dd10cbe48f61cf53e1cf01404d8b96386736df5/packages/beacon-node/src/chain/archiveStore/utils/archiveBlocks.ts#L185)

Comment (g11tech) [reply packages/beacon-node/src/chain/archiveStore/utils/archiveBlocks.ts:233]: is this change missing because of pending rebase?

Comment (matthewkeil) [reply packages/beacon-node/src/chain/archiveStore/utils/archiveBlocks.ts:233]: do we also need to add this same check to the columns?

```ts
    const canonicalDataColumnSidecarsEntries: KeyValue<Slot, Uint8Array>[] = await Promise.all(
      canonicalBlocks
        .filter((block) => config.getForkSeq(block.slot) >= ForkSeq.fulu)
```

**Review by matthewkeil — COMMENTED** [review]
Just the question about whether we need to also add the check to columns as well.

File: packages/beacon-node/src/chain/archiveStore/utils/archiveBlocks.ts (hunk 1 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/archiveStore/utils/archiveBlocks.ts:233]: @matthewkeil good catch, just added that

Comment (twoeths) [reply packages/beacon-node/src/chain/archiveStore/utils/archiveBlocks.ts:233]: @g11tech I can't trace which specific commit was it but think it's just merge/rebase issue

**Review by matthewkeil — APPROVED** [review]
LGTM!!  🚀

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.34.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.34.0) :tada:
