### PR TITLE
fix: avoid Buffer.from copies

### LINKED ISSUE #6688: Review `Buffer.from` usage
Review how `Buffer.from` is used within Lodestar, and check the following:
- is it required to convert to `Buffer` at all?
- can we convert to `Buffer` without memory copy?
- does it impact browser compatibility?

Eg. a good example of incorrect `Buffer.from` usage
https://github.com/ChainSafe/lodestar/blob/252fd2f50a7e759d53983286dcd89f9e7e8d5f60/packages/validator/src/slashingProtection/block/blockBySlotRepository.ts#L57
Which either should not be a `Buffer` at all as based on type a `Uint8Array` is valid, or if `Buffer` is required should avoid the memory copy.

Depending on the size of the `Uint8Array`, converting to `Buffer` with memory copy is quite expensive while without copy it's essentially free

From https://github.com/ChainSafe/lodestar/compare/unstable...nflaig/bench-buffer-from
```
Buffer utils
✔ Buffer.from - copy                  7.286412 ops/s    137.2418 ms/op   x1.024         38 runs   5.82 s
✔ Buffer.from - no copy                1117318 ops/s    895.0000 ns/op   x0.982     723013 runs   1.11 s
✔ Buffer.from - no copy with offset    1179245 ops/s    848.0000 ns/op        -    2699558 runs   3.85 s
```

Related https://github.com/ChainSafe/lodestar/pull/6687

### PR DESCRIPTION
**Pull request by wemeetagain**
**Motivation**

- Resolve #6688

**Description**

- Avoid `Buffer.from` copies in performance sensitive code, beacon-node, validator and dependencies (test folders left untouched)
- Replace `buffer-xor` dependency with a vendored Uint8Array variant (also avoids unnecessary allocation)
- Some Buffers didn't need to be Buffer, can just be Uint8Array, Remove the `Buffer.from` wrapper entirely 
- Some Buffers need to be Buffer, Use the extended form of `Buffer.from` that avoids binary data copy
- Avoid Buffer-specific API where possible, eg: convert `Buffer#copy` to `Uint8Array#set`

### CODE REVIEW

File: packages/api/src/beacon/server/beacon.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export function getRoutes(config: ChainForkConfig, api: ServerApi<Api>): ServerR
         const response = await api.getBlock(...reqSerializers.getBlock.parseReq(req));
         if (response instanceof Uint8Array) {
           // Fastify 3.x.x will automatically add header `Content-Type: application/octet-stream` if Buffer
-          return Buffer.from(response);
+          return Buffer.from(response.buffer, response.byteOffset, response.byteLength);
```
Comment (jeluard) [inline packages/api/src/beacon/server/beacon.ts]: Fastify does this same [logic](https://github.com/fastify/fastify/blob/13f9b6eb9083e5f5dcd8de5895adc81101603db4/lib/reply.js#L186) for Uint8Array, so might consider just passing as is for simplicity.

File: packages/state-transition/package.json [hunk 2]
```diff
@@ -68,12 +68,9 @@
...
     "@lodestar/types": "^1.18.0",
     "@lodestar/utils": "^1.18.0",
-    "bigint-buffer": "^1.1.5",
-    "buffer-xor": "^2.0.2"
-  },
-  "devDependencies": {
-    "@types/buffer-xor": "^2.0.0"
+    "bigint-buffer": "^1.1.5"
   },
+  "devDependencies": {},
```
Comment (jeluard) [inline packages/state-transition/package.json]: Remove?

File: packages/state-transition/src/block/processRandao.ts [hunk 3]
```diff
@@ -28,6 +27,14 @@ export function processRandao(
   }
 
   // mix in RANDAO reveal
-  const randaoMix = xor(Buffer.from(getRandaoMix(state, epoch)), Buffer.from(digest(randaoReveal)));
+  const randaoMix = xor(getRandaoMix(state, epoch), digest(randaoReveal));
   state.randaoMixes.set(epoch % EPOCHS_PER_HISTORICAL_VECTOR, randaoMix);
 }
+
+function xor(a: Uint8Array, b: Uint8Array): Uint8Array {
```
Comment (jeluard) [inline packages/state-transition/src/block/processRandao.ts:34]: https://github.com/ChainSafe/lodestar/pull/6485#issuecomment-1967746399 :D

File: packages/state-transition/src/util/shuffle.ts [hunk 4]
```diff
@@ -101,7 +101,7 @@ function innerShuffleList(input: Shuffleable, seed: Bytes32, dir: boolean): void
 
   // Seed is always the first 32 bytes of the hash input, we never have to change this part of the buffer.
   const _seed = seed;
-  Buffer.from(_seed).copy(buf, 0, 0, _SHUFFLE_H_SEED_SIZE);
+  buf.set(_seed.subarray(0, _SHUFFLE_H_SEED_SIZE), 0);
```
Comment (jeluard) [inline packages/state-transition/src/util/shuffle.ts]: Do we know if there's some perf impact?

Comment (wemeetagain) [reply packages/state-transition/src/util/shuffle.ts]: good call, I further simplified this and added some perf tests that show that .set is roughly equivalent to .copy when there's no allocation of a source subarray.

File: packages/state-transition/src/block/processRandao.ts (hunk 3 above)
Comment (wemeetagain) [reply packages/state-transition/src/block/processRandao.ts:34]: yeah... its finally happening. Also able to use the slightly more efficient [inplace](https://github.com/browserify/buffer-xor/blob/master/inplace.js)

File: packages/state-transition/src/util/shuffle.ts [hunk 5]
```diff
@@ -100,8 +102,7 @@ function innerShuffleList(input: Shuffleable, seed: Bytes32, dir: boolean): void
   }
 
   // Seed is always the first 32 bytes of the hash input, we never have to change this part of the buffer.
-  const _seed = seed;
-  Buffer.from(_seed).copy(buf, 0, 0, _SHUFFLE_H_SEED_SIZE);
+  buf.set(seed, 0);
```
Comment (nflaig) [inline packages/state-transition/src/util/shuffle.ts:105]: memory copy might be intentional here?

File: packages/beacon-node/src/util/sszBytes.ts [hunk 6]
```diff
@@ -150,7 +152,7 @@ export function getAttDataBase64FromSignedAggregateAndProofSerialized(data: Uint
   }
 
   // base64 is a bit efficient than hex
-  return Buffer.from(
+  return toBuffer(
```
Comment (twoeths) [inline packages/beacon-node/src/util/sszBytes.ts]: maybe better to use `toBase64()` function as in electra-fork as suggested by @nflaig https://github.com/ChainSafe/lodestar/blob/6573be51534214257ef0cd5067c36753a065b3c8/packages/beacon-node/src/util/sszBytes.ts#L303

File: packages/state-transition/src/util/shuffle.ts (hunk 5 above)
Comment (wemeetagain) [reply packages/state-transition/src/util/shuffle.ts:105]: This update is fine, I think more eyes on this change will confirm that.

File: packages/state-transition/src/util/shuffle.ts [hunk 7]
```diff
@@ -90,6 +90,8 @@ function innerShuffleList(input: Shuffleable, seed: Bytes32, dir: boolean): void
   const listSize = input.length >>> 0;
   // check if list size fits in uint32
   assert.equal(listSize, input.length, "input length does not fit uint32");
+  // check that the seed is 32 bytes
+  assert.lte(seed.length, 32, "seed length is not lte 32 bytes");
```
Comment (twoeths) [inline packages/state-transition/src/util/shuffle.ts]:
```suggestion
  assert.lte(seed.length, _SHUFFLE_H_SEED_SIZE, `seed length is not lte ${_SHUFFLE_H_SEED_SIZE} bytes`);
```

File: packages/state-transition/src/util/shuffle.ts (hunk 5 above)
Comment (twoeths) [reply packages/state-transition/src/util/shuffle.ts:105]: confirm it's fine, maybe more clear to bound `seed` by `_SHUFFLE_H_SEED_SIZE` instead of 32 which will make it equivalent to the current implementation

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.19.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.19.0) :tada:
