### PR TITLE
fix: avoid emitting stale light client updates

### LINKED ISSUE #7476: Stale `LightClientFinalityUpdate`s sent during sync
### Describe the bug

It seems that Lodestar propagates stale `LightClientFinalityUpdate`s on gossip. I suspect these are from syncing nodes.

I added some logging to Lighthouse to catch the updates we are rejecting, and I've found several from Lodestar that were _very_ old:

- received finality update from slot 3567251, but expected 3660662
  that's 93411 slots behind
  sending peer: Lodestar v1.25.0, `16Uiu2HAkwepnLHcFXrWzvMPAmXrQSpMdoQg42Z4aguHx51kiftht`
- received finality update from slot 3567136, but expected 3660619
  that's 93483 slots behind
  sending peer: Lodestar v1.25.0, `16Uiu2HAkxCFSKMbWnShN75PJvgmyZb6hpJJYqjNU1czStjd7yZwW`

### Expected behavior

Lodestar shouldn't publish stale light client updates if it knows it's syncing. Perhaps there's an argument to say this behaviour is harmless, in case the node is eclipsed and has been tricked into thinking it is syncing when it isn't? However, given that these are finality updates, they are likely only useful if the node is _not_ eclipsed (i.e. is part of the 2/3+ of validators that are finalizing the chain).

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.25.0

### PR DESCRIPTION
**Pull request by nflaig**
- Closes https://github.com/ChainSafe/lodestar/issues/7476

### CODE REVIEW

File: packages/beacon-node/src/chain/lightClient/index.ts [hunk 1]
```diff
@@ -533,12 +538,17 @@ export class LightClientServer {
...
     const attestedFork = this.config.getForkName(attestedHeader.beacon.slot);
 
-    // Emit update
-    // Note: Always emit optimistic update even if we have emitted one with higher or equal attested_header.slot
-    this.emitter.emit(routes.events.EventType.lightClientOptimisticUpdate, {
-      version: attestedFork,
-      data: headerUpdate,
-    });
+    // Check if node is syncing / too far behind to avoid emitting stale light client updates
+    const isStaleLightClientUpdate = this.clock.currentSlot - signatureSlot > SLOTS_PER_EPOCH;
```
Comment (nflaig) [inline packages/beacon-node/src/chain/lightClient/index.ts:542]: this is similar to the check we have in import block https://github.com/ChainSafe/lodestar/blob/793f92c091c563a744a4cc4ec261e142d299853f/packages/beacon-node/src/chain/blocks/importBlock.ts#L460

which uses a fixed 64 slots, we could use the same here but using `SLOTS_PER_EPOCH` seems ok to me as well

Comment (nflaig) [reply packages/beacon-node/src/chain/lightClient/index.ts:542]: this is same to https://github.com/ChainSafe/lodestar/blob/793f92c091c563a744a4cc4ec261e142d299853f/packages/beacon-node/src/api/impl/validator/index.ts#L349

Comment (twoeths) [reply packages/beacon-node/src/chain/lightClient/index.ts:542]: may want to log/track in metrics for this case

Comment (nflaig) [reply packages/beacon-node/src/chain/lightClient/index.ts:542]: I added a new metric for it

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.36.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.36.0) :tada:
