### PR TITLE
fix: request columns by peer custodied columns

### LINKED ISSUE #8329: [block-input-refactor] Received a columnSidecar that was not requested
### Describe the bug

got this error a couple of times during syncing

```
Sep-05 03:05:17.827[sync]            debug: Error downloading in BlockInputSync.fetchBlockInput attempt=3, rootHex=0xe81f474d8bd7f94e891f664165f7ea3af9841ff3b7a17a20f9bc54647f5b0480, peer=16Uiu2HAm3k5Npu6EaYWxiEvzsdLseEkjVyoVhvbxWEuyqdBgBBbq, peerClient=Grandine, code=DOWNLOAD_BY_ROOT_ERROR_EXTRA_SIDECAR_RECEIVED, peer=16...BgBBbq, blockRoot=0xe81f…0480, invalidIndex=126
Error: Received a columnSidecar that was not requested
    at fetchAndValidateColumns (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:457:13)
    at fetchByRoot (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:197:26)
    at downloadByRoot (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:71:49)
    at BlockInputSync.fetchBlockInput (file:///usr/src/lodestar/packages/beacon-node/src/sync/unknownBlock.ts:512:21)
    at wrapError (file:///usr/src/lodestar/packages/beacon-node/src/util/wrapError.ts:18:32)
    at BlockInputSync.downloadBlock (file:///usr/src/lodestar/packages/beacon-node/src/sync/unknownBlock.ts:319:17)
```

this is also found during the review https://github.com/ChainSafe/lodestar/pull/8200#discussion_r2318049013

### Expected behavior

filter columns before sending to peers

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

mkeil/refactor-block-input-on-unstable cc933e5eed04937fbab2f51b90789e391e37c514

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- before we send `beacon_data_columns_by_root` or `beacon_data_columns_by_range` to peer, we need to filter by peers' custofied columns
- otherwise, will get error
```
Sep-05 03:05:17.827[sync]            debug: Error downloading in BlockInputSync.fetchBlockInput attempt=3, rootHex=0xe81f474d8bd7f94e891f664165f7ea3af9841ff3b7a17a20f9bc54647f5b0480, peer=16Uiu2HAm3k5Npu6EaYWxiEvzsdLseEkjVyoVhvbxWEuyqdBgBBbq, peerClient=Grandine, code=DOWNLOAD_BY_ROOT_ERROR_EXTRA_SIDECAR_RECEIVED, peer=16...BgBBbq, blockRoot=0xe81f…0480, invalidIndex=126
Error: Received a columnSidecar that was not requested
    at fetchAndValidateColumns (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:457:13)
    at fetchByRoot (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:197:26)
    at downloadByRoot (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:71:49)
    at BlockInputSync.fetchBlockInput (file:///usr/src/lodestar/packages/beacon-node/src/sync/unknownBlock.ts:512:21)
    at wrapError (file:///usr/src/lodestar/packages/beacon-node/src/util/wrapError.ts:18:32)
    at BlockInputSync.downloadBlock (file:///usr/src/lodestar/packages/beacon-node/src/sync/unknownBlock.ts:319:17)
```

**Description**

- fix for `downloadByRange` and `downloadByRoot` flows

Closes #8329

### CODE REVIEW

File: packages/beacon-node/src/sync/utils/downloadByRoot.ts [hunk 1]
```diff
@@ -448,12 +464,14 @@ export async function fetchAndValidateColumns({
     return needed;
   }
 
+  const peerColumns = new Set(peerMeta.custodyGroups ?? []);
+  const requestedColumns = columnMeta.missing.filter((c) => peerColumns.has(c));
```
Comment (twoeths) [inline packages/beacon-node/src/sync/utils/downloadByRoot.ts:468]: the main fix for `downloadByRoot` flow

File: packages/beacon-node/src/sync/range/range.ts [hunk 2]
```diff
@@ -207,7 +207,7 @@ export class RangeSync extends (EventEmitter as {new (): RangeSyncEmitter}) {
       logger: this.logger,
       peerIdStr: peer.peerId,
       batchBlocks,
-      ...batch.requests,
+      ...batch.getRequestsForPeer(peer),
```
Comment (twoeths) [inline packages/beacon-node/src/sync/range/range.ts:210]: the main fix for `downloadByRange` flow

**Review by wemeetagain — APPROVED** [review]
