### PR TITLE
Make block proposing flow resilient to errors

### LINKED ISSUE #3700: Error proposing block - Cannot get tree for index
**Describe the bug**

One of our beacon nodes has been encountering this error for some hours

```
Feb-06 07:07:11.526 [ETH1]            error: Error updating eth1 chain cache code=ETH1_ERROR_DUPLICATE_DISTINCT_LOG, newIndex=292236, prevIndex=293927
Error: ETH1_ERROR_DUPLICATE_DISTINCT_LOG
    at Eth1DepositsCache.add (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositsCache.ts:45:15)
    at Eth1DepositDataTracker.updateDepositCache (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:163:5)
    at Eth1DepositDataTracker.update (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:144:33)
    at Eth1DepositDataTracker.runAutoUpdate (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:118:29)
Feb-06 07:07:15.243 [ETH1]            error: Error updating eth1 chain cache code=ETH1_ERROR_DUPLICATE_DISTINCT_LOG, newIndex=292236, prevIndex=293927
Error: ETH1_ERROR_DUPLICATE_DISTINCT_LOG
    at Eth1DepositsCache.add (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositsCache.ts:45:15)
    at Eth1DepositDataTracker.updateDepositCache (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:163:5)
    at Eth1DepositDataTracker.update (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:144:33)
    at Eth1DepositDataTracker.runAutoUpdate (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:118:29)
```

Then when it had to propose a block it couldn't get the deposit tree due to missing deposits

```
Feb-06 05:52:11.151 [API]             error: Req req-rdg produceBlockV2 error message=Cannot get tree for index: 294009, maxIndex: 293927
Error: Cannot get tree for index: 294009, maxIndex: 293927
    at getTreeAtIndex (/usr/app/node_modules/@chainsafe/lodestar/src/util/tree.ts:7:11)
    at getDepositsWithProofs (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/utils/deposits.ts:45:44)
    at Eth1DepositsCache.get (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositsCache.ts:29:33)
    at getDeposits (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/utils/deposits.ts:28:20)
    at Eth1DepositDataTracker.getDeposits (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:104:12)
    at Eth1DepositDataTracker.getEth1DataAndDeposits (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:77:22)
    at assembleBody (/usr/app/node_modules/@chainsafe/lodestar/src/chain/factory/block/body.ts:64:32)
    at assembleBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/factory/block/index.ts:44:11)
    at Object.produceBlock (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:182:21)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
Feb-06 05:52:11.157 [API]             debug: Res req-rdg produceBlockV2 - 500
```

**Expected behavior**

- Not get dead locked with ETH1_ERROR_DUPLICATE_DISTINCT_LOG
- The block that was proposed after this missed one contained 0 deposits. Why did a faulty depositTree stopped a block proposal?

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

Error https://github.com/ChainSafe/lodestar/issues/3700 could have been avoided because this block did not had to include any deposits

**Description**

- Only read deposits from DB if the block needs to include deposits
- If eth1Data vote computation errors, just vote for current eth1Data. This is a tradeoff between chain liveness and stalling the deposit queue.

Closes https://github.com/ChainSafe/lodestar/issues/3700

### CODE REVIEW

**Review by g11tech — APPROVED** [review]

File: packages/lodestar/src/eth1/eth1DepositDataTracker.ts [hunk 1]
```diff
@@ -99,6 +105,11 @@ export class Eth1DepositDataTracker {
     state: CachedBeaconStateAllForks,
     eth1DataVote: phase0.Eth1Data
   ): Promise<phase0.Deposit[]> {
+    // No new deposits have to be included, continue
+    if (eth1DataVote.depositCount === state.eth1DepositIndex) {
+      return [];
+    }
```
Comment (twoeths) [inline packages/lodestar/src/eth1/eth1DepositDataTracker.ts:111]: @dapplion do we also want to try/catch the below code to guarantee we can produce block even if there are errors in `getDeposits()`?

Comment (dapplion) [reply packages/lodestar/src/eth1/eth1DepositDataTracker.ts:111]: No, because if don't include all the deposits necessary the block is invalid

**Review by twoeths — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]
