### PR TITLE
SSZ static spec tests for merge

### LINKED ISSUE #3282: Ssz static spec test does not scan merge ssz types
**Describe the bug**

Due to this https://github.com/ChainSafe/lodestar/blob/f86e5985f34d2c58d31aacccda9531f726c0b9a2/packages/spec-test-runner/test/spec/allForks/ssz_static.ts#L27 we always scan phase0 ssz type folder

**Expected behavior**

need to correct and make sure we can through merge types

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

We miss merge type because we always scan through "phase0" folder

**Description**

+ Remove the "phase0" hard coded value
+ Move `PowBlock` to the common "types" package as the ssz static test needs it

Closes #3282

### CODE REVIEW

File: packages/lodestar/src/chain/blocks/importBlock.ts [hunk 1]
```diff
@@ -164,6 +165,16 @@ export async function importBlock(chain: ImportBlockModules, fullyVerifiedBlock:
   pendingEvents.emit();
 }
 
+function toPowBlock(powBlock: PowMergeBlock): merge.PowBlock {
+  return {
+    blockHash: fromHexString(powBlock.blockhash),
+    parentHash: fromHexString(powBlock.parentHash),
+    totalDifficulty: powBlock.totalDifficulty,
+    // TODO
```
Comment (twoeths) [inline packages/lodestar/src/chain/blocks/importBlock.ts]: Note this "TODO"

File: packages/fork-choice/src/forkChoice/interface.ts [hunk 2]
```diff
@@ -149,14 +143,14 @@ export type OnBlockPrecachedData = {
    * powBlock = getPowBlock((block as merge.BeaconBlock).body.executionPayload.parentHash)
    * ```
    */
-  powBlock?: PowBlock;
+  powBlock?: merge.PowBlock;
```
Comment (dapplion) [inline packages/fork-choice/src/forkChoice/interface.ts]: Why is this necessary? The fork-choice doesn't care about the root at all, so converting to bytes is useless work. To make the distinction clear you can keep the old `PowBlock` in the fork-choice renamed to `PowBlockHex` or something

Comment (twoeths) [reply packages/fork-choice/src/forkChoice/interface.ts]: ok so I'll make 2 types:
+ PowBlock for the spec test
+ PowBlockHex for forkchoice

**Review by dapplion — APPROVED** [review]
