### PR TITLE
Reuse variables in forkchoice

### LINKED ISSUE #2755: Improve forkchoice addLatestMessage
**Describe the bug**

This is the profile from a full attestation subnet subscriptions
Screen Shot 2021-06-28 at 14 02 09

It takes almost 14% of the time for the following

+ We access the same tree data in the loop and pass to `addLatestMessage`
+ Then `addLatestMessage` keeps calling `toHexString` of the same root

**Expected behavior**

+ Avoid accessing the same tree property in a for loop
+ May want string instead of Root for `addLatestMessage`

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**
This is from profiling a full attestation subnet subscriptions node: redundant call of tree backed `get` and `toHexString` causes 14% of total time

+ attestation data is a tree backed and we keep accessing same data in for loops
+ `addLatestMessage` keeps doing `toHexString` for the same root
+ some functions keep accessing same properties of tree backed objects

**Description**
+ add more variables to functions, reuse them as much as possible
+ `addLatestMessage` now accepts a RootHex to avoid redundant `toHexString` call

Closes #2755

### CODE REVIEW

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 1]
```diff
@@ -747,30 +753,28 @@ export class ForkChoice implements IForkChoice {
     // is from a prior epoch to the attestation, then the target root must be equal to the root
     // of the block that is being attested to.
     const expectedTarget =
-      target.epoch > computeEpochAtSlot(block.slot)
-        ? indexedAttestation.data.beaconBlockRoot
-        : fromHexString(block.targetRoot);
+      target.epoch > computeEpochAtSlot(block.slot) ? beaconBlockRoot : fromHexString(block.targetRoot);
```
Comment (dapplion) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: Instead of converting `block.targetRoot` to Root, can we convert `beaconBlockRoot` to string and compare them as strings below?

**Review by dapplion — DISMISSED** [review]
Looks great!

File: packages/fork-choice/src/forkChoice/forkChoice.ts (hunk 1 above)
Comment (twoeths) [reply packages/fork-choice/src/forkChoice/forkChoice.ts]: will do that

**Review by wemeetagain — APPROVED** [review]
:+1:
