### PR TITLE
Attestation Service

### LINKED ISSUE #1382: Lack of random subnet subscription
**Describe the bug**

We don't track how many active validators are attached to node so we are always to subscribed to one random subnet.

**Expected behavior**

Use validator duties or attestation publish to track how many active validators we have and subscribe to appropriate number of random subnets.

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version: 
 - Branch: 
 - Commit hash:

### LINKED ISSUE #2456: prepareBeaconCommitteeSubnet performance bottleneck
**Describe the bug**

`prepareBeaconCommitteeSubnet` takes too much potentially breaking the validator's workflow. In average it takes about 12 seconds but this snapshot it takes 4s. The cost comes from `computeSubnetForSlot()`

Screenshot from 2021-05-01 16-03-28
Screenshot from 2021-05-01 16-05-46

**Expected behavior**

`prepareBeaconCommitteeSubnet` should almost be free since that information should already be cached in the epoch context.

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ We need to coordinate short-lived subnets and long-lived subnets subscriptions/unsubscriptions
+ We need to track known validators

**Description**

+ Remove most of logic in AttestationCollector, only handle committee attestation when we really need to (see `shouldProcessAttestation`)
+ Remove InteropSubnetsJoiningTask
+ Create new AttestationService to handle subnets and track connected/known validators there
+ Known validators are expired after 150 slots as in lighthouse implementation

Closes #1382 

Closes https://github.com/ChainSafe/lodestar/issues/2456 by removing the calls to the extremely slow `computeSubnetForSlot()`

### CODE REVIEW

File: packages/lodestar/src/network/attestation-service/service.ts [hunk 1]
```diff
@@ -0,0 +1,384 @@
...
+   * Duplicate randomSubnets to nextForkRandomSubnets to make sure same ENR advertisement
+   * Subscribe to respective gossip topics with next fork.
+   * No need to update ENR
+   * @param nextFork
+   */
+  private subscribeToNextForkRandomSubnets(nextFork: ForkName): void {
+    const currentSlot = this.chain.clock.currentSlot;
+    const activeSubnets = this.randomSubnets.getActive(currentSlot);
+    for (const subnet of activeSubnets) {
+      this.nextForkRandomSubnets!.request({
```
Comment (dapplion) [inline packages/lodestar/src/network/attestation-service/service.ts]: Could you find a way to not have to use the `!` operator? Maybe ensure it's defined first of change the data structure

File: packages/lodestar/src/network/attestation-service/service.ts [hunk 2]
```diff
@@ -0,0 +1,384 @@
...
+  }
+
+  /**
+   * Subscribe to a committee subnet.
+   */
+  private handleSubscription(subnetId: number, slot: Slot): void {
+    // Check if the subnet currently exists as a long-lasting random subnet
+    const randomSubnetToSlot = this.randomSubnets.getToSlot(subnetId);
+    const fork = this.chain.getForkName();
+    if (randomSubnetToSlot && randomSubnetToSlot >= 0) {
```
Comment (dapplion) [inline packages/lodestar/src/network/attestation-service/service.ts]: Check for `randomSubnetToSlot !== undefined`

File: packages/lodestar/src/network/attestation-service/service.ts [hunk 3]
```diff
@@ -0,0 +1,384 @@
...
+
+  /**
+   * A known validator has not sent a subscription in a while. They are considered offline and the
+   * beacon node no longer needs to be subscribed to the allocated random subnets.
+   *
+   * We don't keep track of a specific validator to random subnet, rather the ratio of active
+   * validators to random subnets. So when a validator goes offline, we can simply remove the
+   * allocated amount of random subnets.
+   */
+  private handleKnownValidatorExpiry(currentSlot: Slot): void {
```
Comment (dapplion) [inline packages/lodestar/src/network/attestation-service/service.ts]: You could re-org this function by doing
1. Iterate `this.knownValidators` and delete expired directly without storing them on a set
2. Then compute `targetRandomSubnetCount = this.knownValidators.size * this.config.params.RANDOM_SUBNETS_PER_VALIDATOR`
3. Then if `activeRandomSubnets < targetRandomSubnetCount` add more, if `activeRandomSubnets > targetRandomSubnetCount` remove some

Comment (dapplion) [reply packages/lodestar/src/network/attestation-service/service.ts]: Points 2 + 3 could be a new function `rebalanceRandomSubnets` and be called too after adding a new known validator, deduplicating logic

File: packages/lodestar/src/network/attestation-service/service.ts [hunk 4]
```diff
@@ -0,0 +1,384 @@
...
+  };
+
+  private transitionToNextFork(): void {
+    const fork = this.chain.getForkName();
+    assert.true(this.nextForkRandomSubnets !== undefined, "No next fork random subnets subscriptions");
+    assert.equal(
+      fork,
+      this.nextForkRandomSubnets?.getForkName(),
+      "Chain fork name is not same to next fork random subnet"
+    );
```
Comment (dapplion) [inline packages/lodestar/src/network/attestation-service/service.ts]: If this conditions throw they will interrupt the flow of onSlot. We may not want that

Comment (twoeths) [reply packages/lodestar/src/network/attestation-service/service.ts]: this is just like a precondition before running this function to make it easy to understand, we had a check in `onSlot` already so it should be safe.
It's ok to remove the `assert()` but I found it's easier to understand that way.

File: packages/lodestar/src/network/attestationService.ts [hunk 5]
```diff
@@ -343,30 +337,38 @@ export class AttestationService implements IAttestationService {
...
+  private rebalanceRandomSubnets(): void {
+    const {RANDOM_SUBNETS_PER_VALIDATOR} = this.config.params;
+    const numValidators = this.knownValidators.size;
+    // random subnet is renewed automatically
+    let numRandomSubnets = this.randomSubnets.getAll().length;
+    // subscribe to more random subnets
+    const currentFork = this.chain.getForkName();
+    const targetRandomSubnetCount = numValidators * RANDOM_SUBNETS_PER_VALIDATOR;
+    while (targetRandomSubnetCount > numRandomSubnets && numRandomSubnets < ATTESTATION_SUBNET_COUNT) {
+      this.subscribeToRandomSubnet(currentFork);
```
Comment (dapplion) [inline packages/lodestar/src/network/attestationService.ts]: You could pass the number of new subnets to subscribe to here and won't need to iterate with a while. The logic inside `subscribeToRandomSubnet` can be re-used if subscribing to multiple subnets at once. Consider moving the `ATTESTATION_SUBNET_COUNT` check there too to compact the logic

File: packages/lodestar/src/network/attestationService.ts [hunk 6]
```diff
@@ -0,0 +1,400 @@
...
+
+  // Map of random subnets and the slot until they are needed of current fork
+  private randomSubnets: SubnetMap;
+  // Map of random subnets and the slot until they are needed of next fork
+  // TODO: handle multiple hard forks?
+  private nextForkRandomSubnets: SubnetMap | undefined;
+  // Map of committee subnets and the slot until they are needed
+  private committeeSubnets: SubnetMap;
+  // subset of committeeSubnets with exact slot for aggregator
+  private subscribedCommitteeSubnets: SubnetMap;
```
Comment (wemeetagain) [inline packages/lodestar/src/network/attestationService.ts]: Might be helpful for these comments to be `/** */` comments so they show up as help text in IDE.

File: packages/lodestar/src/network/attestationService.ts (hunk 5 above)
Comment (wemeetagain) [reply packages/lodestar/src/network/attestationService.ts]: Yeah, might be a small gain, but agree, `subscribeToRandomSubnet` could take a second `count` param. Then we only filter/select subnets / update the ENR once.

File: packages/lodestar/src/network/attestationService.ts [hunk 7]
```diff
@@ -0,0 +1,400 @@
...
+    if (this.nextForkRandomSubnets) {
+      return this.nextForkRandomSubnets.getActive(this.chain.clock.currentSlot);
+    }
+    return [];
+  }
+
+  /**
+   * Called from /eth/v1/validator/beacon_committee_subscriptions api when validator is an attester.
+   */
+  validatorSubscriptions(subscriptions: phase0.BeaconCommitteeSubscription[] = []): void {
```
Comment (wemeetagain) [inline packages/lodestar/src/network/attestationService.ts]: might call this function `addValidatorSubscriptions`, `addBeaconCommitteeSubscriptions` or similar.

File: packages/lodestar/src/network/peers/peerManager.ts [hunk 8]
```diff
@@ -141,11 +136,9 @@ export class PeerManager {
   }
 
   /**
-   * Request to find peers on a given subnet.
+   * Run after validator subscriptions request.
    */
-  requestAttSubnets(requestedSubnets: RequestedSubnet[]): void {
-    this.subnets.request(requestedSubnets);
-
+  onValidatorSubscriptions(): void {
```
Comment (wemeetagain) [inline packages/lodestar/src/network/peers/peerManager.ts]: Not a huge fan of the term "validator subscriptions" as we know we will be adding different types of subscriptions (beacon committee vs sync committee) and "validator subscriptions" is/will be vague.
Suggestion to use "beacon committee subscriptions" or similar.

**Review by wemeetagain — DISMISSED** [review]
Minor feedback, overall this looks really good :100:

File: packages/lodestar/src/network/util.ts [hunk 9]
```diff
@@ -110,3 +112,19 @@ export function prettyPrintPeerId(peerId: PeerId): string {
 export function getAgentVersionFromPeerStore(peerId: PeerId, metadataBook: MetadataBook): string {
   return new TextDecoder().decode(metadataBook.getValue(peerId, "AgentVersion")) || "N/A";
 }
+
```
Comment (twoeths) [inline packages/lodestar/src/network/util.ts:115]: @dapplion I moved the `getCurrentAndNextFork` over here so that it can be used for `AttestationServices`, made some small changes and unit tests for it

Comment (dapplion) [reply packages/lodestar/src/network/util.ts:115]: Looks good! On demand from cayman config.forks are sorted in ascending order. We can use that fact to prevent having to sort the forks everytime. So passing `config` to forks instead of an array of ForkInfo

**Comment by dapplion** [comment]
I've review the design to simplify how we handle fork transitions. Instead of having multiple data structures per fork this approach just does:
- 2 epochs before the fork epoch: re-subscribe all existing long lived subnet subs to the next fork (keeping the old)
- between 2 epochs of the fork epoch: any new subscription gets subscribed to both forks.
- 2 epochs after the fork epoch: un-subscribe all 64 subnets.

With this approach we satisfy the spec with much less complexity. The SubnetMaps don't have to be aware of forks and we don't need to keep timeouts around.

**Review by dapplion — APPROVED** [review]
