### PR TITLE
fix: fix proposer boost reorg by suppressing fcu call during import

### LINKED ISSUE #7235: Block proposer error when weak head detected
### Describe the bug

On one of the server we enabled `chain.proposerBoostReorg` flag, weak head detected

Image

however there was a block proposer error at the same time:

Image

### Expected behavior

when weak head detected, we still need to be able to propose block

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.21.0

### PR DESCRIPTION
**Pull request by ensi321**
We need to suppress fcu call during gossip block import when the incoming block is weak. This is because once notified EL, it will treat the new block as head and will not reorg back to parent if we try to reorg.

- Add `shouldOverrideForkChoiceUpdate`
- Call `shouldOverrideForkChoiceUpdate` during gossip block import, and skip fcu call if result is true
- Modify `predictProposerHead` to be a simple wrapper around `shouldOverrideForkChoiceUpdate`

Closes #7235

cc. @twoeths @nflaig

### CODE REVIEW

File: packages/beacon-node/src/chain/chain.ts [hunk 1]
```diff
@@ -832,18 +832,12 @@ export class BeaconChain implements IBeaconChain {
...
-
-    try {
-      return this.forkChoice.updateAndGetHead({mode: UpdateHeadOpt.GetPredictedProposerHead, slot}).head;
-    } catch (e) {
-      this.metrics?.forkChoice.errors.inc({entrypoint: UpdateHeadOpt.GetPredictedProposerHead});
-      throw e;
-    } finally {
-      timer?.();
+  shouldOverrideForkchoiceUpdate(block: ProtoBlock): boolean {
+    const maybeOverride = this.forkChoice.shouldOverrideForkchoiceUpdate(block);
```
Comment (nflaig) [inline packages/beacon-node/src/chain/chain.ts]: variable name seems strange, if this is `true` doesn't it mean we should override, "maybe override" suggests even if it is `true` we may not override

Comment (ensi321) [reply packages/beacon-node/src/chain/chain.ts]: > variable name seems strange, if this is `true` doesn't it mean we should override, "maybe override" suggests even if it is `true` we may not override

If it is true, we may or may not override (reorg). If false, it is a hard no to override (absolutely no reorg). So I think `maybeOverride` is appropriate.

Comment (nflaig) [reply packages/beacon-node/src/chain/chain.ts]: but if this returns true shouldn't we always override fcU because head is weak?

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 2]
```diff
@@ -248,28 +288,24 @@ export class ForkChoice implements IForkChoice {
...
-    }
+    // TODO: Maybe add a transcient flag in ProtoBlock to flag `shouldOverrideFcu` block when importing
+    // so we don't need to call shouldOverrideForkChoiceUpdate again.
+    const result = this.shouldOverrideForkChoiceUpdate(currentSlot, headBlock.blockRoot);
 
-    const currentTimeOk = headBlock.slot === currentSlot;
-    if (!currentTimeOk) {
-      return headBlock;
+    if (result.shouldOverrideFcu) {
+      this.logger?.info("Current head is weak. Predicting next block to be built on parent of head");
```
Comment (nflaig) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: we should include block roots in the log via context

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 3]
```diff
@@ -223,6 +224,46 @@ export class ForkChoice implements IForkChoice {
...
+    if (prelimProposerHead === headBlock) {
+      return {shouldOverrideFcu: false};
+    }
+
+    const currentTimeOk = headBlock.slot === currentSlot;
+    if (!currentTimeOk) {
+      return {shouldOverrideFcu: false};
+    }
+
+    this.logger?.info(`Block ${blockRoot} is weak. Should override forkchoice update`);
```
Comment (nflaig) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: would be better to use context to pass variables instead

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 4]
```diff
@@ -212,6 +213,28 @@ export async function importBlock(
...
+      //  1) This is a gossip block
+      //  2) We are proposer of next slot
+      //  3) Proposer boost reorg related flag is turned on (this is checked inside the function)
+      //  4) Block meets the criteria of being re-orged out (this is also checked inside the function)
+      shouldOverrideFcu = this.shouldOverrideForkChoiceUpdate(this.clock.currentSlot, blockSummary.blockRoot);
+    }
+  }
+
+  if (shouldOverrideFcu) {
+    this.logger.info("Weak block detected. Skip fcu call in importBlock");
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: should include block root(s) in log, maybe even the slot so it will show up if you filter by slot

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 5]
```diff
@@ -248,28 +288,24 @@ export class ForkChoice implements IForkChoice {
...
     }
 
-    const {prelimProposerHead} = this.getPreliminaryProposerHead(headBlock, parentBlock, proposalSlot);
+    currentSlot = currentSlot ?? this.fcStore.currentSlot;
 
-    if (prelimProposerHead === headBlock) {
-      return headBlock;
-    }
+    // TODO: Maybe add a transcient flag in ProtoBlock to flag `shouldOverrideFcu` block when importing
+    // so we don't need to call shouldOverrideForkChoiceUpdate again.
```
Comment (nflaig) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: but don't we need to re-evaluate this each time? what's the current scenario in which we don't wanna call `shouldOverrideForkChoiceUpdate` again?

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 6]
```diff
@@ -212,6 +213,28 @@ export async function importBlock(
   const newHead = this.recomputeForkChoiceHead(ForkchoiceCaller.importBlock);
   const currFinalizedEpoch = this.forkChoice.getFinalizedCheckpoint().epoch;
 
+  // Suppress fcu call if this is true
+  let shouldOverrideFcu = false;
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: why do we need to call this up here? this should be post bellatrix only

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 7]
```diff
@@ -212,6 +213,28 @@ export async function importBlock(
...
+      //  4) Block meets the criteria of being re-orged out (this is also checked inside the function)
+      shouldOverrideFcu = this.shouldOverrideForkChoiceUpdate(this.clock.currentSlot, blockSummary.blockRoot);
+    }
+  }
+
+  if (shouldOverrideFcu) {
+    this.logger.info("Weak block detected. Skip fcu call in importBlock");
+  }
+
+  // TODO: Skip this too when shouldOverrideFcu == true?
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: I don't think so cc @twoeths

File: packages/beacon-node/src/chain/blocks/importBlock.ts (hunk 4 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/blocks/importBlock.ts]: this is more like technical information, maybe change to `verbose` level? `info` log is for users

Comment (twoeths) [reply packages/beacon-node/src/chain/blocks/importBlock.ts]: also we wanna add a `gauge` metric in this case, that'll help us investigate later

File: packages/beacon-node/src/chain/blocks/importBlock.ts (hunk 7 above)
Comment (twoeths) [reply packages/beacon-node/src/chain/blocks/importBlock.ts]: yeah it's still a head so we'll still emit it
just keep it as is and drop this `TODO` comment

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 8]
```diff
@@ -212,6 +213,28 @@ export async function importBlock(
   const newHead = this.recomputeForkChoiceHead(ForkchoiceCaller.importBlock);
   const currFinalizedEpoch = this.forkChoice.getFinalizedCheckpoint().epoch;
 
+  // Suppress fcu call if this is true
+  let shouldOverrideFcu = false;
+
+  if (opts.isGossipBlock && isExecutionStateType(postState)) {
+    const proposerIndex = postState.epochCtx.getBeaconProposer(blockSlot + 1);
```
Comment (twoeths) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: this `getBeaconProposer` can throw so either need to do a try/catch here
if `blockSlot` is end of this epoch we can't get proposer of next slot so maybe handle it separately

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 9]
```diff
@@ -223,6 +224,46 @@ export class ForkChoice implements IForkChoice {
     }
   }
 
+  // Basically calls `predictProposerHead`. If the result is not same as blockRoot's block, return true else false
+  // See https://github.com/ethereum/consensus-specs/blob/a94d85bb3b33f84a5830eb98945b790b02ae80e8/specs/bellatrix/fork-choice.md#should_override_forkchoice_update
+  // Return true if the given block passes all criteria to be re-orged out
+  // Return false otherwise.
+  // Note when proposer boost reorg is disabled, it always returns false
+  shouldOverrideForkChoiceUpdate(currentSlot: Slot, blockRoot: RootHex): ShouldOverrideForkChoiceUpdateResult {
```
Comment (twoeths) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: can you add a unit test for this function? also I'm curious if this function scanned through spec tests or not

File: packages/fork-choice/src/forkChoice/forkChoice.ts (hunk 5 above)
Comment (ensi321) [reply packages/fork-choice/src/forkChoice/forkChoice.ts]: ~~I mean, when we import a gossip block, we have already called `shouldOverrideForkChoiceUpdate` to determine if we want to suppress fcu call. But we also call `shouldOverrideForkChoiceUpdate` during `prepareNextSlot` which is redundant.~~

~~`shouldOverrideForkChoiceUpdate` returns the same result on the same block whether it is during the first 4s, or at 8s.~~

File: packages/beacon-node/src/chain/blocks/importBlock.ts (hunk 6 above)
Comment (ensi321) [reply packages/beacon-node/src/chain/blocks/importBlock.ts]: > why do we need to call this up here? this should be post bellatrix only

Can you elaborate? `shouldOverrideFcu` will always be false pre-bellatrix, which will follow the original flow (ie. no proposer reorg)

File: packages/beacon-node/src/chain/blocks/importBlock.ts (hunk 8 above)
Comment (ensi321) [reply packages/beacon-node/src/chain/blocks/importBlock.ts:220]: If `blockSlot` is end of epoch, we don't reorg anyway due to this condition
https://github.com/ChainSafe/lodestar/blob/3c7d6d16870d79a8eb69b718930c171d11587f14/packages/fork-choice/src/forkChoice/forkChoice.ts#L1480

And we don't record `NotReorgedReason` here, so there is no need to handle this separately.

File: packages/fork-choice/src/forkChoice/forkChoice.ts (hunk 9 above)
Comment (ensi321) [reply packages/fork-choice/src/forkChoice/forkChoice.ts]: > also I'm curious if this function scanned through spec tests or not

@twoeths Hmmmm, there is, but we pass these tests even before we implemented proposer boost reorg

https://github.com/ethereum/consensus-specs/blob/6507cd11c2d5bf1a50c3de7b21555730d49b2f96/tests/core/pyspec/eth2spec/test/bellatrix/fork_choice/test_should_override_forkchoice_update.py#L36

File: packages/beacon-node/src/chain/blocks/importBlock.ts (hunk 6 above)
Comment (nflaig) [reply packages/beacon-node/src/chain/blocks/importBlock.ts]: I am mostly wondering why this logic is up here and not around L356

File: packages/fork-choice/src/forkChoice/forkChoice.ts (hunk 5 above)
Comment (nflaig) [reply packages/fork-choice/src/forkChoice/forkChoice.ts]: > shouldOverrideForkChoiceUpdate returns the same result on the same block whether it is during the first 4s, or at 8s.

don't we evaluate single attestations already in fork choice which could change the result?

File: packages/beacon-node/src/metrics/metrics/lodestar.ts [hunk 10]
```diff
@@ -741,6 +742,11 @@ export function createLodestarMetrics(
         help: "Total number of imported blobs by source",
         labelNames: ["blobsSource"],
       }),
+      notOverrideFcuReason: register.gauge<{reason: NotReorgedReason}>({
```
Comment (nflaig) [inline packages/beacon-node/src/metrics/metrics/lodestar.ts]: we should start using counter where applicable
```suggestion
      notOverrideFcuReason: register.counter<{reason: NotReorgedReason}>({
```

File: packages/fork-choice/src/forkChoice/forkChoice.ts (hunk 5 above)
Comment (ensi321) [reply packages/fork-choice/src/forkChoice/forkChoice.ts]: > > shouldOverrideForkChoiceUpdate returns the same result on the same block whether it is during the first 4s, or at 8s.
> 
> don't we evaluate single attestations already in fork choice which could change the result?

Oh yea you are right. Forgot about single attestations

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 11]
```diff
@@ -225,6 +233,47 @@ export async function importBlock(
...
+        this.logger.warn("Unable to get beacon proposer. Do not override fcu.", {slot: blockSlot + 1}, e as Error);
+      }
+    }
+  }
+
+  if (shouldOverrideFcu) {
+    if (this.metrics) {
+      this.metrics.importBlock.notOverrideFcuReason.inc({reason: shouldOverrideFcuReason});
+    } else {
+      this.logger.verbose("Weak block detected. Skip fcu call in importBlock", {
```
Comment (twoeths) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: let's have both logger and metrics, this should be very rare anyway

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 12]
```diff
@@ -225,6 +233,47 @@ export async function importBlock(
   const newHead = this.recomputeForkChoiceHead(ForkchoiceCaller.importBlock);
   const currFinalizedEpoch = this.forkChoice.getFinalizedCheckpoint().epoch;
 
+  // Suppress fcu call if this is true
```
Comment (twoeths) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: add context of this issue to this comment, also refer to the issue itself to make it easier to reason about later

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 13]
```diff
@@ -225,6 +233,47 @@ export async function importBlock(
...
+        shouldOverrideFcuReason = NotReorgedReason.NotShufflingStable;
+      } else {
+        this.logger.warn("Unable to get beacon proposer. Do not override fcu.", {slot: blockSlot + 1}, e as Error);
+      }
+    }
+  }
+
+  if (shouldOverrideFcu) {
+    if (this.metrics) {
+      this.metrics.importBlock.notOverrideFcuReason.inc({reason: shouldOverrideFcuReason});
```
Comment (twoeths) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: the name is inconsistent: `notOverrideFcuReason` vs `shouldOverrideFcuReason`

File: packages/fork-choice/src/forkChoice/forkChoice.ts (hunk 9 above)
Comment (ensi321) [reply packages/fork-choice/src/forkChoice/forkChoice.ts]: Unit test added.

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 14]
```diff
@@ -223,6 +224,50 @@ export class ForkChoice implements IForkChoice {
...
+    const headBlock = this.getBlockHex(blockRoot);
+    if (headBlock === null) {
+      // should not happen beacause this block just got imported. Fall back to no-reorg.
+      return {shouldOverrideFcu: false, reason: NotReorgedReason.HeadBlockNotAvailable};
+    }
+    // Skip re-org attempt if proposer boost (reorg) are disabled
+    if (!this.opts?.proposerBoost || !this.opts?.proposerBoostReorg) {
+      this.logger?.verbose("Skip shouldOverrideForkChoiceUpdate check since the related flags are disabled");
```
Comment (twoeths) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: should log both block slot + root, check other log statements as well

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 15]
```diff
@@ -314,9 +322,52 @@ export async function importBlock(
...
+      }
+    }
+  }
+
+  if (shouldOverrideFcu) {
+    if (this.metrics) {
+      this.metrics.importBlock.notOverrideFcuReason.inc({reason: notOverrideFcuReason});
+    }
+    this.logger.verbose("Weak block detected. Skip fcu call in importBlock", {
+      blockRoot: blockRootHex,
```
Comment (twoeths) [inline packages/beacon-node/src/chain/blocks/importBlock.ts:366]: need to also log slot

**Review by twoeths — COMMENTED** [review]
I'd like to have both block root + slot in all log statements so that we can debug easier later, looks good to me other than that

**Review by twoeths — DISMISSED** [review]

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 16]
```diff
@@ -314,9 +322,53 @@ export async function importBlock(
...
+      } else {
+        this.logger.warn("Unable to get beacon proposer. Do not override fcu.", {slot: blockSlot + 1}, e as Error);
+      }
+    }
+  }
+
+  if (shouldOverrideFcu) {
+    if (this.metrics) {
+      this.metrics.importBlock.notOverrideFcuReason.inc({reason: notOverrideFcuReason});
+    }
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]:
```suggestion
    this.metrics?.importBlock.notOverrideFcuReason.inc({reason: notOverrideFcuReason});
```

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 17]
```diff
@@ -314,9 +322,53 @@ export async function importBlock(
...
+        shouldOverrideFcu = result.shouldOverrideFcu;
+        if (!result.shouldOverrideFcu) {
+          notOverrideFcuReason = result.reason;
+        }
+      }
+    } catch (e) {
+      if (isStartSlotOfEpoch(blockSlot + 1)) {
+        notOverrideFcuReason = NotReorgedReason.NotShufflingStable;
+      } else {
+        this.logger.warn("Unable to get beacon proposer. Do not override fcu.", {slot: blockSlot + 1}, e as Error);
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: `slot` here might be misleading as it's the proposal slot, not block slot or clock slot

maybe add const `proposalSlot` as we do `blockSlot + 1` in multiple places
```suggestion
        this.logger.warn("Unable to get beacon proposer. Do not override fcu.", {proposalSlot}, e as Error);
```

File: packages/beacon-node/src/chain/blocks/importBlock.ts [hunk 18]
```diff
@@ -314,9 +322,53 @@ export async function importBlock(
...
+      }
+    }
+  }
+
+  if (shouldOverrideFcu) {
+    if (this.metrics) {
+      this.metrics.importBlock.notOverrideFcuReason.inc({reason: notOverrideFcuReason});
```
Comment (nflaig) [inline packages/beacon-node/src/chain/blocks/importBlock.ts]: why would we set `notOverrideFcuReason` (reason why we are not overriding) if `shouldOverrideFcu == true` meaning we override fcu call?

(same for the [log below](https://github.com/ChainSafe/lodestar/blob/692eaacd20e905da312b234cb315aec63536fa23/packages/beacon-node/src/chain/blocks/importBlock.ts#L361-L365))

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 19]
```diff
@@ -223,6 +224,52 @@ export class ForkChoice implements IForkChoice {
...
+    const headBlock = this.getBlockHex(blockRoot);
+    if (headBlock === null) {
+      // should not happen beacause this block just got imported. Fall back to no-reorg.
+      return {shouldOverrideFcu: false, reason: NotReorgedReason.HeadBlockNotAvailable};
+    }
+    // Skip re-org attempt if proposer boost (reorg) are disabled
+    if (!this.opts?.proposerBoost || !this.opts?.proposerBoostReorg) {
+      this.logger?.verbose("Skip shouldOverrideForkChoiceUpdate check since the related flags are disabled", {
+        slot: currentSlot,
+      });
```
Comment (nflaig) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: could print out flags here

```suggestion
      this.logger?.verbose("Skip shouldOverrideForkChoiceUpdate check since the related flags are disabled", {
        slot: currentSlot,
        proposerBoost: this.opts?.proposerBoost,
        proposerBoostReorg: this.opts?.proposerBoostReorg,
      });
```

could destructure opts above if-statement

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 20]
```diff
@@ -223,6 +224,52 @@ export class ForkChoice implements IForkChoice {
     }
   }
 
+  // Basically called by `predictProposerHead`. If the result is not same as blockRoot's block, return true else false
+  // See https://github.com/ethereum/consensus-specs/blob/a94d85bb3b33f84a5830eb98945b790b02ae80e8/specs/bellatrix/fork-choice.md#should_override_forkchoice_update
```
Comment (nflaig) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]:
```suggestion
  // See https://github.com/ethereum/consensus-specs/blob/v1.5.0/specs/bellatrix/fork-choice.md#should_override_forkchoice_update
```

File: packages/beacon-node/src/metrics/metrics/lodestar.ts [hunk 21]
```diff
@@ -744,6 +745,11 @@ export function createLodestarMetrics(
         help: "Total number of imported blobs by source",
         labelNames: ["blobsSource"],
       }),
+      notOverrideFcuReason: register.counter<{reason: NotReorgedReason}>({
+        name: "beacon_import_block_not_override_fcu_reason_total",
```
Comment (nflaig) [inline packages/beacon-node/src/metrics/metrics/lodestar.ts]:
```suggestion
        name: "lodestar_import_block_not_override_fcu_reason_total",
```

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 22]
```diff
@@ -248,28 +294,26 @@ export class ForkChoice implements IForkChoice {
...
-    // No reorg if parentBlock isn't available
-    if (parentBlock === undefined) {
+    if (headBlock.slot === currentSlot) {
+      // If head block aka the head cache is current, that means `updateHead` is called during gossip handling,
+      // that can only happen if shouldOverrideForkChoiceUpdate = false so no reorg
       return headBlock;
     }
 
-    const {prelimProposerHead} = this.getPreliminaryProposerHead(headBlock, parentBlock, proposalSlot);
+    currentSlot = currentSlot ?? this.fcStore.currentSlot;
```
Comment (nflaig) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: why is passing `currentSlot` optional? doesn't look like we call this function without passing it

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 23]
```diff
@@ -223,6 +224,52 @@ export class ForkChoice implements IForkChoice {
     }
   }
 
+  // Basically called by `predictProposerHead`. If the result is not same as blockRoot's block, return true else false
```
Comment (nflaig) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]: we are calling this separately now as well, this kinda contradicts with the other comment here
https://github.com/ChainSafe/lodestar/blob/692eaacd20e905da312b234cb315aec63536fa23/packages/fork-choice/src/forkChoice/interface.ts#L117-L120

File: packages/fork-choice/test/unit/forkChoice/shouldOverrideForkChoiceUpdate.test.ts [hunk 24]
```diff
@@ -0,0 +1,220 @@
...
+    expectedNotReorgedReason?: NotReorgedReason;
+  }[] = [
+    {
+      id: "Case that meets all conditions to be re-orged",
+      parentBlock: {...baseParentHeadBlock},
+      headBlock: {...baseHeadBlock},
+      expectReorg: true,
+    },
+    {
+      id: "No reorg when head block is timly",
```
Comment (nflaig) [inline packages/fork-choice/test/unit/forkChoice/shouldOverrideForkChoiceUpdate.test.ts]:
```suggestion
      id: "No reorg when head block is timely",
```

File: packages/fork-choice/test/unit/forkChoice/shouldOverrideForkChoiceUpdate.test.ts [hunk 25]
```diff
@@ -0,0 +1,220 @@
...
+
+  for (const {
+    id,
+    parentBlock,
+    headBlock,
+    expectReorg,
+    currentSlot: blockSeenSlot,
+    expectedNotReorgedReason,
+  } of testCases) {
+    it(`${id}`, async () => {
```
Comment (nflaig) [inline packages/fork-choice/test/unit/forkChoice/shouldOverrideForkChoiceUpdate.test.ts]:
```suggestion
    it(id, async () => {
```

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 26]
```diff
@@ -223,6 +224,52 @@ export class ForkChoice implements IForkChoice {
...
+  // See https://github.com/ethereum/consensus-specs/blob/a94d85bb3b33f84a5830eb98945b790b02ae80e8/specs/bellatrix/fork-choice.md#should_override_forkchoice_update
+  // Return true if the given block passes all criteria to be re-orged out
+  // Return false otherwise.
+  // Note when proposer boost reorg is disabled, it always returns false
+  shouldOverrideForkChoiceUpdate(currentSlot: Slot, blockRoot: RootHex): ShouldOverrideForkChoiceUpdateResult {
+    const headBlock = this.getBlockHex(blockRoot);
+    if (headBlock === null) {
+      // should not happen beacause this block just got imported. Fall back to no-reorg.
```
Comment (nflaig) [inline packages/fork-choice/src/forkChoice/forkChoice.ts]:
```suggestion
      // should not happen because this block just got imported. Fall back to no-reorg.
```

**Comment by philknows** [comment]
Would like an update on this for #7926 and its testing status on `feat4`

**Review by nflaig — DISMISSED** [review]
LGTM - we should consider enabling proposer boost reorg by default

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.33.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.33.0) :tada:
