### PR TITLE
fix: peer id check in `initPrivateKeyAndEnr`

### LINKED ISSUE #8151: Issues and warnings reading ENR
Noticed those warnings when running a node on fusaka devnets

on first startup
```
warn: Unable to read peerIdFile, creating a new peer id
```
when restarting the node
```
warn: Stored local ENR doesn't match peerIdFile, creating a new ENR
```

related code https://github.com/ChainSafe/lodestar/blob/ae65362a223dcaf1b92d6bdb1c82c5c2ae1af49c/packages/cli/src/cmds/beacon/initPeerIdAndEnr.ts#L161-L176

### PR DESCRIPTION
**Pull request by ensi321**
Closes #8151

### CODE REVIEW

File: packages/cli/src/cmds/beacon/initPeerIdAndEnr.ts [hunk 1]
```diff
@@ -154,11 +155,11 @@ export async function initPrivateKeyAndEnr(
     let privateKey: PrivateKey;
     let enr: SignableENR;
 
-    // attempt to read stored peer id
+    // attempt to read stored private key
     try {
       privateKey = readPrivateKey(peerIdFile);
     } catch (_e) {
-      logger.warn("Unable to read peerIdFile, creating a new peer id");
+      logger.warn("Unable to read peerIdFile, creating a new private key");
```
Comment (nflaig) [inline packages/cli/src/cmds/beacon/initPeerIdAndEnr.ts]: creating a new private key implies a new peer id, I would probably just keep the log as is

**Review by nflaig — COMMENTED** [review]
looks good, we should test this with peerDAS changes and verify that our cgc is properly restored from ENR after these changes because right now it definitely doesn't seem to be the case

**Comment by ensi321** [comment]
> looks good, we should test this with peerDAS changes and verify that our cgc is properly restored from ENR after these changes because right now it definitely doesn't seem to be the case

Tested this change with peerDAS branch. Can confirm everything in the stored enr stayed the same after restart (excluding seq and signature).

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.34.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.34.0) :tada:
