### PR TITLE
Fix eth1 data issue when depositContractDeployBlock not set

### LINKED ISSUE #1580: Error updating eth1 chain cache
**Describe the bug**
```
2020-09-22 23:11:36  [ETH1]            error: Error updating eth1 chain cache Error: missing response (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":958516,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8545}, url="http://localhost:8545", code=SERVER_ERROR, version=web/5.0.1)
Error: missing response (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":958516,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8545}, url="http://localhost:8545", code=SERVER_ERROR, version=web/5.0.1)
    at Logger.makeError (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at /home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/web/lib/index.js:142:36
    at step (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.throw (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/web/lib/index.js:14:53)
    at rejected (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/web/lib/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Expected behavior**
No error

**Steps to Reproduce**
Goerli Geth launched with...
```
geth --goerli --datadir="$HOME/Goerli" --http --http.addr=earth.thegalaxy --http.port=8545 --ws --ws.addr=earth.thegalaxy --ws.port=8546 --syncmode=full --nat=extip:1.2.3.4 --port=13431
```
earth.thegalaxy resolves to 192.168.0.2
```
➜  lodestar git:(master) nslookup earth.thegalaxy
Server:         192.168.0.1
Address:        192.168.0.1#53

Name:   earth.thegalaxy
Address: 192.168.0.2
```

Beacon launched with...
```
node --trace-deprecation --stack-size=6000 --max-old-space-size=9192 ./packages/lodestar-cli/bin/lodestar beacon --rootDir=/home/seamonkey/.eth2/lodestar --metrics.enabled=true --metrics.serverPort=8010 --testnet=medalla --network.discv5.bindAddr='/ip4/0.0.0.0/udp/13430' --network.localMultiaddrs='/ip4/0.0.0.0/tcp/13430' --api.enabled=true --enr-ip='1.2.3.4' --logFile=/home/seamonkey/.eth2/lodestar/lodestar.log --network.maxPeers=1000 --api.port=9596 --eth1.enabled=true --eth1.provider.url=http://192.168.0.2:8545
```

```
➜  lodestar git:(master) ss -tulnp | grep geth
udp   UNCONN 0      0                                      *:13431            *:*         users:(("geth",pid=11327,fd=62))
tcp   LISTEN 0      4096                         192.168.0.2:8545       0.0.0.0:*         users:(("geth",pid=11327,fd=39))
tcp   LISTEN 0      4096                         192.168.0.2:8546       0.0.0.0:*         users:(("geth",pid=11327,fd=68))
tcp   LISTEN 0      4096                                   *:13431            *:*         users:(("geth",pid=11327,fd=61))
```

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 20
 - Branch: Master
 - Commit hash: 7885cc5370d158577b72286f1ea81f22e213aadd

### PR DESCRIPTION
**Pull request by dapplion**
If depositContractDeployBlock is not set, Eth1ForBlockProduction would error on every loop until it finds the first deposit event (which can take a while). It also warns if depositContractDeployBlock is not set which should not happen in normal conditions. In https://github.com/ChainSafe/lodestar/issues/1580 is was caused by an already initialized config file without setting the deploy block

Fixes https://github.com/ChainSafe/lodestar/issues/1580

### CODE REVIEW

**Comment by mpetrunic** [comment]
TBH, I think defaulting to 0 is fine, but no deposits should not be error as it's perfectly fine thing to happen.

**Comment by dapplion** [comment]
> TBH, I think defaulting to 0 is fine, but no deposits should not be error as it's perfectly fine thing to happen.

This is the goal of this PR. To not error if the deploy block defaults to 0. However, I believe the warning is necessary otherwise it can take a while until the node has scanned millions of blocks and reached the eth1 head potentially missing the chance to propose blocks.

**Comment by mpetrunic** [comment]
> This is the goal of this PR. To not error if the deploy block defaults to 0. However, I believe the warning is necessary otherwise it can take a while until the node has scanned millions of blocks and reached the eth1 head potentially missing the chance to propose blocks.

Yeah, let's dial it down to warn log level.

**Comment by dapplion** [comment]
> > This is the goal of this PR. To not error if the deploy block defaults to 0. However, I believe the warning is necessary otherwise it can take a while until the node has scanned millions of blocks and reached the eth1 head potentially missing the chance to propose blocks.
> 
> Yeah, let's dial it down to warn log level.

It's at warn log level
https://github.com/ChainSafe/lodestar/blob/712e72e854965c63e42c9739b4617a193bf776b7/packages/lodestar/src/eth1/eth1ForBlockProduction.ts#L58

**Comment by mpetrunic** [comment]
> > > This is the goal of this PR. To not error if the deploy block defaults to 0. However, I believe the warning is necessary otherwise it can take a while until the node has scanned millions of blocks and reached the eth1 head potentially missing the chance to propose blocks.
> > 
> > Yeah, let's dial it down to warn log level.
> 
> It's at warn log level
> https://github.com/ChainSafe/lodestar/blob/712e72e854965c63e42c9739b4617a193bf776b7/packages/lodestar/src/eth1/eth1ForBlockProduction.ts#L58

Im talking about this error:

https://github.com/ChainSafe/lodestar/issues/1580#issuecomment-697154546

**Comment by dapplion** [comment]
> Im talking about this error:
> 
> [#1580 (comment)](https://github.com/ChainSafe/lodestar/issues/1580#issuecomment-697154546)

Oh got it, that error should not happen at all with this PR.

**Comment by mpetrunic** [comment]
> > Im talking about this error:
> > [#1580 (comment)](https://github.com/ChainSafe/lodestar/issues/1580#issuecomment-697154546)
> 
> Oh got it, that error should not happen at all with this PR.

What if there is really 1000 blocks without deposit after deposit contract is deployed? :smile:

**Comment by dapplion** [comment]
`Eth1ForBlockProduction` is meant to fetch blocks only after the first deposit event.

**Comment by dapplion** [comment]
> What if there is really 1000 blocks without deposit after deposit contract is deployed? smile

`Eth1ForBlockProduction` is meant to fetch blocks only after the first deposit event.

File: packages/lodestar/src/eth1/eth1ForBlockProduction.ts [hunk 1]
```diff
@@ -161,21 +165,24 @@ export class Eth1ForBlockProduction implements IEth1ForBlockProduction {
...
     const lowestEventBlockNumber = await this.depositsCache.getLowestDepositEventBlockNumber();
-    const fromBlock = Math.max(
-      this.getFromBlockToFetch(lastCachedBlock),
-      // depositCount data is available only after the first deposit event
-      lowestEventBlockNumber || 0
-    );
+
+    // Do not fetch any blocks if no deposits have been fetched yet
+    // depositCount data is available only after the first deposit event
+    if (lowestEventBlockNumber === null || lastProcessedDepositBlockNumber == null) {
```
Comment (twoeths) [inline packages/lodestar/src/eth1/eth1ForBlockProduction.ts]: `===`? :D

**Review by wemeetagain — APPROVED** [review]
