### PR TITLE
fix(slashing-protection): filter by db bucket when loading pubkeys

### LINKED ISSUE #4261: slashing protection exports goes OOM while exporting 500 validators kiln data
From: https://github.com/ChainSafe/lodestar/pull/4257#issuecomment-1177936632
On our kiln node with 500 dbs which has `8GB` ram, but the process got killed as it went OOM:
```typescript
Jul-07 16:33:38.807[]                 info: Extracting the slashing protection logs version=4, format=complete, dbPath=/root/kiln-data/lodestar/validator-db, file=/root/kiln-data/lodestar/spexport.json
Jul-07 16:33:38.885[]              verbose: Fetching the pubkeys from the slashingProtection db
./lodestar: line 7: 2437989 Killed                  node --trace-deprecation --max-old-space-size=4096 ./packages/cli/bin/lodestar.js "$@"
```

as per our new logs, it happened while listing pub keys from the `slashingProtection` module, it could be same issue that affected the validator decoding in the validator start that we fixed via serializing.

Investigate and fix, the run shouldn't go OOM

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Closes https://github.com/ChainSafe/lodestar/issues/4261

**Description**

Applies min-max key filter to db query to only get pubkeys from bucket used by repository. The OOM mentioned in https://github.com/ChainSafe/lodestar/issues/4261 was caused by a combination of https://github.com/ChainSafe/lodestar/issues/5356 (causing the db state to be quite huge) and the db query not applying any filtering.

**Note:** There is currently no limit on how many attestation are stored in the db. In some extrem cases could still run into OOM issues. This is likely only relevant for big operators that run many validators but pruning strategy for attestation would be something useful to implement in the future.

https://github.com/ChainSafe/lodestar/blob/f0dec8c89957ef0653bb40e3a969750db8d0a869/packages/validator/src/slashingProtection/attestation/index.ts#L46

Other solution that can be implemented is to provide the option to just export the slashing protection for a subset of validators

https://github.com/ChainSafe/lodestar/blob/f0dec8c89957ef0653bb40e3a969750db8d0a869/packages/cli/src/cmds/validator/slashingProtection/export.ts#L49

Depends on https://github.com/ChainSafe/lodestar/pull/5436 to be merged first to avoid conflicts.

### CODE REVIEW

File: packages/validator/src/slashingProtection/attestation/attestationByTargetRepository.ts [hunk 1]
```diff
@@ -36,14 +39,16 @@ export class AttestationByTargetRepository {
...
+    this.maxKey = encodeKey(this.bucket + 1, Buffer.alloc(0));
   }
 
   async getAll(pubkey: BLSPubkey, limit?: number): Promise<SlashingProtectionAttestation[]> {
     const attestations = await this.db.values({
-      ...this.dbReqOpts,
       limit,
       gte: this.encodeKey(pubkey, 0),
       lt: this.encodeKey(pubkey, Number.MAX_SAFE_INTEGER),
+      bucketId: this.bucketId,
```
Comment (nflaig) [inline packages/validator/src/slashingProtection/attestation/attestationByTargetRepository.ts:51]: Unrelated change, just minor follow up to https://github.com/ChainSafe/lodestar/pull/5436

`FilterOptions` does not extend `DbReqOpts` and therefore is not guaranteed to be a superset of it, to avoid type issues in the future should rather not destructure `this.dbReqOpts` here

https://github.com/ChainSafe/lodestar/blob/3ed8d04c7971f753570f0d054a3c44bc2c382be1/packages/db/src/controller/interface.ts#L10

also inline with implementation here

https://github.com/ChainSafe/lodestar/blob/3ed8d04c7971f753570f0d054a3c44bc2c382be1/packages/db/src/abstractRepository.ts#L249-L252

File: packages/validator/src/slashingProtection/block/blockBySlotRepository.ts [hunk 2]
```diff
@@ -68,7 +73,7 @@ export class BlockBySlotRepository {
   }
 
   async listPubkeys(): Promise<BLSPubkey[]> {
-    const keys = await this.db.keys(this.dbReqOpts);
+    const keys = await this.db.keys({gte: this.minKey, lt: this.maxKey, bucketId: this.bucketId});
```
Comment (dapplion) [inline packages/validator/src/slashingProtection/block/blockBySlotRepository.ts:76]: How is this not taken care of by the underlying db repository impl?

Comment (nflaig) [reply packages/validator/src/slashingProtection/block/blockBySlotRepository.ts:76]: The repositories on the validator do not extend [Repository](https://github.com/ChainSafe/lodestar/blob/3ed8d04c7971f753570f0d054a3c44bc2c382be1/packages/db/src/abstractRepository.ts#L19) and the [db itself](https://github.com/ChainSafe/lodestar/blob/3ed8d04c7971f753570f0d054a3c44bc2c382be1/packages/db/src/controller/level.ts#L143) does not handle that.

This is mostly do to the fact that there are incompatibilities with parameters and returns types which does not allow to override methods such as `encodeKey`.

Another more historic decision I found is that it was desired to keep db interface required by validator to be more minimal.
As mentioned in https://github.com/ChainSafe/lodestar/pull/1954 and a separate type [LodestarValidatorDatabaseController](https://github.com/ChainSafe/lodestar/blob/3ed8d04c7971f753570f0d054a3c44bc2c382be1/packages/validator/src/types.ts#L22).

Maybe a good refactor would be to create a base repository for the validator repositories with a minimal set of methods.

Comment (nflaig) [reply packages/validator/src/slashingProtection/block/blockBySlotRepository.ts:76]: I can look into creating a base repository for subset of methods required by validator repositories. Will have to see if that refactor even makes sense but would prefer to do it in another PR.

**Comment by nflaig** [comment]
Just to reconfirm, exporting a 200MB slashing protection file works on a VC with 2k keys, would consider the OOM issue fixed.

File: packages/validator/src/slashingProtection/block/blockBySlotRepository.ts (hunk 2 above)
Comment (dapplion) [reply packages/validator/src/slashingProtection/block/blockBySlotRepository.ts:76]: I'll merge this for now, and feel free to open PR to dedup

**Review by dapplion — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.9.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.9.0) :tada:
