### PR TITLE
fix: ignore discovered peers with no multiaddrs

### LINKED ISSUE #5733: Uncaught exception: Cannot read properties of undefined (reading '0')
### Describe the bug

After upgrade to libp2p 0.45.9, there are frequent uncaught exceptions

```
Jul-05 13:35:02.052[]                error: uncaughtException: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at Libp2pNode.PeerDiscovery.onDiscoveredPeer (file:///home/devops/goerli/lodestar/packages/beacon-node/src/network/peers/discover.ts:276:60)
    at Libp2pNode.[nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
    at Libp2pNode.dispatchEvent (node:internal/event_target:704:26)
    at Libp2pNode.dispatchEvent (file:///home/devops/goerli/lodestar/node_modules/@libp2p/interfaces/src/events.ts:64:26)
    at Libp2pNode.safeDispatchEvent (file:///home/devops/goerli/lodestar/node_modules/@libp2p/interfaces/src/events.ts:79:17)
    at EventEmitter.<anonymous> (file:///home/devops/goerli/lodestar/node_modules/libp2p/src/libp2p.ts:102:14)
    at EventEmitter.[nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
    at EventEmitter.dispatchEvent (node:internal/event_target:704:26)
    at EventEmitter.dispatchEvent (file:///home/devops/goerli/lodestar/node_modules/@libp2p/interfaces/src/events.ts:64:26)
    at EventEmitter.Libp2pNode.events.dispatchEvent (file:///home/devops/goerli/lodestar/node_modules/libp2p/src/libp2p.ts:65:30) Cannot read properties of undefined (reading '0'
```

### Expected behavior

No uncaught exception

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

7280234bea66b49da3900b916a1b54c4666e4173

### PR DESCRIPTION
**Pull request by wemeetagain**
**Motivation**

- Resolves https://github.com/ChainSafe/lodestar/issues/5733
Upgrading to libp2p 0.45.9, it changed how / when it emits `"peer:discovery"` events.

**Description**

Update `onDiscoveredPeer` to handle the case where `multiaddrs: Multiaddr[]` is empty.

### CODE REVIEW

**Comment by nflaig** [comment]
Getting another but similar error running this branch

```
TypeError: Cannot read properties of undefined (reading 'length')
    at Libp2pNode.PeerDiscovery.onDiscoveredPeer (file:///home/devops/goerli/lodestar/packages/beacon-node/src/network/peers/discover.ts:277:20)
    at Libp2pNode.[nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
    at Libp2pNode.dispatchEvent (node:internal/event_target:704:26)
    at Libp2pNode.dispatchEvent (file:///home/devops/goerli/lodestar/node_modules/@libp2p/interfaces/src/events.ts:64:26)
    at Libp2pNode.safeDispatchEvent (file:///home/devops/goerli/lodestar/node_modules/@libp2p/interfaces/src/events.ts:79:17)
    at EventEmitter.<anonymous> (file:///home/devops/goerli/lodestar/node_modules/libp2p/src/libp2p.ts:102:14)
    at EventEmitter.[nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
    at EventEmitter.dispatchEvent (node:internal/event_target:704:26)
    at EventEmitter.dispatchEvent (file:///home/devops/goerli/lodestar/node_modules/@libp2p/interfaces/src/events.ts:64:26)
    at EventEmitter.Libp2pNode.events.dispatchEvent (file:///home/devops/goerli/lodestar/node_modules/libp2p/src/libp2p.ts:65:30) Cannot read properties of undefined (reading 'length')
```

There is also a max listeners warning, could be related
```
(node:593428) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 finish listeners added to [ConsoleDynamicLevel]. Use emitter.setMaxListeners() to increase limit
```

**Review by matthewkeil — DISMISSED** [review]
LGTM! 🚀

**Review by twoeths — DISMISSED** [review]

File: packages/beacon-node/src/network/peers/discover.ts [hunk 1]
```diff
@@ -267,10 +268,17 @@ export class PeerDiscovery {
...
 
   /**
-   * Progressively called by libp2p peer discovery as a result of any query.
+   * Progressively called by libp2p as a result of peer discovery or updates to its peer store
    */
   private onDiscoveredPeer = (evt: CustomEvent<PeerInfo>): void => {
     const {id, multiaddrs} = evt.detail;
+
+    // libp2p may send us PeerInfos without multiaddrs
+    if (multiaddrs.length === 0) {
```
Comment (twoeths) [inline packages/beacon-node/src/network/peers/discover.ts]: with this error `Cannot read properties of undefined (reading '0')` we need to handle undefined `multiaddrs` too

```suggestion
    if (!multiaddrs || multiaddrs.length === 0) {
```

**Review by twoeths — APPROVED** [review]

**Review by nflaig — APPROVED** [review]
Looks good now, no more errors

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.10.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.10.0) :tada:
