### PR TITLE
Do not lookahead for altair duties as the api currently errors pre-altair

### LINKED ISSUE #3752: Empty SyncCommitteeCache error on a local devnet run
This error came up on the kurtosis local testnet runs (2 lodestar beacon nodes with attached validators), where altair epoch =1, bellatrix 2 and was consistently reproducible.
```
Feb-11 16:59:56.001 []                 info: Synced - slot: -1 - head: 0 0xf9ba…d781 - finalized: 0x0000…0000:0 - peers: 1
Feb-11 16:59:58.004 [NETWORK]          info: Subscribing gossip topics to next fork nextFork=bellatrix
Feb-11 16:59:58.004 [NETWORK]          info: Suscribing to random attnets to next fork nextFork=bellatrix
Feb-11 16:59:58.005 [NETWORK]          info: Suscribing to random attnets to next fork nextFork=bellatrix
Feb-11 16:59:58.006 [NETWORK]          info: Subscribed gossip core topics
Feb-11 16:59:58.012 [SYNC]             info: Subscribed gossip core topics
Feb-11 16:59:58.477 [API]             error: Req req-h getSyncCommitteeDuties error message=Empty SyncCommitteeCache
Error: Empty SyncCommitteeCache
    at SyncCommitteeCacheEmpty.get validatorIndexMap [as validatorIndexMap] (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/cache/syncCommitteeCache.ts:27:11)
    at Object.getSyncCommitteeDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:392:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
Feb-11 16:59:58.535 [API]             error: Req req-j getSyncCommitteeDuties error message=Empty SyncCommitteeCache
Error: Empty SyncCommitteeCache
    at SyncCommitteeCacheEmpty.get validatorIndexMap [as validatorIndexMap] (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/cache/syncCommitteeCache.ts:27:11)
    at Object.getSyncCommitteeDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:392:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
```

Expected: no error

### PR DESCRIPTION
**Pull request by g11tech**
**Motivation**
We start call `pollSyncCommittees` with a lookahead of 1 in the validator in anticipation of altair fork, but right now lodestar beacon doesn't support look ahead.
```typescript
/** Placeholder object for pre-altair fork */
export class SyncCommitteeCacheEmpty implements SyncCommitteeCache {
  get validatorIndices(): ValidatorIndex[] {
    throw Error("Empty SyncCommitteeCache");
  }

  get validatorIndexMap(): SyncComitteeValidatorIndexMap {
    throw Error("Empty SyncCommitteeCache");
  }
}
```
This results into error

Remove the lookahead in the validator duties for altair
Closes #3752

### CODE REVIEW

File: packages/validator/src/services/syncCommitteeDuties.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ import {ValidatorStore} from "./validatorStore";
 /** Only retain `HISTORICAL_DUTIES_PERIODS` duties prior to the current periods. */
 const HISTORICAL_DUTIES_PERIODS = 2;
 /** Epochs prior to `ALTAIR_FORK_EPOCH` to start fetching duties */
-const ALTAIR_FORK_LOOKAHEAD_EPOCHS = 1;
+const ALTAIR_FORK_LOOKAHEAD_EPOCHS = 0;
```
Comment (dapplion) [inline packages/validator/src/services/syncCommitteeDuties.ts:28]: Add a nice chunk of text in the JSDocs of this variable with context and linking to the issue that started this PR:

"Before it was 1 but, bla bla issue link. Now we use 0 and we believe this is okay because bla bla.

**Review by dapplion — APPROVED** [review]
Looks great! Thanks for the nice jsdocs
