### PR TITLE
Handle attester duties reorg

### LINKED ISSUE #3211: ERR_INVALID_ATTESTATION_DOUBLE_VOTE
**Describe the bug**

A user in discord reported  https://discord.com/channels/593655374469660673/593655641445367808/889555125448892427

```
error: Error signing attestation slot=1304012, index=17, head=0xdca5…3d80, validator=0xa87e…afb1 code=ERR_INVALID_ATTESTATION_DOUBLE_VOTE, attestation={"sourceEpoch":40749,"targetEpoch":40750,"signingRoot":"0x667cbb5b329650705425bddc216491a059be6e4e4dcab96727b5f1989a7bd847"}, prev={"sourceEpoch":40749,"targetEpoch":40750,"signingRoot":"0x4818486efdecad5d700e2b048c7ca3c4f85132cfbc929fc5f932b85199a952c3"}
```

Lodestar version=v0.30.0 (npm), network=prater
Neither my vc or bn node were restarting. I am running both in cli. I couldn't find any grafana dashboards for metrics. Can you please link it?
I plan on running  lodestar using systemd but will probably do that later on today. Unfortunately, I don't have any saved logs.

Perhaps it's my network settings? I have a lighthouse node running on port 9000 so I switched lodestar to use 9001. These are the settings I'm using. 

```
lodestar beacon --network prater --network.localMultiaddrs /ip4/0.0.0.0/tcp/9001 --network.discv5.bindAddr /ip4/0.0.0.0/udp/9001 --eth1.providerUrls https://goerli.infura.io/v3/XXX --network.targetPeers 50 --network.maxPeers 55
```

**Expected behavior**

Ǹot happen

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ When getting attester duties for current epoch, we have `notWhileSyncing()` check and it's good but not enough when validator ask for next epoch
+ For example in https://github.com/ChainSafe/lodestar/issues/3211#issuecomment-926320834, head epoch is at 41250 while validator asked for attester duties at epoch 41252, node should throw error instead of returning unreliable duties

**Description**

+ Check requested epoch vs headEpoch (instead of currentEpoch), it should be <=1
+ Closes #3211

### CODE REVIEW

File: packages/lodestar/src/api/impl/validator/index.ts [hunk 1]
```diff
@@ -280,7 +280,13 @@ export function getValidatorApi({
       await waitForNextClosestEpoch();
 
       // Check if the epoch is in the future after waiting for requested slot
-      if (epoch > chain.clock.currentEpoch + 1) {
+      const headEpoch = computeEpochAtSlot(chain.forkChoice.getHead().slot);
+      if (epoch > headEpoch + 1) {
```
Comment (g11tech) [inline packages/lodestar/src/api/impl/validator/index.ts]: ~~ideally you should || i.e. epoch > headEpoch + 1 || epoch > chain.clock.currentEpoch + 1
in both scenarios reject api call~~
notWhileSyncing wouldn't take care of this?

**Comment by g11tech** [comment]
just to mention @wemeetagain 's comment on the lodestar-testnet-alerts channel which might be relevant:

>You may wonder, why even allow getting duties if we're not fully synced? Well it's not always clear whether you're fully synced or not.
>In normal network conditions, yes, its easy to determine that your node is synced. Your clock ticks to the next slot, you receive and process that slot's block via gossip, your node determines that the new block is the new head of the chain.
>However when the network is degraded, for example during a long chain of skip slots, being synced looks just like being unsynced. So a node always needs to be able to handle this unsure area and ensure that their validators will be able to progress the chain even in these conditions.

in case of skipped slots, this will cause the attestation to freeze and not get involved in voting for zero blocks (atleast)
duties reorg with throwing of the double vote error behavior is a valid behavior and is harmless.

**Review by dapplion — CHANGES_REQUESTED** [review]
This can be very dangerous is there are many skipped slots, like +64. It won't allow validators to participate anymore right? Because the head will be too far back.

**Comment by dapplion** [comment]
I think that if the validator tracks the head event with dependant root this issue will be fixed much cleanly since the validator would realize in time when the re-org happens

**Comment by g11tech** [comment]
> I think that if the validator tracks the head event with dependant root this issue will be fixed much cleanly since the validator would realize in time when the re-org happens

true, as long as validators dont double vote, duties reorg is much preferred behavior

**Comment by twoeths** [comment]
**Update**
1. Only change validator, keep the node as is. Right now validator only detect duties reorg passively
2. We want to track duties reorg actively through ChainHeadTracker
  + If new head comes at the same to dependentRoot's epoch of any dutyEpoch, and the new root is different to what's the validator is tracking, and it's the last slot of an epoch => poll duties again
  + If it's not the last slot of epoch, put it to pending state. When it's 2/3 slot to the next epoch, poll duties again. (in this case, dependentRoot may not be the last slot of an epoch)
3. Refactor AttestationDutiesService to store dependent root by epoch in 2 new maps, and prune them when needed

TODOs
- [x] Test on prater (not easy to detect attesterDuties reorg but at least want to make sure it does not affect normal flow)

In my test node, I was able to catch an error like that when the node is syncing
```
Sep-28 06:56:17.478 []                 info: Found attesterDuties reorg through new head slot=1358079, dutyEpoch=42441, root=0x3ad269556b768a43571b5dfc212ed09fb056a13e3573054d008145ef94ebd8d1
Sep-28 06:56:19.665 []                 warn: Attester duties re-org. This may happen from time to time priorDependentRoot=0x816f62c55d1d95b99dcba47909fdc67e30da83c03010b58f1226dec3f165a27b, dependentRoot=0x3ad269556b768a43571b5dfc212ed09fb056a13e3573054d008145ef94ebd8d1
```

Validator works well after that

**Review by g11tech — DISMISSED** [review]
just an idea or rather curiosity, why shouldn't we connect through websocket for just piping the events from bn to the connected validator processes rather than polling to bn, then validator would be more naturally processing events.

**Comment by twoeths** [comment]
need to `implement/consume previousDutyDependentRoot and currentDutyDependentRoot` in https://ethereum.github.io/beacon-APIs/#/Events/eventstream

**Comment by twoeths** [comment]
Update: 
+ handle attester duties reorg due to the node is syncing
+ (new) handle attester duties reorg due to the head is reorg

File: packages/lodestar/src/api/impl/events/index.ts [hunk 2]
```diff
@@ -29,17 +30,26 @@ export function getEventsApi({chain, config}: Pick<ApiModules, "chain" | "config
...
-        // Todo implement
-        previousDutyDependentRoot: ZERO_HASH_HEX,
-        currentDutyDependentRoot: ZERO_HASH_HEX,
-      },
-    ],
+    [routes.events.EventType.head]: (head) => {
+      const state = chain.stateCache.get(head.stateRoot);
+      if (!state) {
+        throw Error("cannot get state for head " + head.stateRoot);
+      }
```
Comment (dapplion) [inline packages/lodestar/src/api/impl/events/index.ts:37]: This is dangerous. The state is really not needed. You can figure out the dependant root only with the forkchoice. The dependant root is the parent of the target block. The `head` event argument here should already include all the data necessary

File: packages/validator/src/services/chainHeaderTracker.ts [hunk 3]
```diff
@@ -28,12 +38,30 @@ export class ChainHeaderTracker {
     return null;
   }
 
+  runOnNewHead(fn: RunEveryFn): void {
+    this.fns.push(fn);
+  }
+
```
Comment (dapplion) [inline packages/validator/src/services/chainHeaderTracker.ts:44]: What about the reorg event? Should we subscribe to it too? Are other clients using the head + reorg events or only head?

File: packages/validator/src/services/chainHeaderTracker.ts [hunk 4]
```diff
@@ -28,12 +38,30 @@ export class ChainHeaderTracker {
...
     if (event.type === EventType.head) {
       const {message} = event;
-      this.headBlockSlot = message.slot;
-      this.headBlockRoot = fromHexString(message.block);
-      this.logger.verbose("Found new chain head", {slot: message.slot, blockRoot: message.block});
+      const {slot, block, previousDutyDependentRoot, currentDutyDependentRoot} = message;
+      this.headBlockSlot = slot;
+      this.headBlockRoot = fromHexString(block);
+      for (const fn of this.fns) {
+        void fn({
```
Comment (dapplion) [inline packages/validator/src/services/chainHeaderTracker.ts]: Better to .catch() here than void just in case

File: packages/lodestar/src/api/impl/events/index.ts (hunk 2 above)
Comment (dapplion) [reply packages/lodestar/src/api/impl/events/index.ts:37]: Here these is some example code on how to compute dependant roots using the fork-choice https://github.com/ChainSafe/lodestar/blob/93a179e6fd9b64febbcf4239dccab366b215ec3f/packages/lodestar/src/chain/regen/interface.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L271

It should be improved, removing the `!` operator

File: packages/validator/src/services/attestationDuties.ts [hunk 5]
```diff
@@ -16,23 +20,29 @@ export type AttDutyAndProof = {
...
 };
 
-// To assist with readability
-type AttDutyAtEpoch = {dependentRoot: Root; dutyAndProof: AttDutyAndProof};
-
 export class AttestationDutiesService {
   /** Maps a validator public key to their duties for each epoch */
-  private readonly dutiesByEpochByIndex = new Map<ValidatorIndex, Map<Epoch, AttDutyAtEpoch>>();
+  private readonly dutiesByEpochByIndex = new Map<ValidatorIndex, Map<Epoch, AttDutyAndProof>>();
+  private readonly dependentRootByEpoch = new Map<Epoch, RootHex>();
```
Comment (dapplion) [inline packages/validator/src/services/attestationDuties.ts]: I think you can merge this two data structures together using
```ts
dutiesByEpochByIndex = new Map<
  Epoch, 
  {dependantRoot: RootHex, dutiesByIndex: Map<ValidatorIndex, AttDutyAndProof>}
>();
```
Indexing by epoch -> validator should be as fast as now, and it allows faster pruning too

File: packages/validator/src/services/attestationDuties.ts [hunk 6]
```diff
@@ -167,24 +198,94 @@ export class AttestationDutiesService {
...
+    head,
+    previousDutyDependentRoot,
+    currentDutyDependentRoot,
+  }: HeadEventData): Promise<void> => {
+    const currentEpoch = computeEpochAtSlot(slot);
+    const nextEpoch = currentEpoch + 1;
+    const nextTwoEpoch = currentEpoch + 2;
+    const nextTwoEpochDependentRoot = this.dependentRootByEpoch.get(currentEpoch + 2);
+    // node is syncing, it may cause the attester duties reorg
+    if (nextTwoEpochDependentRoot && head !== nextTwoEpochDependentRoot) {
```
Comment (dapplion) [inline packages/validator/src/services/attestationDuties.ts:237]: Please add a nice comment here explaining why this 3rd case is necessary, linking to the original issue that caused it. Also please add white space (1 new line) between each of the three cases

File: packages/validator/src/services/chainHeaderTracker.ts (hunk 3 above)
Comment (twoeths) [reply packages/validator/src/services/chainHeaderTracker.ts:44]: Teku handles both https://github.com/ConsenSys/teku/blob/669c608d5a5a3eae1345e8a751d3c6c1754a6e3d/validator/client/src/main/java/tech/pegasys/teku/validator/client/AbstractDutyScheduler.java#L74 (see `onChainHead()` and `onChainReorg()`)

File: packages/lodestar/src/api/impl/events/index.ts (hunk 2 above)
Comment (twoeths) [reply packages/lodestar/src/api/impl/events/index.ts:37]: @dapplion forkchoice may not store the block of `compute_start_slot_at_epoch(currentEpoch - 1) - 1` because it's pruned (given the current status of https://prater.beaconcha.in/) so I have to go with getting the head state here. I think getting headState is safe enough as it should be the same data to forkchoice, let me know if you still think it's dangerous.

just check that Teku also fetch dependent root from state https://github.com/ConsenSys/teku/blob/669c608d5a5a3eae1345e8a751d3c6c1754a6e3d/storage/src/main/java/tech/pegasys/teku/storage/client/RecentChainData.java#L322

Comment (dapplion) [reply packages/lodestar/src/api/impl/events/index.ts:37]: Got it, but they don't assume that the head state will be in the cache. I understand that `retrieveStateAndBlockSummary` is sort of a regen call. I'm okay merging this now and cleaning up our regen strategy latter.

File: packages/validator/src/services/chainHeaderTracker.ts (hunk 3 above)
Comment (twoeths) [reply packages/validator/src/services/chainHeaderTracker.ts:44]: Lighthouse instead keep polling duties per slot so it does not need to handle reorg or head event.

With the mature `on_head` event api at this time, I think handling `on_head` is enough for us. As long as dependent roots are not changed, it's not necessary to poll duties again even through it's a reorg.

**Comment by twoeths** [comment]
tested with a node of 4 validators, I think the performance is the same. We'll need to produce attestation data as soon as validator see new head in a separate PR.

Screen Shot 2021-10-19 at 21 21 01

File: packages/validator/src/services/attestationDuties.ts [hunk 7]
```diff
@@ -17,39 +20,72 @@ export type AttDutyAndProof = {
...
       }
     }
 
     return duties;
   }
 
+  /**
+   * If a reorg dependent root comes at a slot other than last slot of epoch
+   * just update this.pendingDependentRootByEpoch() and process here
+   * @returns
```
Comment (wemeetagain) [inline packages/validator/src/services/attestationDuties.ts]: stray `@returns` line

File: packages/validator/src/services/attestationDuties.ts [hunk 8]
```diff
@@ -17,39 +20,71 @@ export type AttDutyAndProof = {
...
 
-    for (const dutiesByEpoch of this.dutiesByEpochByIndex.values()) {
-      const dutyAtEpoch = dutiesByEpoch.get(epoch);
-      if (dutyAtEpoch && dutyAtEpoch.dutyAndProof.duty.slot === slot) {
-        duties.push(dutyAtEpoch.dutyAndProof);
+    const epochDuties = this.dutiesByIndexByEpoch.get(epoch);
+    if (epochDuties === undefined) {
+      return duties;
+    }
+    for (const validatorDuty of epochDuties.dutiesByIndex.values()) {
```
Comment (dapplion) [inline packages/validator/src/services/attestationDuties.ts:58]: Add white space before for loop

File: packages/validator/src/services/attestationDuties.ts [hunk 9]
```diff
@@ -139,50 +173,122 @@ export class AttestationDutiesService {
...
     });
 
-    let alreadyWarnedReorg = false;
-    for (const duty of relevantDuties) {
-      let dutiesByEpoch = this.dutiesByEpochByIndex.get(duty.validatorIndex);
-      if (!dutiesByEpoch) {
-        dutiesByEpoch = new Map<Epoch, AttDutyAtEpoch>();
-        this.dutiesByEpochByIndex.set(duty.validatorIndex, dutiesByEpoch);
+    const prior = this.dutiesByIndexByEpoch.get(epoch);
+    const priorDependentRoot = prior?.dependentRoot;
```
Comment (dapplion) [inline packages/validator/src/services/attestationDuties.ts]: You can merge this lines into 
```ts
const priorDependentRoot = this.dutiesByIndexByEpoch.get(epoch)?.dependentRoot;
```
And use `priorDependentRoot` in the if statement below

**Review by dapplion — APPROVED** [review]

**Comment by dapplion** [comment]
Awesome! :fire:
