### PR TITLE
fix getHeaders/finalized call

### LINKED ISSUE #2157: Can't fetch finalized block via API
### Describe the bug

Fetching the finalized block using the API fails with 404

### Steps to Reproduce

`curl localhost:9596/eth/v1/beacon/headers/finalized`

### PR DESCRIPTION
**Pull request by 3xtr4t3rr3str14l**
resolves #2157

### CODE REVIEW

File: packages/lodestar/src/api/impl/beacon/blocks/utils.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ export async function resolveBlockId(
     return db.blockArchive.get(GENESIS_SLOT);
   }
   if (blockId === "finalized") {
-    return db.block.get(forkChoice.getFinalizedCheckpoint().root.valueOf() as Uint8Array);
+    return await db.blockArchive.get(forkChoice.getFinalizedCheckpoint().epoch);
```
Comment (mpetrunic) [inline packages/lodestar/src/api/impl/beacon/blocks/utils.ts:39]: don't we have last finalized block in memory?

Comment (wemeetagain) [reply packages/lodestar/src/api/impl/beacon/blocks/utils.ts:39]: I don't think so, I don't think we have any blocks in memory for much time. Either pushed into the `block`, `pendingBlock` or `blockArchive` dbs.

**Comment by wemeetagain** [comment]
looks like a unit test is failing

**Review by wemeetagain — APPROVED** [review]
