### PR TITLE
Explicitly convert checkpoint subtrees to struct

### LINKED ISSUE #2258: Ensure that roots are not subtrees
**Describe the bug**

Currently, roots/checkpoints are used and held in a variety of places. We may be unintentionally storing subtrees when the roots/checkpoints are retrieved from a tree-backed object.

See https://github.com/ChainSafe/persistent-merkle-tree/pull/26 for why this is an issue, and remains an issue in Node <v14

**Expected behavior**

Ensure that roots and checkpoints are always explicitly converted to struct, eg: Uint8Array, by calling `valueOf`.

Relies on https://github.com/ChainSafe/ssz/pull/82
Also may be implemented in parallel with https://github.com/ChainSafe/ssz/issues/83

### PR DESCRIPTION
**Pull request by wemeetagain**
**Motivation**

See #2258 

**Description**

Resolves #2258
(Along with https://github.com/ChainSafe/lodestar/blob/master/packages/beacon-state-transition/src/phase0/fast/util/flat.ts#L10 tweaked in #2289)

Inspecting a heap snapshot, the only remaining subtrees are in the fork choice, fixed here.

### CODE REVIEW

**Review by twoeths — DISMISSED** [review]

**Comment by dapplion** [comment]
Can you add a comment above each line explaining the reasoning and importance of the change?

**Review by mpetrunic — DISMISSED** [review]

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 1]
```diff
@@ -280,7 +280,7 @@ export class ForkChoice implements IForkChoice {
         });
       }
       if (state.currentJustifiedCheckpoint.epoch > this.fcStore.bestJustifiedCheckpoint.epoch) {
-        this.updateBestJustified(state.currentJustifiedCheckpoint, justifiedBalances);
+        this.updateBestJustified(state.currentJustifiedCheckpoint.valueOf() as phase0.Checkpoint, justifiedBalances);
```
Comment (wemeetagain) [inline packages/fork-choice/src/forkChoice/forkChoice.ts:285]:
```suggestion
        // `valueOf` coerses the checkpoint, which may be tree-backed, into a javascript object
        // See https://github.com/ChainSafe/lodestar/issues/2258
        this.updateBestJustified(state.currentJustifiedCheckpoint.valueOf() as phase0.Checkpoint, justifiedBalances);
```

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 2]
```diff
@@ -290,7 +290,7 @@ export class ForkChoice implements IForkChoice {
 
     // Update finalized checkpoint.
     if (state.finalizedCheckpoint.epoch > this.fcStore.finalizedCheckpoint.epoch) {
-      this.fcStore.finalizedCheckpoint = state.finalizedCheckpoint;
+      this.fcStore.finalizedCheckpoint = state.finalizedCheckpoint.valueOf() as phase0.Checkpoint;
```
Comment (wemeetagain) [inline packages/fork-choice/src/forkChoice/forkChoice.ts:297]:
```suggestion
      // `valueOf` coerses the checkpoint, which may be tree-backed, into a javascript object
      // See https://github.com/ChainSafe/lodestar/issues/2258
      this.fcStore.finalizedCheckpoint = state.finalizedCheckpoint.valueOf() as phase0.Checkpoint;
```

File: packages/fork-choice/src/forkChoice/forkChoice.ts [hunk 3]
```diff
@@ -316,7 +316,7 @@ export class ForkChoice implements IForkChoice {
           error: new Error("No validator balances supplied"),
         });
       }
-      this.updateJustified(state.currentJustifiedCheckpoint, justifiedBalances);
+      this.updateJustified(state.currentJustifiedCheckpoint.valueOf() as phase0.Checkpoint, justifiedBalances);
```
Comment (wemeetagain) [inline packages/fork-choice/src/forkChoice/forkChoice.ts:325]:
```suggestion
      // `valueOf` coerses the checkpoint, which may be tree-backed, into a javascript object
      // See https://github.com/ChainSafe/lodestar/issues/2258
      this.updateJustified(state.currentJustifiedCheckpoint.valueOf() as phase0.Checkpoint, justifiedBalances);
```

**Review by dapplion — APPROVED** [review]
