### PR TITLE
Protect Validator API

### LINKED ISSUE #1380: Ensure VC knows of BN syncing status
**Describe the bug**
See https://discordapp.com/channels/593655374469660673/593655641445367808/742254419156009072

The validator never realizes that the beacon node is still syncing. Leads to confusing logs and beacon node errors.

**Expected behavior**
Validator API responses are tailored / conditional on syncing status
Validator is aware of syncing status

### LINKED ISSUE #1391: Validator can trigger errors in Beacon Node
**Describe the bug**
See https://discordapp.com/channels/593655374469660673/593655641445367808/742868789452079194

> So everytime I get one of these in the validator

> It freezes up the beacon chain for 5-10 mins with this:

> so i have shut down the validator just so the beacon can catch back up

**Expected behavior**
Validator cannot cause errors in the beacon node

### PR DESCRIPTION
**Pull request by twoeths**
resolves #1391 
resolves #1380 

For validator api:
+ Do a check before `processSlots()` to make sure our node is not suspended if epoch is too far in the future
+ throw Error with detailed sync status if our node is syncing

image

### CODE REVIEW

**Review by wemeetagain — DISMISSED** [review]
Awesome. :+1:

Do you happen to know which http response code fastify sends back in the errored case?

**Comment by twoeths** [comment]
> Do you happen to know which http response code fastify sends back in the errored case?

it's 500 as in `{"statusCode":500,"error":"Internal Server Error","message":"Node is syncing, status: {\"headSlot\":\"69568\",\"syncDistance\":\"26318\"}"}`

File: packages/lodestar/src/api/impl/validator/validator.ts [hunk 1]
```diff
@@ -75,6 +75,10 @@ export class ValidatorApi implements IValidatorApi {
     randaoReveal: Bytes96,
     graffiti = ""
   ): Promise<BeaconBlock> {
+    if (!this.sync.isSynced()) {
+      const syncStatus = this.config.types.SyncingStatus.toJson(await this.sync.getSyncStatus());
+      throw new Error(`Node is syncing, status: ${JSON.stringify(syncStatus)}`);
```
Comment (mpetrunic) [inline packages/lodestar/src/api/impl/validator/validator.ts]: Can you throw ApiError that contains prop statusCode and throw it here with status code set to 503.
Rest api should handle this error and return proper status code

**Review by mpetrunic — CHANGES_REQUESTED** [review]
You should add test case to rest api unit tests

File: packages/lodestar/src/api/impl/validator/validator.ts (hunk 1 above)
Comment (twoeths) [reply packages/lodestar/src/api/impl/validator/validator.ts]: I switched to using our middlware, it used 503 there.
Since we use it in single place, I don't think we need ApiError?

**Comment by twoeths** [comment]
> You should add test case to rest api unit tests

I added `should return 503 when node is syncing`

File: packages/lodestar/src/api/impl/validator/validator.ts (hunk 1 above)
Comment (mpetrunic) [reply packages/lodestar/src/api/impl/validator/validator.ts]: I don't think we should use middleware as we might consume this api directly (not trough rest)

**Review by mpetrunic — CHANGES_REQUESTED** [review]
We should deal with sync status bug before merging. We currently don't handle situation before head  block, when we are in waitingForPeers and when target < current slot

**Comment by wemeetagain** [comment]
> We should deal with sync status bug before merging. We currently don't handle situation before head block, when we are in waitingForPeers and when target < current slot

This seems like it should be tackled as a separate PR.
We also may want the API to still work in that case, or at least when our head is at the current epoch.

**Comment by mpetrunic** [comment]
> > We should deal with sync status bug before merging. We currently don't handle situation before head block, when we are in waitingForPeers and when target < current slot
> 
> This seems like it should be tackled as a separate PR.
> We also may want the API to still work in that case, or at least when our head is at the current epoch.

True but we cannot merge this before fixing this silly bug 😅

File: packages/lodestar/src/sync/gossip/handler.ts [hunk 2]
```diff
@@ -49,7 +50,9 @@ export class BeaconGossipHandler implements IGossipHandler {
     this.subscribe(forkDigest);
   };
 
-  private subscribe = (forkDigest: ForkDigest): void => {
+  private subscribe = async (forkDigest: ForkDigest): Promise<void> => {
+    // TODO: remove this once we fix in gossipsub-js
```
Comment (twoeths) [inline packages/lodestar/src/sync/gossip/handler.ts]: @wemeetagain I was not able to subscribe to `/beacon_block/` immediately after we start gossip (`/beacon_block/` was not even shown in `gossip subscriptions` log) so I have to delay 100ms like this in order to pass e2e.

File: packages/lodestar/src/api/impl/validator/util.ts [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+import {assert} from "@chainsafe/lodestar-utils";
+import {computeEpochAtSlot, computeStartSlotAtEpoch} from "@chainsafe/lodestar-beacon-state-transition";
+import {processSlots} from "@chainsafe/lodestar-beacon-state-transition/lib/fast/slot";
+
+export async function safeProcessSlots
+(config: IBeaconConfig, epoch: Epoch, chain: IBeaconChain): Promise<ITreeStateContext> {
+  const {epochCtx, state} = await chain.getHeadStateContext();
+  assert.lte(
+    epoch,
+    computeEpochAtSlot(config, state.slot) + 2,
```
Comment (mpetrunic) [inline packages/lodestar/src/api/impl/validator/util.ts]: I don't think we need this anymore because if we are in sync, this would stall us

File: packages/lodestar/test/e2e/noEth1Sim.test.ts [hunk 4]
```diff
@@ -68,21 +72,29 @@ describe("no eth1 sim (multi-node test)", function () {
         }
       }
 
+      // wait for all nodes to be synced first or Validator API would failed
```
Comment (mpetrunic) [inline packages/lodestar/test/e2e/noEth1Sim.test.ts]: Isn't it the goal for api to fail until we are synced?

Comment (mpetrunic) [reply packages/lodestar/test/e2e/noEth1Sim.test.ts]: Maybe we can just put warning in VC instead of error in case of syncing

File: packages/lodestar/test/unit/sync/gossip/handler.test.ts [hunk 5]
```diff
@@ -42,6 +43,7 @@ describe("gossip handler", function () {
     });
     const handler = new BeaconGossipHandler(chainStub, networkStub, dbStub, logger);
     await handler.start();
+    await sleep(100);
```
Comment (mpetrunic) [inline packages/lodestar/test/unit/sync/gossip/handler.test.ts]: We need to investigate this, putting random sleep in unit tests cannot be solution. That worked before?!

Comment (twoeths) [reply packages/lodestar/test/unit/sync/gossip/handler.test.ts]: it seems there is an issue in gossip or the way we handle gossip so I have to sleep(100) for unit tests in order to confirm the e2e tests, I'm investigating it.

File: packages/lodestar/src/network/gossip/gossip.ts [hunk 6]
```diff
@@ -147,6 +147,7 @@ export class Gossip extends (EventEmitter as { new(): GossipEventEmitter }) impl
     event: keyof IGossipEvents | string,
     listener?: unknown,
     params: Map<string, string> = new Map()): void {
+    if (!this.listeners(event as keyof IGossipEvents).includes(listener as (...args: unknown[]) => void)) return;
```
Comment (twoeths) [inline packages/lodestar/src/network/gossip/gossip.ts:150]: @wemeetagain so gossip is fine, this caused the incorrect unsubscription of gossip topic

File: packages/lodestar/test/e2e/noEth1Sim.test.ts (hunk 4 above)
Comment (twoeths) [reply packages/lodestar/test/e2e/noEth1Sim.test.ts]: I removed this, validator is handling pregenesis nicely with logs like `Waiting for genesis time waitTime=26s`

File: packages/lodestar/test/unit/sync/gossip/handler.test.ts (hunk 5 above)
Comment (twoeths) [reply packages/lodestar/test/unit/sync/gossip/handler.test.ts]: resolved the issue

File: packages/lodestar/src/api/impl/validator/validator.ts [hunk 7]
```diff
@@ -189,19 +198,22 @@ export class ValidatorApi implements IValidatorApi {
...
   ): Promise<void> {
+    await this.checkSyncStatus();
     await Promise.all([
       this.db.aggregateAndProof.add(signedAggregateAndProof.message),
       this.network.gossip.publishAggregatedAttestation(signedAggregateAndProof)
     ]);
   }
 
   public async getWireAttestations(epoch: number, committeeIndex: number): Promise<Attestation[]> {
+    await this.checkSyncStatus();
```
Comment (mpetrunic) [inline packages/lodestar/src/api/impl/validator/validator.ts]: We don't need it here?

**Comment by wemeetagain** [comment]
file conflicts

**Review by mpetrunic — APPROVED** [review]
How does logs look like on validator side?

**Comment by twoeths** [comment]
@mpetrunic 

> How does logs look like on validator side?

there is no error, it's like
```
2020-08-18 15:13:24  []                 info: Checking genesis time and beacon node connection
2020-08-18 15:13:24  []                 info: Waiting for genesis time waitTime=2s
2020-08-18 15:13:24  []                 info: Checking genesis time and beacon node connection
2020-08-18 15:13:24  []                 info: Waiting for genesis time waitTime=2s
2020-08-18 15:13:27  []                 info: Checking genesis time and beacon node connection
2020-08-18 15:13:27  [VALIDATOR 0-8]    info: Chain start has occured!
2020-08-18 15:13:27  [VALIDATOR 0-8]    info: on new block epoch epoch=0, validator=0xa99a76ed7796f7be22d5b7e85deeb7c5677e88e511e0b337618f8c4eb61349b4bf2d153f649f7b53359fe8b94a38e44c
```

**Comment by mpetrunic** [comment]
> @mpetrunic
> 
> > How does logs look like on validator side?
> 
> there is no error, it's like
> 
> ```
> 2020-08-18 15:13:24  []                 info: Checking genesis time and beacon node connection
> 2020-08-18 15:13:24  []                 info: Waiting for genesis time waitTime=2s
> 2020-08-18 15:13:24  []                 info: Checking genesis time and beacon node connection
> 2020-08-18 15:13:24  []                 info: Waiting for genesis time waitTime=2s
> 2020-08-18 15:13:27  []                 info: Checking genesis time and beacon node connection
> 2020-08-18 15:13:27  [VALIDATOR 0-8]    info: Chain start has occured!
> 2020-08-18 15:13:27  [VALIDATOR 0-8]    info: on new block epoch epoch=0, validator=0xa99a76ed7796f7be22d5b7e85deeb7c5677e88e511e0b337618f8c4eb61349b4bf2d153f649f7b53359fe8b94a38e44c
> ```

Maybe we should have logs so user knows something is wrong?

**Comment by twoeths** [comment]
> > @mpetrunic
> > > How does logs look like on validator side?
> > 
> > 
> > there is no error, it's like
> > ```
> > 2020-08-18 15:13:24  []                 info: Checking genesis time and beacon node connection
> > 2020-08-18 15:13:24  []                 info: Waiting for genesis time waitTime=2s
> > 2020-08-18 15:13:24  []                 info: Checking genesis time and beacon node connection
> > 2020-08-18 15:13:24  []                 info: Waiting for genesis time waitTime=2s
> > 2020-08-18 15:13:27  []                 info: Checking genesis time and beacon node connection
> > 2020-08-18 15:13:27  [VALIDATOR 0-8]    info: Chain start has occured!
> > 2020-08-18 15:13:27  [VALIDATOR 0-8]    info: on new block epoch epoch=0, validator=0xa99a76ed7796f7be22d5b7e85deeb7c5677e88e511e0b337618f8c4eb61349b4bf2d153f649f7b53359fe8b94a38e44c
> > ```
> 
> Maybe we should have logs so user knows something is wrong?

Last time I did see a lot of errors thrown at validator side because nodes run regular sync. With the latest code it does not run regular sync and nodes are up to date from the beginning (since I added genesisDelay in multinode test) so we don't see any errors anymore.

**Review by wemeetagain — APPROVED** [review]
Lets merge this, tackle additional logging in a separate PR
