### PR TITLE
Use validator balances of justified checkpoint for forkchoice

### LINKED ISSUE #1692: Javascript heap out of memory
**Describe the bug**
Sync Medalla until slot 503311 and I got OOM issue
```
Tuyens-MacBook-Pro-16519:lodestar-cli tuyennguyen$ rm .medalla.weak/enr.json 
Tuyens-MacBook-Pro-16519:lodestar-cli tuyennguyen$ rm -rf .medalla.weak/peerstore/
Tuyens-MacBook-Pro-16519:lodestar-cli tuyennguyen$ !node
node --inspect lib/index.js beacon --testnet medalla --root-dir .medalla.weak > .medalla.weak.log.7
Debugger listening on ws://127.0.0.1:9229/35de6389-fe4b-4800-a759-5f0d5209ef15
For help, see: https://nodejs.org/en/docs/inspector
Tuyens-MacBook-Pro-16519:lodestar-cli tuyennguyen$ rm -rf .medalla.weak/peerstore/
Tuyens-MacBook-Pro-16519:lodestar-cli tuyennguyen$ !node
node --inspect lib/index.js beacon --testnet medalla --root-dir .medalla.weak > .medalla.weak.log.7
Debugger listening on ws://127.0.0.1:9229/8dfa08a2-9676-4b53-9c9d-51fa7085ffb9
For help, see: https://nodejs.org/en/docs/inspector
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100078c35 node::Abort() [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
 2: 0x100078db9 node::OnFatalError(char const*, char const*) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
 3: 0x10016e8d7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
 4: 0x10016e873 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
 5: 0x1002f2605 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
 6: 0x1002f3d2d v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
 7: 0x1002f0ae6 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
 8: 0x1002eea3c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
 9: 0x1002fa114 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
10: 0x1002fa18f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
11: 0x1002d2940 v8::internal::Factory::NewBigInt(int, v8::internal::AllocationType) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
12: 0x10040d2c9 v8::internal::MutableBigInt::LeftShiftByAbsolute(v8::internal::Isolate*, v8::internal::Handle<v8::internal::BigIntBase>, v8::internal::Handle<v8::internal::BigIntBase>) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
13: 0x1005c8fe6 v8::internal::Runtime_BigIntBinaryOp(int, unsigned long*, v8::internal::Isolate*) [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
14: 0x1009288f9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/tuyennguyen/.nvm/versions/node/v12.10.0/bin/node]
Abort trap: 6
```
In my branch I cache 64 blocks max so I don't think that's an issue.
Last time I can sync to slot 525000 so this is not decided by how far we can sync Medalla, it happens kind of randomly.

**Expected behavior**
OOM issue should never happen

### PR DESCRIPTION
**Pull request by twoeths**
resolves #1692 
+ This comes from the directions in #1693 
+ Use balances of justified checkpoint state instead of current checkpoint for forkchoice
+ Improve memory cache: Caching balances of active validator is much smaller compared to EpochProcess

### CODE REVIEW

File: packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts [hunk 1]
```diff
@@ -49,7 +49,8 @@ export class EpochContext {
   public currentShuffling!: IEpochShuffling;
   public nextShuffling!: IEpochShuffling;
   public config: IBeaconConfig;
-  public epochProcess?: IEpochProcess;
+  // validator balance at the time of epoch transition, not the one in state
+  public balances?: Gwei[];
```
Comment (mpetrunic) [inline packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts]: Are those justfied balances? Maybe rename it to justifiedBalances.
Comment above it confuses me even more haha

File: packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts [hunk 2]
```diff
@@ -248,10 +247,10 @@ export class ForkChoice implements IForkChoice {
    *
    * The supplied block **must** pass the `state_transition` function as it will not be run here.
    *
-   * `epochProcess` is passed in so that justified balances can be updated synchronously.
+   * `balances` balances of justified state which is updated synchronously.
    * This ensures that the forkchoice is never out of sync.
    */
-  public onBlock(block: BeaconBlock, state: BeaconState, epochProcess?: IEpochProcess): void {
+  public onBlock(block: BeaconBlock, state: BeaconState, balances?: Gwei[]): void {
```
Comment (mpetrunic) [inline packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts]: probably better to rename it to justifiedBalances

File: packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts (hunk 1 above)
Comment (twoeths) [reply packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts]: it's not justified balance, it's balance when we process an epoch and prepare `epochProcess`. Maybe `checkpointBalance` or `epochBalance`?

once a checkpoint becomes justified, it becomes justified balance

File: packages/lodestar/src/chain/blocks/stateTransition.ts [hunk 3]
```diff
@@ -137,7 +139,10 @@ export async function runStateTransition(
     verifySignatures: !job.trusted,
   }) as ITreeStateContext;
   const oldHead = forkChoice.getHead();
-  forkChoice.onBlock(job.signedBlock.message, postStateContext.state, postStateContext.epochCtx.epochProcess);
+  // current justified checkpoint should be prev epoch or current epoch if it's just updated
+  const balances = (await db.checkpointStateCache.get(postStateContext.state.currentJustifiedCheckpoint))?.epochCtx
```
Comment (twoeths) [inline packages/lodestar/src/chain/blocks/stateTransition.ts]: will rename to `justifiedBalance` here

File: packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts [hunk 4]
```diff
@@ -49,7 +49,8 @@ export class EpochContext {
   public currentShuffling!: IEpochShuffling;
   public nextShuffling!: IEpochShuffling;
   public config: IBeaconConfig;
-  public epochProcess?: IEpochProcess;
+  // validator balance at the time of epoch transition
+  public epochBalances?: Gwei[];
```
Comment (wemeetagain) [inline packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts]: I think we should expose the epochProcess to lodestar like:
```typescript
interface IStateContext {
  state: BeaconState;
  epochCtx: EpochContext;
  epochProcess?: EpochProcess;
}
```
And then downstream, in lodestar, remove the epoch process / store balances:
```typescript
...
// remove the epoch process
const ctx = {
  state: stateCtx.state,
  epochCtx: stateCtx.epochCtx,
};
// pull out the balances
const balances = stateCtx.epochProcess.statuses.map((s) => (s.active ? s.validator.effectiveBalance : BigInt(0)));

// store trimmed down state ctx
await db.stateCache.add(ctx);
await db.checkpointStateCache.add(checkpoint, ctx);
// store balances
await db.checkpointBalanceCache.add(checkpoint, balances);
```

**Review by wemeetagain — CHANGES_REQUESTED** [review]

File: packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts (hunk 4 above)
Comment (twoeths) [reply packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts]: so we introduce a new `checkpointBalanceCache` in db? Do we have any other use cases in the future using this?
also, I suppose we should have `prune` logic similar to what we have with `checkpointStateCache`

fyi I still got OOM using this PR (I thought we don't have to reduce `MAX_EPOCHS`), I'll try again with `MAX_EPOCH` as 10. The memory usage should be the same with this change.

Comment (wemeetagain) [reply packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts]: > so we introduce a new checkpointBalanceCache in db? Do we have any other use cases in the future using this?

Yea this is just a first idea. What I don't like about the current situation is adding ad-hoc pieces of the epochProcess to the epochCtx. Trying to avoid that.
There's also an issue if we don't have the balances (or epochCtx) in the cache.

Perhaps we can save all of the cache changes for a separate PR.
Simply have this PR do: "Use balances of justified checkpoint state instead of current checkpoint for forkchoice".

**Comment by twoeths** [comment]
## Update: 
1. separate EpochContext to different interfaces bc they're designed for different things
+ The old EpochContext is the standard one, and that's also the exchange interface of beacon-state-transition module. The name is the same.
+ The StateTransitionEpochContext: this is private use of EpochContext in beacon-state-transition module, it contains EpochProcess
+ The LodestarEpochContext: this is private use of EpochContext in lodestar, it contains `epochBalances`

2. Also `IStateContext` is an exchange interface of beacon-state-transition, it has `epochProcess` inside so that lodestar can pull whatever it wants.
3. `ITreeStateContext` is similar interface of lodestar but it does not have `epochProcess` to save in-memory data, and it contains `LodestarEpochContext`
4. Fix forkchoice `shouldUpdateJustifiedCheckpoint` to return true when we're syncing

**Comment by mpetrunic** [comment]
spec tests failling ^^

**Comment by twoeths** [comment]
spec tests passed, ready for review

**Review by wemeetagain — APPROVED** [review]
