### PR TITLE
SyncCommittee: track chain head by event stream api

### LINKED ISSUE #2823: Validator SyncCommittee Service: handle skipped slot
**Describe the bug**

For a skipped slot, the validator says:

```
Jul-09 02:43:40.017 []                error: Error on runSyncCommitteeTasks slot=157418 message=Error producing SyncCommitteeMessage - Not Found: No block found for id '157418'
Error: Error producing SyncCommitteeMessage - Not Found: No block found for id '157418'
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:85:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as getBlockRoot] (/usr/app/packages/api/src/client/utils/client.ts:71:19)
    at SyncCommitteeService.produceAndPublishSyncCommittees (/usr/app/packages/validator/src/services/syncCommittee.ts:93:29)
    at /usr/app/packages/validator/src/services/syncCommittee.ts:51:31
    at Clock.runAtMostEvery (/usr/app/packages/validator/src/util/clock.ts:68:7)
```

at node side
```
Jul-09 02:43:40.014 [API]             error: Req req-390f getBlockRoot error message=No block found for id '157418'
Error: No block found for id '157418'
    at resolveBlockId (/usr/app/packages/lodestar/src/api/impl/beacon/blocks/utils.ts:33:11)
    at Object.getBlockRoot (/usr/app/packages/lodestar/src/api/impl/beacon/blocks/index.ts:123:21)
    at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
```

as on every slot, we issue an http GET request to get block root at a slot

**Expected behavior**

+ The spec says that we want to get head block root at a slot, rather than an exact block root at a slot.
+ Consider using event stream api instead of having to issue a separate http GET request at every slot

**Steps to Reproduce**

Sync `yeerongpilly`

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ For SyncCommittee service, we get exact block root from a slot
+ The spec wants the head block root of chain at a slot

**Description**

+ Use event stream api to track the head slot/blockRoot so we don't have to issue http GET requests at every slot
+ This follows Teku strategy

Closes #2823

**Test with yeerongpilly**
+ Node shows that 159092 is skipped slot
```
Jul-09 08:18:30.001 []                 info: Synced - finalized: 4967 0x5dd6…2959 - head: 159091 0xe0da…1384 - clockSlot: 159092 - peers: 3
Jul-09 08:18:42.002 []                 info: Synced - finalized: 4967 0x5dd6…2959 - head: 159093 0x63fe…bd92 - clockSlot: 159093 - peers: 3
Jul-09 08:18:54.008 []                 info: Synced - finalized: 4967 0x5dd6…2959 - head: 159094 0x0b35…64eb - clockSlot: 159094 - peers: 3
```
+ Validator was still able to publish sync committee at that slot
```
Jul-09 08:18:28.861 []                 info: Published SyncCommitteeMessage slot=159092, count=78
Jul-09 08:18:29.523 []                 info: Published attestations slot=159092, index=0, count=17
Jul-09 08:18:32.287 []                 info: Published SyncCommitteeContribution slot=159092, index=1, count=1
Jul-09 08:18:32.291 []                 info: Published SyncCommitteeContribution slot=159092, index=2, count=2
```

### CODE REVIEW

**Comment by dapplion** [comment]
Good catch!

Maybe it's not 100% necessary but we can offer via a flag to switch between polling and relying on the stream. In this case not using the stream is just requesting the head block instead of a number.

For duties we do polling now, but should switch to using the stream https://github.com/ChainSafe/lodestar/issues/2430. We can keep both implementations and switch between them.

**Comment by twoeths** [comment]
> Maybe it's not 100% necessary but we can offer via a flag to switch between polling and relying on the stream. In this case not using the stream is just requesting the head block instead of a number.

I think the only reason for a validator to not use event stream api is it does not support that, so I made a fallback to issue http GET request with "head" instead of a slot

**Review by dapplion — DISMISSED** [review]

**Comment by twoeths** [comment]
Benchmark CI failed as in #2825

**Comment by dapplion** [comment]
> Benchmark CI failed as in #2825

Hope this fixes it https://github.com/ChainSafe/lodestar/pull/2827, can you rebase on top of master?

File: packages/validator/src/services/chainHeaderTracker.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+/**
+ * Track the head slot/root using the event stream api "head".
+ */
+export class ChainHeaderTracker {
+  private headBlockSlot: phase0.Slot;
+  private headBlockRoot: phase0.Root;
+
+  constructor(private readonly logger: ILogger, private readonly api: Api) {
+    this.headBlockSlot = GENESIS_SLOT;
+    this.headBlockRoot = ZERO_HASH;
```
Comment (dapplion) [inline packages/validator/src/services/chainHeaderTracker.ts]: You can initialize to null and return that if it still hasn't been set

**Review by dapplion — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]
