### PR TITLE
fix: correctly get signature from single attestation bytes

### LINKED ISSUE #7259: BlsMultiThreadWorkerPool error - Value is not a valid number: Infinity
Caught the following error during Kurtosis testing

```
Nov-28 14:24:39.365[chain]           error: BlsMultiThreadWorkerPool error - Value is not a valid number: Infinity
TypeError: Value is not a valid number: Infinity
    at /usr/app/node_modules/prom-client/lib/histogram.js:237:10
    at Histogram.observeWithoutExemplar (/usr/app/node_modules/prom-client/lib/histogram.js:74:54)
    at Timeout.BlsMultiThreadWorkerPool.runJob [as _onTimeout] (file:///usr/app/packages/beacon-node/src/chain/bls/multithread/index.ts:490:49)
```

I don't think it's specific to the configuration I used but might be isolated to small network only as it's liekly due to dividing by 0 here
https://github.com/ChainSafe/lodestar/blob/48dea55f542b6356d301663ec7c36e5ab9412c1b/packages/beacon-node/src/chain/bls/multithread/index.ts#L490

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Need to correctly handle extracting signature from single attestation

**Description**

Use `getSignatureFromSingleAttestationSerialized` to extract signature from bytes for post-electra single attestations

Closes https://github.com/ChainSafe/lodestar/issues/7259

### CODE REVIEW

**Review by twoeths — APPROVED** [review]

File: packages/beacon-node/src/chain/validation/attestation.ts [hunk 1]
```diff
@@ -470,7 +471,9 @@ async function validateAttestationNoSignatureCheck(
   let attDataRootHex: RootHex;
   const signature = attestationOrCache.attestation
     ? attestationOrCache.attestation.signature
-    : getSignatureFromAttestationSerialized(attestationOrCache.serializedData);
+    : !isForkPostElectra(fork)
```
Comment (ensi321) [inline packages/beacon-node/src/chain/validation/attestation.ts:474]: Personally would like to see the fork switching logic to be hidden in `sszBytes.ts`

Maybe a function named `getSignatureFromBeaconAttestationSerialized` in a similar fashion  as `getBlockRootFromBeaconAttestationSerialized`.

Comment (nflaig) [reply packages/beacon-node/src/chain/validation/attestation.ts:474]: was debating that as well but figured we only use those in network processor and this pattern was used before already so I went with explicit fork logic in validation itself
https://github.com/ChainSafe/lodestar/blob/957684fe0393b3f50087fc618fb319156ab683fd/packages/beacon-node/src/chain/validation/attestation.ts#L265-L267

Either one seems fine to me

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.26.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.26.0) :tada:
