### PR TITLE
Set peer preferred encoding in reputation store

### LINKED ISSUE #871: Sending requests with wrong encoding to peers
**Describe the bug**

If peers connects to us and sends status request with ssz encoding, we will send future requests with ssz_snappy encoding which peer doesn't support.

**Expected behavior**

We should either store peer prefered encoding in metadata and use it when sending requests or send requests with both encoding at the same time.

I would prefer first solution as it reduces noise and number of requests.

**Steps to Reproduce**

1. start one node
2. start second node and connect to first node with ssz encoding
3. disconnect

### PR DESCRIPTION
**Pull request by twoeths**
## Goal
+ resolves #871

### CODE REVIEW

File: packages/lodestar/src/network/reqResp.ts [hunk 1]
```diff
@@ -80,7 +84,7 @@ export class ReqResp extends (EventEmitter as IReqEventEmitterClass) implements
             pipe(
               stream.source,
               eth2RequestDecode(this.config, this.logger, method, encoding),
-              this.handleRpcRequest(peerId, method),
+              this.handleRpcRequest(peerId, method, encoding),
```
Comment (mpetrunic) [inline packages/lodestar/src/network/reqResp.ts]: Feels like it would be a lot cleaner if you add additional function before request handling that would store encoding instead of passing that troughout stack.
like:
```typescript
pipe(
stream.source,
eth2RequestDecode,
storePeerEncodingPreference,
this.handleRpcRequest
)
```
This pipe will respond with proper encoding anyways, issue is just when we are sending request.

**Comment by wemeetagain** [comment]
Just a note, once we migrate to libp2p v0.28, we plan on removing reputation store in favor of the libp2p peer store.

**Review by mpetrunic — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
e2e test failure

**Comment by mpetrunic** [comment]
e2e tests failing

**Comment by twoeths** [comment]
I can't reproduce the failed e2e in local env. I restarted the check in CI and the issue is gone too.
