### PR TITLE
fix: new error code NOT_ENOUGH_SIDECARS_RECEIVED

### LINKED ISSUE #8350: [block-input-refactor] DOWNLOAD_BY_ROOT_ERROR_EXTRA_SIDECAR_RECEIVED
### Describe the bug

```
Sep-08 07:52:49.794[sync]            ^[[34mdebug^[[39m: Error downloading in BlockInputSync.fetchBlockInput attempt=1, rootHex=0xe7087da6e6de260f93f0809ff0e3437ecf9b16c9731fd6cdf2cf4dcf11a5fee7, peer=16Uiu2HAm5fFWWBQTPjReVC5wzSZ5n7SKjqvJTb72j9jpFpjrYhL2, peerClient=Lighthouse, code=DOWNLOAD_BY_ROOT_ERROR_EXTRA_SIDECAR_RECEIVED, peer=16...jrYhL2, blockRoot=0xe708…fee7, invalidIndex=51
Error: Received a columnSidecar that was not requested
    at fetchAndValidateColumns (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:352:13)
    at fetchByRoot (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:201:26)
    at downloadByRoot (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:69:49)
    at BlockInputSync.fetchBlockInput (file:///usr/src/lodestar/packages/beacon-node/src/sync/unknownBlock.ts:512:21)
    at wrapError (file:///usr/src/lodestar/packages/beacon-node/src/util/wrapError.ts:18:32)
    at BlockInputSync.downloadBlock (file:///usr/src/lodestar/packages/beacon-node/src/sync/unknownBlock.ts:319:17)
```

Image

### Expected behavior

in this debug screen shot, I found that we requested 89 columns but Prysm peer returned only 43 columns
  - should we accept this response if all returned data is valid?
  - but at least, the error message is not correct. It should say not enough data returned instead

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

mkeil/refactor-block-input-on-unstable

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- when not enough sidecars received, we throwed `DOWNLOAD_BY_ROOT_ERROR_EXTRA_SIDECAR_RECEIVED`

**Description**

- define and use the new `NOT_ENOUGH_SIDECARS_RECEIVED` error instead

Closes #8350

### CODE REVIEW

File: packages/beacon-node/src/sync/utils/downloadByRoot.ts [hunk 1]
```diff
@@ -346,6 +346,21 @@ export async function fetchAndValidateColumns({
...
+  if (columnSidecars.length < requestedColumns.length) {
+    throw new DownloadByRootError(
+      {
+        code: DownloadByRootErrorCode.NOT_ENOUGH_SIDECARS_RECEIVED,
+        peer: prettyPrintPeerIdStr(peerIdStr),
+        blockRoot: prettyBytes(blockRoot),
+        invalidIndex: requestedColumns.length - columnSidecars.length,
+      },
+      "Did not receive enough columnSidecars"
+    );
```
Comment (matthewkeil) [inline packages/beacon-node/src/sync/utils/downloadByRoot.ts]:
```suggestion
    throw new DownloadByRootError(
      {
        code: DownloadByRootErrorCode.NOT_ENOUGH_SIDECARS_RECEIVED,
        peer: prettyPrintPeerIdStr(peerIdStr),
        blockRoot: prettyBytes(blockRoot),
        missingIndices: prettyPrintIndices(requestedColumns.filter(c => !columnSidecars.includes(c.index))),
      },
      "Did not receive all of the requested columnSidecars"
    );
```

File: packages/beacon-node/src/sync/utils/downloadByRoot.ts [hunk 2]
```diff
@@ -439,6 +455,12 @@ export type DownloadByRootErrorType =
       blockRoot: string;
       invalidIndex: number;
     }
+  | {
+      code: DownloadByRootErrorCode.NOT_ENOUGH_SIDECARS_RECEIVED;
+      peer: string;
+      blockRoot: string;
+      invalidIndex: number;
```
Comment (matthewkeil) [inline packages/beacon-node/src/sync/utils/downloadByRoot.ts]:
```suggestion
      missingIndices: string;
```

**Review by wemeetagain — APPROVED** [review]
