### PR TITLE
Apply peer action when there are gossip validation errors

### LINKED ISSUE #3772: Apply peer action when there are gossip validation errors
**Describe the bug**

Hetzner-s2 shows a lot of rejected ContributionAndProof gossip messages but other nodes show nothing
Screen Shot 2022-02-18 at 14 28 24

The `lodestar_gossip_validation_accept_total` metric is the same for all nodes.

```
ls 2022-02-16 | grep "contribution" |  wc -l
174
 ls 2022-02-15 | grep "contribution" |  wc -l
125
```

**Expected behavior**

+ It should be consistent across nodes

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ if a node keeps receiving invalid messages from another node, right now it only decreases gossip score of peer, we also should decrease score at lodestar side, and in the end disconnect the peer

**Description**

+ Decay score in PeerManager hearbeat (we missed that)
+ GossipError now has PeerAction, based on that we'll penalizing peer at lodestar side when errors happen, refer to lighthouse implementation https://github.com/sigp/lighthouse/blob/c3a793fd73a3b11b130b82032904d39c952869e4/beacon_node/network/src/beacon_processor/worker/gossip_methods.rs#L1339

Closes #3772

### CODE REVIEW

**Comment by twoeths** [comment]
I leave the test node for 24h, Gossip peer score is increased, number of mesh peers are increased as well

Screen Shot 2022-02-23 at 10 08 54

File: packages/lodestar/src/network/gossip/validation/index.ts [hunk 1]
```diff
@@ -95,7 +99,7 @@ function getGossipValidatorFn<K extends GossipType>(
         throw new GossipActionError(GossipAction.REJECT, {code: (e as Error).message});
```
Comment (twoeths) [inline packages/lodestar/src/network/gossip/validation/index.ts]: need to apply action here

**Review by dapplion — DISMISSED** [review]
LGTM!

**Review by dapplion — APPROVED** [review]
